### PR TITLE
Update the fallback recommendations skill

### PR DESCRIPTION
**Pull request by LinusSkucas**
**Name of your skill**: Fallback Recommendations Skill

Removes some methods that the skill uses that will be removed in 20.02

### CODE REVIEW

**Comment by krisgesling** [comment]
Looks good. Let me just deal with the failing tests, they're unrelated to this Skill though.

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
Hey Linus, I just noticed the branch conflict. Did I just completely miss that before?

Did you use the usual `msk submit` or was this a manual PR?

Anyway, can you resolve that conflict, should be something like:
```
git clone https://github.com/LinusS1/mycroft-skills.git
git checkout -b LinusS1-update-fallback-recommendations-skill 19.08
git pull https://github.com/LinusS1/mycroft-skills.git update-fallback-recommendations-skill
git checkout 19.08
git merge --no-ff LinusS1-update-fallback-recommendations-skill
git push origin 19.08
```

**Comment by LinusSkucas** [comment]
Alright, it seems like that fallback recommendations skill did not make it into 19.08 for some reason (there should be some way of notifying that a skill did not get in). I've submitted the skill, through `msk`, and created a new pr: #1112

**Pull request closed without merging**
