### PR TITLE
Upgrade email

### PR DESCRIPTION
**Pull request by LinusSkucas**
'This upgrades email to include the following new commits:

 - [Fix retrieving the password from home](https://github.com/LinusS1/email-skill/commit/da716ea6f37efb6708115c7d3fbcee9e2cf964f9)
 - [Merge branch 'bugfix/fix-config-file'](https://github.com/LinusS1/email-skill/commit/2d7553405ed9ff0fe76ac5349041fb4e3d610bb6)
 - [Fixed the retrieving the password from the config file (#9)](https://github.com/LinusS1/email-skill/commit/bac9e1aa99ced1f948084ac977403d8810eb17e5)
 - [catalan translations and fix spanish typos (#6)](https://github.com/LinusS1/email-skill/commit/8e0e263c7583c28bedc752b437f0ce424a3b0a3e)
 - [spanish translation (#3)](https://github.com/LinusS1/email-skill/commit/c93b736e840a6e160ba312f59e4199d8e792b0b1)
 - [German Transaltion (#2)](https://github.com/LinusS1/email-skill/commit/ef70e7ed04e3989d7120421a464ae9427e9f7da4)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by LinusSkucas** [comment]
Not sure what's happening with this...

**Comment by el-tocino** [comment]
Did you push the commit to mycroft-skills instead of your own repo?

**Comment by LinusSkucas** [comment]
No, I used ask upgrade .
I wanted to update the skill.

**Comment by KathyReid** [comment]
Hi @LinusS1, thank you so much for your work on this Skill. 
Something isn't quite right with this PR - it looks like it's tried to merge a copy of `mycroft-skills` rather than just the `email-skill`.

What I would recommend doing here is closing this PR, and using `msk upgrade` again to generate a new PR.

**Comment by LinusSkucas** [comment]
Hey @KathyReid thanks for the pointers. I am working on a new version of this skill, which I'll submit (hopefully) soon so I'll just close this pr.

**Comment by KathyReid** [comment]
Thanks @LinusS1, really appreciate the great communication :+1:

**Pull request closed without merging**
