### PR TITLE
Add airplay

### PR DESCRIPTION
**Pull request by LinusSkucas**
## Info

This PR adds the new skill, [airplay](https://github.com/LinusS1/airplay-skill), to the skills repo.

## Description

Once you install the skill, you can connect to it using any iOS or macOS device and play music through it!
The name of the speaker is the hostname of the computer.
The install takes a little while because it needs to build Shairport-sync. Once it is done installing, it will restart. If it doesn't restart, you'll need to restart it manually.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
I don't have any Apple devices here, I am going to ask for assistance in testing this Skill.

**Comment by KathyReid** [comment]
I *think* the Skill tester for this is failing because it can't install `sharepoint-sync` as one of the requirements.

**Comment by LinusSkucas** [comment]
@KathyReid It seems that the skill tester fails is because it doesn't have ufw installed, but the skill in the `requirements.sh` opens the ufw ports so that airplay enabled devices can connect to mycroft.

To my understanding, the mark 1 uses ufw to block all ports.

**Comment by LinusSkucas** [comment]
Alright, pushed a new update, seems to pass the skill tester now.

**Comment by KathyReid** [comment]
Great, thanks so much @LinusS1!
I'm still trying to find someone with a MacOS / iOS device to test this.

**Comment by krisgesling** [comment]
Hey Linus,

I tried to give this a run today but ran into a few problems. On a Mark 1 the `mycroft` user that owns all the skills within the system is prevented from performing certain sudo commands for security purposes (like make and altering ufw rules). I'm also mindful of anything that can pull in external code and execute it from an unmanaged repo. So I'll need to look into how we might be able to make this work without compromising that.

I got AirPlay on MacOS to connect to a Debian Linux machine but haven't managed to get sound output yet.

**Comment by LinusSkucas** [comment]
Hi Gez, I'm just going to close this. If people really wanted Airplay on Mycroft, then we should get apple's official docs, and not just a standalone thing. Also, it'd be hard to debug because I'm using a third party tool. For the record, I tested this on a Picroft, and it worked, but I don't have a Mark 1 to test with.

**Comment by krisgesling** [comment]
Fair enough. I think it's definitely something worth revisiting at a later date though, so I'll keep it on my radar. The ability to cast audio to other devices is super helpful.

**Pull request closed without merging**
