### PR TITLE
Add mosquito speak to 18.02

### PR DESCRIPTION
**Pull request by CarstenAgerskov**
## Description:

Allow Mycroft to notify you on events, by speaking text received on a mqtt bus. Send utterances to activate other mycroft skills, over mqtt.

## Checklist:
  - [x ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ x] Skill has been tested and works
  - [ x] README.md has been updated with the following:
  ```
[submodule "carstena-mosquito-speak"]
	path = carstena-mosquito-speak
	url = https://github.com/CarstenAgerskov/skill-mosquito-speak.git

 ```
 - [x ] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by forslund** [comment]
I've updated it so it doesn't fail at least but currently it only run the first of the skills. The code has been added but I need to revamp some of the docker image still. Soon though :)

**Comment by KathyReid** [comment]
@forslund have you tested this Skill - is it OK to merge or is it still waiting updates to Docker?

**Comment by KathyReid** [comment]
@forslund just following up this Skill - is it OK to merge or is it still waiting updates to Docker?

**Comment by CarstenAgerskov** [comment]
Closing as agreed. Will be opened again later :)

**Pull request closed without merging**
