### PR TITLE
Upgrade mycroft-pairing

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-pairing to include the following new commits:

 - [Merge pull request #57 from PureTryOut/remove-uuid](https://github.com/MycroftAI/skill-pairing/commit/6e8afa98485dd6771ffa3b282e35cfe5098b223a)
 - [Remove old uuid dependency](https://github.com/MycroftAI/skill-pairing/commit/c77c2e14cd9152fb3ff0a27e2ae78cd8514dd97f)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1323))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1323))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1323))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1323))

**Comment by forslund** [comment]
The error is due to an issue in the CI job setup and not the skill. Merging.

**Pull request merged**
