### PR TITLE
Add my-episodes

### PR DESCRIPTION
**Pull request by brezuicabogdan**
## Info

This PR adds the new skill, [my-episodes](https://github.com/brezuicabogdan/skill-my-episodes), to the skills repo.

## Description

You will be able to ask Mycroft to check the status of your shows list handled by [MyEpisodes.com](http://www.myepisodes.com).
At this point Mycroft will be able to give you the number of episodes not acquired and optionally the number of episodes acquired but not watched.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
run test

**Comment by brezuicabogdan** [comment]
I see some tests failed but I cannot identify the cause.
`INFO - Downloading skill: https://github.com/brezuicabogdan/skill-my-episodes.git
INFO - Reading from manifest.yml
INFO - Installing system requirements...
INFO - Installing requirements.txt for my-episodes
INFO - Problem performing action. Restoring skill to previous state...
Saving identifier...
fatal: 'mine' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Build step 'Execute shell' marked build as failure`

Is there something I need to do on the PR?

Also for the conflict should I resolve it or should someone else do it as as far as I can see it is because some other skill was committed in the meantime too.

Thanks.

**Comment by forslund** [comment]
Doing a manual install attempt I get:
```
PipRequirementsException: 
Pip returned code 1:
Requirement already satisfied: feedparser in ./.venv/lib/python3.6/site-packages (5.2.1)
Collecting md5

  Could not find a version that satisfies the requirement md5 (from versions: )
No matching distribution found for md5
You are using pip version 18.0, however version 19.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Seems there is no package called *md5* on pypi

**Comment by krisgesling** [comment]
Hi Bogdan, 

Thanks for creating and submitting a Skill, from a first glance it looks great!

As forslund mentioned the md5 requirement is causing the test runner to fail during skill installation. Removing md5 from `manifest.yml` installs successfully and 13/14 tests pass.
`014.QueryNoUnwatched.json` returns 
> 'Warning! My episodes dot com requires credentials but you did not configure the my episodes skill.'  

instead of 
> 'You have .* unacquired episode.*.'

You can run these tests locally by using:
`mycroft-skill-testrunner /opt/mycroft/skills/skill-directory`

I will give this skill a better run through in the next few days too.

**Comment by brezuicabogdan** [comment]
Hello,

And thank you all for the feedback. Unfortunately my home server I was running Mycroft on crashed and currently I have no way of testing any changes. I am working on rebuilding it and will fix this ASAP, including l the merge conflicts. 

Thank you.

**Comment by krisgesling** [comment]
No worries, don't worry about the merge conflicts in .gitmodules, this should work itself out when you resubmit with:
`mycroft-msk submit /opt/mycroft/skills/your-skill`

If not we can resolve them quickly here. There will always be more skills being added so no way to completely avoid it.

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 Apr 2019 9:20pm CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [ ] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> This icon file appears to be from the MyEpisodes.com website and the license to use it is unclear.
> Please choose a different icon like a simple tv or monitor icon, for example:
> https://raw.githack.com/FortAwesome/Font-Awesome/master/svgs/solid/desktop.svg
> https://raw.githack.com/FortAwesome/Font-Awesome/master/svgs/solid/tv.svg

- [ ] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> There is no title - possibly it did not post correctly to the readme since the short description begins with "My Episodes".  Need to pull this again
> The short description could be modified to something like "Check status of your MyEpisodes show list".  
> Long description is good.

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> not constrained to a particular device

- [x] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes

- [x] **Tags**
Are listed tags appropriate for this Skill?

> yes

- [x] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> MIT License

**Comment by krisgesling** [comment]
Looking at the [raw README.md text](https://raw.githubusercontent.com/brezuicabogdan/skill-my-episodes/master/README.md) it looks like the title got bumped to a new line. Just need to bring that up onto the same line as the image eg:
`#  My Episodes`

**Comment by ricargoes** [comment]
## Meta  
* Platform: Linux
* Mycroft-core version: 19.2.6
* Who: [@ricargoes](https://github.com/ricargoes) / @ricargoes  
* Datestamp: 2019-04-26_18:38:23_CEST  
* Language and dialect of tester: Spanish from Spain (review made in English)

## 0. Automated tests 
Are all automated tests passing?  
- [ ] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> The main concern refers to some functions (`updateUnacquired`, `updateUnwatched`, and `getFeed`) being able to return different kinds of data (a boolean, a dictionary or nothing at all). This situation, besides being confusing, is not adequately handled where they are called and, while it does not generate any with the current code, it makes future revisions harder to maintain and error prone.

- [x] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> The code is well structured in a way that the main source of errors (Asking for feeds to a third-party service) is encapsulated in a function. That function logs when an unexpected behavior has occurred, however it does nothing to propagate the errors; it neither throws an exception nor returns something to handle later. In any case there is no error handling at any point of the code, anything but the happy path will probably crash the skill.

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> It only uses one library outside the python core or Mycroft framework: `feedparser`. It is being appropriately used in the code.

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

>  Library `feedparser` is correctly listed in the `requirement.txt` (though no minimum version is specified)

- [x] **Settings**  
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

> Settings are being used, the file has all the expected fields and the json inside is valid

- [x] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test` folder?

> There are integration tests for all of the utterances. However they do not check a correct execution of the skill. Also, it would be recommendable to test the skill behavior when the request to myepisodes.com is not returned or is returned with non-expected data. The last test fails. Most of the others, while passing, end execution with an exception, error handling should help with that.

- [ ] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

> It seems like most of the file tree is replicated inside the vocab dir. Only the `en-us` dir is needed.
> Also dir `regex/en-us` appears to be empty.

### Actions Required:

* Remove all files except `en-us` in the vocab dir (Required)
* Standardized returning type of functions. (Recommended: It would improve future iterations and readability)
* Propagate request errors in the `getFeed` function (Recommended: It is necessary for proper error handling but it is not necessary for the skill core functionality)
* Provide error handling (Recommended: Error handling is highly recommended to avoid unexpected behaviors and funny states, but again in this case it should not have an impact in the skill core functionality)
* Fix tests (Recommended: Making real use case test should help to detect problems and help with refactors)

**Comment by lb803** [comment]
## Meta  
* Who: [@lb803](https://github.com/lb803) / @lb803  
* Datestamp: 2019-04-28_07:28:47_BST  
* Language and dialect of tester: English (second language)

## 3. Functional Review - intuitive and expected  
- [ ] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method:  `msm install  https://github.com/brezuicabogdan/skill-my-episodes` (inside a docker container)
> Output:  
> ```
> INFO - Downloading skill: https://github.com/brezuicabogdan/skill-my-episodes
> INFO - Installing requirements.txt for skill-my-episodes
> INFO - Successfully installed skill-my-episodes
> ```
> Checking that STT transcribes correctly: "install my episodes" 
> ```  
>  SkillInstallerSkill - ERROR - MSM failed: SkillNotFound(my episodes)
> ```
> I suspect this skill is not enabled for voice installation yet. Still, if the skill is installed via msm, and then I query Mycroft "uninstall my episodes" I get:
> ```
> msm.mycroft_skills_manager - INFO - Best match (0.49): skill-my-episodes.brezuicabogdan by brezuicabogdan
> msm.skill_entry - INFO - Successfully removed skill-my-episodes.brezuicabogdan
> ```
> This suggests me that "my episodes" is recognised correctly by Mycroft, and so it is a suitable skill name. 

- [x] **Settings**  
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> Yes, fool proof.

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Dialogs look good! There's a lot of variations, so reiteration doesn't feel dull.

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [x] **"Check my episodes"** (when no episodes are marked)

> Searching
> There are no unacquired episodes.

- [x] **"Check my episodes"** (when some episodes are marked)

> Searching
> There are 1 unacquired episode.
> Do you want details?
>
> yes
>
> Friends season 10, episode 18,
> You also have 1 acquired but not watched episode.

### Actions Required
A short list of any _Actions Required_. It is also great to provide a short statement of your impressions from using the Skill.
* I would work on the vocab (specifically, Query.voc). While there are a lot of different combinations (13!), I found very easy to forget the required, precise word sequences to trigger the skill method. I would recommend using an [adapt intent](https://mycroft.ai/documentation/adapt/adapt-tutorial/) requiring meaningful groups of words (one for verbs, i.e. 'check'; a second one for nouns, i.e. 'episodes', 'tv shows') instead.

**Comment by lb803** [comment]
Hi there,
just created a [pull request](https://github.com/brezuicabogdan/skill-my-episodes/pull/3) in response to my previous suggestion.
Luca

**Comment by ricargoes** [comment]
I have updated the code review to make clear which actions are requirement to pass the review and which ones are just recommendations. Sorry if it was not clear from the beginning.

**Comment by krisgesling** [comment]
Thanks @lb803 and @ricargoes, excellent reviews and really helpful suggestions!

**Comment by krisgesling** [comment]
Closing in favour of #1122

**Pull request closed without merging**
