### PR TITLE
added podcast skill

### PR DESCRIPTION
**Pull request by JamesPoole**
## Description:

Podcast Skill

Use mycroft to play your favourite podcasts.

(Hopefully third time submitting lucky)

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [X] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by KathyReid** [comment]
* Platform: Ubuntu 18.04 Bionic Beaver
* Device version: 18.2.12b
* Who: @kathyreid / @kathy-mycroft 
* Datestamp: Wed 15 Aug 00:39:12 AEST 2018
* Language and dialect of tester: Native English speaker, Australian accent

### Install Skill 
The Skill is not yet in the `18.02` repo so is not voice-installable. Doing `msm` installation. 
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/JamesPoole/podcast-skill
INFO - Downloading skill: https://github.com/JamesPoole/podcast-skill
INFO - Installing requirements.txt for podcast-skill
INFO - Successfully installed podcast-skill
```
Validate by showing files on filesystem

```
(.venv) kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/podcast-skill.jamespoole$ ls -las
total 60
4 drwxr-xr-x  7 kathyreid kathyreid 4096 Aug 15 00:43 .
4 drwxr-xr-x 35 kathyreid kathyreid 4096 Aug 15 00:43 ..
4 drwxr-xr-x  3 kathyreid kathyreid 4096 Aug 15 00:43 dialog
4 drwxr-xr-x  8 kathyreid kathyreid 4096 Aug 15 00:43 .git
4 -rw-r--r--  1 kathyreid kathyreid   20 Aug 15 00:43 .gitignore
8 -rw-r--r--  1 kathyreid kathyreid 7186 Aug 15 00:43 __init__.py
4 -rw-r--r--  1 kathyreid kathyreid 1051 Aug 15 00:43 LICENSE
4 drwxr-xr-x  2 kathyreid kathyreid 4096 Aug 15 00:43 __pycache__
4 -rw-r--r--  1 kathyreid kathyreid 1957 Aug 15 00:43 README.md
4 -rw-r--r--  1 kathyreid kathyreid   14 Aug 15 00:43 requirements.txt
4 -rw-r--r--  1 kathyreid kathyreid   54 Aug 15 00:43 settings.json
```
**Outcome** installation successful, no issues

### Update Settings

* Updated Settings in home.mycroft.ai, screen shot below
screenshot from 2018-08-15 00-59-30

### Test functionality

* Tested each of the Intents, each one was successful, EXCEPT for the Bad Voltage podcast. I deliberately chose that podcast because it uses the Ogg Vorbis open file format. It **would not play**. 

* I was particularly impressed with the voice user interface used to scroll through the 'deck' of podcasts using play, next and previous. 

* The Intents for finding new podcasts worked very well, the voice user interface presented which showed the current episode from each podcast was very nicely designed and a pleasure to use. 

**Recommendation**: Please consider supporting Ogg Vorbis files as well as mp3
But I won't block the approval of the Skill on this, this is a nice to have ;-) 

### Standard Skill checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> Skill name is easily picked up via voice, as tested in CLI. Passing.

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> All `dialog` run through `mimic`. All sounds very good. Again, well designed dialog. 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> The `Play` Intent is currently overloaded, having the `Put On` Intent is very useful. @penrods has something in build to reduce the loading of the `Play` Intent. Otherwise, no other comments. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> Skill is a candidate for being a DEFAULT Skill. I will recommend to Skills Team. 

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, Skipping 

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README is lovely

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> Only one requirement, version not specified

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Very well laid out, good UI

---

### Additional observations

@JamesPoole This is one of the best designed and executed Skills I've seen for a while. The design thinking, the voice user interaction and your execution on this Skill are **excellent**. Thank you for taking such care with development. 

Merging to `18.02`, Skill will be available for voice install.

**Comment by KathyReid** [comment]
Am liaising internally to see why tests are failing.

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
@JamesPoole hi there! I checked in with my colleague @forslund around why this Skill wasn't passing tests and there were two issues; 

* The Skill Settings are not being populated during the tests. If a user has not yet filled out their Settings, then this causes the Skill to fail. What I'd recommend here is having a default setting that is used if the Skill Setting are not yet populated. This will allow the Skill to pass testing. 

* The Padatious Intents could use a little polishing - generally they aren't just a single word. 

If you're able to take a look at these, I can re-test the Skill. 

Best, Kathy

**Comment by KathyReid** [comment]
@JamesPoole hi there! I checked in with my colleague @forslund around why this Skill wasn't passing tests and there were two issues; 

* The Skill Settings are not being populated during the tests. If a user has not yet filled out their Settings, then this causes the Skill to fail. What I'd recommend here is having a default setting that is used if the Skill Setting are not yet populated. This will allow the Skill to pass testing. 

* The Padatious Intents could use a little polishing - generally they aren't just a single word. 

If you're able to take a look at these, I can re-test the Skill. 

Best, Kathy

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
Just a ping on this one - we think this is a really great Skill and would love to include it - it would just take a couple small changes. 
Best, Kathy

**Comment by JamesPoole** [comment]
My apologies, I see the changes I need to make. I have been pretty scattered of late. I will get an updated version up asap in the next few days!! Sorry about the delay hassle and thanks for taking interest! It is much appreciated.

**Comment by KathyReid** [comment]
Hi @JamesPoole, just a friendly ping on this one. Let me know if we can assist with those couple of minor changes, otherwise this is a very robust and well designed Skill :-)

**Comment by KathyReid** [comment]
Closing this in favour of working from #643

**Pull request closed without merging**
