### PR TITLE
Upgrade mycroft-weather

### PR DESCRIPTION
**Pull request by chrisveilleux**
This upgrades mycroft-weather to include the following new commits:

 - [Merge pull request #165 from emphasize/fix/percnumber_placeholder](https://github.com/MycroftAI/skill-weather/commit/b7a4984b457bb9a800de4ec1aa2d5265d540a9b7)
 - [fix the percentage-number placeholder name](https://github.com/MycroftAI/skill-weather/commit/8312c6ecdb16e39ceee39141a51ece62b7bcf087)
 - [Merge pull request #162 from MycroftAI/20.08](https://github.com/MycroftAI/skill-weather/commit/d4392e4243c289e527ea11315952f3b8552dcf29)
 - [Merge pull request #158 from MycroftAI/make-weather-great-again](https://github.com/MycroftAI/skill-weather/commit/c9244c21cd181030960d70b1164f24e0e399b518)
 - [Move the rest of the old dialog class to the new ones.](https://github.com/MycroftAI/skill-weather/commit/37de4a58f0c0c691966184de6e9f24990327763d)
 - [fix VK test failures.](https://github.com/MycroftAI/skill-weather/commit/47b6baad98b38fb9c16d76e4ce2ce17839e4f7d9)
 - [fixed errant dialog names found in VK testing.](https://github.com/MycroftAI/skill-weather/commit/3a19904648ba826df087c7631a84c146c3af2054)
 - [apply new dialog file naming convention to tests.](https://github.com/MycroftAI/skill-weather/commit/04aca837b1af1a73700d1c92653df1260f3028cc)
 - [resolve merge conflicts](https://github.com/MycroftAI/skill-weather/commit/bb5ab990d5aee9e573ca8908afdab8b413dd9c3b)
 - [Merge remote-tracking branch 'origin/20.08' into make-weather-great-again](https://github.com/MycroftAI/skill-weather/commit/d3e4293a5c4dd99f247421de00048a91f4876fa4)
 - [use the new CardDelegate defined in the mycroft-gui repository to abstract some of the grid-style card layout commonalities.](https://github.com/MycroftAI/skill-weather/commit/054c9b29b6173071d1e7a8c88513ca4e2990abd4)
 - [applied code review changes](https://github.com/MycroftAI/skill-weather/commit/9ca144ac5ae8991c177ba0b0902049cecb7688b0)
 - [renamed dialog and vocab files to be lower case and dash delimited.](https://github.com/MycroftAI/skill-weather/commit/872cf61b3a109494f8c87678e465dd9d5028f4f5)
 - [added location data to the forecast screen](https://github.com/MycroftAI/skill-weather/commit/05134fbd4d5fa574db754b251e3b44dd879b526f)
 - [small bug fix](https://github.com/MycroftAI/skill-weather/commit/cdac17969c85c098a4e21b761cf11cc53bd24d2d)
 - [tweaks to GUI screens based on design changes](https://github.com/MycroftAI/skill-weather/commit/a8197b5d9bf2d1f35188254f3d1959c81a2562fa)
 - [renamed "source" directory to "skill"](https://github.com/MycroftAI/skill-weather/commit/b39098c32456b535ad4c211884f6c31352852a49)
 - [Added location to the top of weather screens that didn't have it.](https://github.com/MycroftAI/skill-weather/commit/730e0c538e1a354f06598c0454e484723d72da80)
 - [Refactored logic that selected an image or animation to use in the GUI](https://github.com/MycroftAI/skill-weather/commit/aad8a27df3f2e573d650d2d9eb25fd5d92bea3e2)
 - [Add a new GUI screen for sunrise and sunset.](https://github.com/MycroftAI/skill-weather/commit/a6b73e3b6968d3032b074a9bdb67c1b54f21c5fb)
 - [Add a new GUI screen for a single day of weather.](https://github.com/MycroftAI/skill-weather/commit/42924cae9a9b7150f5864b951c30e6134e509178)
 - [Bug fixes](https://github.com/MycroftAI/skill-weather/commit/4c62179768a5ff3ffb43a691e6055bb652d6bea5)
 - [Second pass at refactoring, including reworking the dialog classes, removing a bunch of condition specific dialog files, code review changes and other minor cleanups.](https://github.com/MycroftAI/skill-weather/commit/5d38589c10e59accc30a0fc96288d89742113ac2)
 - [Renamed resource files to be consistent with en-us locale.](https://github.com/MycroftAI/skill-weather/commit/10ea9656713877da5c3d528e1520152896828882)
 - [Add OpenWeatherMap language support.](https://github.com/MycroftAI/skill-weather/commit/b15367d1ab5fac2655519dace26c536d77105cdc)
 - [Add PyCharm IDE files to gitignore](https://github.com/MycroftAI/skill-weather/commit/cdfacb630b6e4a1a36a564803b7688d88d88e92a)
 - [Move dialog, vocabulary and regex files to the locale directory as per the latest convention.](https://github.com/MycroftAI/skill-weather/commit/74e994f8ee875389806d9e27ef761d73176790f7)
 - [New xfail scenario example](https://github.com/MycroftAI/skill-weather/commit/0b31a7f95c9605c0a70ed87d88a3bcaf7551da83)
 - [New feature files for hourly weather](https://github.com/MycroftAI/skill-weather/commit/7c5a76ba91ec9e9de5985a261703f0ea299fa9f0)
 - [Minor font size change](https://github.com/MycroftAI/skill-weather/commit/09262810e585b0ce5df7c0ef82c1f717e3a34ae1)
 - [Remove unused import](https://github.com/MycroftAI/skill-weather/commit/5b8b6ceb0ecccf994cf7c41f2e571634025da208)
 - [Take today out of the relative day vocabulary file as it was conflicting with some of the current weather intents.](https://github.com/MycroftAI/skill-weather/commit/276a2bb249e4abb29b39e297ab9b21a1c751e557)
 - [Add index out of range handling for hourly requests more than 48 hours in the future and daily requests more than seven days in the future](https://github.com/MycroftAI/skill-weather/commit/368c368f8c21657d4ef2bb6cb9386976637839b2)
 - [Uncomment the feature files.](https://github.com/MycroftAI/skill-weather/commit/782816cb718055b51b6ebfa471859216875caf17)
 - [Renamed delegates for consistency, added abstractions to reduce code duplication.](https://github.com/MycroftAI/skill-weather/commit/13526e510cee3df3bdd38586ea5355a514714bf4)
 - [Introduce a 16 pixel grid unit property and remove an unused import](https://github.com/MycroftAI/skill-weather/commit/f8284f821d4f4e535b8c6098d0207eb6c5a0a3d0)
 - [Fixed a bug introduced during code cleanup](https://github.com/MycroftAI/skill-weather/commit/5cafea4adb118669354aa02223ce2dc862a4ee02)
 - [Added comments](https://github.com/MycroftAI/skill-weather/commit/747569ab28a0d24ffa78388c00171aba20041bc5)
 - [Added comments and formatting.](https://github.com/MycroftAI/skill-weather/commit/6fdea43375cc23587cf186ee6f20e0f838e348f9)
 - [Add documentation and rename the "generic" QML files to a more descriptive "scalable"](https://github.com/MycroftAI/skill-weather/commit/cb2707cf529b611d4c7d307299d5685364f7332d)
 - [Add a section for temperatures](https://github.com/MycroftAI/skill-weather/commit/fd1da4991c920c2d01f868681352d97dd736d221)
 - [Added license information block.](https://github.com/MycroftAI/skill-weather/commit/0ab455efc65ad03f8b84a25f8fc37211130cd1b0)
 - [Removed unused QML file](https://github.com/MycroftAI/skill-weather/commit/1a79f9cc795a6fad373c412aa15cb804438f6726)
 - [Update the README file.](https://github.com/MycroftAI/skill-weather/commit/20465b20b501e21d4705f6723ff1426bba01c904)
 - [Refactor the GUI code.  Add Mark II specific QML files.](https://github.com/MycroftAI/skill-weather/commit/884401709e931fda9e4012541d8c1b67a6126e8a)
 - [refactor weather skill](https://github.com/MycroftAI/skill-weather/commit/10af4d3d28c1e533627c17a45f9d5997bb0316e5)
 - [Merge pull request #160 from AIIX/fix-resizing-bug-remove-autofit](https://github.com/MycroftAI/skill-weather/commit/203653386c0facb48a012a7d3ceafd0b590c1249)
 - [fix scaling for forecast delegate and weather page text alignment](https://github.com/MycroftAI/skill-weather/commit/96ae297af370e4651ef8ead58b1033bb1a5153ab)
 - [make sure the background is black](https://github.com/MycroftAI/skill-weather/commit/aeb638aed01b416b1caa1d7a2639554bb9f8bfb5)
 - [Fix text resizing issue remove autofit label](https://github.com/MycroftAI/skill-weather/commit/4980419c2cbc39c521e171d101a661ad9b21b057)
 - [Merge branch '20.08' into make-weather-great-again](https://github.com/MycroftAI/skill-weather/commit/759cb1a99c63b738c46b4e95f6cbe86e161d9db6)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
The only failure seems to be the timeout of the test as there have been so many additions to the default Skills.

I know we've talked about many ideas for improving the test framework as a whole, but it seems like we need to figure out a shorter-term strategy to get us through for the moment.

We could do something like https://github.com/MycroftAI/mycroft-core/pull/2811 to run the tests in parallel?
Or disable a proportion of the tests and only run a subset during the CI?

**Comment by forslund** [comment]
The first batch of tests for the weather skill fails, this could be a source of the extreme runtime (540s) of the tests since each failure has a 10 second timeout and will trigger a retry so each fail will add at least 20 seconds per failing scenario.

A simple thing to do for now is to extend the job timeout to 90 minutes just to get a feeling for what is taking so long?

**Comment by krisgesling** [comment]
Yeah, I was wanting to get a version of your Parallel Skill Tester PR in instead, but I haven't got that ready, so have instead done the quick fix of extending the job timeout. At least we'll unblock PR's temporarily.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1537)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1537/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1537/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1537/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1537/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1537/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1537)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1537/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1537/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1537/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1537/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1537/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1537)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1537/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1537/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1537/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1537/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1537/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1537)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1537/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1537/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1537/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1537/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1537/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1537)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1537/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1537/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1537/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1537/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1537/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1537)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1537/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1537/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1537/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1537/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1537/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1537))

**Pull request merged**
