### PR TITLE
Add MBTA-Bus-Tracking

### PR DESCRIPTION
**Pull request by richhowley**
## Info

This PR adds the new skill, [MBTA-Bus-Tracking](https://github.com/richhowley/mbta-bus-tracking-skill), to the skills repo.

## Description

Mycroft will announce estimated arrival times of MBTA busses  at your stop so you never leave the house before you have to.  All data and arrival predictions used by this skill are provided by the MBTA.

See below for full documentation, including how to track busses traveling toward your stop, but to get started just say "Hey Mycroft, T Bus Arrivals".  You will be prompted for the bus route, direction and stop name.  Mycroft will respond with all estimated arrival times at your stop.

<details><summary>View Sample dialog</summary>
<dl>
<dt>Hey Mycroft T Bus Arrivals</dt>
<dd>Which route are you ridingj?</dd>
<dt>One</dt>
<dd>Are you going outbound toward Harvard or Inbound toward Dudley?</dd>
<dt>Inbound</dt>
<dd>Which stop?</dd>
<dt>Mount Auburn Street at Putnam Ave</dt>
<dd>Route One service to Dudley arrivals for Mount Auburn Street at Putnam Avenue:<dd>
<dd>Arriving in 11 minutes<dd>
<dd>Arriving in 21 minutes<dd>
<dd>Arriving in 34 minutes<dd>
</dl>
</details>

<details><summary>View Full Documentation</summary>

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
Hey Rich, apologies that it's taken us so long to get back to this. I have to say this is a fantastic Skill, really well done!

I haven't finished the review yet but a couple of things from the code review:
- The `settings` dictionary will never return results in the `__init__` method, but will work as expected if you shift them to `initialize`. I updated the [docs on Skill Settings](https://mycroft-ai.gitbook.io/docs/skill-development/skill-settings#using-settings-in-your-skill) as this wasn't clear before.
- We have also slightly modified the callback registration for handling when settings change. You can see the [new format in the docs here](https://mycroft-ai.gitbook.io/docs/skill-development/skill-settings#handling-settings-changes). The format you have in this Skill is deprecated and planned for removal in the 20.02 release of Mycroft Core so we want to get everyone switched over.

Optional / FYI / Question:
- You no longer need to import the logger, it is now available automatically on the MycroftSkill class as [`self.log.xxxx`](https://mycroft-ai.gitbook.io/docs/skill-development/introduction/logging)
- The substitution of "st" on [L231](https://github.com/richhowley/mbta-bus-tracking-skill/blob/e57423ed7f2c9c93c0ada024c7a14e23c2dc794c/__init__.py#L231) will only replace the left most occurence. I noticed some output dialog such as: "arrivals for washington street @ beacon st"
- From lines 697-725 is the routeName variable intentionally local rather than accessing the class variable of the same name? My reading of it is that it allows for the local `routeName` to be reset to None and prevent a few commands being run, but still allow lines 729 onward to run as `self.routeName` may still exist. As such I'm assuming this is intended, but wanted to check.

PS Don't worry about the failing check, looks like it's another Skill playing up. I'll have a look at that tomorrow, and should be able to finish the Skill review then too.

**Comment by richhowley** [comment]
Hi Kris,  thanks for looking at my skill and the helpful comments.  I'll get to the changes as soon as I can.  That will mean a new PR, right?

**Comment by krisgesling** [comment]
No worries. 

It looks like you generated the PR yourself rather than using the Mycroft Skills Kit is that right?

The benefit of MSK is that you can rerun the command
`mycroft-msk submit /opt/mycroft/skills/your-skill-directory`
and generate the PR for you. If a PR already exists, it will detect it and update that rather than creating a new one.

So the easiest option might be to close this and run msk submit.

**Comment by krisgesling** [comment]
## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  

- [ ] **Description**  

The short description will be cut off in the Marketplace card view. Perhaps cut it after busses?
> "Announce arrivals of MBTA busses at your desi..."  


Some of the formating of the long description is unlikely to be rendered correctly. You can get a rough view here: https://raw.githack.com/MycroftAI/mycroft-skills/19.08/meta_editor.html
The second paragraph might work better as:
> To get started just say "Hey Mycroft, T Bus Arrivals". You will be prompted for the bus route, direction and stop name. Mycroft will respond with all estimated arrival times at your stop.
> Full documentation, including how to track busses traveling toward your stop, is available on [Github](https://github.com/richhowley/mbta-bus-tracking-skill/blob/master/README.md#-mbta-bus-tracking).

Then if you add a "## Documentation" heading, the Marketplace will ignore that section.
If any of this isn't clear, I could send you a PR with some suggestions.

- [x] **Examples**  

- [x] **Supported Devices**  

- [x] **Categories**  

- [x] **Tags**  

- [x] **License**  


## 3. Functional Review - intuitive and expected  
- [x] **Installation**

> MSM Installs succesfully and Skill name is properly transcribed allowing voice install.

- [x] **Settings**  

- [x] **Dialog**

Small suggestions 
- in `Error.Calling.Server.dialog` the final "ai" will be read by most TTS as some variation of "aye" unless it is capitalized "AI" or is separated by periods "a.i."
- Single letter acronyms are also often mispronounced so you might be better writing the dialog as "tea bus" or something similar.

#### Skill Functions  
_For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each._

I played around with this for a while and it seemed to be working great. Using "shut down" is a minor challenge if the "transit" or "t bus" doesn't get picked up properly it will ask to shutdown the device. Just something to consider for future updates.

I love that if it doesn't pick up a full command (route, direction and stop), it doesn't fail, it asks for more information to build up what it needs.

## Summary  
Thanks for submitting this, it's an excellent Skill. You have clearly thought out conversational interface quite well.

Now I'll have to take a holiday to Boston to try it out for reals :smile:

**Comment by richhowley** [comment]
Hi Kris,

I’ve made the code changes:
moved code from __init__ to initialize
followed the new callback registration
removed logger import
fixed regex on street abbreviation, good catch there 
the business with local and class version with routeName is intentional, it’s meant to distinguish between the utterance route and the validated good route, if validation fails Mycroft will prompt for a route name
I did use msk to make the PR, will try to update it as you suggested.

In terms of long description, it looks like only a small subset of markdown is supported (even on the README generator the headers disappear).  I would rather leave the README as is since it’s the way I want it to look on GitHub.

- Rich

**Comment by krisgesling** [comment]
run test

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
