### PR TITLE
Add what-can-you-do

### PR DESCRIPTION
**Pull request by luke5sky**
## Info

This PR adds the new skill, [what-can-you-do](https://github.com/luke5sky/what-can-you-do-skill), to the skills repo.

## Description

It tells you what you can do with Mycroft (some examples)
and lists the installed skills (if you want).

Just a simple script but i missed it

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>

### CODE REVIEW

**Comment by luke5sky** [comment]
Skill Tester shows Failure in Mycroft Alarm, but my skill does not (at least "should not") use this.  Can anyone have a look?

**Comment by MatthewScholefield** [comment]
@luke5sky Other intents can be a little unstable (there's a fix for this coming in the next release). Try retriggering the build by re-running `msk upload`.

**Comment by luke5sky** [comment]
@MatthewScholefield Thanks for the tip, unfortunatly that didn't do the trick. But i got a new error message:
`==================== 1 failed, 77 passed in 214.43 seconds =====================
+ RESULT=1
+ echo 'Saving identifier...'
Saving identifier...
+ cp /root/.mycroft/identity/identity2.json /mnt/host
+ exit 1
fatal: 'mine' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Build step 'Execute shell' marked build as failure
Setting status of 1f78f20d23f8dda156df31e98100fa82f7dbbf98 to FAILURE with url https://jenkins.mycroft.team/job/skill-tester/321/ and message: 'Skill tests failed...
 '
Using context: Skill tester
Finished: FAILURE`

**Comment by luke5sky** [comment]
@MatthewScholefield thanks for your help. Works now :-)

**Comment by KathyReid** [comment]
### Summary
All checks pass OK, merging

#### Review of `what-can-you-do`

* Platform: Mark 1
* Device version: 18.2.10b
* Who: @kathyreid / kathy-mycroft
* Datestamp: Thu 12 Jul 16:28:29 UTC 2018
* Language and dialect of tester: English native speaker, Australian accent

---

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This Skill is not yet in the `18.02` branch and so will not be available using voice install yet. Falling back to `msm` install

```
pi@mark_1:~ $ msm install https://github.com/luke5sky/what-can-you-do-skill
INFO - Downloading skill: https://github.com/luke5sky/what-can-you-do-skill
INFO - Successfully installed what-can-you-do-skill
```

> Validated on the file system

```
pi@mark_1:~/skills/what-can-you-do-skill.luke5sky $ ls -las
total 56
 4 drwxr-xr-x  7 mycroft mycroft  4096 Jul 12 16:34 .
 4 drwxrwxrwx 44 mycroft mycroft  4096 Jul 12 16:34 ..
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jul 12 16:34 dialog
 4 drwxr-xr-x  8 mycroft mycroft  4096 Jul 12 16:34 .git
 4 -rw-r--r--  1 mycroft mycroft    21 Jul 12 16:34 .gitignore
 4 -rw-r--r--  1 mycroft mycroft  3057 Jul 12 16:34 __init__.py
12 -rw-r--r--  1 mycroft mycroft 10169 Jul 12 16:34 LICENSE
 4 drwxr-xr-x  2 mycroft mycroft  4096 Jul 12 16:34 __pycache__
 4 -rw-r--r--  1 mycroft mycroft   307 Jul 12 16:34 README.md
 4 -rw-r--r--  1 mycroft mycroft    35 Jul 12 16:34 settings.json
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jul 12 16:34 test
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jul 12 16:34 vocab
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> All `dialog` files run through `mimic`; no issues

* Check the **Intents** defined in the `vocab` directory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> The Intents are fairly granular but the `IntentHandler()` uses `require()` so the risk of Intent Collisions is fairly minimal.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> regex not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README appears complete and follows `metaeditor` format

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> No requirements, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Not used, skipping check

#### Python code checks of the Skill

* Inline documentation - is the code documented in line?

> there is no inline commenting, but it's a fairly simple Skill

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> no deps

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> no callbacks

* Error handling - are there any specific checks we make for error handling or graceful degradation?

> handles the only 'no' case well

* Automatic tests - do automatic tests of the **Skill** pass

> yes

**Pull request merged**
