### PR TITLE
Upgrade mycroft-date-time

### PR DESCRIPTION
**Pull request by penrods**
'This upgrades mycroft-date-time to include the following new commits:

 - [Switch to _extract_location() instead of _get_location()](https://github.com/MycroftAI/skill-date-time/commit/473867bd67d3e6c78d324d2de79d02839070cab8)
 - [Merge pull request #49 from andlo/fix_nice_date](https://github.com/MycroftAI/skill-date-time/commit/8845497c60c068cbb1526d6eafec8acad6754bc4)
 - [fix nice_date using self.lang](https://github.com/MycroftAI/skill-date-time/commit/2ea59649c0869abb46f68cb771dd2b37a6917301)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by penrods** [comment]
Run tests

**Comment by penrods** [comment]
Run tests

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Tested and working

**Pull request merged**
