### PR TITLE
dictation skill

### PR DESCRIPTION
**Pull request by JarbasAl**
## Description:

saves user speech and sends by email

char-rnn auto complete for human + machine writing

## Checklist:
  - [ yes] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ yes] Skill has been tested and works
  - [ yes] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [ yes] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by penrods** [comment]
Please populate your README.md using the http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html

Additional sections (like TODO) can be added below the standard ones.

**Comment by JarbasAl** [comment]
done

**Comment by el-tocino** [comment]
Would prefer to see this without a random IP in the default URL, particularly since I can't get a response from that IP, and if it ever changes hands would be an easy security hole.

**Comment by KathyReid** [comment]
Thank you so much for your work on this Skill. This Skill was submitted to the `mycroft-skills` repo just before we implemented [Skill Branching](https://mycroft.ai/blog/skill-branching-18-02/). We'd really like to include this Skill in our 18.02 branch, however this means that the Skill would need to be re-submitted to the `18.02` branch. We also now have some helpful documentation available on [Automated Skills Testing]() and our new [Mycroft Skills Kit]() which assists with Skill submission. We also recently [dropped support for Python 2.7 and have moved to Python 3.4+](). We look forward to working with you to bring your Skill into the `18.02` branch.

**Comment by KathyReid** [comment]
I'm going to close this one off for now - if you'd like to rework this to be Python 3 compliant and re-submit to the `18.02` branch, we can then run it through the [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/). 

We have further information available to assist: 

*  [Mycroft Skills Kit](https://mycroft.ai/documentation/skills/msk/)
*  [Skill Branching](https://mycroft.ai/blog/skill-branching-18-02/)
*  [Automated Skills Testing](https://mycroft.ai/documentation/skills/automatic-testing/)

We look forward to working with you to bring your Skill into the `18.02` branch.

**Pull request closed without merging**
