### PR TITLE
Change the release of core the skill tests will run against to 21.2.1

### PR DESCRIPTION
**Pull request by chrisveilleux**
## Description:

Update the base image used to build the Docker image for VK tests in this repository

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by krisgesling** [comment]
For some reason the pulseaudio daemon is now failing on every run which causes the Volume Skill to fail. Will see if I can work out what's going on...

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1566)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1566/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1566/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1566/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1566/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1566/logs/enclosure.log)

**Comment by krisgesling** [comment]
The only remaining failures are the Timer Skill but can't update the Timer Skill without this fix. So merging.

**Pull request merged**
