### PR TITLE
skill revision

### PR DESCRIPTION
**Pull request by DerekCaelin**
## Description:

**Skill scrapes the CIVICUS Monitor and returns an overview of the civic space status of the selected country. 

This is a resubmission of an [earlier pull request](https://github.com/MycroftAI/mycroft-skills/pull/286#partial-pull-merging) with revisions suggested by Kathy.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] README.md has been updated with the following:
 ```
 - [x ] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by DerekCaelin** [comment]
What does the above mean? "The Travis CI build could not complete due to an error."

**Comment by el-tocino** [comment]
See https://travis-ci.org/MycroftAI/mycroft-skills/builds/375550165?utm_source=github_status&utm_medium=notification for more on what it failed on.

**Comment by DerekCaelin** [comment]
OK, I've reviewed the errors and made adjustments to .gitmodules. Ready for your test.

**Comment by KathyReid** [comment]
NEXT ACTION: 
Could someone else (not with a heavy Austraaaaaaaaaalian accent) please test the `.vocab` on this Skill - just to make sure that it's just not an issue with my accent? If it's a more general problem, I will work with @DerekCaelin to re-work the `.vocab` and how the `Intent`s are triggered.

**Comment by AIIX** [comment]
- Skill seems to be broken and doesn't load
- Installation from:  https://github.com/DerekCaelin/skill-civicus-monitor.git

`` 19:29:47.169 - mycroft.skills.core:load_skill:105 - INFO - ATTEMPTING TO LOAD SKILL: skill-civicus-monitor with ID skill-civicus-monitor
19:29:47.171 - mycroft.skills.core:load_skill:144 - ERROR - Failed to load skill: skill-civicus-monitor
Traceback (most recent call last):
File "/home/aix/mycroft-core/mycroft/skills/core.py", line 115, in load_skill
('.py', 'rb', imp.PY_SOURCE)
File "/usr/lib/python3.6/imp.py", line 235, in load_module
return load_source(name, filename, file)
File "/usr/lib/python3.6/imp.py", line 172, in load_source
module = _load(spec)
File "<frozen importlib._bootstrap>", line 684, in _load
File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 674, in exec_module
File "<frozen importlib._bootstrap_external>", line 781, in get_code
File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
File "/opt/mycroft/skills/skill-civicus-monitor/__init__.py", line 44
global cstatus
^
SyntaxError: name 'cstatus' is used prior to global declaration``

**Comment by DerekCaelin** [comment]
Looks like I should review and make it work with the updates! Thanks folks, will resubmit.

**Pull request closed without merging**
