### PR TITLE
Add MBTA-Bus-Tracking

### PR DESCRIPTION
**Pull request by richhowley**
## Info

This PR adds the new skill, [MBTA-Bus-Tracking](https://github.com/richhowley/mbta-bus-tracking-skill), to the skills repo.

## Description

Mycroft will announce estimated arrival times of MBTA busses  at your stop so you never leave the house before you have to.

All data and arrival predictions used by this skill are provided by the MBTA.  You must register for an API key on the [MBTA website](https://api-v3.mbta.com/register).  Enter the API key for this skill at Mycroft Home.

See below for full documentation, including how to track busses traveling toward your stop, but to get started just say "Hey Mycroft, T Bus Arrivals".  You will be prompted for the bus route, direction and stop name.  Mycroft will respond with all estimated arrival times at your stop.

<details><summary>View Sample dialog</summary>
<dl>
<dt>Hey Mycroft T Bus Arrivals</dt>
<dd>Which route are you ridingj?</dd>
<dt>One</dt>
<dd>Are you going outbound toward Harvard or Inbound toward Dudley?</dd>
<dt>Inbound</dt>
<dd>Which stop?</dd>
<dt>Mount Auburn Street at Putnam Ave</dt>
<dd>Route One service to Dudley arrivals for Mount Auburn Street at Putnam Avenue:<dd>
<dd>Arriving in 11 minutes<dd>
<dd>Arriving in 21 minutes<dd>
<dd>Arriving in 34 minutes<dd>
</dl>
</details>

<details><summary>View Full Documentation</summary>

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by richhowley** [comment]
The tester may contact me for an API key and tips on how to test.

**Comment by krisgesling** [comment]
Hey Rich, another great looking Skill!

I just had a very quick look on their developer site and saw that:
> Requests made without an API key are subject to a limit of 20 requests per minute.
> Requests made with a valid API key are limited to a default of 1000 requests per minute.

Is there a chance this would allow use of the API without an API Key or are multiple requests per query required?

**Comment by richhowley** [comment]
Hi Kris,  that's a great catch.  I'm planning on reworking the skill to function with ant without an API key.

**Comment by richhowley** [comment]
Hey Kris,  I've updated the code so that an API key is optional and am hoping the approval process can proceed.

**Comment by krisgesling** [comment]
Hey that's great news!

To add the new commits to this PR you can run `msk submit` again. In this case it might be:
`mycroft-msk submit /opt/mycroft/skills/mbta-bus-tracking-skill.richhowley/`

**Comment by richhowley** [comment]
api key required

**Pull request closed without merging**
