### PR TITLE
Add Travel Time Skill

### PR DESCRIPTION
**Pull request by TheLastProject**
**Name of your skill**: Travel Time

## Description:

Get traffic information for your route

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works 
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
## Meta  
* Platform: Debian Linux
* Mycroft-core version: 19.8.6
* Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft  
* Datestamp: 2020-01-17_14:50_ACST  
* Language and dialect of tester: English, Australian accent

## 0. Automated tests  
Are all automated tests passing?  
- [x] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
_NOTE: We do not enforce PEP8 Checks on Skills_

- [ ] **Error Handling**  

> Is it worth catching network errors if the device can't reach openstreetmaps for any reason?
> I also managed to raise a WRCError from Waze that should be handled. See the functional test below for details.

- [x] **Libraries**  

- [x] **Required Dependencies**  

- [x] **Settings**  

- [ ] **Integration Tests**  

> No tests included. Can we add a couple of simple tests? There is some documentation on this at: https://mycroft-ai.gitbook.io/docs/skill-development/testing/automatic-testing however it does need a clean up.

- [x] **Other Files**  

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  

- [x] **Description**  

> Suggestion only - wonder if the first sentence might read better as:
> "Get traffic information for any route. By default your Mycroft device's location will be used as the departure point. This can be changed in the Skill settings."

- [x] **Examples**  

- [x] **Supported Devices**  

- [x] **Categories**  

- [x] **Tags**  

- [x] **License**  


## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> `mycroft-msm install https://github.com/TheLastProject/travel-time-skill`
>  Successfully installed travel-time-skill
>
> Checking that STT transcribes correctly
> Utterance: ['install travel time']
> STT transcribing name perfectly.

- [x] **Settings**  
If skill includes a `settingsmeta` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> Suggestion: Perhaps add a brief decription for "Location Aliases". What format is best to use? Complete addresses?

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

Without adding locations in Skill settings

- [ ] **"What's the traffic like to Nightcliff"**

> Interpretted starting location as "like" rather than defaulting to `home` and hence failed. "Like" resolves to (54.9031601,23.6964565)

```
Traceback (most recent call last):
  File "/home/kris/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/travel-time-skill.thelastproject/__init__.py", line 128, in handle_time_travel
    route_info = route.calc_route_info()
  File "/home/kris/mycroft-core/.venv/lib/python3.7/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 193, in calc_route_info
    route = self.get_route(1, time_delta)
  File "/home/kris/mycroft-core/.venv/lib/python3.7/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 142, in get_route
    raise WRCError(response_json.get("error"))
WazeRouteCalculator.WazeRouteCalculator.WRCError: Internal Error
```

- [x] **"How is the traffic to Nightcliff?"**

- [x] **"Is there traffic to Palmerston hospital?"**

- [ ] **"What's the traffic to the hospital"**

> "the hospital" resolved to somewhere in Costa Rica (9.9291872,-84.0889969)
```
2020-01-17 15:55:35.187 | ERROR    | 15245 | mycroft.skills.mycroft_skill.mycroft_skill:on_error:805 | An error occurred while processing a request in Travel Time
Traceback (most recent call last):
  File "/home/kris/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/travel-time-skill.thelastproject/__init__.py", line 130, in handle_time_travel
    route_info = route.calc_route_info()
  File "/home/kris/mycroft-core/.venv/lib/python3.7/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 193, in calc_route_info
    route = self.get_route(1, time_delta)
  File "/home/kris/mycroft-core/.venv/lib/python3.7/site-packages/WazeRouteCalculator/WazeRouteCalculator.py", line 142, in get_route
    raise WRCError(response_json.get("error"))
WazeRouteCalculator.WazeRouteCalculator.WRCError: Internal Error
```

- [ ] **"travel time from austin to dallas"**

> "austin" not resolved uses "home instead"

- [ ] **"how long to darwin hospital"**

> Destination being resolved as "dar" with specifier "hospital"
> Seems to be a Padatious issue rather than with the Skill itself.

- [ ] **"What's the traffic like from amsterdam to brussels?"**

> Destination specifier resolved as "like"
> Also a Padatious issue?

- [x] **"What's the traffic from amsterdam to brussels?"**

- [x] **"how long to 10 trower road casuarina"**

- [x] **"how long to work"**

> "I could not find where work is"


After setting home and work addresses in Skill settings

- [x] **"how long to Nightcliff"**

- [x] **"how long to work"**

- [ ] **"how long to {very close destination}"**

> seems that if destination is under 1 km away Skill responds:
> "It is kilometers and under a minute from..."

## Summary  
Thanks for submitting this, it's a great Skill.

There is clearly something not right with the Padatious entity extraction. We'll have to investigate that further.

As described above it would great to
- add one or more integration tests.
- add error handling for Waze and potential connection errors for OSM Nominatim API.
- handle "0 kilometers" (or "less than a kilometer" perhaps?)

Optional suggestions:
- I wonder if it would be worth adding a `get_response` if the system is unable to find a location. There's a high chance users will say the location again more clearly and without any other content, so you can lookup their entire response.
- Consider wording of description as outlined above.
- Consider adding description of settings as outlined above.

Thanks again for a really useful Skill!

**Comment by TheLastProject** [comment]
Thanks for the review and hints on improving things.

With regard to unit tests though, I am not quite sure how to deal with it, as the output varies a lot depending on traffic conditions. If traffic is bad on a certain highway, Waze may pick a longer route that avoids that highway, so even the distance often fluctuates. As an example, for my trip to work, the distance can easily fluctuate by 10 kilometers. How would I deal with such inconsistent output?

**Comment by forslund** [comment]
The test framework allows a couple of different levels of testing. An utterance hitting the expected intent handler method

```json
{
    "utterance": "will it rain today",
    "intent_type": "handle_isit_raining"
}
```

It's better if you can check that the expected dialog is hit (or one of a list of correct dialogs):
```json
{
    "utterance": "will it rain today",
    "intent_type": "handle_isit_raining",
    "expected_dialog": ["possible_dialog_file1", "possible_dialog_file2"]
}
```

Not sure if that answers your question?

**Comment by TheLastProject** [comment]
I think that answers my question perfectly, thank you @forslund :)

**Comment by TheLastProject** [comment]
I've added tests.

I couldn't reproduce the issues of "like" being misunderstood and they aren't misunderstood in my tests either.

>seems that if destination is under 1 km away Skill responds:
>"It is kilometers and under a minute from..."

This was a bug in Lingua Franca that has since been fixed: https://github.com/MycroftAI/lingua-franca/issues/75.

Things like "the hospital" not working is something I would like to resolve at some point, but I am currently unsure how to fix the code to prefer nearby locations if there are multiple matches without overly taxing OSM Nominatim. I do believe that the skill is still useful enough to be included as is.

**Comment by TheLastProject** [comment]
Hmm, test failure. Interesting. Will have to debug this then.

**Comment by krisgesling** [comment]
Thanks for reporting the bug to LF!

I had a quick look at your tests and noticed you are using both `expected_dialog` and `expected_response`. This should work fine, but will mean if you update a dialog file you need to remember to update the test as well. 

I'm also presuming the tester will do everything in US measures like miles as the majority of our team still haven't realised how superior the metric system is :stuck_out_tongue:

**Comment by forslund** [comment]
```
Evaluating message:  {'utterance': 'It is four hundred and eight miles and six hours twelve minutes from Amsterdam to berlin by car', 'expect_response': False, '__type__': 'speak'}

Evaluating message:  {'name': 'TravelTime.handle_time_travel', '__type__': 'mycroft.skill.handler.complete'}
Evaluation failed
Failure: ['match', 'utterance', 'It is .* kilometers and .* minutes from Amsterdam to berlin by car']
```

Seems like the answer is in miles but the match is against kilometers. Might depend on the unit setting of the user perhaps?

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
