### PR TITLE
Upgrade mycroft-timer

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-timer to include the following new commits:

 - [Merge pull request #100 from forslund/bugfix/wait-for-process](https://github.com/MycroftAI/mycroft-timer/commit/ad26ce283bbb42c198a9a3ef1f9b727806cd57c8)
 - [Wait for play_wav to ensure the process is terminated](https://github.com/MycroftAI/mycroft-timer/commit/84b3af71e214d5fa2217c6e1360090838ce72c70)
 - [Merge pull request #97 from MycroftAI/bugfix/failing-vk-test](https://github.com/MycroftAI/mycroft-timer/commit/13bbdcf081305fdcd537c0947fd7a5985a08bd6a)
 - [Fixed name of dialog file that was still using the old convention.](https://github.com/MycroftAI/mycroft-timer/commit/c9a391345c483f2aa77a3b4ff9ffac229dc1b4a4)
 - [Merge pull request #96 from MycroftAI/bugfix/marketplace-errors](https://github.com/MycroftAI/mycroft-timer/commit/ccca4656760f7ae9bdfa4565eedca511d0c4bacc)
 - [Wait for expired timer dialog to finish speaking before setting the expiration announced to true](https://github.com/MycroftAI/mycroft-timer/commit/be6db0038dc1cfc818417cf473355858d31fb66f)
 - [Alter the sequence of GUI logic so that other skills can take over the GUI while the timer is running.](https://github.com/MycroftAI/mycroft-timer/commit/2da15dbeffe759c6008a68a5a2586f35880dbf22)
 - [Fixed errors showing up in the GUI log when timers 2-4 do not exist](https://github.com/MycroftAI/mycroft-timer/commit/dbd9cdd9d4f1b2b8ebabd81176e8b46742103655)
 - [reset the skill when a user says stop and subsequently responds that active timers should be canceled.](https://github.com/MycroftAI/mycroft-timer/commit/f361b6e550602a417a46098c9253bc34d61efe44)
 - [fix a bug where the timer gui was not displaying when a new timer is added.](https://github.com/MycroftAI/mycroft-timer/commit/a2973a2429cb6092a33d51162f65cb8cf2cbec92)
 - [fixed a bug with resetting the timer index](https://github.com/MycroftAI/mycroft-timer/commit/aae8c273fb1fbe203f80e5a66c2a3cf6b406434c)
 - [Merge pull request #93 from MycroftAI/make-timer-great-again](https://github.com/MycroftAI/mycroft-timer/commit/0b3e92630e7fa0450a5d0d3e469f9ebd177d4658)
 - [Merge remote-tracking branch 'origin/21.02' into make-timer-great-again](https://github.com/MycroftAI/mycroft-timer/commit/c4400b87438e50fd2bd1c547f3fc32ae7c2135c1)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1561)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1561/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1561/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1561/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1561/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1561/logs/enclosure.log)

**Comment by krisgesling** [comment]
Looks like the custom Steps are using new methods that aren't in the 21.02.0 release.

I've also had some strange behaviour on the Mark II. 

1. Setting a timer showed no GUI.
2. Went in to add some logging to `_display_timers_on_gui()` and saving it reloaded the Skill and the existing timer started showing.
3. "stop" correctly asked if I wanted to cancel the active timer, and the timer stopped but is still shown on the screen
4. tried to start another timer - "set a timer for 15 minutes" and received the following error:
```
Traceback (most recent call last):
  File "/opt/mycroft/mycroft/skills/mycroft_skill/event_container.py", line 73, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-timer.mycroftai/__init__.py", line 112, in handle_start_timer
    self._start_new_timer(message)
  File "/opt/mycroft/skills/mycroft-timer.mycroftai/__init__.py", line 192, in _start_new_timer
    timer = self._build_timer(duration, name)
  File "/opt/mycroft/skills/mycroft-timer.mycroftai/__init__.py", line 345, in _build_timer
    self.timer_index += 1
TypeError: unsupported operand type(s) for +=: 'CountdownTimer' and 'int'
```
5. "cancel all timers" > "there are no active timers" but it did clear the screen
6. "set a timer for 15 minutes" > started the timer but again no display


Functions I've tried that are all working:
- Setting multiple timers
- Setting named timers
- Cancelling named timer by name
- Cancelling unnamed timer by assigned name
- Report time left on multiple timers
- Cancel timer based on original duration
- Cancel single timer
- Start a named timer without duration
- Start two timers with the same duration
- Cancel one timer by duration when two such timers exist
- Set a very short timer
- "stop" when beeping silences
- start a pretty long timer  eg 4 hrs
- start a timer longer than 24 hours prompts to set an alarm


Possible UX improvements:
- With the assigned names eg "Timer 2" we then get dialog like "Timer 2 timer cancelled". Given the user set this without a name it would be ideal if we could refer to it as the original duration eg "10 minute timer cancelled".
  -  this is also confusing when the timers are re-ordered. You get "Timer 2 timer for x has y remaining, Timer 1 timer for i has j remaining"
- "start a pasta timer" > "how long of a timer" > "10 minutes" > "I've started a timer named Timer 3 for ten minutes"
- Mark II action button push should silence the beeping rather than activate the listener.
- "Cancel timer 1" > "I have stopped the second timer for ten minutes called Timer 4" - when a "Timer 1" existed. Was the one that got stopped the closest to expiring or the shortest total duration?
- "cancel the 40 minute timer" > started a new timer
- if reading a long list of timers, the mic doesn't get activated, jumps straight to fail. Maybe a bug in get_response()?
- "start a timer for 2 days" >  "timers cannot be more than 24 hours long. Would you like to set an alarm intead?" > no response OR "no" > "I've started a timer for two days"

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1561)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1561/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1561/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1561/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1561/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1561/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1561)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1561/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1561/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1561/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1561/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1561/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1561))

**Pull request merged**
