### PR TITLE
HomeSeer - Home Automation Skill

### PR DESCRIPTION
**Pull request by samclane**
## Description:

A port of the HomeSeer functionality from Alexa to Mycroft. Allows the user to interact with smart-objects using voice control. Currently allows devices to be turned on/off, change values/percentages, lock/unlock items, and get the current status of any device.

https://github.com/samclane/homeseer-mycroft

Note: I've added a `TESTING.md` to the repository with info on how to configure and test the skill. 

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by KathyReid** [comment]
Thanks @samclane for such a well put together Skill. Your `testing.md` is really well laid out and your notes are very clear. Unfortunately I don't have a HomeSeer hub here to test on. What we do in such a situation is request that a second person install the Skill and test on _their_ HomeSeer hub - essentially 'vounching' that the Skill works. It's really the only way we have of ensuring that the functionality is OK before merging this into the `mycroft-skills` repo.

**Comment by ghost** [comment]
@KathyReid I will vouch for this!  I have had it installed on my mycroft on Linux and it has been running with no problems since I installed.  All voice commands work as listed.

**Comment by samclane** [comment]
Thanks @jhend7 ! I had messaged the client I made the skill for, but you were lightning fast.

**Comment by KathyReid** [comment]
This Skill has been functionally validated by other Community members, now performing non-functional checks as part of the [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/). 

## Summary
* Please remove the empty `requirements.sh` file - it's just good practice to remove the file if it's not required. 
* Please add an appropriate LICENSE in the `LICENSE` file - and to the top of the `__init__.py` file too - we recommend the Apache2 License but you're welcome of course to choose one you're comfortable with that allows us to distribute the Skill through `.gitmodules`. 

Once these changes I'm very comfortable merging the Skill. Some really mature work here, huge thank you for all your efforts. 

### Non-functional checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> Check that the phrase 'home seer' is picked up by STT. `install homeseer` transcribed correctly, which mean that voice install will work when the Skill is pulled into the branch. 

> Check manual installation => OK

```
kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ source venv-activate.sh 
Entering mycroft-core virtual environment.  Run 'deactivate' to exit
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/samclane/homeseer-mycroft
INFO - Downloading skill: https://github.com/samclane/homeseer-mycroft
INFO - Successfully ran requirements.sh for homeseer-mycroft
INFO - Installing requirements.txt for homeseer-mycroft
INFO - Successfully installed homeseer-mycroft
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Run `dialog` files through `mimic` - 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> All Intents run through `mimic`, no likely Intent collisions, pronunciation is good on all the `dialog` files

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` are excellent, very specific use so will match phrasing well. 

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> This README fills me with joy and happiness. I wish every README was like. I want to give this README a gold star ;-) 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> `requirements.txt` does not specify versions. `requirements.sh` not used, file should be removed. 

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> `settingsmeta.json` not used, skipping check

#### Python code checks of the Skill

* Inline documentation - is the code documented in line?

> Code does not include a LICENSE - without an appropriate LICENSE I cannot merge this into the `mycroft-skills` repo. We use the Apache 2 license, but you're welcome to use a license of your choosing that allows us to distribute the Skill via Mycroft. 

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> all the libraries it calls are used

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> not used, skipping check

* Error handling - are there any specific checks we make for error handling or graceful degradation?

> error catching in place, fails with appropriate message to user

* Automatic tests - do automatic tests of the **Skill** pass?

> sure do

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> Skill Settings not used, skipping check

_NOTE: We do not enforce PEP8 Checks on Skills_

**Comment by samclane** [comment]
I have no idea why the skill test fails when I add the skill to git submodules. I've tried reverting and trying again 3 times. It seems to be unable to find/install `homeseer-mycroft`, even though it's being provided. Maybe you can make more sense of the output.

**Comment by KathyReid** [comment]
Run test
_this comment triggers a build and run tests again_

**Comment by KathyReid** [comment]
Hey @samclane I think this is an issue on our testing infrastructure, because the Skill was previously installed and checks ran OK/green. 

```shell
+ [[ 0 -gt 0 ]]
+ for SKILL in $@
+ echo 'Installing homeseer-mycroft'
Installing homeseer-mycroft
++ msm -u https://github.com/forslund/mycroft-skills.git -b skill_WTFhYp install homeseer-mycroft
+ MSM_OUTPUT='MsmException: Invalid branch: skill_WTFhYp'
+ RESULT=225
+ grep -q AlreadyInstalled
+ echo MsmException: Invalid branch: skill_WTFhYp
+ '[' 225 '!=' 0 ']'
+ break
+ '[' 225 == 0 ']'
+ echo 'Saving identifier...'
Saving identifier...
+ cp /root/.mycroft/identity/identity2.json /mnt/host
+ exit 225
fatal: 'mine' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Build step 'Execute shell' marked build as failure
Setting status of 215dda691036616c2ff1bfc60d4431663b154d4a to FAILURE with url https://jenkins.mycroft.team/job/18.02-skill-tester/501/ and message: 'Skill tests failed...
 '
Using context: Skill tester
Finished: FAILURE
```

@forslund - can we manually remove the installed Skill from Jenkins so that the test runner can complete successfully. Should I raise an Issue for this?

**Comment by forslund** [comment]
Seems the job lost it's credentials when it was renamed. Will investigate and fix. (Sorry for the inconvenience @samclane)

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Now the tester is running as expected but seems to be unable to launch the homeseer skill :/

**Comment by samclane** [comment]
Gosh, I have no idea what to do. I read over the console output of the Skiller Tester. and I can't really make any more sense of it than what you said. 

At this point, my only idea would be to start from scratch; Delete my forked repo, re-fork the repo, and add the submodule again. It would probably force another pull request, which would be a little dirty, but that's all I got...

**Comment by forslund** [comment]
Let me try it locally before doing something rash

**Comment by forslund** [comment]
This my traceback:
```
Traceback (most recent call last):
  File "/home/ake/projects/python/mycroft-core/mycroft/skills/core.py", line 122, in load_skill
    skill = skill_module.create_skill()
  File "/opt/mycroft/skills/homeseer-mycroft.samclane/__init__.py", line 223, in create_skill
    return HomeSeerSkill()
  File "/opt/mycroft/skills/homeseer-mycroft.samclane/__init__.py", line 44, in __init__
    self.hs = HomeseerInterface(self.config.get('url'), self.config.get('username'), self.config.get('password'))
  File "/opt/mycroft/skills/homeseer-mycroft.samclane/homeseer_interface/HomeseerInterface.py", line 32, in __init__
    if url[:4] != "http":  # ensure user-entered IP address has `http` prefix
TypeError: 'NoneType' object is not subscriptable
```

**Comment by forslund** [comment]
I believe as the config isn't created it errors out when receiving `None` values

**Comment by samclane** [comment]
Oh yeah, that's it for sure! If you don't have your config file set up it won't work. Is there any way around that? I have the required credentials for testing in `TESTING.md`.

**Comment by ghost** [comment]
if its the user IP, could that Homeseer test server be used?

**Comment by samclane** [comment]
@jhend7 We should be using the demo server that they provide us. If we gave it your credentials, testing the skill would cause your devices to change status as well (I didn't add a Testing Context to the Skill).

The config should contain this entry:

```json
  "HomeSeerSkill" : {
    "url" : "https://connected2.homeseer.com",
    "username" : "demo@homeseer.com",
    "password" : "demo100"
  }
```

**Comment by forslund** [comment]
@samclane I'll be posting a PR to your repo which shows how to mock out some of these things.

Sadly, at the moment mocking can't be done during the startup sequence which means the skill has to be able to load. (This is also considered good form, so intents that are hit can report back that it's not connected)

I'll be wedging in some temporary code for that purpose as well.

**Comment by samclane** [comment]
@forslund Is there a way to check if we're in testing or in production? So I can do something like this:

```python
# Overwrite config object with mock-config
if IS_TESTING:
  self.config = {
    "url" : "https://connected2.homeseer.com",
    "username" : "demo@homeseer.com",
    "password" : "demo100"
  }
```

Edit: I'll still look out for your PR. Just shooting off a potential idea.

**Comment by forslund** [comment]
Not with configuration, I'm afraid. In the 18.08 branch there is a settings field in the json file which can be used. Currently it's not used during `__init__()` but I will extend the possibility of the mocking to also work during skill creation. I can try to add a IS_TESTING member to the skill during loading

A note: we're moving away from using the configuration file for skills, it's recommended using the settings.json in the skill folder.

**Comment by samclane** [comment]
So if I add those parameters to a `settingsmeta.json`, so they're accessible through the web-interface, would it be able to take values then?

EDIT: Merged. Sweaty palms time.😬

**Comment by forslund** [comment]
No, the settings hasn't been downloaded on first use so they wouldn't register directly. The settings to use can however be entered in the testcase files

```json
{
  "utterance": "what are my settings",
  "intent_type": "WhatSettings.intent",
  "expected_dialog": "YourSettings",
  "settings": {
    "url": "http://fidgetspinner.org",
    "port": 1337
  }
}
```

(But again won't be available during `__init__`)

**Comment by forslund** [comment]
**Virtual High-five**

**Comment by samclane** [comment]
@forslund ~~Skill test failed again..~~

~~Is there any way I can see the stack trace, like you showed me earlier? I can only see the "Console Output", which is basically 50 different ways of saying "fail".~~

Page just updated and now it works!

**Comment by forslund** [comment]
Um, you must be reading the wrong log. This latest says SUCCESS

**Comment by samclane** [comment]
Great! Is there anything else I need to do? Like change from using config to using settings?

**Comment by forslund** [comment]
I'll leave it to the skills team to decide but since the tests are passing and the skill is verified to work when it's configured. I think it'll be good for now, moving to settings can always be done in an update.

Btw, I don't know if you've read about `msk` a small tool which is designed to help with the upload process here (so you don't need to do the git work manually)

`msk upload /path/to/my/skill`
`msk upgrade /path/to/my/skill`

Full docs here: https://mycroft.ai/documentation/skills/msk/

**Comment by KathyReid** [comment]
Tests pass, Skill has been validated by community, non-functional checks pass.
Merging to `mycroft-skills`, making it available for voice installation.

**Pull request merged**
