### PR TITLE
Add espy

### PR DESCRIPTION
**Pull request by Dark5ide**
## Info

This PR adds the new skill, [espy](https://github.com/Dark5ide/espy-skill), to the skills repo.

## Description

This skill has been created for the makers and hackers who want to build their own home automation system based on esp8266. the purpose of this skill is to be able to use mycroft to send commands to all esp8266s on the local network. the communication protocol can be selected (websocket, mqtt, http get).

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Run test

(this text triggers the Skill tester on Jenkins again)

**Comment by KathyReid** [comment]
Hi there @Dark5ide, we did a bit of digging to see why the Skill Tester was failing this Skill. The reason is that the Settings are not populated on first run, so it errors out. What we usually recommend here is setting some default values instead.

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 May 2019
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [ ] **Icon**  
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> needs an icon

- [x] **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> Needs to change Description to About - I made a suggested edit to the Readme.md file

- [] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> no constraints listed

- [ ] **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> there are no categories

- [ ] **Tags**  
Are listed tags appropriate for this Skill?

> there are no tags

- [x] **License**  
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> GPL-3.0

**Comment by krisgesling** [comment]
Thanks for the information review GPVM :slightly_smiling_face: 

@Dark5ide - to clarify slightly the tags are optional, however without a category listed, the Marketplace wouldn't know where to display the Skill by default.

As this pull request was made last year on the 18.08 branch, we also need to get it resubmitted to 19.02. So I'll close this PR, but if you are still keen to share your work with a broader audience, please use the new MSK command - `msk submit`. This replaced the numerous other commands and now works for both new and updated Skills. So to generate a new PR on the 19.02 branch just run:
`mycroft-msk submit /opt/mycroft/skills/your-skill`

Please let me know if you have any questions, or if we can help get your Skill included.

**Pull request closed without merging**
