### PR TITLE
Add learning

### PR DESCRIPTION
**Pull request by gras64**
## Info

This PR adds the new skill, [learning](https://github.com/gras64/learning-skill), to the skills repo.

## Description

This Skill helps to give Mycroft a personality by learning any new information that you provide.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by gras64** [comment]
if you want to add a new category. you just have to add a category under mycroft ai. Mycroft will then ask you for the name in your language.

**Comment by krisgesling** [comment]
Hey Andreas, I got a strange response with the latest changes. After starting the skill conversation, and being asked "which category is it", the skill then went through setting up new categories: 
> "I recognized a new category love, what would you like to call it?"
> My response: "love"
> "I recognized a new category science, what would you like to call it?"
> My response: "science"

It then resumed normal operation and asked for my question.

This is also where the integration tests are failing:
```
>> I recognized a new category , what would you like to call it?
22:34:35.979 - mycroft.skills.core:wrapper:1035 - ERROR - An error occurred while processing a request in Learning Skill
Traceback (most recent call last):
  File "/app/mycroft-core/mycroft/skills/core.py", line 1026, in wrapper
    handler(message)
  File "/opt/mycroft/skills/learning.gras64/__init__.py", line 129, in handle_interaction
    if catego in self.init_category(cat):
  File "/opt/mycroft/skills/learning.gras64/__init__.py", line 57, in init_category
    self.add_category(cat, path)
  File "/opt/mycroft/skills/learning.gras64/__init__.py", line 65, in add_category
    data={"cat": cat})
  File "/app/mycroft-core/test/integrationtests/skills/skill_tester.py", line 336, in get_response
    response = test_case['responses'].pop(0)
IndexError: pop from empty list
```

**Comment by gras64** [comment]
my tests were successful. it seems to be a problem with the variable possible categories that will i check tonight. categories are now separated only by comma such as "humor, love"

**Comment by gras64** [comment]
now I'm at a loss. I have reinstalled the skill extra and it works. also in English

**Comment by krisgesling** [comment]
Hi Andreas,

I'm finding that my settings are None rather than an empty string. As such this conditional evaluates to True:
```
if self.settings.get('allow_category_ex') != "":
    self.allow_category = self.settings.get('allow_category_ex')
```
This then means that `self.allow_category` gets set to `None`
and when you attempt to `split(",")` this variable on line 128 the Skill crashes with the following error:
> AttributeError: 'NoneType' object has no attribute 'split'
This is the error showing up in the integration test and on my local machine.

Rather than setting defaults and then checking if other settings exist, you can do both at once using:
`self.allow_category = self.settings.get('allow_category_ex', "humor,love,science")`
This would remove the need for all the `if self.settings.get() != ""` conditionals and better handle if remote settings are not available.

Does that make sense?

**Comment by krisgesling** [comment]
Hi Andreas,

I'll follow up with our team to see what's happening with settings.get() but I've sent you a PR with an alternative solution, along with a few other little things. 

Let me know what you think

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 May 2019
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [x] **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> I recommend the demonstration of how the Skill works (under Credits) plus the section 'Add a new Category' be moved to the About section.  I have proposed this edit to you from the readme file.

- [x] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> I proposed minor edits for grammar and spelling.  otherwise looks good

- [x] **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> no constraints listed

- [x] **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> Entertainment Information Productivity

- [x] **Tags**  
Are listed tags appropriate for this Skill?

> learning science

- [x] **License**  
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> Apache-2.0

**Comment by krisgesling** [comment]
## Meta  
* Platform: Debian Linux
* Mycroft-core version: 19.08.2
* Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft  
* Datestamp: 2019-10-24_21:46_UTC  
* Language and dialect of tester: English, Australian accent

## 0. Automated tests  
Are all automated tests passing?  
- [x] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> On line 118, the privacy path gets reassigned to `self.public_path` so it seems that everything will be saved in the public directory. Given this is not a real security mechanism this can probably get resolved in a future update.

- [x] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> No but not essential in this instance.

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

- [x] **Settings**  
Is the `settingsmeta` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

> The top-level "name" attribute has been deprecated, this is now pulled from the README to ensure consistency between the Marketplace and Skill settings. It will show a deprecation warning in the logs for users but otherwise will just be ignored. This can be removed in a future update.

- [x] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test/intent` folder?

- [x] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

## 2. Information Review - accurate and understandable  
Completed by GPVM

## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method: `mycroft-msm install https://github.com/gras64/learning-skill`
>  
> Checking that STT transcribes correctly
> Utterance: ['install learning skill']
> ```  
>  Best match (0.7): learning-skill.gras64 by gras64
> ```

- [x] **Settings**  
If skill includes a `settingsmeta` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Some of the English dialog could be tweaked for grammar, but it is all pronounced well by the TTS.

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [x] **"Do you want to learn something"**

> I like to learn, Which category is it?

- [x] **"science"**

> What is your question?

- [x] **"how far away is the moon"**

> give me keywords

- [x] **"distance to the moon"**

> What should I know about it

- [x] **"too far for a picnic"**

>  So I'm supposed to answer the question how far away is the moon with too far for a picnic?

- [x] **"yes"**

> _data saved, no verbal response_

> Some suggestions for future versions.
> - It might be good to have a very short final confirmation on save eg "Got it."
> - The unknown category dialog is worded as if it is a get_response(). I'm assuming that the intention is to add that in.


## Summary  
Sorry it's taken way too long to get this fully reviewed. I was meaning to come back to it a few months ago and then things run away. It's a great concept and I can see that there's plenty more in the works for the future.

Thanks for a great Skill :)

**Comment by krisgesling** [comment]
run test

**Pull request merged**
