### PR TITLE
Add date

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [date](https://github.com/MycroftAI/skill-date), to the skills repo.

## Description

Get the past, current and future date.  Dates are given in MM/DD/YYYY or DD/MM/YYYY
format based on the Date Format setting of your account at
[account.mycroft.ai](https://account.mycroft.ai/devices/preferences)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
This was added to test the Jenkins server. It will fail as it has intent conflicts with the Date-Time Skill.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1607)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1607/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1607/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1607/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1607/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1607/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1607)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1607/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1607/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1607/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1607/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1607/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
