### PR TITLE
New Skill - person detector

### PR DESCRIPTION
**Pull request by patilaum**
## Description:

This skill detects the number of persons in front of a webcam. It uses tensorflow for object detection.
The object detection module is to be downloaded from [(https://github.com/tensorflow/models/tree/master/research/object_detection)]
In the file __init__.py update MODEL_NAME = 'path/to/detection_graph/'

## Checklist:
- [x ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x ] Skill has been tested and works
  - [ x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x ] README.md has been updated with the following:
  ```
  +[submodule "person detector"]
  +	path = person-detector
  +	url = https://github.com/patilaum/mycroft-person-detect-skill.git
 ```
 - [x ] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by KathyReid** [comment]
Hi there @patilaum, thank you so much for your Skill Submission. 

The automated tests for this Skill have unfortunately failed; you can see the test output at; 
https://jenkins.mycroft.team/job/skill-tester/248/console

My quick reading of this is that `tensorflow` is a requirement for this Skill - is it listed as a requirement in `requirements.txt`? Is there any other reason that it would not be installed as a requirement - perhaps because it is a large library? 

Kind regards, Kathy

**Comment by el-tocino** [comment]
One other thing: in requirements.txt, unless you need a specific version of it, can you use >= instead of ==?

**Comment by el-tocino** [comment]
The contents of the mycroft-person-detect directory need to be one level up (in the root).

**Comment by KathyReid** [comment]
Hi @patilaum, just checking in on this one - let us know if you need some assistance with the requested changes :-)

**Comment by KathyReid** [comment]
Hi @patilaum, just checking in on this one - let us know if you need some assistance with the requested changes :-)

**Comment by KathyReid** [comment]
We haven't heard back from you on this one, so I'm going to go ahead and close this PR. Feel free to re-open / re-submit if you'd like to have the Person Detector Skill added to the official Mycroft Skills repo.

**Pull request closed without merging**
