### PR TITLE
Add hotCompagny

### PR DESCRIPTION
**Pull request by FoxBandyKoot**
## Info

This PR adds the new skill, [hotCompagny](https://github.com/FoxBandyKoot/hot-compagny-skill), to the skills repo.

## Description

Toast bread with the best toaster in the world, or the universe

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1496)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1496/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1496/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1496/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1496/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1496/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1496)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1496/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1496/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1496/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1496/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1496/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hi there,

Welcome to Mycroft. It's great to see you are exploring Mycroft Skill development.

The submission process you used is how you can submit your completed Skills to the public Skills Marketplace. Any Mycroft user will then be able to install the Skill either by tapping a button or saying "install name-of-your-skill".

For testing purposes you don't need to submit the Skill, you can install it on any Mycroft device by running:
```
mycroft-msm install https://github.com/author/skill-repo
```

It looks like the Skill you've submitted today is probably for your own testing and not quite ready for prime time. I will close the PR until you're ready to have it reviewed by our Skill Testing Team. You can read more about that [review process in our documentation](https://mycroft.ai/documentation/skills/skills-acceptance-process/)

Also if you haven't already please join our Community [Chat](https://chat.mycroft.ai/community/channels/skills) or [Forums](https://community.mycroft.ai/) if you have any questions or just want to chat with other developers and users.

**Comment by FoxBandyKoot** [comment]
Hello,

Thank you for your answer, and it was a mistake sorry, indeed, I am
discovering Mycroft Skill development.

Have a nice day,

Charly

Le mar. 23 mars 2021 à 05:19, Kris Gesling ***@***.***> a
écrit :

**Pull request closed without merging**
