### PR TITLE
Added submodule: nevermind-skill

### PR DESCRIPTION
**Pull request by ChanceNCounter**
**Name of your skill**: nevermind-skill
## Description:

Teaches Mycroft to be dismissed. When you speak the wake word, and then change your mind, Mycroft should certainly say something other than, "I don't know what that means!"

Includes a setting to disable verbal feedback, but does not currently include a mechanism for toggling that setting.

I haven't written any tests because I don't know what I'd test. There's no logic whatsoever. When the intent is matched, `if(verbal_feedback): speak_dialog("Okay")` and that's the whole skill.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works 
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] .gitmodules has been updated with the following:

```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have push any updates in the meantime be sure to run `mycroft-msk submit /opt/mycroft/skills/your-skill-dir` to update this pull request. Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by krisgesling** [comment]
I'm guessing you setup the submodule manually for this?

It looks like it's using SSH variant of the github remote URL. As the clients necessarily authenticated with Github this will fail to download the Skill. 

The best option is to use our Mycroft Skills Kit to submit. If you already have Mycroft installed on your system you can run:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`
This will setup the submodule and generate a PR for you.

In terms of tests, you can simply test that the utterances you expect to trigger your Skill do in fact get parsed correctly.  Something like:
```
{
    "utterance": "nevermind",
    "intent_type": "name.of.your.intent",
    "expected_dialog": "dismissed"
}
```
The `intent_type` or intent name goes inside the `IntentBuilder('')` portion of your handler decorator.

**Comment by ChanceNCounter** [comment]
Holy cow, it sure is using SSH! My embarrassing mistake. That'll get fixed with the rest.

**Comment by krisgesling** [comment]
All good, SSH is definitely the easier method for your own workflow. 

I like the simplicity of the Skill too, nice to have a way to quickly cancel an activation. 

We are also trying to tackle this problem by first reducing false activations, and second detecting if the captured audio is not a genuine utterance. Meaning if a false activation does occur, Mycroft can not respond, discard the utterance, and not shout to the room that they're learning new things everyday :yum:

**Comment by ChanceNCounter** [comment]
I was gonna nuke this PR and use the MSK, but I was already halfway there, so instead I've nuked this PR's commit =P the submodule is now using HTTPS, and the skill repo now contains a test.

**Comment by ChanceNCounter** [comment]
Well here's the epitome of "it works on my computer." Screw it, I'll go the other route.

**Pull request closed without merging**
