### PR TITLE
Add Wiktionary

### PR DESCRIPTION
**Pull request by TREE-Ind**
## Info

This PR adds the new skill, [Wiktionary](https://github.com/TREE-Ind/Wiktionary-Skill), to the skills repo.

## Description

Use this skill to request the definition of any word with just your voice.  By harnessing wiktionary this skill does not require any type of API key but is dependent on Wiktionary being up and accessible.

Further enhancements will include being able to ask about related words and parts of speech using conversational context.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by ricargoes** [comment]
I will start reviewing it now

**Comment by ricargoes** [comment]
## Meta  
* Platform: Linux
* Mycroft-core version: 19.2.6
* Who: [@ricargoes](https://github.com/ricargoes) / @ricargoes  
* Datestamp: 2019-06-25_18:38:23_CEST  
* Language and dialect of tester: Spanish from Spain (review made in English)

## 0. Automated tests 
Are all automated tests passing?  
- [x] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> Code is simple and straightforward

- [ ] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> The code is so simple that error handling is mostly not needed. However in line 23, there will be an unmanaged exception when the wiktionary query returns an empty array. Though it may not happen very often I would recommend to place some error handling, checking the returned list is not empty would be enough; a try .. except block would do the trick too but it would not be so clean.

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> It includes the wiktionary parser which makes sense

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

>  The only requirement (wiktionary) is listed in a requirements.txt. It could be a good idea to freeze the module version to prevent future updates to break compatibility.

- [x] **Settings**  
Is the `settingsmeta.json` file well laid out? If ssome error handling, checking the returned list is not empty would be enough; ettings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name ofwould do the trick too but it would not be
> No settings

- [x] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test` folder?

> There is just one test but it is enough given the simplicity of the skill. I would add another one to test the handling of errors as pointed above.

- [x] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

> No other files

### Actions Required:
* Add error handling in line 23

Everything else is good to go! And it is a very nice skill.

**Comment by ricargoes** [comment]
## Meta  
* Platform: Linux
* Mycroft-core version: 19.2.6
* Who: [@ricargoes](https://github.com/ricargoes) / @ricargoes  
* Datestamp: 2019-06-25_18:38:23_CEST  
* Language and dialect of tester: Spanish from Spain (review made in English)

## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method:  using msm in linux. Dependencies and skill were installed with no problem at all.
>  

> Checking that STT transcribes correctly: I did not try voice installation but I tested the STT of all words involved, specially 'wiktionary' (see below). Everything worked great. 

- [x] **Settings**  
If Skill includes a `settingsmeta` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> No settings

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Dialogs are simple enough

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [x] **"What is the definition of a computer"**

>> The definition of the word "computer" is: a machine for performing calculations automatically.
   The word "computer" has 1 other definition

- [x] **"find the definition for python"**

>> Here is the definition of python: A type of large constricting snake.

- [x] **"What is the definition of wiktionary"**

>> The definition of wiktionary is: Any on-line lexicon resembling Wiktionary.

- [ ] **"What is the definition of alkajdslkja"**

>> An error occurred while processing a request in Wiktionary Skill

> When asking for something wiktionary does not find, the skill returns an empty array and it tries to access the first element, crashing with an OutOfRange exception. Some kind of handling would be desired.

> I cheated to easily find a "strange word", I typed (=smashed the keyboard) instead of saying it out loud just to test the limits of the skill. I reckon it can be hard to find a speakable word with no entry in wiktionary but even so, the error handling should be very easy to include.

### Actions Required
* Create some error handling so estrange words with no entry in wiktionary make the skill crash. A quick validation or a try .. except block should be enough. Since the crash will not happen very often (if ever) this issue is not really a MUST-DO. However, given the solution is so easy to implement, I strongly suggest to do it.

On summary, a simple and nice skill which provides a very useful utility.

**Comment by ricargoes** [comment]
## Meta  
* Platform: Linux
* Mycroft-core version: 19.2.6
* Who: [@ricargoes](https://github.com/ricargoes) / @ricargoes  
* Datestamp: 2019-06-25_18:38:23_CEST  
* Language and dialect of tester: Spanish from Spain (review made in English)

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> It takes it from raw.githack.com

- [x] **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> All explanation are very clear and concise

- [x] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> The examples are representative and well chosen

- [x] **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> All devices are supported

- [x] **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> One category listed

- [x] **Tags**  
Are listed tags appropriate for this Skill?

> Definitely yes

- [ ] **License**  
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> No license

### Actions Required
* License

**Comment by TREE-Ind** [comment]
@ricargoes, Thank you very much for taking the time to review our skill.  We'll go ahead and add the basic error handling w/ corresponding test and get a license in there as well.

**Comment by TREE-Ind** [comment]
License and Error handling has been added.

**Comment by ricargoes** [comment]
Sorry for the delay, I was on holiday.

I reviewed the error handling, it looks good.
So everything is OK on my end.

**Comment by krisgesling** [comment]
Hey Josh, 

Thanks for updating the error handling. 

I can't however seem to see any license info. This I think we have to be very consistent on so I'm not comfortable merging this until it has the license file included. You probably already know this but just in case - you can add the license info in the browser by selecting a template license file. Github has instructions here: https://help.github.com/en/articles/adding-a-license-to-a-repository

Once this is done run `msk submit /path/to/your/skill` again to update this PR. 

Thanks

**Comment by krisgesling** [comment]
Excellent thanks Josh!

Looks like the "Wednesday bug" caused the test to fail so I'll rerun that after midnight and then merge.

**Comment by TREE-Ind** [comment]
run test

**Pull request merged**
