### PR TITLE
Upgrade national-park

### PR DESCRIPTION
**Pull request by richhowley**
'This upgrades national-park to include the following new commits:

 - [Remove API key](https://github.com/richhowley/national-parks-skill/commit/c340bec998ae7de772b5091da1fcaa81402be668)
 - [Remove unused regex files](https://github.com/richhowley/national-parks-skill/commit/3503ad4b01b1bec4ac3cbb322ae59e6d8cad0b7d)
 - [Move loacation from regex to voc](https://github.com/richhowley/national-parks-skill/commit/63c1beb8956f0f21a9274cabe75749ab0a1d5b36)
 - [convert total returned by API to int](https://github.com/richhowley/national-parks-skill/commit/be433729762087403f15cf1dd7eedc4f896e9762)
 - [Merge pull request #4 from devs-mycroft/translate-2019-01-27](https://github.com/richhowley/national-parks-skill/commit/708fa52220661792f92f6b41d6f74aed9dcc47d5)
 - [Merge pull request #3 from devs-mycroft/translate-2019-01-21](https://github.com/richhowley/national-parks-skill/commit/34b8d5f33c4b6692c61cb8fac8886804e1cef0e5)
 - [Merge pull request #2 from devs-mycroft/translate-2018-12-31](https://github.com/richhowley/national-parks-skill/commit/53cf8379453def9df2f5d4c6c359bb73bc00daf7)
 - [Update translations](https://github.com/richhowley/national-parks-skill/commit/bb98b0b423caee11d2a37697f237bf4b9afa396b)
 - [Update translations](https://github.com/richhowley/national-parks-skill/commit/5620280e49a1b3ab728625224c05c100f34485bc)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
A Weather Skill test is failing, high chance that it's not related to this skill, will take a closer look later in the week.

**Comment by forslund** [comment]
Run test

**Comment by trekjunky** [comment]
I would like to validate this on mycroft-core version 19 oh 2, release 11. How do I download the upgrade?

**Comment by krisgesling** [comment]
I find the easiest way is to first uninstall the skill by saying "remove national park skill", Mycroft will ask you to confirm. Then to install the latest commit from the master branch of a repo run:
`mycroft-msm --latest install https://github.com/richhowley/national-parks-skill`

**Comment by trekjunky** [comment]
I did it exactly the way you said and I still get an error...

*Cane Kostovski*
www.pc-tamer.com
__________________________________________
“Here, where a thousand
Captains swore grand conquest. . .Tall
Grass their monument.”
― Basho

"Too many people are beacons of light with hate for others...
If only some of that light would shine on them
showing them as they are, NOT as they wish they were!!!!!"
― Cane Kostovski
__________________________________________

**Comment by krisgesling** [comment]
Will message you on Chat to see what's happening

**Comment by LinusSkucas** [comment]
# Skills test for National parks skill 🌲🏞🌴🎋🎄🌳🌲
---

## Meta
*   Platform: Picroft
*   Mycroft-core version: 19.02
*   Who: [@LinusS1](https://github.com/linuss1) Mattermost/forum: brrn
*   Datestamp: 2019-07-12_10:35:08_PDT
*   Language and dialect of tester: (American) English

## 0. Automated tests
Are all automated tests passing?
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1.  Code Review - secure and stable
- [x]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

> Good.

- [x]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

> There are some try/except handlers with the api

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

>

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.
Also check to see if `requirements.txt` and `requirements.sh` are empty, if they are, they can be deleted.

> No deps

- [x]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

>Good.

- [x]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

>Yes!


- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

>Nope!


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

The Readme was not changed in this update.

## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method: `msm -l install https://github.com/rickhowley/national-park-skill.git`
> Output:
> ```
> I was unable to capture the actual log output, but it installed perfectly.
>
> ```
>
> Checking that STT transcribes correctly:
> ```
> Again, I couldn't get the log output, but it transcribed nicely.
>
> ```

- [x]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

>Looks good.

- [x]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

>Sound alright.

#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described. Also check that the sample utterances activate the skill

- [-]   **"List national parks in Utah."**

>It gave me a very long string of parks, which sounded bad with mimic 2 because it rushes on long sentences. Perhaps break it up into multiple dialogs, put commas in between the parks, and before the final one, put an `and` just to make it sound nicer. I'm not requiring this, it's just a suggestion.

- [x]   **"Tell me about Yellowstone national park"**

>~~This one the question and answers skill (the commonqa skill) picked this one up before your skill. Not sure how to deal with this, but this could mean making the skill at least a bit commonqa like. I'm going to ping @krisgesling because he knows better than I do on this on (but it'll take a while, he's currently gone.)~~
This now works nicely

- [x]   **"Quiz me on national parks"**

>Which state is Harpers Ferry park located in?
I then answered the wrong state, and the skill corrected me.


> This is a really great skill. Using Common qa could make getting information easier, so that is definitely something to consider, but I'm not going to hold this skill because of it.

-Linus

**Comment by richhowley** [comment]
Thanks for looking at the skill.

As documented in the README. it responds to:  "Describe Yellowstone national park"

Please try that.

**Comment by LinusSkucas** [comment]
@richhowley Thanks, I misread the readme: The review is corrected.

This skill is ready to be merged, and be updated.

**Comment by krisgesling** [comment]
Thanks for the review Linus, and of course to you Rich for the update!

**Pull request merged**
