### PR TITLE
Add tmdb-skill

### PR DESCRIPTION
**Pull request by builderjer**
## Info

This PR adds the new skill, [tmdb-skill](https://github.com/builderjer/tmdb-skill), to the skills repo.

## Description

Uses the TMDb api to call information about movies, actors, production companies and the like.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by builderjer** [comment]
I read the checks, and I'm not sure why it failed.  Can you explain?

**Comment by krisgesling** [comment]
It appears to be problem with the alarm skills test suite. We've been having a little trouble with it lately. Let me check it out properly tomorrow and I'll let you know if there's actually a problem.

**Comment by krisgesling** [comment]
If anyone else wants to look into it in the meantime, `008.delete.alarm.json` appears to be returning dialog to cancel 1 alarm, when there should be 2 alarms still set.

**Comment by builderjer** [comment]
I have submitted a couple of commits to this skill, mainly to clean up the code.  Everything but line length is pep8 compatibale now, but I still don't see any errors.  

I'm not sure I put them where the comment says, but I thought I did.  If not, the latest code is in the main repo

**Comment by krisgesling** [comment]
Hey, to get those latest commits into this PR, just run
`mycroft-msk upload /opt/mycroft/skills/your-skill`

This will also re-run the tests. 

No worries about the PEP8 line length either.

**Comment by builderjer** [comment]
It looks like this skill passed the tests this time!!

I would love to get some feedback on this.  Maybe some code streamlining?

**Comment by builderjer** [comment]
I did a bug fix, and now it is not passing the tests.  Once again, I don't think it is this skill, but the alarm skill

**Comment by builderjer** [comment]
Everything has passed, it would be great to get some feedback on this skill. @andlo , I added a couple more vocab and dialog files maybe you could translate for me and do a PR for them?  That would be great!!

**Comment by forslund** [comment]
Run test

**Comment by builderjer** [comment]
Nice!! Everything passed!!

**Comment by krisgesling** [comment]
Closing PR on old branch.

**Pull request closed without merging**
