### PR TITLE
Add time

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [time](https://github.com/MycroftAI/skill-time), to the skills repo.

## Description

Get the local time or time for major cities around the world.  Times
are given in 12-hour (2:30 pm) or 24-hour format (14:30) based on the
Time Format setting at [account.mycroft.ai](https://account.mycroft.ai/devices/preferences)

Time can optionally be shown on a display when it is idle, like a digital clock.  See
the [Skill Setting](https://account.mycroft.ai/skills).

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
This was added to test the Jenkins server. It will fail as it has intent conflicts with the Date-Time Skill.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1606)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1606/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1606/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1606/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1606/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1606/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1606)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1606/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1606/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1606/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1606/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1606/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
