### PR TITLE
Add find-restaurant-skill

### PR DESCRIPTION
**Pull request by TondiToday**
## Info

This PR adds the new skill, [find-restaurant-skill](https://github.com/TondiToday/orderr-food-skill), to the skills repo.

## Description

Ordering food

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi there, thanks for submitting your first Skill to the Mycroft Marketplace!

For a Skill to be accepted, they are first reviewed by our Community Team and before they did did that I wanted to check in around the Yelp API. 

Are there any restrictions or costs associated with it? Mycroft has over 30,000 users, and whilst not all of them will use your Skill, we don't want you to be out of pocket, or be violating the terms of a 3rd party service as your API key would likely be terminated and the Skill would stop working.

**Comment by krisgesling** [comment]
## Meta
*   Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft
*   Datestamp: 2019-04-27_14:54_ACST

## 1. Code Review - secure and stable  
- [ ] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> Looks good. Nice and simple API call.
> Would be best to remove the print statement on line 23. This keeps the CLI interface clean.

_Action Required: Please remove print statement on line 23_

- [x] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> General error used.

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Yes - Appropriate

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> NA

- [ ] **Settings**  
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

> Settingsmeta.json not required.

_Action Required: Please remove settingsmeta.json_

- [ ] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test` folder?

> No, it can be harder to write full tests for Skills like this, however a simple test to ensure your example utterance is triggering your intent can be very helpful. It is very useful for the project more broadly as we can use these to tell if other skills, or code changes are causing anything to break. There's more on [integration tests in our documentation](https://mycroft.ai/documentation/skills/automatic-testing/), but please let us know if you have any questions about them.

_Action Required: Add a simple integration test_

- [ ] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

> Looks like your IDE has created the .idea folder. These aren't necessary for the Skill and can be removed from the repo. You can add it to your `.gitignore` to prevent these files being uploaded to your remote repo while keeping them on your local machine. See https://git-scm.com/docs/gitignore for more about `.gitignore`.

_Action Required: Remove .idea folder from Github repo_

## Summary  
Great Skill, it will make a really useful addition to the Marketplace.

Please do consider if there will be any challenge using the public API, but in the meantime we'll get it reviewed by the Skill Testing Team.

Once you have completed any updates, you can update this pull request by running 
`mycroft-msk submit /opt/mycroft/skills/your-skill`

Thanks

**Comment by LinusSkucas** [comment]
# Skills test for Find restaurants skill 🥘 
 
## Meta
*   Platform: Picroft
*   Mycroft-core version: 19.02
*   Who: [@LinusS1](https://github.com/linuss1) Mattermost/forum: brrn
*   Datestamp: 2019-05-12_10:00:33_PDT
*   Language and dialect of tester: (American) English

I'm going to continue off from where @krisgesling left off. This is test 2/3 (the third one being a functional review)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

🛑 ⚠️ **Before the readme file can be throughly reviewed, please regenerate it using the meta editor: https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html**

- [ ]   **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> Unable to test - Please generate the readme with the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html)

- [ ]   **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

>First, please  generate the readme with the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html). The descriptions right now could use a bit of cleaning up:
 - The Title (The first "Find nearby restaurants") could be changed to Find restaurants.
 - The short description looks good 👍 
 - The long description could be improved to give the use a fuller understanding of the skill: (Example, don't feel like you have to use this):
```
Don't feel like cooking? Find nearby restaurants using this skill. This skill looks up restaurants nearby you and will suggest them to you!
```

- [ ]   **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> Please clean up the examples: Put in a apostrophe in `don't` 😄 
Also, consider adding more examples: the more the better!

- [ ]   **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

>Unable to test - Please generate the readme with the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html)

- [ ]   **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

>Unable to test - Please generate the readme with the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html)

- [ ]   **Tags**
Are listed tags appropriate for this Skill?

>Unable to test - Please generate the readme with the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html)

- [ ]   **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

>No license - please add one. Mycroft recommends using the Apache license, but you can choose any widely known license.


## Summary
 - [ ] Please add a license
 - [ ] Generate the readme with the meta editor
 - [ ] Do the general cleaning up explained in the tests


Once you have completed any updates, you can update this pull request by running `msk submit /path/to/skill/directory`

Just one thing that I noticed was that you can use `location` (or other location-like attributes) attribute of the MycroftSkill class: https://mycroft-core.readthedocs.io/en/master/source/mycroft.html#mycroft.MycroftSkill.location

Thanks! Can't wait to see this skill in the marketplace!

**Comment by gadgetguy08** [comment]
# Meta

      * Who: @gadgetguy08 
      * Datestamp: 2019-05-13_13:35_EDT
      * Language and dialect of tester:  English

This is my first go at reviewing and at using Markdown so it is a bit of a mess.

# 3. Functional Review - intuitive and expected

    

  * Installation



    Install method:mycroft-msm install 
    Output:  

Installed without errors.     
     

    Checking that STT transcribes correctly:

     
     

    

  * Settings
    I see some settings in the Mycroft Home screen, but not sure what they are for.
    
    

  * Dialog

    It understood me when I said "I don't feel like cooking" and "Find nearby restaurants".



  * Skill Functions

    I was unable to test further due to an error (see below).

```

14:01:24.242 - QuestionsAnswersSkill - INFO - Searching for what are nearby restaurants
14:01:34.137 - QuestionsAnswersSkill - INFO - Timeout occured check responses
14:01:34.352 - mycroft.skills.core:wrapper:1054 - ERROR - An error occurred while processing a request in Find Restaurant
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 1045, in wrapper
    handler(message)
  File "/opt/mycroft/skills/orderr-food-skill.tonditoday/__init__.py", line 35, in finding_restaurant
    restaurants = find_restaurants(message.data['place'])
KeyError: 'place'
~~~~04 - WolframAlphaSkill - ERROR - HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)
Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 937, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 799, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 583, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/mycroft/skills/fallback-wolfram-alpha.mycroftai/__init__.py", line 199, in CQS_match_query_phrase
    self.config_core['system_unit'])
  File "/opt/mycroft/skills/fallback-wolfram-alpha.mycroftai/__init__.py", line 109, in spoken
    'units': units}})
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 65, in request
    return self.send(params)
  File "/home/pi/mycroft-core/mycroft/api/__init__.py", line 136, in send
    data=data, json=json_body, timeout=(3.05, 15)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.mycroft.ai', port=443): Read timed out. (read timeout=15)   
```

# Actions Required

Not sure what is going on.

**Comment by el-tocino** [comment]
The URL errors aren't skill related in and of themselves, there appears to have been an external issue occurring.  https://community.mycroft.ai/t/is-api-mycroft-ai-down-or-am-i-doing-something-wrong/6472/7  Should also be fixed now.

**Comment by gadgetguy08** [comment]
Interesting.  The error still occurs even after removing the skill, reinstalling and rebooting several times.

**Comment by krisgesling** [comment]
Hey sorry @gadgetguy08 I completely missed this error in the middle:
```
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 1045, in wrapper
    handler(message)
  File "/opt/mycroft/skills/orderr-food-skill.tonditoday/__init__.py", line 35, in finding_restaurant
    restaurants = find_restaurants(message.data['place'])
KeyError: 'place'
```
You were correct, that is certainly the Skill failing. 

@TondiToday - there's currently no way for the Skill to receive `place` as this is defined in a separate intent file `place.intent`. This doesn't have a corresponding intent handler so will never get used. Looking at your dialog files though, I don't _think_ that's what you were aiming for.

Was your idea to first call `food.orderr.dialog` and ask the user:
`"What is your current location?"`
Then the user would respond with their location, which you can then pass to `find_restaurants`?

If so, you might want to take a look at the [get_response](https://mycroft-core.readthedocs.io/en/master/source/mycroft.html#mycroft.MycroftSkill.get_response) method. This can be as simple as:
`place = get_response(food.orderr)`
This would prompt the user with the dialog in `food.orderr.dialog` and assign the response to the `place` variable. Though I would suggest changing the name of that dialog file as well.

Another option would be to try `self.location` or `self.location_pretty` however I haven't used these myself, and at best I think you will get a city name, which may not be precise enough for your purposes.

I hope that helps, but please feel free to ask further questions here or in our [~Skills channel in Chat](https://chat.mycroft.ai/community/channels/skills).

**Pull request closed without merging**
