### PR TITLE
Upgrade theia-ide

### PR DESCRIPTION
**Pull request by andlo**
This upgrades theia-ide to include the following new commits:

 - [Merge pull request #24 from devs-mycroft/translations](https://github.com/andlo/theia-ide-skill/commit/708d10fae496b2533793e46b31fd79a793e999e6)
 - [Update translations](https://github.com/andlo/theia-ide-skill/commit/726d17c6614a72c2855b685e1b05d71c963911b6)
 - [more pyls](https://github.com/andlo/theia-ide-skill/commit/dbfb90042c9b142969bcc76ef4fb5f981f53b043)
 - [added linter and lang server to manifest.yml](https://github.com/andlo/theia-ide-skill/commit/b6f48155635b3ded1a5acb3b08975466027476e0)
 - [fix pep8](https://github.com/andlo/theia-ide-skill/commit/175aca8d59e3eb4650adfb36043e1cc2e2ff215e)
 - [added label to settingsmeta](https://github.com/andlo/theia-ide-skill/commit/5e19a2f4bd09bcde51c59290f0d9672e5c652ce5)
 - [fix settings on home](https://github.com/andlo/theia-ide-skill/commit/4f6acbda8916678420875bf7d43fd32ccdf26918)
 - [adding manifest.yml](https://github.com/andlo/theia-ide-skill/commit/d5a13fac671212c2528dc5f4be2888e289089d86)
 - [added info about settings on home](https://github.com/andlo/theia-ide-skill/commit/ca392c8163b79ef1c784ab53d0bb986a6223b7af)
 - [fixing settingsmeta.yaml](https://github.com/andlo/theia-ide-skill/commit/7418e9e178ec9f816151581676294ed5dde53912)
 - [more fix](https://github.com/andlo/theia-ide-skill/commit/8e8457e947e267dbd52e7fa0fcf73d2e3253020f)
 - [fix rmdir in build once more](https://github.com/andlo/theia-ide-skill/commit/28902581371acf400e960beed738b6716bca3190)
 - [fix remove folder in build](https://github.com/andlo/theia-ide-skill/commit/9a3fd59e54a642841f78198be8359996687456cf)
 - [fix safepath](https://github.com/andlo/theia-ide-skill/commit/e10bf350037804bcd585bdb3681da4c77d1ea1cd)
 - [fix platform check](https://github.com/andlo/theia-ide-skill/commit/ff2d31945781e0c1fd80b16ca5b07f0e41a024c0)
 - [minor fix](https://github.com/andlo/theia-ide-skill/commit/553b6f492b57a31d57d5ce05f118f6c525ecdfe5)
 - [some minor fixex](https://github.com/andlo/theia-ide-skill/commit/00895e95c4d13213d4e3e876e7311932761a34fe)
 - [adding workspace to home settings](https://github.com/andlo/theia-ide-skill/commit/7d2c65b5c7b6463b685a65c862d2c4daf53aa292)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/2051f1682299e2ec6b50979d8bd9201fd8f58ebf)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/8d8afa715b34adef5780c368e1810a40f2fdb217)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/cadf86e9bd55e0b0c23ef5cb1ca5324c06fd0576)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/7c12e2cb3450ba06fec38f148c7930da8d1fa159)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/77c638b28a94eafac8bae6b9604056d866d0632e)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/e9667e3a8baa6007f13ce4b4ba59be80940a8d55)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/e245fa1d29064e5b0a2aa686bed5257318083e4f)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/2a2b44b7330d69e3bd41f4d2c4b6e5eff43ea286)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/a0474bfbf18d6125e8ede9ec7cc561a5fd700286)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/1a9a22315db05d60b401903b5cc10279fdf00a87)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/36850d4b7c84f0912ef269cd8f7f5954c292282c)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/8428be8fe8353e9351988b5b8f5c41eaa934a769)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/30702bfe5ad361896735c14f85ef7de1bfb7af3c)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/908ea63e03b0509a58feaafdd5f35f60b2cc42a1)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/43b4f48c19ea3d6e3dab215fffa04ae94741318a)
 - [fix](https://github.com/andlo/theia-ide-skill/commit/72e8815c8fe4ef40eeff5a3e35919e6e364a01cc)
 - [small fix](https://github.com/andlo/theia-ide-skill/commit/1eb0a04a74ba712e11b4f2b98194f29fc5d6b968)
 - [fix unknwn install](https://github.com/andlo/theia-ide-skill/commit/1df4dc8fdbd50cd8978aa931402c8b73eee57e7a)
 - [fix for install on platform unknown](https://github.com/andlo/theia-ide-skill/commit/b7eccaf6dcbf47390a0887fc87a973c0ca01e180)
 - [Merge pull request #20 from andlo/new-way](https://github.com/andlo/theia-ide-skill/commit/c34ad7431c819193b8b1f3cb249fdc61c80ca2bc)
 - [...](https://github.com/andlo/theia-ide-skill/commit/db2a6648c5d8b30bd2b487f19f2ade5a50c395e3)
 - [...](https://github.com/andlo/theia-ide-skill/commit/ee2b5a4e24f5dbc6c0ed258140ee2f8f1f805c91)
 - [...](https://github.com/andlo/theia-ide-skill/commit/ca1af0affb6f74e439d16d3976dfafddb793ae70)
 - [fix stop problem](https://github.com/andlo/theia-ide-skill/commit/597b579c6552de64bb946df651fa3913c6221931)
 - [moved dialog and vocab to locale](https://github.com/andlo/theia-ide-skill/commit/76ea90175c183dee306e979bad7d0b74f7ed6384)
 - [...](https://github.com/andlo/theia-ide-skill/commit/fd1f1a10bb3a2b721290d6ff2970a1da6bdb2cb7)
 - [dialog files](https://github.com/andlo/theia-ide-skill/commit/429e6a06dfdf3dc46a857e1f539c1e066101ec92)
 - [..](https://github.com/andlo/theia-ide-skill/commit/dad12e361c931d73931e2d93026057fa3a6dd5be)
 - [fixes](https://github.com/andlo/theia-ide-skill/commit/0906867cd998df4ad269031abcd09d0932b5ee79)
 - [initial work](https://github.com/andlo/theia-ide-skill/commit/96007fa3af6f6c9b1efacaef218aa4af3c133b37)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by andlo** [comment]
To summer up this update include:
* Installer rewrite so picroft is downloading precompiled package and prepaired for other precompiled packages for other platforms. Installer wil always install latest Theia-for-Mycroft from https://github.com/andlo/theia-for-mycroft/
* Installer Builds and compile on systems where there isnt precompiled package for if system has more than 4 Gb memmory.
* No more support for Mark_1 as debian jessie isnt supported and theia cant build properly.
Added workspace setting on home.mycroft.at. Default to skills directory.
* Debug is working by using PTVSD, but requere remote-debug skill to activate and inject debug adaptor https://github.com/andlo/remote-debug-skill and change settings for padatious single_thread. remote-debug skills is at time of writing on way to market and PR to makea setting for controling padatious single_thread is on its way to mycroft.core.
* lots of fixes to set settings in the IDE best suitet for mycroft skills making.

**Comment by andlo** [comment]
I cant figure out why the skill tester fails...

**Comment by krisgesling** [comment]
Thanks Andlo, looks like a huge amount of work. 

Trying to get through our Skills backlog at the moment. There are a few outstanding so might be a little while. However we do have a new deal, anyone who conducts a Skill review for someone else gets their Skill prioritised. 

So if you want to jump the queue, we'd love to get more help for the Skill Testing Team in reviewing other peoples Skills :)

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
@andlo seems like a transient issue with a test in the weather skill. A re-run fixed it :) All nice and green checkmark now!

**Comment by andlo** [comment]
> So if you want to jump the queue, we'd love to get more help for the Skill Testing Team in reviewing other peoples Skills :)

I were thinking of joining the skils tester team....I have benen laying low from mycroft most of last year, but I hope to have more time this year :)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1165))

**Pull request closed without merging**
