### PR TITLE
Update translations for Number Guess and Crystal Ball

### PR DESCRIPTION
**Pull request by Arc676**
Updated translations as provided by Mycroft Translate. Reverted one incorrect translation.

Anything I need to know to prepare these skills for 19.02? I haven't followed Mycroft development lately; unfortunately I've been busy with other things.

### CODE REVIEW

**Comment by forslund** [comment]
Translations only, Merging (Error is the alarm Wednesday error)

**Comment by forslund** [comment]
@Arc676 I just noticed this was against the old 18.08 branch. Can you submit again against the 19.02 branch?

**Comment by Arc676** [comment]
@forslund Are there any changes I need to be aware of before resubmitting for the new branch, or can these skills be merged as they currently are with the new branch?

**Comment by forslund** [comment]
The skills were moved over to the 19.02 branch since they cleared the automatic tester so nothing major should be needed.

**Pull request merged**
