### PR TITLE
Add youtubedlp

### PR DESCRIPTION
**Pull request by ghost**
## Info

This PR adds the new skill, [youtubedlp](https://github.com/pjalsGit/youtubedlp-skill), to the skills repo.

## Description

Plays videos from youtube using youtube-dlp.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1580)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1580/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1580/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1580/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1580/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1580/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

At a quick glance there were a few things I wanted to flag: 
- Your `manifest.yaml` uses tabs however YAML doesn't support them. So the installation of the Skill is currently failing. Just replacing the tabs for spaces should get it going.
- You can delete the `requirements.txt` file as the python packages are already included in your manifest.
- Because a lot of Skills can "play {things}". There is a Common Play Framework that we use for any Skill wanting to respond to these commands. More information on that [here in our docs](https://mycroft-ai.gitbook.io/docs/skill-development/skill-types/common-play-framework).
- The `settingsmeta.yaml` appears to be the default dummy contents. So this can also be deleted.
- You might also be interested in some of the filesystem methods we have available. These ensure your Skills data is saved to a namespaced location that will work on any Mycroft system: https://mycroft-ai.gitbook.io/docs/skill-development/skill-structure/filesystem


If you make any updates to your Skill, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

**Comment by ghost** [comment]
did i make it ***more*** compatible with the standards?

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1580)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1580/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1580/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1580/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1580/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1580/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1580)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1580/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1580/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1580/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1580/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1580/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hey there, it looks like you're on the right track.

You might also be interested in seeing some of the existing Youtube Skills that exist: https://github.com/search?q=mycroft+skill+youtube
Take note of when they were last updated - this will indicate how actively they are being worked on.

**Comment by ghost** [comment]
> Hey there, it looks like you're on the right track.
> 
> You might also be interested in seeing some of the existing Youtube Skills that exist: [github.com/search?q=mycroft+skill+youtube](https://github.com/search?q=mycroft+skill+youtube) Take note of when they were last updated - this will indicate how actively they are being worked on.

i know about those skills, but none of those have what i want (using youtube-dlp, which is much faster and doesn't have its development halted)

**Comment by krisgesling** [comment]
Yeah cool - I just wanted to make sure as it's easy to miss things that are out on Github.

**Comment by ghost** [comment]
by the way, whats with the CI failing, is that normal?

**Comment by krisgesling** [comment]
I think it's failing on your system dependency. Try a manifest.yml of:
```
dependencies:
  python:
    - yt-dlp
    - urllib

  system:
    all: vlc
```

If I'm right then it's something that it should be able to handle, as intuitively you think of them as a list of packages.

**Comment by ghost** [comment]
i thought i removed the need for vlc?

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1580)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1580/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1580/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1580/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1580/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1580/logs/enclosure.log)

**Pull request closed without merging**
