### PR TITLE
Upgrade theia-ide

### PR DESCRIPTION
**Pull request by andlo**
This upgrades theia-ide to include the following new commits:

 - [changes to readme.md](https://github.com/andlo/theia-ide-skill/commit/99e3cd6f983539e7c2166ecd3a617d0b873a2fdc)
 - [update screenshot](https://github.com/andlo/theia-ide-skill/commit/6e8b1fcd8008c23b5c82a94afcff48e56622b17b)
 - [...](https://github.com/andlo/theia-ide-skill/commit/00ad39cd82b2c698a328c09eea2d6b07e88822be)
 - [Readme update](https://github.com/andlo/theia-ide-skill/commit/aea2d0cd2f0dd61285565bc38015559e6eb35ab9)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Andreas,

Did the Mark 1 version stop working or the firewall just makes this too difficult?

A few comments on the README changes:
- The one line description immediately under the title will get cut off on the card view of the Marketplace. You get roughly 50 characters of space there (as it's a variable-width font this is not exact). This is totally up to you, it won't prevent the update being merged, but just wanted to let you know.
- We need the description heading to be called "About" so that our scripts parse it correctly, otherwise I don't think it will detect that the description exists so will show blank in the Marketplace.
- For installation methods, you can also say "Hey Mycroft, install I D E" and your skill returns a 62% confidence which is sufficient to match and prompt a confirmation to install.
- For updating, this should update automatically as new versions are pushed to the Marketplace. Please let us know if you don't think this is happening.
- the changes made under Git Integration seem to have added some typo's, some possible wording would be:
> The IDE does not have a way to ask for your Github username and password. For seamless integration, you can set Git to remember your username and password by entering three `git` commands. This can be done in the terminal directly in the IDE.

I'll have a look at those new dependencies when I have a moment too.

**Comment by andlo** [comment]
> The one line description immediately under the title will get cut off on the card view of the Marketplace. You get roughly 50 characters of space there (as it's a variable-width font this is not exact). This is totally up to you, it won't prevent the update being merged, but just wanted to let you know.
> We need the description heading to be called "About" so that our scripts parse it correctly, otherwise I don't think it will detect that the description exists so will show blank in the Marketplace.
> 
I now made some changes to the readme.

> For installation methods, you can also say "Hey Mycroft, install I D E" and your skill returns a 62% confidence which is sufficient to match and prompt a confirmation to install.
Added this to readme aswell

> For updating, this should update automatically as new versions are pushed to the Marketplace. Please let us know if you don't think this is happening.
That is normal behaivor of a skill, but this skill pulls down a precompiled package, and that won be updated just because the skill is. The actual IDE is only updated when new package is pulled down. And I hasnt made a way to update automatly when I compile a new precompiled package.

> the changes made under Git Integration seem to have added some typo's, some possible wording would be:
I made changes to readme for this aswell

About mark 1, I hassnt made any new pckages for a while, as it is difficult to get it working on raspbian jessie - not only because the firewall, but because git integration dosnt work because old version of git on jessie. And on top of that my mark 1 is broken :( So I thaught removing support for mark 1 is the easiest way until mark 1 is on strech some day. 
Ill expect to make a mark 2 support as soon I have a mark 2. And are thinking of making a native linux installation to - but this part I am not sure about. Does people working on a "real" computer not also have a prefeared IDE ?

I just made a new build of the precompiled package, and are relly close to get debugging to work. I face some issues on ptvsd on arm, but are working upstream on fixing that as I located where it is erroring. I can get it to work but not in a nice easy way, but if the errors in ptvsd are fixed, debugging should be easy to activate :) 

Last comment - Ill expect soon to be able to brand the IDE so adding mycroft logo etc, and when that is posible I would like to rename the skill to Mycroft IDE. I also are looking at adding mycroft documentation and acces on menu to control mycroft services, but are alo here facing some issues (links in the documentation are not relative making it difficult to include it. But could maybe fixed by parsing all the docs before including it. But would prefear to point to the real documentation and not a parsed copy.

**Comment by krisgesling** [comment]
Hey, what happened to the Mark 1? Is it a software or hardware problem? 
If there's anything we can do to help, let us know. You do so much for Mycroft and the community!

> And are thinking of making a native linux installation to - but this part I am not sure about. Does people working on a "real" computer not also have a prefeared IDE ?

I think you are correct that it's less likely to be used by people running Linux as their main OS. However we've seen more people using Mycroft inside a VM running something like Ubuntu server, so this could still be really useful for them to have a full GUI IDE.

**Comment by andlo** [comment]
> Hey, what happened to the Mark 1? Is it a software or hardware problem?
If there's anything we can do to help, let us know. You do so much for Mycroft and the community!

Mark 1 is running on raspbian jessie and that is someway outdated. Git is on an old version and cant be used in integration. I did compile git and include it in the mark 1 package, but that were difficult and not fun. 
So I think that trying to get Theia working forward and not on old software is the way to go.

It would be much better to get mark 1 to run on newer raspbians and be more "compatible" with picroft. 

> more people using Mycroft inside a VM running something like Ubuntu server, so this could still be really useful for them to have a full GUI IDE.
Yah that sounds like a good usecase. And as we dont know the platform a generic install is needed. I think I can make that as one may expect that there isnt same restrictions on rescourses as on a Raspberrypi making compilation much easier and faster.

**Comment by krisgesling** [comment]
Finished checking this out, looks good to me :)

**Pull request merged**
