### PR TITLE
Add fairytalez

### PR DESCRIPTION
**Pull request by andlo**
## Info

This PR adds the new skill, [fairytalez](https://github.com/andlo/fairytalez-skill), to the skills repo.

## Description

This skill enables Mycroft to tell lots of fairytales. So make a cup of coco, and sit back and enjoy listning to the good tales.

Content is from fairytalez.com, so please go visit there if you like the stories.
Fairytalez.com is the world's largest collection of fairy tales, fables and folktales. Discover more than 2,000 classic tales plus new stories by fairy tale fans.
http://www.fairytalez.com

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
## Meta

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.10, `dev` branch
* Who: @kathy-mycroft / @kathyreid 
* Datestamp: Tue  8 Jan 16:39:11 UTC 2019
* Language and dialect of tester: Native English speaker, Australian accent

## Standard checks 

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.
> This is the first time this has been submitted to `mycroft-skills`, checking for STT transcription
`~~~~0 - __main__:handle_utterance:62 - INFO - Utterance: ['install fairy tales']`
> proceeding to `msm install`

```
(.venv) kathyreid@kathyreid-ubuntu-X510UQ:~/mycroft-core$ msm install https://github.com/andlo/fairytalez-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/andlo/fairytalez-skill
INFO - Successfully installed fairytalez-skill
```
> Installed OK

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.
> Ran each `dialog` file through `mimic`. Made several PRs based on this review; 
* https://github.com/andlo/fairytalez-skill/pull/7
* https://github.com/andlo/fairytalez-skill/pull/6
* https://github.com/andlo/fairytalez-skill/pull/8

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> I added a PR to add some more natural speech phrases here;
https://github.com/andlo/fairytalez-skill/pull/9

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._
> README looks good

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 
> there is no `requirements.txt` but this Skill uses BeautifulSoup - should it be in `requirements.txt`?

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?
> not used, skipping check

## Python checks

* Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL? 
> Yes, GPL 3

* Inline documentation - is the code documented in line?
> not a lot of inline documentation; consider adding some in future versions

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> OK, just uses BeautifulSoup

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> handled well in code

* Automatic tests - do automatic tests of the **Skill** pass?
> yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

## Functional check

* `Hey Mycroft, tell a fairytale`
> "What would you like to hear, I have thousands"
> `Red Riding Hood`
> "Do you mean Little Red Riding Hood"

Story was successfully chosen as Little Red Riding Hood and played back using the Librivox recording. 

* `Tell me a good story`
> Tried this a few times and it correctly selected a story each time.

Functionally passing

## Summary
Thanks so much @andlo for this Skill! Some more great work! Just a couple minor changes and we can merge this; 

* Please merge the PR for new `dialog` changes
* Please merge the PR for new `vocab` changes
* Please confirm whether BeautifulSoup should be listed in `requirements.txt`

**Comment by andlo** [comment]
Did add bs4 to requerements and your good PR's to dialog and intent files. Thanks.

**Comment by KathyReid** [comment]
Thanks so much @andlo! Lovely work. 
The Skill Tester is doing the Wednesday-alarm-fail error, so I am overriding and merging. 
Mange tak :-)

**Pull request merged**
