### PR TITLE
Add mattermost

### PR DESCRIPTION
**Pull request by domcross**
## Info

This PR adds the new skill, [mattermost](https://github.com/domcross/mattermost-for-mycroft-skill), to the skills repo.

## Description

In your skill settings at home.mycroft.ai you must enter your username (as given in Mattermost account settings) and your personal access token. In case you do not have a token you can specify your login-id (usually that is your email) and your password. NOTE: your password will be stored in clear text in your settings.json!)

There is also the option to set the time interval between refresh/check for updates. When monitoring is active the skill will use that time period for automated checking.
The option "notify on updates" is only applicable when monitoring is active - when option is activated Mycroft willl speak out loud the number of unread messages and mentions.

You can also specify the server configuration. Default settings are for chat.mycroft.ai so you should already be ready to go. NOTE: change anything here and you are on your own! ;-)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi @domcross, 

Thanks for putting this skill together, it looks great!

Before we do a full review I want to have a chat with our team about enabling Personal Access Tokens on chat.mycroft.ai so that users can use this option instead of entering their username and password into the settings. I see that you flagged this as a warning to users which is great. Just hoping we can avoid it altogether!

Three other quick things I noticed while they're on my mind:
- Your 'requirements.txt' lists the `python-Levenshtein` package but I can't see it being used, does that still need to be there? 
- For fuzzywuzzy, is there a reason not to allow future updates of that package?
- The dialog in `skill.not.initialized.dialog` has a typo in the "home.mycroft.ai" url

Will get back to you soon regarding the tokens though :)

**Comment by domcross** [comment]
Hello @krisgesling 
Thanks for looking into this PR. Here are some quick answers to your questions:

- The `python-Levenshtein`gives improved performance for fuzzy matching and is automatically used by `fuzzywuzzy` when present.

- Regarding the version requirements - to be honest I have copy&pasted this from another skill. I see no reason why newer package version shouldn't be allowed. I have pushed an update with less strict requirements.

- I have also pushed a fix for the typo in `skill.not.initialized.dialog` and added license information to `__init__.py`.

**Comment by krisgesling** [comment]
## Meta

*   Platform: Linux - Debian Buster
*   Device version: 18.8.11
*   Who: [@KrisGesling](https://github.com/KrisGesling) / @gez-mycroft
*   Datestamp: 2019-01-30_15:31:18_ACST
*   Language and dialect of tester: Native English speaker, Australian accent

## Standard checks

*   Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is the first time the Skill has been submitted; not available for voice install.
> Using `msm install`
```
(.venv) kris@bigBench:~/mycroft-core$ msm install https://github.com/domcross/mattermost-for-mycroft-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Installing requirements.txt for mattermost-for-mycroft-skill
INFO - Successfully installed mattermost-for-mycroft-skill
```

> Checking that STT transcribes correctly;
> `__main__:handle_utterance:62 - INFO - Utterance: ['install mattermost for minecraft']`  
> `msm.mycroft_skills_manager - INFO - Best match (0.64): mattermost-for-mycroft-skill.domcross by domcross`
> and my personal favourite, that still picked up the right skill...
> `__main__:handle_utterance:62 - INFO - Utterance: ['install mac and moist for microsoft']`
> `msm.mycroft_skills_manager - INFO - Best match (0.39): mattermost-for-mycroft-skill.domcross by domcross`

_Successfully installed_

*   Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Most dialog is great and easy to understand. Given the frequency of usage for message.dialog it would be useful to add extra pauses in and between each message.
> 

_ACTION REQUIRED: Consider adding extra pauses to message dialog eg "{create_at}, user {user_name} wrote: {message}."_

*   Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Clear intents, conflicts unlikely. Some trouble with triggering specific intents described in functional tests.


*   Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

*   Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).

> README is clear.
> Three minor spelling mistakes [MAttermost, perioed, Ende]

_ACTION REQUIRED: Please consider changes to README.md_

*   Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> appropriate requirements usage

*   Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> appropriate use of settings, well laid out
> Is the "Verify" setting required? It looks like this should be unchecked if using a self-signed certificate on the mattermost server, is that right? Given this won't be the case can we remove it? Or provide some more descriptive text to explain it's purpose if we want to give users the ability to use this on other servers.

_ACTION REQUIRED: Review need for "verify" setting or update description._

## Python code check

*   Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL?

> Yes, Apache2 license used

*   Inline documentation - is the code documented in line?

> Minimal but sufficient inline documentation

*   Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> appropriate library usage, however worth noting that mycroft-core has [mycroft.util.parse.fuzzy_match](https://mycroft-core.readthedocs.io/en/master/source/mycroft.util.parse.html#fuzzy-match) and [mycroft.util.parse.match_one](https://mycroft-core.readthedocs.io/en/master/source/mycroft.util.parse.html#match-one). These would remove the need for an external fuzzy matching library.

*   Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> n/a

*   Error handling - are there any specific checks we make for error handling or graceful degradation?

> error handling implemented, passing exceptions to general error message

*   Automatic tests - do automatic tests of the **Skill** pass?

> Two tests provided for activating and deactivating monitoring.
> Tests failing due to lack of required configuration options from user settings
> Could have a single test that checks to see if skill.not.initialized.dialog is properly called instead?

_ACTION REQUIRED: Please revise integration tests_  

*   Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4\. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> N/A

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional tests

*   "Are there unread messages on Mattermost"

> unread messages and mentions provided correctly

* "Name Mattermost channels with unread messages"

> unread and mentions provided correctly for each channel

* "Read messages for channel random"

> I could not get this intent to fire in this format. It was always interpretted as "4-channel" instead of "for channel". Adding "the" resolved this.
> Consider updating the example in the readme.md to be "Read messages for the channel {name}"

* "Read messages for the channel random"

> messages read correctly

* "read all unread messages"

> only triggered unread.messages.intent providing number of unread messages but not reading them.

* "read all unread mattermost messages"

> messages read correctly

* "Begin monitoring of mattermost"

> started monitoring on schedule correctly

* "End monitoring of mattermost"

> Could not get "end" to be recognised. Consider changing "end" to "stop"

* "Deactivate mattermost monitoring"

> monitoring deactivated correctly

_ACTION REQUIRED: Review and update "Read all unread messages" and "End monitoring of mattermost" intents_


## Summary

*   Please consider adding extra pauses to message dialog eg "{create_at}, user {user_name} wrote: {message}."
*   Please consider changes to README.md
*   Review need for "verify" setting or update description
*   Please revise integration tests
*   Review and update "Read all unread messages" and "End monitoring of mattermost" intents

It is an excellent skill though, well done! Thanks for putting in so much effort on it too!

**Comment by domcross** [comment]
Hello @krisgesling,

>  Please consider adding extra pauses to message dialog eg "{create_at}, user {user_name} wrote: {message}."

Changed the dialog as suggested, I also added a 300msec pause between each message

>   Please consider changes to README.md

Fixed typos and updated README

>    Review need for "verify" setting or update description

"Verify" setting is used to turn on/off validation for SSL certificates when using "https", I changed the label in settingsmeta.json to clarify this.

>    Please revise integration tests

Deleted the existing tests and replaced it by one which checks for "skill not initialized" as you have suggested.

>   Review and update "Read all unread messages" and "End monitoring of mattermost" intents

Updated the vocab, but I am afraid "stop ..." will interfere with the mycroft-stop skill?

I have also pushed some more fixes to some issues and PRs (credits go to @andlo for providing Dansk translations)

**Comment by krisgesling** [comment]
Hi @domcross, 

I asked some of the skill testing team to have a go at triggering these intents as my Australian accent can also be the problem at times. There were able to get the "end" to work which probably confirms the accent problem. However they also raised some other questions. 

Regarding the intents, whilst they are working ok, "Mattermost" is not a common word and so Mycroft will always have a little trouble picking it up. Whilst something like "Monitor (mycroft|minecraft) chat" would be much more likely to work for more people. "Minecraft" is a common mis-transcription, so worth having in there too.

This then raised a question around whether many people knew that the Mycroft Chat service was using Mattermost as the underlying platform, and whether using "Mycroft Chat" instead of "Mattermost" would encourage more people to install and use it.

The skill is certainly at a point where it could be added to the Marketplace, however the testing team felt that it could be even better with a few tweaks to the intents. So I wanted to raise those two questions, and see what you thought?

**Comment by domcross** [comment]
Hi @krisgesling 
I pushed another update: "Mattermost" and "Mycroft Chat" can be used as synonyms in the intents. 

If I understand correctly then you also suggest to rename the skill name from "Mattermost" to "Mycroft Chat". I would be happy to do that but I am not sure how to do that - do I have to rename my repository?

**Comment by krisgesling** [comment]
Thanks Dom, if you're happy to change the name, the easiest approach would be for us to close this PR; change the title in README.md; then run `mycroft-msk upload /path/to/skill` to create a new PR and enter the new skill name when prompted.

Feel free to change the primary monitoring intent back to "end" after others tested, I think that's just my accent, and as you said it does have potential conflict with the overall stop command.

I did notice that now if it hears "are there any unread messages on minecraft chat" it repeats  "minecraft" as the service back to the user as it's an accepted term in the service vocab. If I delete "minecraft" from `service.entity` it still registers "are there any unread messages on minecraft chat" and responds with mattermost as the entity. So you could delete minecraft, or add a line of python to reassign service from "minecraft" to "mycroft".

I'll close this PR so you can create a new one, but thanks for sticking with these changes. We want to make sure users get the best experience possible.

**Pull request closed without merging**
