### PR TITLE
Add todo-list

### PR DESCRIPTION
**Pull request by J-Priebe**
## Info

This PR adds the new skill, [todo-list](https://github.com/J-Priebe/todo-skill), to the skills repo.

## Description

Simple to-do list manager that supports the following actions:
- List items on you to-do list
- Complete items
- Delete (archive) items
- Suggest a random item
- Report completion statistics

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1473)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1473/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1473/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1473/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1473/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1473/logs/enclosure.log)

**Comment by J-Priebe** [comment]
Hello, this skill is somewhat similar to the existing "List Manager" skill in the marketplace, but it is more specific to to-do lists and a bit more gamified. I felt it was different enough to warrant a PR, but if the community feels differently I will close it :) 

Also, from the docs I'm not too clear on the standard practice for tests - the Skills Acceptance doc directs to an article on the "Old Test System", presumably there is another standard now? Happy to add tests if there is interest this skill.

**Comment by krisgesling** [comment]
Hi James, certainly space for more Skills! Congratulations on your first Skill :tada:

Thanks for pointing out that link too, it is now pointing to the new Voight Kampff system here:
https://mycroft-ai.gitbook.io/docs/skill-development/voight-kampff

Something has failed in the test runner when it was sourcing your Skill which has caused the devops-mycroft comment above. I'll need to look into that. 

A few quick things for your Skill:
- you can delete settingsmeta and manifest files if you aren't using them
- using strings in your `speak_dialog` calls means that others can't translate the Skill without forking it. These can be added into your `local/en-us/` directory. I've just updated the [docs on Statements](https://mycroft-ai.gitbook.io/docs/skill-development/user-interaction/statements) with more of this detail as they were on my todo list anyway.

**Comment by J-Priebe** [comment]
Thanks for the quick feedback @krisgesling . A question about tests: this skill is backed by a sqlite3 db, and to test nontrivial scenarios I need to seed the db with some existing items (and wipe the db at the end of each test). I figured out how to add custom test steps and "given" statements... However I can't just write to the "production" db every time I run tests, for obvious reasons :smile: 

Do you have suggestion on how I can implement db setup/teardown after each test? I suspect I can specify an environment in the skill's settings, and use some init code to choose a db path depending on the environment, but A) I'm not sure how to override settings in a test, and B) this doesn't really solve the teardown problem - I believe the skill is only initialized at the beginning of the test suite and not after each test.

**Comment by krisgesling** [comment]
Hey, we don't currently have a way to overwrite settings per test, though there is a feature request for it, and one of the blockers for it has been removed:
https://github.com/MycroftAI/mycroft-core/issues/2633

You are correct, the Skill is only initialized once. It would be possible to throw in a hack to make it reload but I think that would be asking for pain...

@chrisveilleux have you thought about this scenario before for VK tests? Any suggestions for how James might approach this?

**Comment by J-Priebe** [comment]
Barring a more robust solution, if there were any way at all for a `MycroftSkill` instance to detect it's running in a test environment (an env var, etc) I think I could hack it with a custom Step that nukes the test DB at the beginning of each test.

Also, my 2 cents from an outside perspective is that **environment/dev settings** is conceptually different from **config/user/product settings**; the former shouldn't really be touched by the end user. It would be cool to have something a la [Django Settings](https://docs.djangoproject.com/en/3.1/topics/settings/) allowing you to specify a settings module/env file upon initialization. Anyway, I don't mean to open a rabbit hole :)

**Comment by krisgesling** [comment]
Would it be worth setting the device platform attribute to "CI" or something? 

Then you can do things like:
```Python
platform = self.config_core['enclosure'].get('platform', 'unknown')
if platform == 'CI':
    print("*Jedi hand wave* everything is fine")
```

Not ideal, but would be a simple change.

**Comment by J-Priebe** [comment]
I think that would work! Just to clarify, does this already exist (`platform = 'CI'` in the test runner)?
Is there a risk that would screw up existing tests from other skills which are platform-specific?

EDIT: after doing a little digging I get the following output for  `self.config_core.get('enclosure')` while running tests:
```
{'port': '/dev/ttyAMA0', 'rate': 9600, 'timeout': 5.0, 'update': True, 'test': False}
```
It seems like that test flag may be suitable for this, and that it *should* be set to `True` in this scenario.

I also dug through `runner.py` a little which suggests you can specify `test.env` files, but I can't grok how they are used or find any examples.

**Comment by J-Priebe** [comment]
Further update: I modified `config.py` and `behavior.py` to load an additional `.conf` file in the VK test runner. It seems like a decent unobtrusive change to me. I'll make a feature request/PR.

**Pull request closed without merging**
