### PR TITLE
Upgrade mycroft-volume

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-volume to include the following new commits:

 - [Merge pull request #33 from MycroftAI/feature/percent](https://github.com/MycroftAI/skill-volume/commit/410472c1234c8f8bab595df95834cda050446b0a)
 - [Minor cleanup](https://github.com/MycroftAI/skill-volume/commit/a8c19ae1bfa36b78132d16f80f4cf0139abd9794)
 - [Add handler for setting volume in percent](https://github.com/MycroftAI/skill-volume/commit/0fdee423c23a7dcafe0b57c60fd0f390f84a8ccb)
 - [Merge pull request #32 from krisgesling/patch-1](https://github.com/MycroftAI/skill-volume/commit/953c8015a484100b42c19a5decc44dcf1de558ef)
 - [query handler: level set using __volume_to_level](https://github.com/MycroftAI/skill-volume/commit/7ef8428fb3261abea1d32fd1754f529c5037d98d)
 - [Merge pull request #31 from MycroftAI/bugfix/round-answer](https://github.com/MycroftAI/skill-volume/commit/58839904a0b6ad1282b18b346acc904fa61b5952)
 - [Round the volume before returning it](https://github.com/MycroftAI/skill-volume/commit/1ca489ca62523051452cd008c127f40547701118)
 - [Merge pull request #30 from devs-mycroft/translate-2019-01-27](https://github.com/MycroftAI/skill-volume/commit/96081367763442b09b7a272c02c783b4cb0b284f)
 - [Update translations](https://github.com/MycroftAI/skill-volume/commit/2bb59f81f9ff8a14bc985d49b0d372db5c72d3df)
 - [Merge pull request #28 from devs-mycroft/translate-2019-01-21](https://github.com/MycroftAI/skill-volume/commit/46e1e89fd08d57e770bbd64fff7eef10d5021667)
 - [Update translations](https://github.com/MycroftAI/skill-volume/commit/172f1eca620a23df2febff86303003ddc0df6a54)
 - [Merge pull request #27 from luke5sky/patch-1](https://github.com/MycroftAI/skill-volume/commit/f2ffdd72dcdc12536a4b834f7d6883566a448841)
 - [Update README.md](https://github.com/MycroftAI/skill-volume/commit/d2f51a7013958ef65fbb11d98d51256b8d78ba32)
 - [Merge pull request #25 from devs-mycroft/translate-2018-10-29](https://github.com/MycroftAI/skill-volume/commit/2c957acc6db2c5be6decadce6952e50674908b07)
 - [Merge pull request #26 from devs-mycroft/translate-2018-11-11](https://github.com/MycroftAI/skill-volume/commit/a586dd6d41aa8144c82b2f858f3ebf7f44777416)
 - [Update translations](https://github.com/MycroftAI/skill-volume/commit/579379f53a023a7101abead7dded17ecd03b229b)
 - [Update translations](https://github.com/MycroftAI/skill-volume/commit/691e728555abb4b3b406b6a9414c9520300e3bc0)
 - [Merge pull request #21 from spagy/18.08](https://github.com/MycroftAI/skill-volume/commit/228c51c78faa4a6e687945572b824b4d64b6f58c)
 - [Merge pull request #22 from MycroftAI/feature/update-readme](https://github.com/MycroftAI/skill-volume/commit/93e8392e8172b2a8314b31a546055a4dd0cbf1dc)
 - [Update readme](https://github.com/MycroftAI/skill-volume/commit/8f87f3e20b8c2dfc8ba5de45a2b30c75c809d7cd)
 - [Add Query.voc](https://github.com/MycroftAI/skill-volume/commit/ba5ace8ca59b2f97b4d43e0963d5fe616e18081d)
 - [Merge pull request #20 from MycroftAI/bugfix/picroft-mixer](https://github.com/MycroftAI/skill-volume/commit/bebf2a25a0a36e8222324d7f4836a9e17210c9da)
 - [Update trying to handle the picroft case](https://github.com/MycroftAI/skill-volume/commit/d4854f8fb6efc421af777e8a6bb55d00c2b97ec7)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Hey I just installed this and the volume query intent is now working for me, however it returns floating point numbers eg
"Hey Mycroft, set the volume to 5"
> Volume set to 5

"Hey Mycroft, what is the volume"
> The volume is set to 4.18

This is also pronounced as "four eighteen" as I'm sure it wasn't intended to be read as a decimal.
Max volume = 9.13
volume 2 = 1.65
volume 1 = 8 (presumably 0.8)

I also can't get the "set volume to 75 percent" intent to trigger, even typing into the cli.

Will try have a dig later to figure out what's going on.

**Comment by forslund** [comment]
I did an update with a simple rounding of the output (which seems to work correctly for me). It doesn't quite match what you're seeing. (with 5 returning 4.18 for you...)

May be something with the in-joke of having 11 steps...

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Working great!
Merging

**Pull request merged**
