### PR TITLE
KC Streetcar Skill

### PR DESCRIPTION
**Pull request by bw3740**
## Description:
Retrieves estimates for next Kansas City streetcar arrival times in both directions.

**Short description of your skill and what it does
Based on a configurable static stop, this skill retrieves the number of minutes until the next streetcars arrive in either the North or South directions. 

Information is provided free-of-charge from http://www.kc-metro.com/tmwebwatch/LiveArrivalTimes. This page makes to POST calls to http://www.kc-metro.com/tmwebwatch/Arrivals.aspx/getStops to get a list of stops and http://www.kc-metro.com/tmwebwatch/Arrivals.aspx/getStopTimes to get the arrival times for a specific stop.

This skill is still in it's early stages of development. It is hard-coded to Southbound 7th & Main St until settings can be implemented.

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ ] Skill has been tested and works
  - [X] README.md has been updated with the following:
  ```
  +[submodule "nerdery-kc-streetcar"]
  +	path = nerdery-kc-streetcar
  +	url = https://github.com/bw3740/nerdery-kc-streetcar.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by penrods** [comment]
Oooh, some KC love!  I like this one!

Can I get you to use the metaeditor format to show intents that work in your README.md?  The current examples of "next street car" don't work.  I.e. add:
```
## Examples 
* "When is the next KC streetcar at 3rd and grand"
```

P.S.  TTS engines are all different, so I'd include both "3rd" and "third" (for example) in .voc files

**Comment by bw3740** [comment]
I've updated the .voc files and README

**Comment by KathyReid** [comment]
Thank you so much for your work on this Skill. This Skill was submitted to the `mycroft-skills` repo just before we implemented [Skill Branching](https://mycroft.ai/blog/skill-branching-18-02/). We'd really like to include this Skill in our 18.02 branch, however this means that the Skill would need to be re-submitted to the `18.02` branch. We also now have some helpful documentation available on [Automated Skills Testing]() and our new [Mycroft Skills Kit]() which assists with Skill submission. We also recently [dropped support for Python 2.7 and have moved to Python 3.4+](). We look forward to working with you to bring your Skill into the `18.02` branch.

**Comment by KathyReid** [comment]
I'm going to close this one off for now - if you'd like to rework this to be Python 3 compliant and re-submit to the `18.02` branch, we can then run it through the [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/). 

We have further information available to assist: 

*  [Mycroft Skills Kit](https://mycroft.ai/documentation/skills/msk/)
*  [Skill Branching](https://mycroft.ai/blog/skill-branching-18-02/)
*  [Automated Skills Testing](https://mycroft.ai/documentation/skills/automatic-testing/)

We look forward to working with you to bring your Skill into the `18.02` branch.

**Pull request closed without merging**
