### PR TITLE
Add list-manager

### PR DESCRIPTION
**Pull request by lb803**
## Info

This PR adds the new skill, [list-manager](https://github.com/lb803/list-manager-skill), to the skills repo.

## Description

*List Manager* is a simple utility for filing lists of things you don't want to forget.
Whether these are titles of books to read, the specs of your new bike, or random thoughts for a new programming project; you can ask [Mycroft](https://mycroft.ai/) to create a list for each them!

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 May 2019
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [x] **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> yes - However I have edited 'Description' to be 'About' instead, as required.  I will propose we make the documentation more clear about this because several authors make this minor mistake.

- [x] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> no constraints listed

- [x] **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> Productivity

- [x] **Tags**  
Are listed tags appropriate for this Skill?

> Notes, Note-taking

- [x] **License**  
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> GPL-3.0

**Comment by ricargoes** [comment]
I will start the code review

**Comment by ricargoes** [comment]
## Meta  
* Platform: Linux
* Mycroft-core version: 19.2.11
* Who: [@ricargoes](https://github.com/ricargoes) / @ricargoes  
* Datestamp: 2019-05-26_12:38:23_CEST  
* Language and dialect of tester: Spanish from Spain (review made in English)

## 0. Automated tests 
Are all automated tests passing?  
- [x] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> The code is nicely written and easy to understand. The IO part has been separated into a module which is appreciated. Good practices and PEP8 compliant. Well done!

- [x] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> There are a lot of checks covering most (if not all) possibilities.

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> It only uses a few modules from myrcroft stack.

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

>  No external dependencies and no requirements file.

- [x] **Settings**  
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

> It does not have any settings and there is no settings file.

- [x] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test` folder?

> Tests are extensive and carefully done. They cover most of uses cases.

- [x] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

> All present files are used and relevant

## Summary

> Nice skill and nicely written. I for one will use it :D

> No actions required

**Comment by ricargoes** [comment]
I will do the functional review now

**Comment by ricargoes** [comment]
## Meta  
* Platform: Linux
* Mycroft-core version: 19.2.11
* Who: [@ricargoes](https://github.com/ricargoes) / @ricargoes  
* Datestamp: 2019-04-26_18:38:23_CEST  
* Language and dialect of tester: Spanish from Spain (review made in English)

## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method: cloned git repo
>
> I did some test and the name "list manager skill" is perfectly transcribe by Mycroft. In addition there are not other skills with similar names.

- [x] **Settings**  
If Skill includes a `settingsmeta` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> No settings are used

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> All dialogs sound good.

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [x] **"add a new list called important"**

> Output: "Your new list important has been added."
> First it understood "Add a new list CALL important" and it did nothing. I tried again and this time it worked fine. It may be an issue with my Spanish accent, every time I focus a little on pronunciation it works well. 

- [x] **"add buy groceries to my important list"**

> Output "buy groceries added to your important list."
> Works fine though sometimes I forget the "my" in the utterance making it not to work.

- [x] **"add vote to my important list"**

> Output "vote added to your important list."

- [x] **"what lists do i have"**

> Output: "Currently you have important list. "

- [x] **"what's on my important list"**

> Output: "In your important list you have buy groceries and vote"

- [x] **"remove buy groceries from my important list"**

> Output: "Are you sure you want to delete buy groceries?"
>
> Input: "yes"
>
> Output: "buy groceries removed from your important list." 

- [x] **"remove my important list"**

> Output: "Are you sure you want to delete important?"
>
> Input: "yes"
>
> Output: "Your list important has been removed." 

## Summary

> Everything seems to work well and as intended.

**Comment by lb803** [comment]
Thank you guys for your feedbacks!!

**Comment by krisgesling** [comment]
Such a great Skill, thanks Luca!

Thanks also to GPVM and Ricargoes for the reviews :tada:

**Pull request merged**
