### PR TITLE
Add localMusic

### PR DESCRIPTION
**Pull request by colla69**
## Info

This PR adds the new skill, [localMusic](https://github.com/colla69/localMusicPlayer-skill), to the skills repo.

## Description

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by el-tocino** [comment]
You might want to wait to submit pr's to the repo until you've completed your coding and testing.

**Comment by krisgesling** [comment]
Hi @colla69,

Thanks for creating a new Skill for Mycroft. It looks like this might be your first Skill, and I wanted to clarify the submission process. This is only needed once you are ready to submit your Skill to the public Marketplace.

You can run the Skill locally on your device and even use the `mycroft-skill-testrunner` to run the integration tests. 

If you have any questions, please let us know, or ask in the ~skills or ~dev channel of chat.mycroft.ai

**Comment by colla69** [comment]
Hey @krisgesling 

thanks.
Please correct me if i am wrong, 
after i submit once with msk, I simply get the skill tester to build again by adding more commits by pushing to the add-localMusic branch on colla69/mycroft-skills. 
right? 

I am sorry for spamming your servers .. so how do i get back in the right workflow? I would like my submission to be called "localMusicPlayer" :) 
On top of that, I seem to be failing the tests becuse of 
/opt/mycroft/skills/mycroft-alarm.mycroftai/test/intent/008.delete.alarm.json
which isn't my skill to begin with, so i have no chance to make it better, am I doing anything else wrong?

Thank you for your help, I really appreciate it :)

**Comment by krisgesling** [comment]
Rather than pushing to the remote repo and needing to wait for the Skill tester to build mycroft, run the tests and report back, you can actually run these locally much quicker.

From the device you have Mycroft running on, use the command:
`mycroft-skill-testrunner /path/to/your/skill`
This performs the same tests, but in a few seconds, rather than 5-10 minutes.

If you want to rename the skill, you will need to close this pull request (PR) and generate a new one with `mycroft-msk submit` then enter the new name when prompted. However you don't need to do this until the Skill is ready to be formally reviewed for inclusion in the Marketplace. 

If you would like some early feedback and testing, others can install your skill by running:
`mycroft-msm install https://github.com/colla69/localMusicPlayer-skill`
The Community Forums are a great place to post asking for others to try your Skill out and provide feedback. See [this example post](https://community.mycroft.ai/t/pokemon-testing-and-feedback/6269) from another skill.

**Comment by krisgesling** [comment]
Oh and Github here will tell you that you can just push to your repository to update the PR however because MSK does some fancy things with git submodules (which are annoying to do manually), you need to run `mycroft-msk submit` to update it. 

This command should check if a PR already exists and either update the existing one, or create a new one if it can't find anything to update.

But again, just working with your repository is the best way to go until it's ready for formal review as part of the [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/).

**Comment by colla69** [comment]
@krisgesling 

Hi i need further help .. now that i have worked out my tests using mycroft-skill-testrunner i would like to submit my Skill.

however mycroft-msk submit doesn't work.. 

it excepts at:
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git submodule add https://github.com/colla69/localmusicplayer-skill.git localMusicPlayer-skill
  stderr: 'A git directory for 'localMusicPlayer-skill' is found locally with remote(s):
  origin	https://github.com/colla69/localMusicPlayer-skill

that happens whenever i try to submit my skill using mycroft-msk and a name I used before... 
thats why i was spamming with PRs before :/

**Comment by krisgesling** [comment]
Hi @colla69 

I've been trying to replicate the issues with MSK but wondered if you could explain a little more about your setup.

From the Chat it sounds like you were originally developing your skill in one directory and possibly shifted that into the `/opt/mycroft/skills/` directory afterward?

When you submit, are you using `mycroft-msk submit` or `upload` or `update`?

What version of Mycroft-core are you running? If you enter the CLI it should say in the top right corner.

**Comment by colla69** [comment]
Hi @krisgesling 

I set up my mycroft with version 18.8 (if i recall correctly) by simply cloning a DEV branch into my usual working folder. Since then i have been pulling an restarting to update.

So I was developing single Skills in a named Folder inside my workDir and installing them by a simple bash script ( Delete from /opt/skills/.... and then simply copy the Folder with ists contents from my workdir to /opt/skills/.. )

On monday i tought my localMusic player has been working pretty well for some time and wanted to share .. so i read about the acceptance process and mycroft-msk and started to prepare everything for the pull request. 

On the first try it didn't work since i wasn't in "/opt/skills /...." so i simply wrote in my bash : 
"msk upload /opt/skills/localMusicPlayer-skill" and it worked fine, 
until it failed some test becuase it needed a package i forgot to install via Requirements.sh .. so i wrote one and started to test it to find out i had no idea to use apt without higher privileges. So i thought i should be testing the script directly on your Skill-tester server ;) 

that's when i started to get the errors  "A git directory for 'localMusicPlayer-skill' is found locally with remote(s): .... " and after that i tried almost anything I could think of (with mycroft-msk [upload|update|upgrade|submit] .
As i was trying to get around the branch-naming collision :S and that's when i started spamming PRs .. than you contacted me.

That should cover my workflow ( more or less ) to reproduce the issue.. if you have any questions feel free to contact me. 
Could you also shortly explain to me, how the correct workflow looks like ? that would be very helpful :)
Thank you in advance :)

**Comment by krisgesling** [comment]
Thanks for that, I'm going to assume that "/opt/skills" is really "/opt/mycroft/skills"

Are you still running 18.08 or has it since updated to 19.02?

If you run `mycroft-cli-client` to bring up the CLI interface it should tell you the version number in the top right corner.

`mycroft-msk submit` should now automatically detect whether it's uploading a brand new Skill, updating an existing PR, or upgrading an existing Skill from the Marketplace. So I'd suggest sticking with that one.

If you want to develop in one location and test in another, there are a few options but the easiest is probably to create a symbolic link which tells your file system to pretend that a file or directory is in one location by pointing to another. 

So if your development directory is `~/Projects/MySkill`, you would run the command:
`ln -s ~/Projects/MySkill /opt/mycroft/skills/MySkill`

To see what this is doing you can run `ls -l /opt/mycroft/skills` and you will see that the new entry points to your Projects directory.

**Pull request closed without merging**
