### PR TITLE
Adding sftsrc-decide skill to 18.08 branch

### PR DESCRIPTION
**Pull request by lhannon**
## Description:

Makes a decision between two options

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-a
Fixes #cceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by lhannon** [comment]
@forslund Is your last comment directed to me?

**Comment by forslund** [comment]
@lhannon, sorry no it wasn't directed to you. I just restarted the autotester. (Something went wrong the first run)

Now all seems fine though :)

**Comment by KathyReid** [comment]
### test of sftsrc-decide

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.08.0
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Wed  5 Sep 02:57:28 AEST 2018
* Language and dialect of tester: English native speaker, Australian accent

### Summary
Hi Laurie, two minor things before I'm comfortable merging this one - below - otherwise this was a "textbook" pull request ;-) 

* Please regenerate README using the [Meta Editor](https://rawgit.com/MycroftAI/mycroft-skills/18.08/meta_editor.html)
* Please remove the `requirements.sh` file as it is not in use

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> The Skill is not yet in the `mycroft-skills` repo, so is not yet voice installable. Checking that the name of the Skill would be picked up correctly in an Utterance. 

```
install skill decide
 >> I didn't find any skill name skill
    decide.
```
This means that the name of the Skill would be picked up correctly => OK
Doing manual install of Skill using `msm`

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/lhannon/sftsrc-decide
INFO - Downloading skill: https://github.com/lhannon/sftsrc-decide
INFO - Successfully ran requirements.sh for sftsrc-decide
INFO - Successfully installed sftsrc-decide
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> This Skill does not use `dialog`, check Skipped

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Checked Intents, none should conflict with default Skills. All seem sensible. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex all seems sensible

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> The README hasn't been generated by the new Meta Editor - could you please regenerate using the Meta Editor https://rawgit.com/MycroftAI/mycroft-skills/18.08/meta_editor.html

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> `requirements.sh` - because this file isn't used, it's a good idea to remove it. 

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Not used, check skipped

#### Python code checks of the Skill

* Inline documentation - is the code documented in line?
>  Yes, simple and clear

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> No dependencies or libraries used

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> No callbacks used

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> No, it's a basic Skill

* Automatic tests - do automatic tests of the **Skill** pass?
>  Yes, nicely done

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to  check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> No Skill settings used, check skipped

### Functional test

`decide between apples and oranges`
> Oranges

`decide between chocolate and strawberry`
> Strawberry

`what should I wear the red or the black`
> black

`what should I wear dress or trousers`
> trousers

`what should I wear jeans or shorts`
> shorts

`what should I eat McDonalds or Burger King`
> Burger King

`what should I eat Pizza or Pasta`
> Pasta

`what should I eat salad or sausages`
> sausages

=> functional tests OK

**Comment by KathyReid** [comment]
Hi Laurie, just two minor things before I'm comfortable pulling this into the 18.08 branch; 

### Summary
Hi Laurie, two minor things before I'm comfortable merging this one - below - otherwise this was a "textbook" pull request ;-) 

* Please regenerate README using the [Meta Editor](https://rawgit.com/MycroftAI/mycroft-skills/18.08/meta_editor.html)
* Please remove the `requirements.sh` file as it is not in use

Best, Kathy

**Comment by lhannon** [comment]
@KathyReid I have pushed the changes to my README and deletion of requirements.sh to my lhannon/sftsrc-decide repo. Let me know if I need to do anything else. 

Thanks,
Laurie

**Comment by KathyReid** [comment]
Hi @lhannon, I think I see what the issue is here - this PR has been opened between your `mycroft-skills` repository and the Mycroft `mycroft-skills` repository, but your `sftsrc-decide` repo is the one that has been updated. You might need to pull in the changes from the `sftsrc-decide` repo into _your_ `mycroft-skills` repo for the open PR to update. 

An alternative is to close this request, then open a new PR from the `sftsrc-decide` repo. 

The [Mycroft Skills Kit](https://mycroft.ai/documentation/skills/msk/) - `msk` - makes this process a lot easier. 

Best, Kathy

**Comment by lhannon** [comment]
@KathyReid I have submitted a separate replacement PR for this work, #555. I had too much trouble trying to get the submodule changes to propagate up to my mycroft-skills fork. I started over with msm and msk. I think it looks right. Let me know if it's not.

**Pull request closed without merging**
