### PR TITLE
Add diploma

### PR DESCRIPTION
**Pull request by mato6t**
**Name of your skill**: _Name goes here_

## Description:

**Short description of your Skill and what it does**

## Checklist:
  - [ ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ ] Skill has been tested and works 
  - [ ] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [ ] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi there,

Welcome to Mycroft. It's great to see you are exploring Mycroft Skill development.

The submission process you used is how you can submit your completed Skills to the public Skills Marketplace. Any Mycroft user will then be able to install the Skill either by tapping a button or saying "install name-of-your-skill".

For testing purposes you don't need to submit the Skill, you can install it on any Mycroft device by running:
mycroft-msm install https://github.com/mato6t/diploma-skill

It looks like the Skill you've submitted today is probably for your own testing and not quite ready for prime time, is that right? If that is the case, I will close the PR until you're ready to have it reviewed by our Skill Testing Team. You can read more about that [review process in our documentation](https://mycroft.ai/documentation/skills/skills-acceptance-process/)

Also if you haven't already please join our Community [Chat](https://chat.mycroft.ai/community/channels/skills) or [Forums](https://community.mycroft.ai/) if you have any questions or just want to chat with other developers and users.

**Comment by mato6t** [comment]
Oh yeah, ok think you

**Comment by mato6t** [comment]
So I shouldnt use msk upload ,only github and then msm isntall?

**Comment by krisgesling** [comment]
Yeah, for your personal use just use the git commands and install using MSM. 

You can even manually place a Skill onto a device at `/opt/mycroft/skills/your-skill-directory` and Mycroft will detect it and attempt to run the Skill. This won't install dependencies etc though.

Once you are ready to submit the Skill to the Marketplace you can use `msk submit`. 

Previously we had `msk upload` and `msk update`, but we've now combined those into `msk submit`. So it will automatically detect whether this is a new Skill and create a new PR, or if it's an existing PR it will update that.

Let us know if you run into any troubles

**Pull request closed without merging**
