### PR TITLE
Add espy

### PR DESCRIPTION
**Pull request by Dark5ide**
## Info

This PR adds the new skill, [espy](https://github.com/Dark5ide/espy-skill), to the skills repo.

## Description

This skill has been created for the makers and hackers who want to build their own home automation system based on esp8266. the purpose of this skill is to be able to use mycroft to send commands to all esp8266s on the local network. the communication protocol can be selected (websocket, mqtt, http get).

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Hi there @Dark5ide, I had a chat with my colleague @forslund around why the automated tester might be failing here. 

It looks like the Skill can't be loaded because the Skill accesses the Skill Settings during loading, and will always fail to start the first time - ie the "first run" - before the Skill entry has been generated on Home. 
See here: https://github.com/Dark5ide/espy-skill/blob/master/__init__.py#L46

We think the way around this would be to add a check for "first run", or default to a sensible value if the Skill Setting can't be accessed.

**Comment by Dark5ide** [comment]
Hi Kathy !

Thanks for your feedback. I will try to fix this bug this weekend.

**Comment by Dark5ide** [comment]
Hi Kathy,

I did the change. I push it on github. How can I do the PR ?

**Comment by KathyReid** [comment]
Sorry for the delayed response @Dark5ide, when you pushed the change to GitHub, did you push it to the **same** branch that this PR was created from? You might want to close this PR and create another one. 

If you send me the link to your GitHub repo I can take a look :+1:

**Comment by Dark5ide** [comment]
Hi @KathyReid,

Yes I pushed the change in the same branch. Here is my GitHub repo : https://github.com/Dark5ide/espy-skill

**Comment by KathyReid** [comment]
@Dark5ide sorry for taking so long to get back to you on this. What I think has happened here is that you have pushed the commits to the `master` branch on your repo, _not_ to the `add/espy` branch. Because this PR was created from the `add/espy` branch, the commits have _not_ automatically been added to this PR. You will also need to push your changes to the `add/espy` branch.

**Comment by KathyReid** [comment]
@Dark5ide how did you go with this one? I can pull it in using `msk` if that helps?

**Comment by JP-MCA** [comment]
@KathyReid : Sorry to answer only now. I don't know the good procedure to do it. I will try this week end but a little bit of help is welcome :-D

**Comment by Dark5ide** [comment]
@KathyReid : Sorry to answer only now. I don't know the good procedure to do it. I will try this week end but a little bit of help is welcome :-D

**Pull request closed without merging**
