### PR TITLE
Update Translations for Crystal Ball and Number Guess skills

### PR DESCRIPTION
**Pull request by Arc676**
Note that I haven't updated the codebase for these skills at least since the default branch was 18.02. Given that these skills are extremely basic, unless something very fundamental in the structure of Mycroft skills has changed, I don't think any updates are necessary. Please let me know if anything needs to be changed, as I haven't been keeping up with Mycroft development.

Otherwise, just another translation update from Mycroft Translate.

### CODE REVIEW

**Comment by ChanceNCounter** [comment]
Well, fwiw, the direct import from `mycroft.skills.core` is deprecated.

The new boilerplate is:
`from mycroft import MycroftSkill, intent_handler`

afaik, at the moment, that's just exposed, so it's not going to break, but it hypothetically *could* since it can now be wrapped where it's exposed.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1456)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1456/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1456/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1456/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1456/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1456/logs/enclosure.log)

**Comment by Arc676** [comment]
@ChanceNCounter Thanks, I'll update that as well then.

I noticed that the failed scenarios in the CI build are for the weather skill though, which is odd. The email sending also seems to have failed.

**Comment by forslund** [comment]
Email sending will not affect the result of the run (but is a config issue I think) and the weather failures looks like a weather api-issue. Will trigger a  re-run.
The updates suggested by @ChanceNCounter would be great if they were handled as well. They are deprecated but the compatibility layer will be around at least until 21.02

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1456))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1456))

**Comment by forslund** [comment]
Tested and working, thanks for the update!

**Pull request merged**
