### PR TITLE
Upgrade picroft-google-aiy-voicekit

### PR DESCRIPTION
**Pull request by andlo**
'This upgrades picroft-google-aiy-voicekit to include the following new commits:

 - [small fix Thanks to @el-tocino](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/d786178d3d075eaba912dd911e38901d6de15ebf)
 - [small fix to install script](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/d8eae4a480e4722909d523cbd6bd3619d77c7c1f)
 - [Merge pull request #11 from devs-mycroft/translate-2018-12-31](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/9ee4b984aa4da00568e4f737b9817e9bba7c74f8)
 - [Update translations](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/03feed06de56f834094aafa6c2b3487705ba252f)
 - [Merge branch 'master' of https://github.com/andlo/picroft-google-aiy-voicekit-skill](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/cd01682831392e3480ba80b67814d9f933db8940)
 - [added license](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/ce6f667e2c621c9dbd2e8a0860fc4e227606ea9d)
 - [Create LICENSE](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/5ace6c7fb0d2c8636abd8fa6d783874806612625)
 - [...](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/8b13f6e6be73375a664db693e076d37fa34ef896)
 - [fixed problem whith protobuf](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/9912082063ba9af9f73d7b23adec5bc48ba8a67c)
 - [a bug in the script is removed](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/9f99a23d9136e3087ac7680dadb3d582dcfa3100)
 - [asound.conf](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/a087c5a7fc4ad656c745dcc75d982e6b1582e55b)
 - [small error in making .asoundrc](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/e15d1e6e444101f1e81b51e8e5b5e118f5e17139)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Review by el-tocino — COMMENTED** [review]
For "install_AIY.sh", the "break" at the very end should probably just be "exit 0" or nothing. Also the altered asound.conf lines...is there a need to tee these? Additionally on that, the previous iteration would overwrite any existing file, while the current one will merely append in every case.  Re-running the script will therefore result in multiple redundant entries.

**Comment by andlo** [comment]
Good points....The install_AIY.sh is just for helping if user hassnt setup the voicekit. But Ill expect the setup is included in the picroft image now or soon.

I will remove the exit 0 but for the question about the tee to enter the asound.conf I dont know. It were the way I got it working as I couldnt get it to work just by echo >> 
Do you have an idea how to make that part better? If the user runs the script multiple times (which isnt nessesary, as runing it once should install everything right)

**Comment by el-tocino** [comment]
Something like 
```
if grep -q "default.ctl.card 0" "${FILE}" || grep -q "default.pcm.card 0" "${FILE}" || grep -q "default.pcm.device 0" "${FILE}" ; then
  # note to user or log "asound.conf has existing config, skipping update."
else 
  # do updates to asound.conf here
fi```

**Comment by andlo** [comment]
Added stuff like you proposed the the script :)

**Comment by andlo** [comment]
Were thinking of the skill should be moved from the category IoT to Configuration or System ?

**Pull request merged**
