### PR TITLE
Add CaffeineWiz

### PR DESCRIPTION
**Pull request by NeonDaniel**
## Info

This PR adds the new skill, [CaffeineWiz](https://github.com/NeonGeckoCom/CaffeineWiz.neon), to the skills repo.

## Description

The skill provides the functionality to inform the user of the caffeine content of the requested drink by collecting the required information from two data sources:

1.  [http://caffeinewiz.com/](http://caffeinewiz.com/) - the main source of information for the drink’s database
2.  [https://www.caffeineinformer.com/the-caffeine-database](https://www.caffeineinformer.com/the-caffeine-database) - secondary source for any non-duplicate drinks

CaffeineWiz uses [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) to pull the tables from the websites above, then strips the html tags, and later formats the results into the comprehensive list. That object is pickled for the future use.

The skill will check for updates periodically. You can modify that time period by changing `TIME_TO_CHECK` parameter on top of the file in the init.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1466)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1466/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1466/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1466/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1466/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1466/logs/enclosure.log)

**Comment by NeonDaniel** [comment]
It appears that msk submitted the "master" branch or my repository, though I had the "dev" branch checked out in the local directory I called msk submit from. Is this expected behavior?

**Comment by krisgesling** [comment]
I'd have to double check but I think it takes the default branch of the repo at the moment. 

For the Marketplace, given they're submodules it doesn't have to be from the default branch that's likely just a limitation of MSK for the moment. You can also submit a PR updating the submodule manually, they're just notoriously annoying to deal with.

**Comment by NeonDaniel** [comment]
Okay, default branch makes some sense, though it could be a nice addition for that to be specified in the CLI when submitting a change.

I agree msk does make dealing with getting the correct submodule changes in the repo a lot simpler.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1466)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1466/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1466/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1466/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1466/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1466/logs/enclosure.log)

**Comment by krisgesling** [comment]
Just to reassure - the reported test failures are not caused by your Skill, I'm working on that currently.

**Comment by NeonDaniel** [comment]
Okay, I noticed the failures didn't appear to involve my skill and all recently submitted skills seem to be affected. Let me know if there is anything I need to address.

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
