### PR TITLE
Add telegram

### PR DESCRIPTION
**Pull request by luke5sky**
## Info

This PR adds the new skill, [telegram](https://github.com/luke5sky/telegram-skill), to the skills repo.

## Description

A skill to connect a telegram bot to MyCroft.

You need to create a telegram bot (via BotFather) and save the Bot Token, your ChatID and your MyCroft Device name on home.mycroft.ai under skill settings.
After this restart your MyCroft Unit.
You can now commmunicate with your MyCroft Unit via this bot.

Settings:
- BOT TOKEN (MANDATORY): Your bot token you got from BotFather
- MYCROFT DEVICE NAME (MANDATORY): Your Device name you configured on home.mycroft.ai - Devices - Registered Devices
- BOT TOKEN SECOND MYCROFT DEVICE (OPTIONAL): If you have a second Mycroft Device and you want to use this skill with it -> put your second bot token here (it has to be an other bot than the first one because telegram only allows one device to get updates from one bot)
- SECOND MYCROFT DEVICE NAME (IF YOU HAVE A SECOND DEVICE): Your Device name from your second Device you configured on home.mycroft.ai - Devices - Registered Devices
- USERNAME 1 (OPTIONAL): You do not need to put anything here, the skill does not use this field. It is only for yourself to know which Chat ID belongs to whom
- CHAT ID 1 (MANDATORY): You will get your Chat ID from the Telegram-Skill if you have configured BOT TOKEN (first field) and MYCROFT DEVICE NAME, saved and then write anything to the bot.
- USERNAME 2 (OPTIONAL): For second User if you have one
- CHAT ID 2 (IF YOU HAVE A SECOND USER): Same as CHAT ID 1 with Telegram-Account of second user

Detailed HowTo:

- Install this skill on your Mycroft Device

- Create a telegram bot:
Open Telegram App on your smartphone, click on the search symbol in the upper right corner
Search for BotFather and click on it
Now type /newbot hit enter
Botfather should reply with: Alright, a new bot. How are we going to call it? please chosse a name for your bot.
Give your bot a displayname like Mycroft
Botfather should reply with: Good. Now let's choose a username for your bot. It must end in bot. Like this, for example: TetrisBot or tetris-bot.
Give your bot unique username like lukesmycroftbot
Botfather should now give you your token for this bot
Save this token and don't post it online or send it to people, safety first!

Telegram documentation on botfather: https://core.telegram.org/bots#6-botfather

- Go to home.mycroft.ai - skills and search for the telegram-skills settings

- Copy/paste your token botfather gave you in the field MYCROFT DEVICE NAME (MANDATORY)

- Copy/paste your device name from home.mycroft.ai - devices in MYCROFT DEVICE NAME (MANDATORY)

- SAVE and wait till the settings are synced to your Mycroft Unit (or reboot your device to trigger the sync)

- Open Telegram App on your smartphone and search (upper right corner) for your bot (username or displayname) click on it and write test or hello to your bot
It should respond with: This is your ChatID: YOURCHATID

- Copy/paste this under CHAT ID 1 (MANDATORY)

- reboot your device to trigger the sync

- Your bot should send you this welcome message: Telegram-Skill on Mycroft Unit YOURUNIT is loaded and ready to use

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>

### CODE REVIEW

**Comment by luke5sky** [comment]
Skill test failes (of course) because, there is not intend, no utterance etc.
i tested it on Mark1 and Ubuntu. Attached a picture of a telegram conversation with mycroft.
If you need any assist, write me here, or on Mattermost (@luke)

Testers are very welcome!!!!
telegram-skill

**Comment by luke5sky** [comment]
ok, seems like if there is not test-intent Jenkins-test just works fine

**Comment by KathyReid** [comment]
### Skill Acceptance test - `telegram`

* Platform: Ubuntu Linux 16.04 LTS
* Device version: 18.02.11, `master/stable`
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Friday 3 August  22:33:39 AEST 2018
* Language and dialect of tester: English native speaker, Australian accent

### Installation of Skill

* Because the Skill is not yet in the `18.02` branch, manual install is required

```
kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core$ source ./venv-activate.sh
Entering mycroft-core virtual environment.  Run 'deactivate' to exit
(.venv) kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core$ msm install https://github.com/luke5sky/telegram-skill
INFO - Downloading skill: https://github.com/luke5sky/telegram-skill
INFO - Installing requirements.txt for telegram-skill
INFO - Successfully installed telegram-skill
```

### Create BotFather bot

* Bot http://t.me/kathyreid1test_bot successfully created using `/newbot` command
* The username of this bot is `@kathyreid1test_bot`
* Token successfully generated 

### Add settings to Mycroft in home.mycroft.ai

The settings in Mycroft were a little unclear to me; here is a screenshot; 
screenshot from 2018-08-03 23-19-04

Something's not quite right with these settings - but I'm not sure what. 

TEST ABANDONED; I AM NOT SURE WHAT THE RIGHT SETTINGS ARE

**Comment by KathyReid** [comment]
Hi @luke5sky I tried to test this but got a little stuck; any advice appreciated. 
Best, Kathy

**Comment by luke5sky** [comment]
Hi @KathyReid Plesse leave 1. ClientID empty, the bot should then give you your correct ClientID. Then put this ID in the settings.

I definetly need to update the description

Regards

**Comment by luke5sky** [comment]
Hi @KathyReid i renamed the fields in the settings (i hope for better understanding) and made a detailed description and howto in the readme. Hope this helps.
Regards

**Comment by KathyReid** [comment]
Thanks @luke5sky, I tried again but could not get a `ClientID` from my bot
screenshot from 2018-08-10 01-59-51
Not sure what I'm doing wrong...

**Comment by luke5sky** [comment]
@KathyReid do you see any error messages on the mycroft CLI?

**Comment by KathyReid** [comment]
Ah, logs would have been useful here. 

```
23:37:16.931 - mycroft.skills.core:load_skill:145 - ERROR - Failed to load skill: telegram-skill.luke5sky
  File "/opt/mycroft/skills/telegram-skill.luke5sky/__init__.py", line 72, in initialize
    self.telegram_updater = Updater(token=self.bottoken) # get telegram Updates
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/.venv/lib/python3.5/site-packages/telegram/ext/updater.py", line 122, in __init__
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/.venv/lib/python3.5/site-packages/telegram/bot.py", line 108, in __init__
  File "/home/kathyreid/Dropbox/PHPworkspace/mycroft-core/.venv/lib/python3.5/site-packages/telegram/bot.py", line 134, in _validate_token
telegram.error.InvalidToken: Invalid token

```
however, that's definitely the token BotFather gave me ...

**Comment by luke5sky** [comment]
Please take a look in the settings.json if the Token is within the " and there is no extra symbol (whitespace for example).

**Comment by luke5sky** [comment]
Also try to go to this in your browser to test if the token is working: https://api.telegram.org/bot<yourtoken>/getMe (should look something like: https://api.telegram.org/bot123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11/getMe)

getMe
A simple method for testing your bot's auth token. Requires no parameters. Returns basic information about the bot in form of a User object.

**Comment by KathyReid** [comment]
Thanks for the pointers @luke5sky

* Checked that the token was within `"` quote marks and that there was no whitespace in `settings.json`

```
"TeleToken1": "685647474:AAHsWq4uxxxxxxxxxxxxxxxxxxxxx"
```
(last part of token replaced by `x`)

* The result of https://api.telegram.org/botYOURTOKEN/getMe was:

```
{"ok":true,"result":{"id":xxxxxxx,"is_bot":true,"first_name":"kathy-mycroft-testbot","username":"kathyreid1test_bot"}}
```

* I then used the `id` from the above in the Skill Settings on home.mycroft. Next, I went to the bot in Telegram and entered text. Nothing happened. 

* Checked my `skills.log` in Mycroft; 

```
kathyreid@kathyreid-Oryx-Pro:/var/log/mycroft$ cat skills.log | grep -i telegram | grep -i error
FileNotFoundError: [Errno 2] No such file or directory: '/home/kathyreid/.mycroft/skills/TelegramSkill/uuid'
22:27:23.236 - mycroft.skills.core:load_skill:145 - ERROR - Failed to load skill: telegram-skill.luke5sky
telegram.error.InvalidToken: Invalid token
22:48:01.106 - mycroft.skills.core:load_skill:145 - ERROR - Failed to load skill: telegram-skill.luke5sky
telegram.error.InvalidToken: Invalid token
23:28:01.259 - mycroft.skills.core:load_skill:145 - ERROR - Failed to load skill: telegram-skill.luke5sky
telegram.error.InvalidToken: Invalid token
```
Luke, do you know what conditions the token would be rendered Invalid under? I'm guessing if the token was invalid it wouldn't have given me an `id` earlier?

Sorry this is such a pain!

**Comment by luke5sky** [comment]
Hi @KathyReid,
sorry for the long delay, very busy summer. 
I don't really know why it says that the token is invalid, it clearly works.
Would you be willing to try to remove the skill and get it fresh from github?

I testet it with Mark 1 and Ubuntu 16.04 and it worked everytime, i am out of ideas.
There for I hope re installation helps.

Regards Luke

**Comment by KathyReid** [comment]
Apologies, I missed your last comment, I'll give it a re-test in the next couple of days. 
Best, Kathy

**Comment by luke5sky** [comment]
#687 new pull request with (hopefully) better error output for user

**Pull request closed without merging**
