### PR TITLE
Add dice-skill

### PR DESCRIPTION
**Pull request by yvie-k**
Adds a skill that can generate random numbers and dice throws.

**Name of your skill**: Dice
## Description:
**Short description of your Skill and what it does**
Generates random numbers or rolls a dice for you.
Uses [dice nation](https://en.wikipedia.org/wiki/Dice_notation) for dice rolls, e.g. 2d6 but no +/- modifier.
The word dice is equivalent to 1d6.

Generating a random number requires a range, e.g. "between -5 and 5", "from 0 to 20", etc.
The order of the range is not important, therefore "generate number **from 0 to 5**" is the same as "generate number **from 5 to 0**".

Some examples:
* Hey Mycroft, **roll a dice** => Generates a random number from 1 to 6
* Hey Mycroft, **roll a d20** => Generates a random number from 1 to 20
* Hey Mycroft, **roll 3d6** => Generates 3 random numbers from 1 to 6
* Hey Mycroft, **generate a random number between -5 and 5** => Generates a random number between -5 and 5
## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works 
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by KathyReid** [comment]
Run test

_This comment triggers a rebuild of our continuous integration process using Jenkins - the errors shown in the Skill Tester are for unrelated Skills like the `mycroft-ip` Skill, so that is why I am re-running the Skill tests._

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
## Meta

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.9
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Sat 29 Dec 00:49:30 AEDT 2018
* Language and dialect of tester: Native English speaker, Australian accent

## Standard checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> this is the first submission of the Skill; until it is pulled into `mycroft-skills`, it won't be available for voice installation. Regardless, I will check that STT transcription picks it up OK. 

`00:51:53.268 - __main__:handle_utterance:61 - INFO - Utterance: ['install dice skill']`
> STT transcription picks it up OK

> using manual installation

```
(.venv) kathyreid@kathyreid-ubuntu-X510UQ:~/mycroft-core$ msm install https://github.com/Dragoncraft89/dice-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/Dragoncraft89/dice-skill
INFO - Successfully ran requirements.sh for dice-skill
INFO - Installing requirements.txt for dice-skill
INFO - Successfully installed dice-skill
```
> installation checks OK

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.
> Ran all the `dialog` files through `mimic`. All the pronunciations were good. 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> The main keyword used is `roll` - it's unlikely to cause Intent Collisions with other Skills

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._
> The README is well done, thank you

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 
> `requirements.txt` and `requirements.sh` are present, but are not used. 
_ACTION REQUIRED: Please remove both `requirements.txt` and `requirements.sh` from your repo, as they are not used 

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?
> Not used, skipping check

## Functional test

* `Hey Mycroft, roll a d12`
> produces a random number 1:12 - tried this several times to ensure it was random, it was

* `Hey Mycroft, roll a dice` and `Hey Mycroft, roll a d6`
> the behaviour of this was equivalent

> Functional tests are good

## Python code checks

* Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL? 
> Yes, GPL

* Inline documentation - is the code documented in line?
> There is not a lot of inline documentation, but it's a simple Skill

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> No libraries used, skipping check

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> error checking already fails gracefully

* Automatic tests - do automatic tests of the **Skill** pass?
> No, but I will override that; it's not failing because of this Skill

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

_NOTE: We do not enforce PEP8 Checks on Skills_

## Summary
Thank you so much for this Skill - there is just one minor change before we can merge this :-) 

* Please remove both `requirements.txt` and `requirements.sh` from your repo, as they are not used

**Comment by yvie-k** [comment]
I've deleted the files from the repository.

Do I need to update the gitmodules to the current commit?

By the way: your test says that there is no regex being used, but `Dice.rx` and `Range.rx` are indeed being used in the code

**Comment by KathyReid** [comment]
Thanks @Dragoncraft89. 

I checked the `regex` files and they are _very_ well designed, thank you. 

I will update the `.gitmodules` and merge this in. 

Thanks again for all your efforts on this Skill!

**Pull request merged**
