### PR TITLE
Upgrade homeassistant

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades homeassistant to include the following new commits:

 - [Merge pull request #2 from JarbasAl/master](https://github.com/MycroftAI/mycroft-homeassistant/commit/5cb692365749c0fc76e6b372675e1f86771d557f)
 - [Merge pull request #4 from devs-mycroft/translate-2019-01-27](https://github.com/MycroftAI/mycroft-homeassistant/commit/30b10d947278c3fea9f044baabe1c5e6bbd4cac4)
 - [Update translations](https://github.com/MycroftAI/mycroft-homeassistant/commit/2f8049c703af62d73bcaf8b91467fda22891ae5d)
 - [credit where credits are due](https://github.com/MycroftAI/mycroft-homeassistant/commit/e6dbaf2796dbe45dfc31c49c270f2d5b189e6fb2)
 - [Update README.md](https://github.com/MycroftAI/mycroft-homeassistant/commit/a2518f6aa31d2851cadf7eaf23851fc39867d327)
 - [Update README.md](https://github.com/MycroftAI/mycroft-homeassistant/commit/37745176726f4e2be777cd40c955f7fe7d619c4a)
 - [Update README.md](https://github.com/MycroftAI/mycroft-homeassistant/commit/12b04786492b02121ac92b9f609312f623f5868a)
 - [Merge pull request #86 from KathyReid/patch-2](https://github.com/MycroftAI/mycroft-homeassistant/commit/9ba299f974ca6c017d0c5a477cc1b9ee222c5cdf)
 - [Update set.climate.intent](https://github.com/MycroftAI/mycroft-homeassistant/commit/e558a4ea27dac427c3df42223a40a59decf3a4d9)
 - [Merge pull request #83 from KathyReid/patch-1](https://github.com/MycroftAI/mycroft-homeassistant/commit/e7dec1827b0d120da56a3a4180ba85443145ed8c)
 - [Update README.md to include tags for common Home Assistant devices](https://github.com/MycroftAI/mycroft-homeassistant/commit/9f93398fc8b31774738f0bcbf72f458e80db31fe)
 - [Merge pull request #82 from btotharye/revert-78-nice_unit](https://github.com/MycroftAI/mycroft-homeassistant/commit/b5926bb2898f7efc7905bdd64282c8d86f28b808)
 - [Revert "WIP: Use new nice_unit instead of old malfunctioning quantulum"](https://github.com/MycroftAI/mycroft-homeassistant/commit/ae2bc553e2d3f747e875241c3c53c1f42d982199)
 - [Merge pull request #78 from nielstron/nice_unit](https://github.com/MycroftAI/mycroft-homeassistant/commit/faeae9f52fcda57a152b86e23ddea3d0d95748e8)
 - [Merge pull request #81 from g3rb3n/master](https://github.com/MycroftAI/mycroft-homeassistant/commit/2c90b89d727dd07976b48d1ce78234f7c4ef8f82)
 - [Fixed configuration changing to default](https://github.com/MycroftAI/mycroft-homeassistant/commit/1a966f6a7aba61f66280aaceb0c4318557a72e29)
 - [Merge pull request #79 from nielstron/improve_name_matching](https://github.com/MycroftAI/mycroft-homeassistant/commit/fb8ddbaf468cffb15d536a540a005bb12b73a35a)
 - [Improve entity name matching](https://github.com/MycroftAI/mycroft-homeassistant/commit/ef40ace97c2baff158d3063798b9442da2f0950a)
 - [Use new nice_unit instead of old malfunctioning quantulum](https://github.com/MycroftAI/mycroft-homeassistant/commit/3ae25b8489bcfe65642e0c6ad290c401344d2082)
 - [Update README.md](https://github.com/MycroftAI/mycroft-homeassistant/commit/10f78beb5a2bff26382654faba201781fbd79563)
 - [Update README.md](https://github.com/MycroftAI/mycroft-homeassistant/commit/fcab3062d4aa489ce7ec790a99451cddcc9a4550)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
I just set up a Home Assistant server to test this out. Having real trouble populating the settings.json form home, so I've just manually configured them on the device at the moment.

Switch intent is working well for individual and group entities

Have been unable to trigger the `LightAdjBrightnessIntent` is that working for others?

**Comment by krisgesling** [comment]
## Meta
*   Platform: Mark 1
*   Mycroft-core version: 19.02.0
*   Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft
*   Datestamp: 2019-03-27_09:56:16_ACST
*   Language and dialect of tester: English with Australian accent

## 0. Automated tests
Are all automated tests passing?
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable
- [x]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

> Looks good.

- [x]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

> Yes. Additional suggestion made re missing url, fix already on the way.

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Yes. Appropriate usage

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> Yes. Appropriate

- [x]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

> Yes, good layout

- [x]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

> Yes, excellent test coverage, great work on the mocking.

- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

> No


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x]   **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> Unchanged

- [ ]   **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> Great long description.
> The short description however is the content above `About`. This is what will show up on the preview card in the Marketplace - "This skill was orphaned and then adopted by the United Skill Writers team". This might fit better in the `Credits` section with a one sentence description of the Skills functionality placed up here.

_Action Required: Update short description above `About` heading_


- [x]   **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> Clear

- [x]   **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> NA

- [x]   **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes

- [x]   **Tags**
Are listed tags appropriate for this Skill?

> yes

- [x]   **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> LGPL3


## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method: `mycroft-msm install https://github.com/MycroftAI/mycroft-homeassistant/`
> ```
> INFO - Downloading skill: https://github.com/MycroftAI/mycroft-homeassistant
> INFO - Installing system requirements...
> INFO - Installing requirements.txt for homeassistant
> INFO - Successfully installed homeassistant
> ```
>
> Checking that STT transcribes correctly:
> ```
> Utterance: ['who stole home assistant']
> > "I will try to find out"
> > Good to know Mycroft is on the case!!
> Utterance: ['install home assistant']
> > INFO - Best match (0.53): homeassistant by MycroftAI
> > "homeassistant has already been installed"
> ```

_Action Required: Default branch is currently 19.02, however this PR is from master. Perhaps revert master to be default or update 19.02 for those installing via MSM._

- [x]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> Yes

- [x]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Yes great dialog



#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [ ]   **Without configuring settings - "Turn off the makerspace lights"**

```
AttributeError: 'NoneType' object has no attribute 'url'
```

> Already reported and fix on the way. Not impacting overall functionality.

- [x]   **turn off all the lights**

> Lights turn off
> > "turned off all."

- [x]   **turn on all the lights**

> Lights turn on
> > "turned all on."

- [ ]   **dim all lights**

> Not yet functional?


## Summary
This is looking great!

I have been having trouble getting the settings from home.mycroft.ai stick, but seems to work after a few saves. However the only blocking change I think is the short description on the README as described above. If someone is able to update this then we can merge :)

**Comment by krisgesling** [comment]
Closing this so we can resubmit to 19.02

**Comment by krisgesling** [comment]
Also realised Steve has already updated the README, so no work required.

**Pull request closed without merging**
