### PR TITLE
Rebase of #1296

### PR DESCRIPTION
**Pull request by forslund**
See #1296 for details

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/core/PR-1305))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/core/PR-1305))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1305))

**Comment by forslund** [comment]
Added PR response in addition to Chris's e-mail (which seem to be lacking some config to actually send the e-mail) This will at least inform of the result...

**Pull request merged**
