### PR TITLE
Upgrade telegram

### PR DESCRIPTION
**Pull request by luke5sky**
This upgrades telegram to include the following new commits:

 - [Merge pull request #18 from luke5sky/development](https://github.com/luke5sky/telegram-skill/commit/d4d5833bf574b3fe8549411fb751b16c328d3c42)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by luke5sky** [comment]
@krisgesling thank you for your hints from the last PR ( #1405  ).
i rewrote the mentioned parts and now no reboot should be needed for the skill to get the bottoken or chatid from settingsmeta.
also the speak and utt functions are now one-liners

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1409))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1409)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1409/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1409/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1409/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1409/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1409/logs/enclosure.log)

**Comment by luke5sky** [comment]
Run test

**Comment by luke5sky** [comment]
Does not look like a problem of the skill rather than Jenkins.
Or am I mistaken?

**Comment by krisgesling** [comment]
No you're right - there was a snafu with the Github credentials and unfortunately it's cached in Jenkins so I need to clear them all out and trigger fresh builds :(

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
