### PR TITLE
Upgrade mycroft-singing

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-singing to include the following new commits:

 - [Merge pull request #30 from MycroftAI/bugfix/missing-import](https://github.com/MycroftAI/skill-singing/commit/5daa788263b3c278fb10c1e07db5b1c77ec552f5)
 - [add missing VK import](https://github.com/MycroftAI/skill-singing/commit/42dd8434156551d221baeba61de0ba54b0e0ec4d)
 - [Merge pull request #29 from MycroftAI/bugfix/stop-test](https://github.com/MycroftAI/skill-singing/commit/11db6ea9a73c167024648457e6d911df8230b020)
 - [new method for detecting audio.service.play Message](https://github.com/MycroftAI/skill-singing/commit/60d6d8beec587734fd45d11500d305be32895b1d)
 - [new method for detecting audio.service.stop Message](https://github.com/MycroftAI/skill-singing/commit/54a64e850f185c3fda370cc829736a2ec48d96dc)
 - [Merge pull request #26 from devs-mycroft/translations](https://github.com/MycroftAI/skill-singing/commit/19a78b32faac2eb49bb5a6eff8ca3a57f1f1d448)
 - [Update translations](https://github.com/MycroftAI/skill-singing/commit/665117e8bd19baad386aa89ebb64022afed1554f)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1350))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1350))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1350))

**Comment by krisgesling** [comment]
Reviewed in the Skill repo. Merging.

**Pull request merged**
