### PR TITLE
Add cbc-news

### PR DESCRIPTION
**Pull request by makew0rld**
## Info

This PR adds the new skill, [cbc-news](https://github.com/makeworld-the-better-one/mycroft-skill-cbc-news), to the skills repo.

## Description

This Mycroft skill is a modification of the npr-skill by jdorleans.
Basically, all I have done is changed the URL from the latest NPR
news feed to CBC Radio's latest news feed.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by makew0rld** [comment]
This is my fork of @chrison999 's project, to see if it can get into the skills repo.

**Comment by KathyReid** [comment]
Hi there @makeworld-the-better-one, thank you so much for your Skill contributions. 
Rather than add a _separate_ news Skill, how would you feel about adding the CBC URL into the _existing_ News Skill? 

I'd be happy to help walk you through this. 

Kind regards, 
Kathy

**Comment by makew0rld** [comment]
Showing me how sounds great. Thanks!

**Comment by forslund** [comment]
This may already been added, there's an entry for `CBC.ca|http://www.cbc.ca/podcasting/includes/hourlynews.xml` in the settingsmeta.json for the npr-news-skill. Is that the same news cast this is adding?

**Comment by makew0rld** [comment]
It appears that it is. Thanks for mentioning it to me!

**Comment by KathyReid** [comment]
@makeworld-the-better-one you're welcome - yes, this is how the new News Channels are added. There is an additional entry added to `skillsmeta.json` and an additional Skill Setting stored. 
You can read more about Skill Settings at;
https://mycroft.ai/documentation/skills/skill-settings/

We also have a Developer Chatroom that you're very welcome to join; 
https://chat.mycroft.ai/community/channels/skills

Best, Kathy

**Pull request closed without merging**
