### PR TITLE
Add bringlist

### PR DESCRIPTION
**Pull request by AZAZ78**
## Info

This PR adds the new skill, [bringlist](https://github.com/AZAZ78/mycroft-bringlist-skill), to the skills repo.

## Description

It lets you add and remove items from your default shopping list and also clear all items.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1476))

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

I took a very quick look and noticed that you have a configurable file that's expected to be in the Skills root directory. This is not guaranteed to be writeable by the Skill. Also if a user edits a file in that directory it will prevent it from updating as this would overwrite their changes. 

I just added this page to our Skill docs showing the filesystem methods we have available for Skills including a specific namespaced directory that it's recommended Skills use for any writeable data files.
https://mycroft-ai.gitbook.io/docs/skill-development/skill-structure/filesystem

If you have any updates to your Skill, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by AZAZ78** [comment]
Hi Kris,

i will have a look on it at weekend. Nevertheless i took this pattern from some other already published skills, thought it is ok🤔 

Best regards
Alex

**Comment by AZAZ78** [comment]
I changed the optional local credentials storage to the proposed persistent skill directory and used mycroft native functionality for this (also in the local credentials creator).

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1476)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1476/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1476/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1476/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1476/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1476/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1476)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1476/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1476/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1476/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1476/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1476/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1476)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1476/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1476/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1476/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1476/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1476/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1476))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1476)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1476/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1476/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1476/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1476/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1476/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1476))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1476)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1476/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1476/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1476/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1476/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1476/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
