### PR TITLE
Add wake-button-rpi

### PR DESCRIPTION
**Pull request by guhl**
## Info

This PR adds the new skill, [wake-button-rpi](https://github.com/guhl/wake-button-rpi-skill), to the skills repo.

## Description

Press a button that is connected to a GPIO input to trigger wakeup so that the device starts listening.
If the button is pressed for a longer time he stops whatever he is doing.
This skill is heavily based on the Google AIY voicekit skill by Andlo.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1414))

**Comment by krisgesling** [comment]
Hey Guhl, thanks for submitting your first Mycroft Skill :tada:

From a quick look it seems very nice!

Two small things:
1. It looks like there's a mismatch between the dialog name in `__init__.py` and the dialog file `s` vs `z` in initialise.
2. I wonder if it would help to add some basic example commands for setting the user permissions to your README? I think it will reduce the number of issues and "bug reports" you get submitted to the repo.

**Comment by krisgesling** [comment]
Sorry I should have also mentioned, that to be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

**Comment by guhl** [comment]
I added a section regarding the GPIO device access rights and fixed the typo in __init__.py

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1414))

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
