### PR TITLE
Upgrade telegram

### PR DESCRIPTION
**Pull request by luke5sky**
This upgrades telegram to include the following new commits:

 - [Merge pull request #17 from luke5sky/development](https://github.com/luke5sky/telegram-skill/commit/b879e91debeb493f5ab05fd3394a3ab5e9ebddf5)
 - [Update requirements.txt](https://github.com/luke5sky/telegram-skill/commit/170665332dc9adc1628abd996b168c3c4dc40604)
 - [Update __init__.py](https://github.com/luke5sky/telegram-skill/commit/5cd0942d1ebdb32ded33a3b80b3c47d163c050f2)
 - [Update __init__.py](https://github.com/luke5sky/telegram-skill/commit/e48e89cbbf9c8d5037d3ca878d4fea2d591094cb)
 - [Merge pull request #16 from luke5sky/master](https://github.com/luke5sky/telegram-skill/commit/ed61012c12cc345850db1640661dc59fab39f8b4)
 - [Merge pull request #15 from luke5sky/development](https://github.com/luke5sky/telegram-skill/commit/0b51fbdfdc4cfcd6f8c34d0e973aab71c2c528be)
 - [Update README.md](https://github.com/luke5sky/telegram-skill/commit/eff525ea9ea9533173c50c0e4c89a95b10bcb4ac)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1405))

**Comment by krisgesling** [comment]
Hey Luke, it seems like the Chat ID is no longer reported by new bots. Have you created a new bot recently? Want to make sure I'm not just missing something obvious.

Also not required for this update, but you might be interested in using [`settings_change_callback`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#mycroft.MycroftSkill.settings_change_callback). This lets you define a callback function that will be executed every time the Skills settings are modified. Would remove the need for people to reboot after entering their settings.

You could also simplify the `sendMycroftSay` and `sendMycroftUtt` methods by using `self.bus.emit`:
```python
from mycroft.messagebus import Message

self.bus.emit(Message('speak',
                      {"utterance": <words to be spoken>,
                       "lang": <language code, e.g. en-us>}))
self.bus.emit(Message('recognizer_loop:utterance',
                      {"utterances": [text],
                       "lang": self.stt.lang,
                       "session": session_id}))
```
[More details here](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mycroft-core/message-types)

**Comment by luke5sky** [comment]
Hi,

i did create a new bot and installed a new mycroft instance (via docker).
Do you get any error messages?`

Thanks for the hints especially the callback function looks pretty neat.
Will look into this!

regards

**Comment by krisgesling** [comment]
No sorry, I misread the instructions, didn't realise you needed to connect the bot, then try chatting to it in order to get your Chat ID. 

Working great now. I'll merge this in and can do another update if you want to add in the settings callback.

Thanks :)

**Pull request merged**
