### PR TITLE
Upgrade cocktails

### PR DESCRIPTION
**Pull request by forslund**
This upgrades cocktails to include the following new commits:

 - [Remove weird failing test](https://github.com/forslund/skill-cocktail/commit/5d38f66ec29acf79750b84d31259e90fdf7fec8e)
 - [Merge pull request #16 from forslund/bugfix/unspecified-amount](https://github.com/forslund/skill-cocktail/commit/22527f5315259c221ba694b7b5a11a6ea46aa93f)
 - [Add behave tests](https://github.com/forslund/skill-cocktail/commit/43123ac654a87b49cdd8a2b3dca8b22ec879e38f)
 - [Merge pull request #15 from forslund/bugfix/unspecified-amount](https://github.com/forslund/skill-cocktail/commit/d3b971b0fac6dbdd8a05cd9fc9e44a2be6de23bc)
 - [Add license](https://github.com/forslund/skill-cocktail/commit/105a0161a111c2640b6afd4f212873cb2476fae8)
 - [Add docstrings and comments and fix style issues](https://github.com/forslund/skill-cocktail/commit/62e7874e58cd957a9ad7cdab6012f10a436a9431)
 - [Handle ingredients without an amount](https://github.com/forslund/skill-cocktail/commit/3fe09724aa43ecc1e3634b2ec9fcae2171fa4e06)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1335))

**Comment by forslund** [comment]
Run test

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1335))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1335))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1335))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1335))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1335))

**Comment by krisgesling** [comment]
run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Minor code revisions. Docs and VK tests :tada:

**Pull request merged**
