### PR TITLE
Add bedtime-stories-skill

### PR DESCRIPTION
**Pull request by TREE-Ind**
## Info

This PR adds the new skill, [bedtime-stories-skill](https://github.com/TREE-Ind/bedtime-stories-skill), to the skills repo.

## Description

A skill that has a small selection of famous bedtime stories  provided by Librivox.

Stories are downloaded with the skill and can be listed by voice, selected by title, or chosen randomly.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by AIIX** [comment]
Tested and works for me.

**Comment by KathyReid** [comment]
## Meta

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.9 `dev` branch
* Who: @kathy-mycroft / @KathyReid 
* Datestamp: Fri  4 Jan 05:47:40 AEDT 2019
* Language and dialect of tester: English native speaker, Australian accent

## Standard checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.
> This is the first time this has been submitted, voice install not yet available. Checking STT transcription works OK
`05:49:30.777 - __main__:handle_utterance:62 - INFO - Utterance: ['install bedtime stories skill']`
> Installing using `msm install`
```bash
(.venv) kathyreid@kathyreid-ubuntu-X510UQ:~/mycroft-core$ msm install https://github.com/TREE-Ind/bedtime-stories-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/TREE-Ind/bedtime-stories-skill
INFO - Successfully installed bedtime-stories-skill
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.
> ran each of the `dialog` files through `mimic`. All good. 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> The Intents are well distinguished with the `story` keyword, should not conflict with the "Tell...." wiki fallback. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._
> There is an error in the icon that is used, I'ved raised a PR to fix it; 
https://github.com/TREE-Ind/bedtime-stories-skill/pull/1
_ACTION REQUIRED: please pull in this PR and push again to this repo_

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 
> none specified, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?
> This file is not used; it should be removed
_ACTION REQUIRED: please remove this file_

## Python checks
* Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL? 
> No, a license file is required
_ACTION REQUIRED: Please add a LICENCE file_

* Inline documentation - is the code documented in line?
> No but it's fairly straightforward

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> The skill takes  a while to install because it's downloading all the `.mp3` files, but no other major dependencies

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> error handling done well

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional test
Functional test already validated, many thanks @AIIX 

## Summary
* Please pull in the PR that fixes the README icon
* Please remove the `settingsmeta.json` file
* Please add a LICENSE file

**Comment by TREE-Ind** [comment]
Thank you for testing out the skill.  All three requested changes have been completed.

    Please pull in the PR that fixes the README - Completed
    Please remove the settingsmeta.json file - Completed
    Please add a LICENSE file - Completed

**Comment by KathyReid** [comment]
Perfect, thank you so much @TREE-Ind. 
Will fix `.gitmodules` conflict and merge. 
Amazing Skill, many thanks!

Cinderella, you **shall** go to the ball tonight! :princess:

**Pull request merged**
