### PR TITLE
Add kodi

### PR DESCRIPTION
**Pull request by pcwii**
## Info

This PR adds the new skill, [kodi](https://github.com/pcwii/kodi-skill), to the skills repo.

## Description

Utilize the kodi API and Python library for controlling the KODI open source media center with Mycroft.ai. The control is mostly geared towards videos/movies but is capable of handling cursor navigation as well.
The Kodi Skill uses conversational dialog to help you to control your KODI instance more naturally.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
This was functionally tested by the Community at; 
https://community.mycroft.ai/t/testing-and-feedback-for-kodi-skill/4196/43

I've made the following PRs to see if that helps the Skill pass the Auto Tester; it's definitely tripping up on this Skill, not other Skills: 

* https://github.com/pcwii/kodi-skill/pull/7

This function: 
https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L476
also seems to be failing because there is no URI schema supplied. In the call to `requests.post()` on line 490, is it possible to supply a URI schema as part of the call? I *think* that is why the test is failing.

**Comment by pcwii** [comment]
@KathyReid, Can you elaborate on next steps, i don't really understand The URI you are requesting. Excuse my ignorance.

**Comment by KathyReid** [comment]
@pcwii Sure. 

In this function: 
https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L476
the `requests.post` command issues a POST call. There is no URI schema in the call - that is, it doesn't state whether it is `http` or `https` or another URI schema (like say `ftp`). It might be worth using `self.logger.debug(put your variables here)` to see what actual URL it is POSTing to.

**Comment by mehmetaergun** [comment]
@KathyReid, is it possible that the tester somehow does not call `on_websettings_changed`[1] during `initialize`[2] before calling `post_kodi_notification`, which might explain the URL `self.kodi_path`[3,4] being blank (`''`) when the tester calls[5] that function?

Otherwise, I wonder, according to the default concatenated values[6], the invalid URL that the tester reports might have been
`http://:@127.0.0.1:8080/jsonrpc`

[1] https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L103 
[2] https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L65 
[3] https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L490 
[4] https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L120 
[5] kodi_pcwii:post_kodi_notification:493 - ERROR - Invalid URL **''**
[6] https://github.com/pcwii/kodi-skill/blob/6e160ec655172559de876823dfdcc33168f52cba/__init__.py#L105 

(Apologies for jumping in like this)

**Comment by pcwii** [comment]
@KathyReid, Truth Is I never actually tried the skill tester on this skill as I do not fully understand how they are expected to test all the utterances and there are many community skills that did not have these implimented. With that said, I would expect that the skill tester should execute the on_websettings_changed as the connection to the kodi device would depend on it and all the JSON requests would fail without a kodi device connection. The URI should return the ip address of the kodi device (likely not 127.0.0.1 that is set in the default).

**Comment by KathyReid** [comment]
@mehmetaergun Thank you so much for your helpful feedback! We really appreciate it, don't mind you jumping in at all :+1:

**Comment by krisgesling** [comment]
Closing as discussed, to be reopened on 19.02 branch.

**Pull request closed without merging**
