### PR TITLE
Add krunner-search-skill

### PR DESCRIPTION
**Pull request by forslund**
## Info

This PR adds the new skill, [krunner-search-skill](https://github.com/forslund/krunner-search-skill), to the skills repo.

## Description

about

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Testing the new KDE image, do not merge.

**Comment by KathyReid** [comment]
Ack, not merging :+1:

**Comment by AIIX** [comment]
Yay Seems to be working thanks @forslund :) ..skills that are already in 18.02 and pass the test shouldn't they be auto moved to the 18.08 branch ?

**Comment by forslund** [comment]
There is a tiny change required here, updating the README.md to 18.08 (the kde-test platform is extracted from that)

**Pull request closed without merging**
