### PR TITLE
Add iching

### PR DESCRIPTION
**Pull request by renayo**
## Info

This PR adds the new skill, [iching](https://github.com/renayo/iching-skill), to the skills repo.

## Description

Quickly call up a randomized hexagram from the i ching to further stimulate thought.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1364))

**Comment by krisgesling** [comment]
Hi Renayo,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Please disregard the test failure that was just reported. It doesn't seem related to your Skill. It would be great to add a simple integration test for your Skill though. This can be as simple as creating a file: `test/behave/iching.feature` with the contents:
```
Feature: random-hexagram
  Scenario: Request a random hexagram
    Given an english speaking user
     When the user says "iching"
     Then "iching" should reply with dialog from "iching.dialog"
```
More details on our integration test framework are [here in the docs](https://mycroft-ai.gitbook.io/docs/skill-development/voight-kampff).

After a brief look, it may also be worth adding close sounding words like "itching" to your Padatious intent. I imagine the STT will find it difficult to transcribe a user saying "iching"? And in case it wasn't clear, you can include whole phrases in your .intent file but this is up to you, eg :
```
give me an iching
tell me an iching
... etc
```

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1364))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1364))

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
