### PR TITLE
Upgrade fallback-query

### PR DESCRIPTION
**Pull request by forslund**
This upgrades fallback-query to include the following new commits:

 - [Merge pull request #12 from devs-mycroft/translations](https://github.com/MycroftAI/skill-query/commit/8122f664ea5faf4e8dc07208188f1fbfcbce139b)
 - [Update translations](https://github.com/MycroftAI/skill-query/commit/ea7227e00e403827f4fd559866df2342f1cc267a)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1306))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1306))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1306))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1306))

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Expermination has taken place, no merging of this one!

**Pull request merged**
