### PR TITLE
18.02

### PR DESCRIPTION
**Pull request by dmwilsonkc**
## Description: 
Control a MagicMirror with Mycroft voice commands via MMM-Remote-Control module

**Short description of your skill and what it does
 You can use this skill to hide or show modules, update the mirror or individual modules, refresh or restart the mirror, list installed modules, install modules by name. It requires a working MagicMirror on a Raspberry Pi, MMM-Remote-Control module installed and working properly, and Mycroft must be installed on the same Raspberry Pi

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] README.md has been updated with the following:
  ```
  +[submodule "magic-mirror-voice-control-skill"]
  +	path = magic-mirror-voice-control-skill
  +	url = https://github.com/dmwilsonkc/magic-mirror-voice-control-skill
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by dmwilsonkc** [comment]
Not sure I did this correctly. This is my first attempt at submitting a skill.

**Comment by KathyReid** [comment]
Is this a duplicate of #373 - should I close out this PR and leave #373 open?

**Comment by KathyReid** [comment]
@dmwilsonkc Is this a duplicate of #373 - should I close out this PR and leave #373 open?

**Comment by dmwilsonkc** [comment]
Yes, sorry.

**Pull request closed without merging**
