### PR TITLE
add learning skill

### PR DESCRIPTION
**Pull request by gras64**
**Learning Skill**: @gras64 

## Description:

Learning Skill This skill teaches you to enable knowledge and humor. This Skill give mycroft a personality

## Checklist:
  - [ x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ x] Skill has been tested and works 
  - [ x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [ x] .gitmodules has been updated with the following:
  
```
[submodule "learning_skill"]
	path = learning_skill
	url = https://github.com/gras64/learning-skill.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Andreas,

I just gave this a test run on a Mark 1 and ran into two problems. 

It seems get_response() is not handling multi-sentence dialog well. So:
"I like to learn. Which category is it?" is triggering the listener after "I like to learn."
However, if I change the period, to a comma it works just fine.
I'll look into this in mycroft-core as it shouldn't be happening, but it may be something to change in the interim.

The directory you are writing to will also change depending on the platform. So this will work on a picroft but not on linux or a Mark 1. On a Mark 1, even though you login as user "pi", it's actually user "mycroft" that runs and owns everything. Linux is generally the user that cloned the repo, but this can depend on how they set it up. I wonder if it would be best to detect the current username and build the local_path and public_path dynamically?

Thanks for the great skill though, and sorry it's taken some time to review.

**Comment by gras64** [comment]
I've converted all the points into dialog also fits the sentence better. as path I have user folder

**Comment by forslund** [comment]
@gras64 the MycroftSkill contains a `.file_system` member which is a link to a skill specific location. Basically `self.file_system.path` will give you a path similar to `~/.mycroft/skills/YourSkill` which may be useful.

I used it in the [zork skill for savegames](https://github.com/forslund/white-house-adventure/blob/master/__init__.py#L92).

**Comment by gras64** [comment]
I want that path to be easy to find and easy to customize to allow cloud. That's why I did not do the other solution. Everyone should be able to see and edit the correct path.

**Comment by krisgesling** [comment]
This is useful for my own knowledge of Mycroft methods :)

Based on my reading of `self.file_system.path` this will always return `~/.mycroft/skills/LearningSkill/`
but because it's being handled by mycroft-core, `~` refers to the home directory of the user who is running mycroft-core rather than having this hard coded in. This perfectly handles the case of the Mark1 by saving the file at `/home/mycroft/.mycroft/skills/LearningSkill/`
or if I run it on my Linux machine as user `kris` > `/home/kris/.mycroft/skills/LearningSkill/`

So the path is consistent if people want to find it or edit it manually.

**Comment by gras64** [comment]
I have set the default path to system and on mycroft.ai the path must be empty. I have also set up a path check in the fallback handler to bypass the error message if the path does not exist.
I hope I have done everything right.

**Comment by krisgesling** [comment]
## Meta
*   Platform: Mark 1
*   Mycroft-core version: 19.02.1
*   Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft
*   Datestamp: 2019-03-26_13:39:54_ACST
*   Language and dialect of tester: English with Australian accent

## 0. Automated tests
Are all automated tests passing?
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable
- [x]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

> Looks good

- [x]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

> Minimal

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Appropriate usage
> sys from os.path no longer required.
> mycroft.util.log is now included in the MycroftSkill base class so doesn't need to be imported just use `self.log`

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> NA

- [ ]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

> Appropriate options - could provide a description for "allowed categories"
> Name in settings to match name in README heading

_Action Required: In settingsmeta.json update skill name and consider a description for "allowed categories"_


- [x]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

> Yes, great work!

- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

> No


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x]   **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> Yes

- [ ]   **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> We are trying to remove the word 'Skill' from all skill names for consistency. I wonder if Learning Fallback might be a good alternative?
> Currently Skill cards only get one line for the short description in the Marketplace. This is the text above 'About', whilst text below that heading is provided on detailed view.
> Perhaps a short description could be something like: "Teach Mycroft knowledge and humor."
> With a longer description below 'About': "This Skill helps to give Mycroft a personality by learning any new information that you provide."

_Action required: Consider changes to README.md_

- [x]   **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> Yes

- [x]   **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> NA

- [x]   **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes

- [ ]   **Tags**
Are listed tags appropriate for this Skill?

> Two small typo's - #learning and #science

_Action required: Fix typo's in tags_

- [ ]   **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> No license included - for a walk through on adding a license to a repo see https://help.github.com/en/articles/adding-a-license-to-a-repository

_Action required: Select a license for the repo_

## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method: `mycroft-msm install https://github.com/gras64/learning-skill`
> ```
> pi@mark_1:~ $ mycroft-msm install https://github.com/gras64/learning-skill
> INFO - Downloading skill: https://github.com/gras64/learning-skill
> INFO - Installing system requirements...
> INFO - Successfully installed learning-skill
> ```
> Checking that STT transcribes correctly:
> ```
> Utterance: ['install learning skilled']
> INFO - Best match (0.62): learning-skill.gras64 by gras64
> ```


- [x]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> As above.

- [x]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

>



#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [ ]   **"do you want to learn something"**

> `"Knowledge makes me more human, give me a category."`
> science
> `"what is your question?"`
> how big is the sun
> `"give me keywords"`
> sun
> `"what should I know about it."`
> it's enormous
```
05:26:16.196 - mycroft.skills.core:wrapper:1035 - ERROR - An error occurred while processing a request in Learning Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 1026, in wrapper
    handler(message)
  File "/opt/mycroft/skills/learning-skill.gras64/__init__.py", line 143, in handle_interaction
    os.makedirs(answer_path)
  File "/opt/venvs/mycroft-core/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/venvs/mycroft-core/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/venvs/mycroft-core/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/science'
```

_Action Required: review answer and question path_

## Summary
Hi Andreas,
* The error directly above seems to stem from the `privacy` variable not being set. This results in the skill attempting to save data into the `/science` directory rather than `/opt/mycroft/skills/...`.
* I've also made a few suggestions for the README and settingsmeta.
* Finally we need to have an appropriate license on the skill. I've included a link above for how to do this in Github.

Once you have completed any updates, you can update this pull request by running `mycroft-msk submit /path/to/skill/directory`

It's an exciting Skill though, interesting to think about how we embed more learning into Mycroft.

Thanks

**Comment by krisgesling** [comment]
Closing in favour of #940 

If you update that PR we can get it added to the Marketplace :)

**Pull request closed without merging**
