### PR TITLE
Added CryptoSkill to fetch info regarding cryptocurrencies

### PR DESCRIPTION
**Pull request by Gobbenobber**
## Description:

This skill utilizes the CoinMarketCap API found on https://api.coinmarketcap.com to deliver cryptocurrency-related functionality for Mycroft.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by el-tocino** [comment]
In requirements.txt you call for gensim to be installed, but I don't see it being called in your code?  Also...no Monero?

**Comment by Gobbenobber** [comment]
Oops, I'll be editing the requirements file to correctly reflect requirements...
Also, Monero has been added ;)!
Should I create a new PR to include these changes?

**Comment by el-tocino** [comment]
No, just push an updated commit.

**Comment by el-tocino** [comment]
Have you considered trying to match the names with fuzzy?  Might also be worth investigating using the symbol names as well, and could even extend to being able to check stock prices.

**Comment by JarbasAl** [comment]
so many bitcoin skills

https://github.com/JarbasAl/cryptocoin_skill  <- all the coins (in cryptonator)

**Pull request merged**
