### PR TITLE
Updating ha skill for 2.1

### PR DESCRIPTION
**Pull request by btotharye**
## Description:
Updated the Home Assistant skill for version 2.1 - https://github.com/btotharye/mycroft-homeassistant/releases/tag/v2.1

Added climate control

**Short description of your skill and what it does

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [X] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by btotharye** [comment]
for what its worth here are my tests passing using the testrunner - https://jenkins.btotharye.com/job/home_assistant_skill/124/console

**Comment by KathyReid** [comment]
Thanks Brian - I don't run HA, I will see if someone else in the Skills Team can run a quick test on this.

**Comment by btotharye** [comment]
Ok thanks @KathyReid I added in some more test files so this should have around 76% coverage now overall.

**Comment by btotharye** [comment]
This can be tested without needing HA at anytime using http://167.99.144.205:8123/states with password password port 8123 in the settings configuration.

Thanks

**Pull request closed without merging**
