### PR TITLE
Add evil-laugh

### PR DESCRIPTION
**Pull request by JarbasAl**
## Info

This PR adds the new skill, [evil-laugh](https://github.com/JarbasAl/skill-laugh), to the skills repo.

## Description

makes mycroft laugh randomly or on request, gender configurable

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by penrods** [comment]
Works, but a couple minor things:
* It works as is, but the stop() method should return True if it "consumes" the stop.  This allows the top button on a Mark 1 to distinguish between when it is being pressed to Stop something, and when it is being pressed to go into Listen mode
* The README doesn't follow the new format, so it won't look right in the Marketplace at all

**Comment by KathyReid** [comment]
Hey @JarbasAI just a bump on this one ;-)

**Comment by JarbasAl** [comment]
skill updated, do i need to update this PR for the specific commit?

**Comment by JarbasAl** [comment]
msk upgrade fails, because skill was not approved yet
upload would re upload it
so i guess i don't need to do anything?
the correct commit now would be fd62194c0888163fe3d6e671b9eca7a4fbe15ace

**Comment by KathyReid** [comment]
Sorry I'm way behind on Skill testing and approvals, I've been debugging Mycroft Translate.

**Pull request closed without merging**
