### PR TITLE
Upgrade mycroft-weather

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-weather to include the following new commits:

 - [Merge pull request #72 from MycroftAI/bugfix/regex](https://github.com/MycroftAI/skill-weather/commit/7ce84236789606f325373d57cf8b338dc0c1bf08)
 - [Remove condition from temperature reply](https://github.com/MycroftAI/skill-weather/commit/e1e2e545be352f4eec49a2d8ffab9dd926aa9713)
 - [Fix regex to work with multiple words](https://github.com/MycroftAI/skill-weather/commit/3c85d55d2935e51ae7d83353a65e562fb4642a3e)
 - [Merge pull request #71 from MycroftAI/feature/review-update](https://github.com/MycroftAI/skill-weather/commit/5934c54fb3f28251b4869ac7d5febcbb7176b939)
 - [Add test for current temperature](https://github.com/MycroftAI/skill-weather/commit/adf62c5f17ca5a579a1f2d4d4cf669a5db29bea6)
 - [Fix weather later](https://github.com/MycroftAI/skill-weather/commit/8f6295337728732a66bea7c0f77badb14797a447)
 - [Make unit translatable](https://github.com/MycroftAI/skill-weather/commit/3b80e9cb328d906af2efda36b6df6a01e3c73607)
 - [Add high and low temperature handlers](https://github.com/MycroftAI/skill-weather/commit/fe9ac79d703304f3cd23d10268c6eb91b8473486)
 - [Add drizzle to Precipitation vocabulary](https://github.com/MycroftAI/skill-weather/commit/ecd9682f2c3bde7e6f5b67ad3fa6fdb14b93ad4d)
 - [Handle temperatures in other locations and times](https://github.com/MycroftAI/skill-weather/commit/e5d43dca811f149539261198196a43b8a584dd59)
 - [Add support for temperature requests.](https://github.com/MycroftAI/skill-weather/commit/bb7462a87912658cec0d7048f75a76eb8e72c819)
 - [Remove extra min.max-message from forecast](https://github.com/MycroftAI/skill-weather/commit/8343249f89014cb5944f945ba9787bbfb96b46b8)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Ake, these generally worked perfectly for me. 

I hit two small issues, but neither should necessarily block this update:  

**1. Weather next weekend**
When asking: "what is the weather like next weekend". For some reason it's not returning a report even though they are available through OWM directly. I also can't see any exception raised, just:
```
06:27:06.342 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/owm/forecast/daily?lang=en&cnt=10&lat=-12.46344&lon=130.845642 HTTP/1.1" 200 2841
06:27:06.378 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
06:27:06.380 - mycroft-weather_mycroftai:request:84 - DEBUG - Using cached OWM Response from 136.187300146
```
Then because the intent generates individual dialogs for Saturday and Sunday's weather report, the user hears two messages that it doesn't know the weather:
> Sorry, I don't know the forecast for Saturday
> Sorry, I don't know the forecast for Sunday
  
**2. Weather in other locations**
The `location` entity seems to be missed if the location is made up of multiple words eg:
"What is the weather like in Ontario Canada" returns local weather in Darwin (my current location)
"What is the weather like in Ontario" returns local weather in Ontario

**Comment by forslund** [comment]
Hmm, let me see if I can clean up the location parsing some more. cities like "Buenos Aires" seem to be failing as well...

**Comment by forslund** [comment]
I did a fix so things like buenos aires will work again. I started on some stuff with things like "Ontario canada" but it's not done yet and as it wasn't working before I think this can be processed.

**Comment by krisgesling** [comment]
Yep, agreed :)

**Pull request merged**
