### PR TITLE
Add pick-number

### PR DESCRIPTION
**Pull request by pcwii**
## Info

This PR adds the new skill, [pick-number](https://github.com/pcwii/skill-pick-number), to the skills repo.

## Description

Mycroft.AI will select a random number between a min and max value.
The minimum and maximum value may be in any order and any value.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
## Meta

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.9, `dev` branch
* Who: @KathyReid / @kathy-mycroft
* Datestamp: Thu  3 Jan 05:20:31 AEDT 2019
* Language and dialect of tester: Native English speaker, Australian accent

## Standard checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is the first time the Skill has been submitted; not available for voice install. 
Checking that STT transcribes correctly; 
`~~~~5 - __main__:handle_utterance:62 - INFO - Utterance: ['install pick number']`
> Using `msm install` 

```bash
(.venv) kathyreid@kathyreid-ubuntu-X510UQ:~/mycroft-core$ msm install https://github.com/pcwii/skill-pick-number
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/pcwii/skill-pick-number
INFO - Installing requirements.txt for skill-pick-number
INFO - Successfully installed skill-pick-number
```

_Successfully installed_

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran each of the `dialog` files through `mimic`. The `error` dialog needed to be broken up a bit, I have raised a PR for this - https://github.com/pcwii/skill-pick-number/pull/1

_ACTION REQUIRED: Please pull in this PR then push to `mycroft-skills` again_

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> The Intent files are really well written, nice work @pcwii. Intent collisions unlikely. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._
> The only niggle I found with the README was that there was a warning in the Categories. Have raised https://github.com/pcwii/skill-pick-number/pull/2 to resolve this. 

_ACTION REQUIRED: Please merge in this PR then push to `mycroft-skills` again_

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> `requirements.txt` is empty; this file should be removed if it is not being used please.

_ACTION REQUIRED: please remove requirements.txt from the repo_

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> not used, skipping check

## Python code check

* Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL? 
> Yes, GPL3 license used

* Inline documentation - is the code documented in line?
> This is a basic Skill, it doesn't require a lot of inline documentation

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> no libraries used, skipping check

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> error handling is done using if.. then conditions rather than try .. catch .. exception blocks, but yes, error handling is done

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional tests

* "select a number between 1 and 10"
> number chosen correctly

* "select a number between 1 and 10"
> number chosen correctly

* "choose a number between 100 and 199"
> number chosen correctly

* "pick a number from 5 to 15"
> number chosen correctly

* "select a number between 20 and 1"
> number chosen correctly

I then repeated these with negative numbers to make sure there were no out of bounds errors, all OK

## Summary
* Please pull in the PR for the `dialog` file
* Please pull in the PR for the README file
* Please remove `requirements.txt`

Other than that, this Skill is really well written - thank you!

**Comment by KathyReid** [comment]
Hey @pcwii just checking in on this one, let me now if you need any assistance :+1:

**Comment by pcwii** [comment]
Sorry @kathyreid, been down a rabit hole with Homeassist and have not found time to upload the changes you requested. Will try to get it done soon. Also looking to move things forward with kodi as well. Thanks for the support.

**Comment by KathyReid** [comment]
No worries, thanks for letting us know @pcwii, this can sit here for a little while ;-)

**Comment by krisgesling** [comment]
@pcwii thanks for fixing up those little things. This looks ready to merge, nice job!

**Comment by pcwii** [comment]
Great news! My first official skill accepted. Now onto my Kodi skill ;-)

**Comment by penrods** [comment]
Lgtm!

**Pull request merged**
