### PR TITLE
Upgrade remember

### PR DESCRIPTION
**Pull request by luke5sky**
'This upgrades remember to include the following new commits:

 - [Merge pull request #2 from devs-mycroft/translate-2018-12-31](https://github.com/luke5sky/remember-skill/commit/0fe72c7704f2d578bacc038c9c75aa64f826e4a7)
 - [Update translations](https://github.com/luke5sky/remember-skill/commit/a629ddbe79de57b29247071b67b61d2fc0c426ca)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by luke5sky** [comment]
Spanish translations

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Review by KathyReid — APPROVED** [review]
Translations only; did a quick desk check, LGTM, merging

**Pull request merged**
