### PR TITLE
Add rodent-facts

### PR DESCRIPTION
**Pull request by btotharye**
## Info

This PR adds the new skill, [rodent-facts](https://github.com/btotharye/rodent-facts-skill), to the skills repo.

## Description

 rodent facts

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
## Skills acceptance check

### Meta

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.8.4 
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Thu  1 Nov 22:43:19 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> The Skill is not yet in the repo, so voice install is not possible. I used the phrase 'install rodent skill' STT to ensure that it was transcribed correctly; it was. Using command line install; 

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/btotharye/rodent-facts-skill
INFO - Downloading skill: https://github.com/btotharye/rodent-facts-skill
INFO - Successfully installed rodent-facts-skill
```
> Successfully installed

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Pronounced OK in `Kusal` voice; have reported an issue with pronunciation of 'OK' to @LearnedVector. 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Checked Intents, added another one just for good disambiguation from the Wikipedia Skill

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> The README does not include an icon, a category or tags
ACTION REQUIRED: please generate the README using the new [meta editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html). 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> no requirements used, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense? 

> `settingsmeta.json` exists but is not used
ACTION REQUIRED: please remove the `settingsmeta.json` as it is not used.


### code checks

* Inline documentation - is the code documented in line?
> simple Skill, documentation not required

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> no libraries or deps

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> not required

* Error handling - are there any specific checks we make for error handling or graceful degradation?

> no, simple Skill

* Automatic tests - do automatic tests of the **Skill** pass?

> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> not relevant, skipping check

### functional check

* `Hey Mycroft, tell me a rat fact`
> rat fact returned correctly

Tried several variations on this, all passing. 

## Summary

* Please update README using new meta editor
* Please remove `settingsmeta.json`

Then I'll merge this one ;-) 

Rat-tastic :rat:

**Comment by btotharye** [comment]
ok updates should be done, let me know @KathyReid

**Comment by KathyReid** [comment]
Lovely, thanks for those commits!

**Pull request merged**
