### PR TITLE
Add routine

### PR DESCRIPTION
**Pull request by ChristopherRogers1991**
## Info

This PR adds the new skill, [routine](https://github.com/ChristopherRogers1991/mycroft_routine_skill), to the skills repo.

## Description

Create named rountines, which are lists of Mycroft commands, that can be run by name, and scheduled to run at particular times.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by ChristopherRogers1991** [comment]
Not quite sure how to test this one with the automated testing framework. The one test that does exist attempts to create a new routine, but if fails when there is no response from the user:

```
Evaluating message:  {'intent_type': 'test-routine.christopherrogers1991:CreateRoutine', 'target': None, 'confidence': 0.4, '__tags__': [{'match': 'create', 'key': 'create', 'start_token': 0, 'entities': [{'key': 'create', 'match': 'create', 'data': [('create', 'test_routine_christopherrogers1991Create')], 'confidence': 1.0}], 'end_token': 0, 'from_context': False}, {'match': 'routine', 'key': 'routine', 'start_token': 2, 'entities': [{'key': 'routine', 'match': 'routine', 'data': [('routine', 'test_routine_christopherrogers1991Routine')], 'confidence': 1.0}], 'end_token': 2, 'from_context': False}], 'utterance': 'Create a new routine', 'Create': 'create', 'Routine': 'routine', '__type__': 'CreateRoutine'}

Evaluating message:  {'name': 'MycroftRoutineSkill._create_routine', '__type__': 'mycroft.skill.handler.start'}

Evaluating message:  {'__type__': 'enclosure.mouth.think'}

Evaluating message:  {'utterance': 'What would you like to name it?', 'expect_response': True, '__type__': 'speak'}

Evaluating message:  {'skill_id': 'test-routine.christopherrogers1991', '__type__': 'active_skill_request'}

Evaluating message:  {'utterance': 'What would you like to name it?', 'expect_response': True, '__type__': 'speak'}

Evaluating message:  {'skill_id': 'test-routine.christopherrogers1991', '__type__': 'active_skill_request'}

Evaluating message:  {'name': 'MycroftRoutineSkill._create_routine', '__type__': 'mycroft.skill.handler.complete'}
Evaluation failed
Rule status:  [['and', ['or', ['endsWith', 'intent_type', 'CreateRoutine', 'succeeded'], ['endsWith', '__type__', 'CreateRoutine'], 'succeeded'], ['equal', 'Create', 'Create'], ['equal', 'Routine', 'routine']]]

```

The other intents (e.g. describe, run, delete, schedule) depend on state - routines must exist to perform those operations. I'm not sure what the framework provides to test things like that.

**Comment by forslund** [comment]
For intents using get_response you can specify a list of replies using

```
  "responses": ["morning routine", "weather", "show time", "that is all"]
```

The test case is also case sensitive which causes
`"Create": "Create",` to fail since the received value for Create is *create*

**Comment by KathyReid** [comment]
#### Test of routine-skill

* Platform: Mark 1
* Device version: 18.2.8b
* Who: @kathyreid / kathy-mycroft
* Datestamp: Wednesday 27 June  04:09:55 AEST 2018
* Language and dialect of tester: Native English Speaker, Austraaaaaalian accent

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This Skill isn't yet in the `18.02` branch so it is not yet voice-installable. Instead, I used `msm` to install. 

```bash
pi@mark_1:~ $ msm install https://github.com/ChristopherRogers1991/mycroft_routine_skill
INFO - Downloading skill: https://github.com/ChristopherRogers1991/mycroft_routine_skill
INFO - Installing requirements.txt for mycroft_routine_skill
INFO - Successfully installed mycroft_routine_skill
```

```bash
pi@mark_1:~/skills/mycroft_routine_skill.christopherrogers1991 $ ls -las
total 92
 4 drwxr-xr-x  7 mycroft mycroft  4096 Jun 26 18:26 .
 4 drwxrwxrwx 36 mycroft mycroft  4096 Jun 26 18:26 ..
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jun 26 18:26 dialog
 4 drwxr-xr-x  8 mycroft mycroft  4096 Jun 26 18:26 .git
 4 -rw-r--r--  1 mycroft mycroft    39 Jun 26 18:26 .gitignore
12 -rw-r--r--  1 mycroft mycroft  8553 Jun 26 18:26 __init__.py
32 -rw-r--r--  1 mycroft mycroft 32472 Jun 26 18:26 LICENSE
 4 drwxr-xr-x  2 mycroft mycroft  4096 Jun 26 18:26 __pycache__
 4 -rw-r--r--  1 mycroft mycroft  2459 Jun 26 18:26 README.md
 4 -rw-r--r--  1 mycroft mycroft    11 Jun 26 18:26 requirements.txt
 4 -rw-r--r--  1 mycroft mycroft    35 Jun 26 18:26 settings.json
 4 -rw-r--r--  1 mycroft mycroft  3097 Jun 26 18:26 skill_developers_testrunner.py
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jun 26 18:26 test
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jun 26 18:26 vocab
```
> I also checked the Utterance to make sure that voice installation _would_ be successful: 
`~~~~- __main__:handle_utterance:61 - INFO - Utterance: ['install routine skill']`
That is, the Utterance is captured OK by STT. 

> OUTCOME: Installation successful

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all the `dialog` through `mimic` - all quite fluent and works well. 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> The `Intents` are quite granular, so I inspected the code to see how they are used in combination. The `intent_handler()` decorators generally use three or more of the `*.voc` files in combination, usually a `Required` combination, so I don't think we're going to get a lot of Intent collision here. Passing. 

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> No regex used, skipping inspection

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> This README fills me with joy and happiness and examples. A lovely README. 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> requirement does not specify a version, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Skill does not use settings, skipping check

#### Functional check 

I had trouble creating a routine from start to finish, primarily because the `get_response()` continually appeared to not capture the Utterance - see below - the Utterances are `null` a lot of the time. 

That said, I'm going to approve this Skill for merging because it may just be my Australian accent - and that way others can try it out and it can be improved iteratively. Other than that, this is a **really** well put together Skill. Thank you. 

```bash
pi@mark_1:/var/log $ cat mycroft-skills.log | grep -i routine | grep -i utterance
19:04:39.153 - SKILLS - DEBUG - {"context": {"ident": "1530039875.73058061646904214", "client_name": "mycroft_listener"}, "data": {"utterances": ["create routine"], "lang": "en-US", "session": "b09dc525-425b-4356-9fd8-eb91bf6c342e"}, "type": "recognizer_loop:utterance"}
19:04:39.179 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1530039875.73058061646904214"}, "type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine", "data": {"mycroft_routine_skill_christopherrogers1991Create": "create", "utterance": "create routine", "target": null, "mycroft_routine_skill_christopherrogers1991Routine": "routine", "__tags__": [{"key": "create", "end_token": 0, "entities": [{"match": "create", "key": "create", "confidence": 1.0, "data": [["create", "mycroft_routine_skill_christopherrogers1991Create"]]}], "start_token": 0, "match": "create", "from_context": false}, {"key": "routine", "end_token": 1, "entities": [{"match": "routine", "key": "routine", "confidence": 1.0, "data": [["routine", "mycroft_routine_skill_christopherrogers1991Routine"]]}], "start_token": 1, "match": "routine", "from_context": false}], "confidence": 1.0, "intent_type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine"}}
19:04:50.587 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:04:58.811 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["team 10"]}}
19:05:13.864 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:05:22.544 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:06:05.433 - SKILLS - DEBUG - {"context": {"ident": "1530039961.1053931646904214", "client_name": "mycroft_listener"}, "data": {"utterances": ["create routine"], "lang": "en-US", "session": "b09dc525-425b-4356-9fd8-eb91bf6c342e"}, "type": "recognizer_loop:utterance"}
19:06:05.446 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["create routine"]}}
19:06:05.565 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1530039961.1053931646904214"}, "type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine", "data": {"mycroft_routine_skill_christopherrogers1991Create": "create", "utterance": "create routine", "target": null, "mycroft_routine_skill_christopherrogers1991Routine": "routine", "__tags__": [{"key": "create", "end_token": 0, "entities": [{"match": "create", "key": "create", "confidence": 1.0, "data": [["create", "mycroft_routine_skill_christopherrogers1991Create"]]}], "start_token": 0, "match": "create", "from_context": false}, {"key": "routine", "end_token": 1, "entities": [{"match": "routine", "key": "routine", "confidence": 1.0, "data": [["routine", "mycroft_routine_skill_christopherrogers1991Routine"]]}], "start_token": 1, "match": "routine", "from_context": false}], "confidence": 1.0, "intent_type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine"}}
19:06:15.372 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["team 10"]}}
19:06:29.945 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["speak hello"]}}
19:06:42.498 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:06:49.969 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:07:17.017 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:07:32.260 - SKILLS - DEBUG - {"context": {"ident": "1530040048.5814721646904214", "client_name": "mycroft_listener"}, "data": {"utterances": ["create routine"], "lang": "en-US", "session": "b09dc525-425b-4356-9fd8-eb91bf6c342e"}, "type": "recognizer_loop:utterance"}
19:07:32.275 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["create routine"]}}
19:07:32.396 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1530040048.5814721646904214"}, "type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine", "data": {"mycroft_routine_skill_christopherrogers1991Create": "create", "utterance": "create routine", "target": null, "mycroft_routine_skill_christopherrogers1991Routine": "routine", "__tags__": [{"key": "create", "end_token": 0, "entities": [{"match": "create", "key": "create", "confidence": 1.0, "data": [["create", "mycroft_routine_skill_christopherrogers1991Create"]]}], "start_token": 0, "match": "create", "from_context": false}, {"key": "routine", "end_token": 1, "entities": [{"match": "routine", "key": "routine", "confidence": 1.0, "data": [["routine", "mycroft_routine_skill_christopherrogers1991Routine"]]}], "start_token": 1, "match": "routine", "from_context": false}], "confidence": 1.0, "intent_type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine"}}
19:07:43.689 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:07:51.832 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:08:10.025 - SKILLS - DEBUG - {"context": {"ident": "1530040086.6573241646904214", "client_name": "mycroft_listener"}, "data": {"utterances": ["create routine"], "lang": "en-US", "session": "b09dc525-425b-4356-9fd8-eb91bf6c342e"}, "type": "recognizer_loop:utterance"}
19:08:10.036 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["create routine"]}}
19:08:10.153 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1530040086.6573241646904214"}, "type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine", "data": {"mycroft_routine_skill_christopherrogers1991Create": "create", "utterance": "create routine", "target": null, "mycroft_routine_skill_christopherrogers1991Routine": "routine", "__tags__": [{"key": "create", "end_token": 0, "entities": [{"match": "create", "key": "create", "confidence": 1.0, "data": [["create", "mycroft_routine_skill_christopherrogers1991Create"]]}], "start_token": 0, "match": "create", "from_context": false}, {"key": "routine", "end_token": 1, "entities": [{"match": "routine", "key": "routine", "confidence": 1.0, "data": [["routine", "mycroft_routine_skill_christopherrogers1991Routine"]]}], "start_token": 1, "match": "routine", "from_context": false}], "confidence": 1.0, "intent_type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine"}}
19:08:21.534 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:08:34.673 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:08:51.478 - SKILLS - DEBUG - {"context": {"ident": "1530040127.89119321646904214", "client_name": "mycroft_listener"}, "data": {"utterances": ["create routine"], "lang": "en-US", "session": "b09dc525-425b-4356-9fd8-eb91bf6c342e"}, "type": "recognizer_loop:utterance"}
19:08:51.491 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["create routine"]}}
19:08:51.611 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1530040127.89119321646904214"}, "type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine", "data": {"mycroft_routine_skill_christopherrogers1991Create": "create", "utterance": "create routine", "target": null, "mycroft_routine_skill_christopherrogers1991Routine": "routine", "__tags__": [{"key": "create", "end_token": 0, "entities": [{"match": "create", "key": "create", "confidence": 1.0, "data": [["create", "mycroft_routine_skill_christopherrogers1991Create"]]}], "start_token": 0, "match": "create", "from_context": false}, {"key": "routine", "end_token": 1, "entities": [{"match": "routine", "key": "routine", "confidence": 1.0, "data": [["routine", "mycroft_routine_skill_christopherrogers1991Routine"]]}], "start_token": 1, "match": "routine", "from_context": false}], "confidence": 1.0, "intent_type": "mycroft_routine_skill.christopherrogers1991:CreateRoutine"}}
19:09:01.213 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["pink panther"]}}
19:09:12.316 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": ["speak the dome the dome"]}}
19:09:28.498 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
19:09:35.782 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-us", "skill_id": "mycroft_routine_skill.christopherrogers1991", "utterances": null}}
```

**Comment by forslund** [comment]
Run test

**Pull request merged**
