### PR TITLE
Add a HTML color picker to the meta-generator for README files #502

### PR DESCRIPTION
**Pull request by anushreejain98**
#502 
## Description:

Added an HTML color picker to the meta-generator for README files

## Checklist:
  - README.md has been updated with the following:
 
colorpicker

### CODE REVIEW

**Comment by penrods** [comment]
Hello, @anushreejain98, thank you for helping with the Mycroft project! We welcome
everyone into the community and greatly appreciate your help as we work to
build an AI for Everyone.
  
To protect yourself, the project, and users of Mycroft technologies we require
a Contributor Licensing Agreement (CLA) before accepting any code contribution.
This agreement makes it crystal clear that along with your code you are
offering a license to use it within the confines of this project. You retain
ownership of the code, this is just a license.
 
Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by penrods** [comment]
Also, I love having a visual color picker, but I'd also like to retain the ability to type in HTML colors (e.g. #FF20AB and such).  There are some good solutions out there and I'd be happy to pull in something that has the right combination of attributes.  I think something like [Spectrum](http://bgrins.github.io/spectrum/) has promise.  It has a compatible license (e.g. MIT) and could be included using https://rawgit.com/bgrins/spectrum/master/spectrum.js.  This would require pulling in jquery, but I don't mind adding that reference.

**Comment by anushreejain98** [comment]
> Also, I love having a visual color picker, but I'd also like to retain the ability to type in HTML colors (e.g. #FF20AB and such). There are some good solutions out there and I'd be happy to pull in something that has the right combination of attributes. I think something like [Spectrum](http://bgrins.github.io/spectrum/) has promise. It has a compatible license (e.g. MIT) and could be included using https://rawgit.com/bgrins/spectrum/master/spectrum.js. This would require pulling in jquery, but I don't mind adding that reference.

Okay @penrods, I got your point.  I can give a try to spectrum too.
 For the time being, could you please merge this PR, if found appropriate and by the time I will look into better solutions for the same as per your suggestions.

**Comment by penrods** [comment]
I went ahead and pulled in #592 which addressed this same issue in a very clean way. Thank you for the submission, but I'm closing it unmerged.

**Pull request closed without merging**
