### PR TITLE
Add speedtest

### PR DESCRIPTION
**Pull request by luke5sky**
## Info

This PR adds the new skill, [speedtest](https://github.com/luke5sky/speedtest-skill), to the skills repo.

## Description

Run a speedtest with Mycroft.
This skill uses the speedtest-cli (https://github.com/sivel/speedtest-cli) which runs an internet bandwidth test using speedtest.net.

Be aware that this speedtest relies on the capability of the network-adapter of your Mycroft device.

Examples for Raspberry Pi:
- Raspberry Pi 3 B  onboard WiFi: max. ~40 Mbit/s, onboard LAN: max. ~100 Mbit/s
- Raspberry Pi 3 B+ onboard WiFi: max. ~100 Mbit/s, onboard LAN: max. ~225 Mbit/s

If a Raspberry Pi 3 B - connected to WiFi - runs Mycroft you won't get more than 40 Mbit/s from the speedtest despite your internet connection may have more bandwith.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
## Meta

*   Platform: PureOS Linux (Debian Buster)
*   Device version: 18.8.11
*   Who: [@KrisGesling](https://github.com/KrisGesling) / @gez-mycroft
*   Datestamp: 2019-01-24_13:13:04_ACST
*   Language and dialect of tester: Native English speaker, Australian accent

## Standard checks

*   Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is the first time the Skill has been submitted; not available for voice install.
> Checking that STT transcribes correctly;
> `__main__:handle_utterance:62 - INFO - Utterance: ['install speed test']`  
> Using `msm install`

```
(.venv) kris@bigBench:~/mycroft-core$ msm install https://github.com/luke5sky/speedtest-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/luke5sky/speedtest-skill
INFO - Installing requirements.txt for speedtest-skill
INFO - Successfully installed speedtest-skill
```

_Successfully installed_

*   Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran each of the `dialog` files through `mimic`. Generally fine however floating point numbers like "18.03" are read as "eighteen and three".

*   Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Clear Intent vocab, collisions unlikely.

*   Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

*   Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> Generally good, have submitted a PR to update some minor spelling and switching primary category to 'productivity'.

_ACTION REQUIRED: Please consider changes to README.md then resubmit using MSK_

*   Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> `requirements.txt` is used appropriately and dependencies successfully installed.

*   Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> not used, skipping check

## Python code check

*   Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL?

> Yes, Apache-2.0 license used

*   Inline documentation - is the code documented in line?

> This is a basic Skill, doesn't require much inline documentation

*   Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> appropriate library usage - single dependency - speedtest

*   Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> n/a

*   Error handling - are there any specific checks we make for error handling or graceful degradation?

>  broad error handling implemented with general error message

*   Automatic tests - do automatic tests of the **Skill** pass?

> All tests pass

*   Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4\. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> N/A

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional tests

*   "run speedtest"

> test conducted and results returned

*   With no internet connection "run speedtest"

> general error message provided

## Summary

*   Please consider changes to README.md then resubmit using MSK

Other than that, this Skill is well written and a great addition to the project - thanks @luke5sky!

**Comment by luke5sky** [comment]
Hi @krisgesling,

Thank you for the feedback.
I just can't find your PR:
> Generally good, have submitted a PR to update some minor spelling and switching primary category to 'productivity'.

**Comment by luke5sky** [comment]
Nevermind, found it :-) new upload in the next minutes

**Comment by krisgesling** [comment]
Excellent, thanks Luke!

Will merge this shortly.

**Comment by penrods** [comment]
Lgtm!

**Pull request merged**
