### PR TITLE
Nmap skill

### PR DESCRIPTION
**Pull request by Nhoya**
## Description:
Execute `nmap` portscan with `scan TARGET IP`

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] README.md has been updated with the following:
  ```
  +[submodule "skill-nmap"]
  +	path = skill-nmap
  +	url = github.com/Nhoya/skill-nmap.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by KathyReid** [comment]
# Review of `skill-nmap`

_NOTE: I've also functionally tested this Skill pretty thoroughly on Mark 1, see https://community.mycroft.ai/t/mycroft-skill-for-nmap-scan/3335/8 for more information_

## Standard checks (non-code checks)
* Check name of Skill - `skill-nmap` is  unlikely to conflict with other vocal `install Skill X` commands = there are no similar phonemes for `nmap`. I tested the vocal installation of the Skill using the Utterances `install en map` and `install N M A P` and Mycroft wasn't able to match either Utterance. _Should we consider naming this Skill something different to facilitate voice installs?_

* Check `dialog` - from a voice user interface perspective the dialog works well. Tested on a Mark 1 using Amy voice.

* Check `vocab` - the `scan` Intent works well, but my natural inclination was to use `en map` as the Intent. _Recommend: adding another Intent_

* Check `regex` - Regex looks good, the named group looks syntactically correct

* Check README for completeness - the README is a little bare and could include information on the options `nmap` is called with, so the user knows how aggressive the `nmap` is, examples of the responses that the Skill comes back with, and a little bit on the requirements. 

* Check `requirements.txt` and `requirements.sh` - we've overcome a few issues identified in `requirements.sh` and this file is now quite sophisticated, including platform identification so that the `nmap` utility can be installed cross-platform. 

* Check `settingsmeta.son` - is not used; there are no user-configurable settings. In a future iteration, you might want to have the user specify the switches that `nmap` is called with - so the user can set the aggressiveness - for example instead of `-sT`, `-p0`. 

* Check `__init__.py` - I'm not fluent with Python yet, so couldn't see any obvious Py issues. 

Now requesting Python code review from Skills Team.

**Comment by el-tocino** [comment]
Can you please update this PR and remove the template updates, submit that as a separate one?

**Comment by Nhoya** [comment]
Done

**Comment by el-tocino** [comment]
I'm kind of iffy about the requirements.sh distro workings. If it doesn't match one, it will fail, and probably not in an obvious way to some users. I suspect the majority of installs are on apt based machines, so perhaps default to that if nothing else matches or, throw an error indicating no matching OS detected? RHEL/Centos/Fedora/OEL and a few others wouldn't get matched.  I suspect there might be some other scripts out there that do package manager detection we could copy and paste for fun and non-profit...

On line 28 might want to use some quoting; in this particular case I think it will still work, unless there's some crazy package not named nmap that installs nmap as unlikely as that is.

**Comment by Nhoya** [comment]
Hi,
using a default `apt` will fail in the same way in RHEL, Centos, Fedora,OEL, on the other side detecting the package manager based on what is installed is not always a nice choose.
Otherwise I can add `exit 1` if the distro is not matched, this way it will fail the installation

For the quoting, the only variable you can quote without breaking the script is `$dep` but since the input is not defined by the user you can't find problems of tricky variable expansion, for me is not a problem to quote it, but IMHO is just useless

**Comment by el-tocino** [comment]
If the skill will fail without the script completing, then a failure would be useful so as to prevent a confused state.  

By defaulting to apt, in the search tree, since it'd be the majority of installs currently (picroft/mk1 would be apt, for instance).

**Pull request merged**
