### PR TITLE
Upgrade mycroft-timer

### PR DESCRIPTION
**Pull request by penrods**
'This upgrades mycroft-timer to include the following new commits:

 - [Merge pull request #24 from MycroftAI/bugfix/path-and-seconds](https://github.com/MycroftAI/mycroft-timer/commit/d3c67d12598a4a45fca20f2798e453c4115b4d96)
 - [Fix two bugs: png paths and "second"](https://github.com/MycroftAI/mycroft-timer/commit/da558fc72f6502ad330b9de1cab364cd7850082f)
 - [Merge pull request #23 from MycroftAI/feature/ui-overhaul](https://github.com/MycroftAI/mycroft-timer/commit/af0139ded1b1b0396172fdf06b9cb7dca0bafcdc)
 - [Autoteests and cleanup](https://github.com/MycroftAI/mycroft-timer/commit/a32c114b25e4355d89e4af0d8686737ef27d63c3)
 - [Merge pull request #22 from MycroftAI/feature/ui-overhaul](https://github.com/MycroftAI/mycroft-timer/commit/6254111d37a022a35690ace1f6783d43a6231163)
 - [Corrected mis-named file reference.](https://github.com/MycroftAI/mycroft-timer/commit/fd508466a1f3a73fe428bf414d10c4cc9b7ac899)
 - [Merge pull request #21 from MycroftAI/feature/ui-overhaul](https://github.com/MycroftAI/mycroft-timer/commit/6010c1271ac301639fc1f0753b7ff184c4f13f30)
 - [Replacing "-.png' with the easier to manipulate "negative.png".](https://github.com/MycroftAI/mycroft-timer/commit/9d621403f48912546ec2abec8b39a24ecc74e3a0)
 - [Major overhaul--Display and multi-timer support](https://github.com/MycroftAI/mycroft-timer/commit/ace98deff59978fd2167b3318044de724baa2048)
 - [Merge pull request #20 from f-e-l-i-x/18.02](https://github.com/MycroftAI/mycroft-timer/commit/18538749b0c1dbdd096f517118106cf8e42bc51c)
 - [spelling error in cancel timer intent](https://github.com/MycroftAI/mycroft-timer/commit/9a0dc52e34a2e81e6e99447c0785592b5461ab97)
 - [unnecessary spaces removed in timer summary](https://github.com/MycroftAI/mycroft-timer/commit/b9aa9ce7cf5af2c4674e9d4addf97c3e005501a8)
 - [error corrected in say.days](https://github.com/MycroftAI/mycroft-timer/commit/91e60054d3d22b277f2a31ee666ab31809385a2d)
 - [added German support](https://github.com/MycroftAI/mycroft-timer/commit/457b2d2ce28968cd2c766064fdce7c912253b4c2)
 - [German support added](https://github.com/MycroftAI/mycroft-timer/commit/6403ede964bd4f049fef5b694e23963f78dc3c92)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Logs which show possible trigger for `TimerSkill` error

```
kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core/scripts/logs$ cat mycroft-skills.log | grep -i Timer | grep -i error
02:41:52.395 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:42:51.146 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:43:32.707 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:44:09.813 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:47:34.107 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:47:54.107 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:49:36.176 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:52:40.456 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
02:59:03.047 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:00:59.870 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:01:20.388 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:02:03.153 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:02:17.362 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:02:33.202 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:02:50.151 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:03:16.736 - mycroft.skills.core:enable_intent:794 - ERROR - Could not enable handle_status_timer, it hasn't been registered.
03:03:46.120 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Timer Skill
03:03:46.121 - SKILLS - DEBUG - {"context": {}, "type": "speak", "data": {"utterance": "An error occurred while processing a request in Timer Skill", "expect_response": false}}
03:05:29.255 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Timer Skill
03:05:29.291 - SKILLS - DEBUG - {"context": {}, "type": "speak", "data": {"utterance": "An error occurred while processing a request in Timer Skill", "expect_response": false}}
03:06:35.350 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Timer Skill
03:06:35.387 - SKILLS - DEBUG - {"context": {}, "type": "speak", "data": {"utterance": "An error occurred while processing a request in Timer Skill", "expect_response": false}}
```

**Comment by KathyReid** [comment]
I think it might be because of this line, where the `handle_status_timer` is _not_ disabled; 
https://github.com/MycroftAI/mycroft-timer/blob/af0139ded1b1b0396172fdf06b9cb7dca0bafcdc/__init__.py#L240

           ` # self.disable_intent("handle_status_timer")  # TODO: needs Adapt`

**Comment by KathyReid** [comment]
* Removed HomeAssistant Skill, re-testing to rule that out as cause of failure

* I've found _another_ issue with the Intent

`start a {{duration}} **second** timer called {{name}}`

This Intent is invariably interpreted as `start a two second timer called {{name}}`

**Comment by KathyReid** [comment]
Also kept getting a bunch of these errors for `11.png` and `10.png`

`kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core/scripts/logs$ cat mycroft-skills.log | grep -i Timer | grep -i error | grep FileNotFoundError | wc -l
52`

**Comment by ajwkc** [comment]
It worked for me! Approved.

**Comment by KathyReid** [comment]
Thx both, merging

**Pull request merged**
