### PR TITLE
Add fallback-recommendations-skill

### PR DESCRIPTION
**Pull request by LinusSkucas**
## Info

This PR adds the new skill, [fallback-recommendations-skill](https://github.com/LinusS1/fallback-recommendations-skill), to the skills repo.

## Description

When Mycroft doesn't know something, he will look it up skills that could help you complete your intent. If he finds a skill, he will download it to your device.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by LinusSkucas** [comment]
Alrighty, @krisgesling, turns out that msk was trying to merge in to the 18.02 branch (?) but everything is alright now!

**Comment by krisgesling** [comment]
Hooray, thanks Linus!

I just want to run it through a final review one more time to be sure. I think this skill is going to be popular!

Previous PR review by Kathy: https://github.com/MycroftAI/mycroft-skills/pull/692

**Comment by krisgesling** [comment]
## Meta

*   Platform: Linux - Debian Buster
*   Device version: 18.8.11
*   Who: [@KrisGesling](https://github.com/KrisGesling) / @gez-mycroft
*   Datestamp: 2019-02-01_09:52:07_ACST
*   Language and dialect of tester: Native English speaker, Australian accent

## Standard checks

*   Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is the first time the Skill has been submitted; not available for voice install.
> Using `msm install`
```
(.venv) kris@bigBench:~/mycroft-core$ msm install https://github.com/LinusS1/fallback-recommendations-skill
INFO - Downloading skill: https://github.com/LinusS1/fallback-recommendations-skill
INFO - Installing requirements.txt for fallback-recommendations-skill
INFO - Successfully installed fallback-recommendations-skill
```

> Checking that STT transcribes correctly;
> `__main__:handle_utterance:62 - INFO - Utterance: ['install recommendations fullback']`  
> `msm.mycroft_skills_manager - INFO - Best match (0.54): mattermost-for-mycroft-skill.domcross by domcross`
> `__main__:handle_utterance:62 - INFO - Utterance: ['install fallback recommendations']`  
> `msm.mycroft_skills_manager - INFO - Best match (0.71): mattermost-for-mycroft-skill.domcross by domcross`

_Successfully installed_

*   Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Dialog is clear and well structured.

*   Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> No intents, fallback skill only.

*   Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

*   Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).

> Wonder if we can work out some clearer wording for non-technical users who might not be familiar with the term 'utterance'. Also would like to remove the 'he' as Mycroft can be other genders.

_ACTION REQUIRED: Please consider changes to README.md in PR from KrisGesling_

*   Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> appropriate requirements usage

*   Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> No settings required.

## Python code check

*   Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL?

> Yes, Apache2 license used

*   Inline documentation - is the code documented in line?

> Adequate inline documentation and docstrings

*   Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Appropriate library usage. Duplicate import of time

*   Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> n/a

*   Error handling - are there any specific checks we make for error handling or graceful degradation?

> handles case of local skill already existing. If it can't provide skill to download, passes to next fallback.

*   Automatic tests - do automatic tests of the **Skill** pass?

> No tests provided.

_ACTION REQUIRED: Please remove testing.md before it is pushed to marketplace_


*   Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4\. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> N/A

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional tests

```(.venv) kris@bigBench:~/mycroft-core$ msm remove dice-skill
INFO - Best match (1.0): dice-skill by Dragoncraft89
INFO - Successfully removed dice-skill
```
*   "roll a dice"

> "Okay, I'm downloading a skill to help you."
> "The Result is 4."  

```(.venv) kris@bigBench:~/mycroft-core$ msm remove spotify
INFO - Best match (0.9): mycroft-spotify by forslund
INFO - Successfully removed mycroft-spotify
```

* "play queen on spotify"

> "Just a second"
> "I'm not sure know how to play queen on spotify"

```(.venv) kris@bigBench:~/mycroft-core$ msm remove speedtest
INFO - Best match (1.0): speedtest by luke5sky
INFO - Successfully removed speedtest
```

* "run speed test"

> "Okay, Let me download a skill to help you with that."
> "Starting speedtest now..."

_Not invoked by the common play framework, but works with all other tested intents._


## Summary

*   Please consider changes to README.md in PR from KrisGesling
*   Please remove testing.md before it is pushed to marketplace
*   I'm going to check in with the team around the common play framework and what it would take to get this also performing fallback for that.

This is an excellent skill, I can see it getting lots of usage, nice work!

**Comment by LinusSkucas** [comment]
Thanks @krisgesling for reviewing the skill!
 - I've merged the readme pr.
 - I minified the testing.md - I'd like to keep something about testing around
 - I'll look into this, maybe the common play skill sends out some Messagebus thing? - This could be in the next release

**Comment by LinusSkucas** [comment]
Okay, @krisgesling I pushed the updates and a new pr has been created: #849 
I'm going to close this one.

**Pull request closed without merging**
