### PR TITLE
WeMo skill

### PR DESCRIPTION
**Pull request by martymulligan**
## Description:

Discover and control WeMo devices

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by forslund** [comment]
run test

**Comment by forslund** [comment]
Run tests

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by btotharye** [comment]
install works but I don't see how this going to find my Wemo devices, how does it make the connection, also it doesn't appear to be working right when asking it list my devices:

```
tail scripts/logs/mycroft-skills.log 
12:06:07.801 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:switch.off.intent
12:06:07.842 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/switch.on.intent", "name": "skill-wemo.martymulligan:switch.on.intent"}, "context": null}
12:06:07.844 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/discover.intent", "name": "skill-wemo.martymulligan:discover.intent"}, "context": null}
12:06:07.845 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/list.intent", "name": "skill-wemo.martymulligan:list.intent"}, "context": null}
12:06:07.846 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/toggle.intent", "name": "skill-wemo.martymulligan:toggle.intent"}, "context": null}
12:06:07.847 - SKILLS - DEBUG - {"type": "mycroft.skills.loaded", "data": {"path": "/opt/mycroft/skills/skill-wemo.martymulligan", "id": "skill-wemo.martymulligan", "name": "WemoSkill", "modified": 1528214759.7386801}, "context": null}
12:06:07.850 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:list.intent
12:06:07.854 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:switch.on.intent
12:06:07.855 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:toggle.intent
12:06:07.858 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:discover.intent
```

```
12:06:47.752 - mycroft.skills.intent_service:send_metrics:241 - DEBUG - Sending metric if opt_in is enabled
12:06:47.755 - SKILLS - DEBUG - {"type": "intent_failure", "data": {"utterance": "list my devices", "lang": "en-us"}, "context": {}}
12:06:47.760 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"handler": "fallback"}, "context": {}}
12:06:47.833 - mycroft.skills.padatious_service:handle_fallback:110 - DEBUG - Padatious fallback attempt: list my devices
12:06:47.836 - WolframAlphaSkill - DEBUG - WolframAlpha fallback attempt: list my devices
12:06:47.836 - WolframAlphaSkill - DEBUG - Non-question, ignoring: list my devices
12:06:47.842 - SKILLS - DEBUG - {"type": "speak", "data": {"utterance": "Please rephrase your request.", "expect_response": false}, "context": {}}
```

**Comment by btotharye** [comment]
It does look like it found my wemo device but the commands mentioned don't seem to be working:

```
12:06:07.784 - skill-wemo_martymulligan - DEBUG - Discovered a We Mo Socket called Christmas lights
12:06:07.797 - mycroft.skills.core:load_skill:129 - INFO - Loaded skill-wemo.martymulligan
12:06:07.798 - SKILLS - DEBUG - {"type": "speak", "data": {"utterance": "Discovered a We Mo Socket called Christmas lights", "expect_response": false}, "context": null}
12:06:07.800 - mycroft.skills.core:load_skill:134 - INFO - First run of skill-wemo.martymulligan
12:06:07.801 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/switch.off.intent", "name": "skill-wemo.martymulligan:switch.off.intent"}, "context": null}
12:06:07.801 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:switch.off.intent
12:06:07.842 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/switch.on.intent", "name": "skill-wemo.martymulligan:switch.on.intent"}, "context": null}
12:06:07.844 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/discover.intent", "name": "skill-wemo.martymulligan:discover.intent"}, "context": null}
12:06:07.845 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/list.intent", "name": "skill-wemo.martymulligan:list.intent"}, "context": null}
12:06:07.846 - SKILLS - DEBUG - {"type": "padatious:register_intent", "data": {"file_name": "/opt/mycroft/skills/skill-wemo.martymulligan/vocab/en-us/toggle.intent", "name": "skill-wemo.martymulligan:toggle.intent"}, "context": null}
12:06:07.847 - SKILLS - DEBUG - {"type": "mycroft.skills.loaded", "data": {"path": "/opt/mycroft/skills/skill-wemo.martymulligan", "id": "skill-wemo.martymulligan", "name": "WemoSkill", "modified": 1528214759.7386801}, "context": null}
12:06:07.850 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:list.intent
12:06:07.854 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:switch.on.intent
12:06:07.855 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:toggle.intent
12:06:07.858 - mycroft.skills.padatious_service:_register_object:92 - DEBUG - Registering Padatious intent: skill-wemo.martymulligan:discover.intent
```

**Comment by btotharye** [comment]
this seems to work if I uninstall the home-assistant skill, not sure how that should work I guess its ok for certain skills that are related to have the same triggers if you would only use 1 of them?  Like I would only use the home assistant skill not the wemo since I can control wemo, hue, and more with the home assistant skill.  Thoughts on this @KathyReid and @forslund ?

**Comment by TREE-Edu** [comment]
Community Skill Validation For WeMo Skill:

Tested on latest dev Git installation of Mycroft, skill installed using msm.

Discover devices: Passed
Turn on/off devices: Passed
Skill responded to expected phrases: Passed
All intents were able to be triggered as expected: Passed

This skill seems to install and work perfectly in a real word test, and for our test played nicely with the HomeAssistant skill.  It has our vote for merging.

**Pull request merged**
