### PR TITLE
Add deckchair-cinema-skill v1

### PR DESCRIPTION
**Pull request by krisgesling**
**Name of your skill**: Deckchair Cinema Skill

## Description:

Find out what is coming up at Deckchair Cinema in Darwin.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works 
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
Damn, one of my suggested calls "what is showing at deckchair tomorrow" 
is getting intercepted by wolfram, will have a look into it.

**Comment by KathyReid** [comment]
Selamat sore, @krisgesling, gimana kabar? 
I'm going to hold off on reviewing this one until you're able to dig into why it's getting picked up by the Wikipedia intent. 
Salam hangat ;-) --Kathy

**Comment by krisgesling** [comment]
Aduh! Just going to close this PR until I've worked out this testing environment.
I have got the contextual follow up questions working though :smiley:

**Comment by KathyReid** [comment]
No worries @krisgesling let us know when you're ready to submit and we'll put it through the [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/).

**Pull request closed without merging**
