### PR TITLE
Add theia-ide

### PR DESCRIPTION
**Pull request by andlo**
## Info

This PR adds the new skill, [theia-ide](https://github.com/andlo/theia-ide-skill), to the skills repo.

## Description

Installs and setup THEIA IDE locally on your Mycroft device.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
### Meta editor
* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.6 stable
* Who: @kathy-mycroft / @kathyreid
* Datestamp: Fri 14 Dec 23:05:42 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

### Standard checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is a new Skill, so we can't use voice install, using `msm` install instead

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/andlo/theia-ide-skill
INFO - Downloading skill: https://github.com/andlo/theia-ide-skill
INFO - Installing requirements.txt for theia-ide-skill
INFO - Successfully installed theia-ide-skill
```
> Installed successfully

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> I ran all the `dialog` files through `mimic` and found several minor issues. I've raise a PR to fix them at; 
https://github.com/andlo/theia-ide-skill/pull/18

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Intents are all good

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> README is lovely

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> requirements text is fine

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> beautifully laid out

### Python code checks

* Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL? 
> No, there is a LICENSE file in the repo, but not in the `__init.py__` file. 
_ACTION REQUIRED: Please add the GPL license text to the `__init.py__` file. 

* Inline documentation - is the code documented in line?
> There is not a lot of inline documentation - please consider adding some in the future. 

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> Dependencies are OK

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> N/A

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> Error checking and handling is well done

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> N/A

_NOTE: We do not enforce PEP8 Checks on Skills_

### Functional checks

> I couldn't do functional checking on Linux, when the Skill tried to load it threw this error; 

```
~~~~TTEMPTING TO LOAD SKILL: theia-ide-skill.andlo with ID theia-ide-skill.andlo
23:42:34.926 - TheiaIde - INFO - Initialize THEIA IDE...
~~~~ls.core:load_skill:159 - ERROR - Failed to load skill: theia-ide-skill.andlo
Traceback (most recent call last):
~~~~home/kathyreid/mycroft-core/mycroft/skills/core.py", line 143, in load_skill
    raise e
~~~~home/kathyreid/mycroft-core/mycroft/skills/core.py", line 139, in load_skill
    skill.initialize()
~~~~pt/mycroft/skills/theia-ide-skill.andlo/__init__.py", line 18, in initialize
    self.install_theia()
~~~~mycroft/skills/theia-ide-skill.andlo/__init__.py", line 70, in install_theia
    "Downloading precompiled package for the " + platform + " platform.")
TypeError: must be str, not NoneType
```

I'm guessing that there is a `platform` or similar string missing which is causing that error. 

This has been functionally validated by the Community at; 
https://community.mycroft.ai/t/theia-ide-skill-new-and-better/5216
so I'm not going to worry about it here

### Summary
@andlo this is a really well-written Skill. It's obvious you've put a lot of time and effort into this Skill - thank you! There are just some minor issues with the Skill before we can merge it into the `mycroft-skills` repo; 

* Please merge PR https://github.com/andlo/theia-ide-skill/pull/18
* Please add the GPL license text to the `__init.py__` file

**Comment by andlo** [comment]
And yes - there is a platform string, and skill is expecting install on picroft or mark_1 only.
Should I add a better errorhandling regarding if someone is trying to install in a not picroft or mark_1 ?

**Comment by andlo** [comment]
Added GPL license in init.py and merged your bugfixes.
A thaught - is the category right in the readme.md file ? or where to place this kind of skill ?

**Comment by KathyReid** [comment]
Run test

(the pesky Alarm Skill is causing the failures)

**Comment by KathyReid** [comment]
Thanks @andlo those new changes look good. 
I am overriding the Skills Tester for this Skill, because it's not your Skill causing the failures. 
I will fix up the `.gitmodules` conflict and then merge.

**Pull request merged**
