### PR TITLE
Added irc-skill

### PR DESCRIPTION
**Pull request by merspieler**
## Description:

Mycroft skill that lets you use IRC via voice commands.

## Checklist:
  - [x] Skill has been tested and works (further improvements WIP)
  - [x] .gitmodules has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by el-tocino** [comment]
README mentions a settings.json, but I don't see that in the repo?

**Comment by merspieler** [comment]
The settings.json file will be written on first use (if you put it into gits hands, an update would overwrite the changes you made to it)

**Comment by forslund** [comment]
That's correct, the settings.json can't be included in the git repo since the skill writes to it.

Since the repo would be dirty from the change, msm wouldn't update the skill ever.

**Comment by merspieler** [comment]
will it get merged?

**Comment by merspieler** [comment]
@el-tocino will it get merged?

**Pull request merged**
