### PR TITLE
Upgrade mycroft-weather

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-weather to include the following new commits:

 - [Remove hardcoded "today"](https://github.com/MycroftAI/skill-weather/commit/30fec0ce439da0dcdee2ef02337da60d30da1da9)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1359))

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
run test

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1359))

**Pull request merged**
