### PR TITLE
Add count

### PR DESCRIPTION
**Pull request by andlo**
## Info

This PR adds the new skill, [count](https://github.com/andlo/count-skill), to the skills repo.

## Description

Simpel skill that count up and down

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
@andlo thank you for submitting this. I just wanted to check if you'd like this Skill to be submitted to the `mycroft-skills` repo - I wasn't sure if you were creating this Skill just to get familiar with the process? 
Best, Kathy

**Comment by andlo** [comment]
Well - for me it dosnt matter, but I notised that mr. mycroft didnt know how to count, and took the posibility to make a skill that so he can. :) so yes it were for me to learn but could be used by others.

So adding it just makes the skill market growing, and that isnt that bad I think ;) I know it isnt a big great skill, but us humans learn to count quiet early so why cant mycroft altså do that :)

**Comment by KathyReid** [comment]
## Skills Acceptance Check

### Meta

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.4
* Who: @kathy-mycroft / @KathyReid 
* Datestamp : Fri  2 Nov 01:18:14 AEDT 2018
* Language and dialect of tester: Native English Speaker, Australian accent

### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is a new Skill, so won't yet be available for voice install. Checking that the STT is able to transcribe the Skill name appropriately => transcribed OK 
```
~~~~:41.541 - __main__:handle_utterance:61 - INFO - Utterance: ['install count']
```
> undertaking manual installation
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/andlo/count-skill
INFO - Downloading skill: https://github.com/andlo/count-skill
INFO - Successfully installed count-skill
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all the `dialog` through `mimic` - they all sounded great :+1: 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> The Intents were generally OK, but I found spelling errors in one of the `vocab` files. I have raised: 
https://github.com/andlo/count-skill/pull/1
to resolve it. 

ACTION REQUIRED: Please pull in this PR

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> README looks lovely :+1: 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> No requirements, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Not used, skipping check 

### Python code checks of the Skill

* Inline documentation - is the code documented in line?
> simple Skill, documentation not required

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> No libraries used, skipping check

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> not required, skipping check

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> error handling is done well :+1:  

* Automatic tests - do automatic tests of the **Skill** pass?
> yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> not required

_NOTE: We do not enforce PEP8 Checks on Skills_

* Check for a valid license in the file
> ACTION REQUIRED - there is no license on the Skill  - please choose a license and ensure that it is included in `__init.py__`. 

### Functional checks

* `Hey Mycroft, count backwards from seventeen`
> correct

* `Hey Mycroft, count to 7`
> correct

* `Hey Mycroft, count from 3 to `2`
> "Say again" <-- this is correct, the from .. to syntax is not yet supported by this Skill. 

=> functionally as expected, you may wish to include support for a `from {{number}} to {{number}}` syntas in a future version. 

## Actions required before merging

* Please pull in the PR that has been raised which fixes the `vocab` files
* Please add a valid LICENSE

**Comment by KathyReid** [comment]
Hey @andlo, just a reminder on this one - the actions required before this one can be merged are; 
* Please pull in the PR that has been raised which fixes the vocab files
* Please add a valid LICENSE

**Comment by andlo** [comment]
Sorry for not getting back on this.
I have pulled in the PR, and just added a license.
Do I then do a msk update or what to do ?

**Comment by luke5sky** [comment]
@andlo another msk upload should do.
Msk upgrade is only for upgrading skills that are already merged into the mycroft skills repo

**Comment by andlo** [comment]
done :)

**Comment by luke5sky** [comment]
It did create a new PR though: #703
I got the same with my telegram skill, i think the Problem is, that github can't get the repo from this PR anymore:
Add count #631
MycroftAI:18.08 unknown repository

But only a hunch, closed the old and referenced the new PR to the old

**Comment by luke5sky** [comment]
It did create a new PR though: #704
I got the same with my telegram skill, i think the Problem is, that github can't get the repo from this PR anymore:
Add count #631
MycroftAI:18.08 unknown repository

But only a hunch, i closed the old and referenced the new PR to the old PR

**Comment by andlo** [comment]
great  -I thaught it were me who did something wrong ;)

**Comment by KathyReid** [comment]
Closing this in favour of #704

**Pull request closed without merging**
