### PR TITLE
Add mycroft-chat

### PR DESCRIPTION
**Pull request by domcross**
## Info

This PR adds the new skill, [mycroft-chat](https://github.com/domcross/mycroft-chat-skill), to the skills repo.

## Description

In your [skill settings](home.mycroft.ai) you must enter your username (as given in your Mycroft Chat account settings) and your personal access token.
In case you do not have a token you can specify your login-id (usually that is your email) and your password.
NOTE: your password will be stored in clear text in your settings.json!)

There is also the option to set the time interval between refresh/check for updates.
When monitoring is active the skill will use that time period for automated checking.
The option "notify on updates" is only applicable when monitoring is active -
when the option is activated Mycroft willl speak out loud the number of unread messages and mentions.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
## Meta

*   Platform: Linux - Debian Buster
*   Device version: 18.8.12
*   Who: [@KrisGesling](https://github.com/KrisGesling) / @gez-mycroft
*   Datestamp: 2019-02-06_14:08:35_ACST
*   Language and dialect of tester: Native English speaker, Australian accent

## 0. Automated tests
Are all automated tests passing?  
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable
- [x]   **Inline Documentation**  
Is the code documented in line? Is there sufficient documentation for the complexity of the Skill?

> Adequate inline documentation

- [x]   **Code Quality**  
Can you understand what the code is doing? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

> No code quality concerns

- [x]   **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> Error handling implemented for lack of settings and passing exceptions to general error message

- [x]   **Python 3**  
Is there any Python 2 code used? Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4\. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> None present

- [x]   **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Appropriate library usage.

- [x]   **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> Appropriate requirements usage

- [x]   **Settings**  
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

> Settings used and well laid out

- [x]   **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

> N/A


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x]   **Icon**   
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com)?

- [x]   **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does?

- [x]   **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

- [x]   **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

- [x]   **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the Marketplace, all others are secondary and used for search results.

- [x]   **Tags**  
Are listed tags appropriate for this Skill?

- [x]   **License**  
*   Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> Apache-2.0 used.


## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is the first time the Skill has been submitted; not available for voice install.
> Using `msm install`
> ```
> (.venv) kris@bigBench:~/mycroft-core$ msm install https://github.com/domcross/mycroft-chat-skill
> INFO - Downloading skill: https://github.com/domcross/mycroft-chat-skill
> INFO - Installing requirements.txt for mycroft-chat-skill
> INFO - Successfully installed mycroft-chat-skill
> ```
>
> Checking that STT transcribes correctly;  
> ```
> __main__:handle_utterance:62 - INFO - Utterance: ['install minecraft chat']
> msm.mycroft_skills_manager - INFO - Best match (0.35): mycroft-chat-skill.domcross by domcross
> __main__:handle_utterance:62 - INFO - Utterance: ['install microsoft chat']
> msm.mycroft_skills_manager - INFO - Best match (0.35): mycroft-chat-skill.domcross by domcross
> ```

> Successfully installed

- [x]   **Settings**  
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> Appropriate use of settings, well laid out and flexible for other Mattermost installs.

- [x]   **Dialog**  

  Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).   

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Dialog is clear and well structured.

- [x]   **Intents**  
Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> No intents, fallback Skill only.

- [x]   **Regex**  
*   Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [ ]   **"Are there unread messages on Mycroft Chat"**

> "There are 393 unread messages on Mycroft Chat You have been mentioned 1 times on Mycroft Chat"  
> A full stop was removed from `no.unread.messages.dialog` causing it to run together if there are also mentions.

_Action Required: Add full stop to end of `no.unread.messages.dialog`_


- [x]   **"Name Mycroft Chat channels with unread messages"**

> Each channel with unread messages or mentions read in turn as expected.

- [x]   **"Read all unread Mycroft Chat messages"**

> Begins reading all unread messages as expected.

- [x]   **"Read messages for the channel {name}"**

> Some trouble invoking this intent, then it randomly started working.
> Begins reading all unread messages as expected.

- [x]   **"Begin monitoring of Mycroft Chat"**

> "Mycroft Chat monitoring is activated"

- [x]   **"Stop monitoring of Mycroft Chat"**

> "Mycroft Chat monitoring is deactivated"



## Summary
*   Add full stop to end of `no.unread.messages.dialog`

Thanks Dom, this looks great! 

It took a couple of goes to get the read channel intent to work but then was fine. Overall, it feels much smoother to use than my last run through. Sorry for the tiny request above, it just feels important as users who are monitoring chat may end up hearing it a bit.

You probably also noticed that the review structure has changed a little. I'm trying a new format that can be split up between community members. I'd be very interested if you had any opinions on how it reads from a skill developer perspective. We want to make these reviews as helpful and easy to read as possible.

**Comment by domcross** [comment]
Hello @krisgesling ,
Thanks again for reviewing this. I have pushed an update with the requested change to the `no.unread.messages.dialog`

Regarding the review : I like the new structure better.

**Comment by krisgesling** [comment]
Hi @domcross, it looks like the new push didn't have the latest commit. Is there a chance you made the edits on a different machine and didn't pull them across before running msk?

I'll look into the test failing too, given it's the exact same code, I assume it's unrelated to your skill.

**Comment by domcross** [comment]
@krisgesling I have pushed another update and now the tests were successfully passed.

by the way: what is the difference between `mycroft-msk update`and `mycroft-msk upgrade`? (I have used the latter one)

**Comment by forslund** [comment]
Msk upgrade is used if a skill already exists in the repo.

Both upload and upgrade are legacy commands for backwards compatibility.

`msk submit` is recommended, it works in all cases.

Edit: I misread, I actually thought update and upgrade did the same thing...(I still recommend using msk submit :) )

**Pull request merged**
