### PR TITLE
lifx-mycroft: Skill allowing interaction with LIFX brand smart-bulbs.

### PR DESCRIPTION
**Pull request by samclane**
## Description:

Allows users to interact with the [LIFX-brand smart-bulbs](https://www.lifx.com/) on their home network through Mycroft. Can change power, brightness, color, and color-temperature of individual Lights and predefined Groups.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by samclane** [comment]
Alright, I'm at a loss now. Jenkins keeps saying:

```
    def test_runner(skill, example, emitter, loader):
>       s = [s for s in loader.skills if s and s.root_dir == skill][0]
E       IndexError: list index out of range
```

Which is some of the code in my `test/__init__.py`. This was actually written by one of the Mycroft team members to help me Mock some services for testing. You can see this exact code working in my "homeseer-mycroft" skill in the official repo. 

I know you guys can see some stuff on the backend. Are there any exceptions being thrown that I'm not seeing?

**Comment by samclane** [comment]
Tried submitting what was essentially the same code to force a rebuild, as I had a similar problem with Skill Tests failing before. However this did not work.

**Comment by forslund** [comment]
@samclane That would suggest the skill fails to load. (It tries to access the first element in the list of loaded skill that matches the name of the skill).

**Comment by samclane** [comment]
Looking over the Jenkins logs, that build fail seems to be in the pre-testing init process. Could you try and kick-off a retest?

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Hmm, seems to be some sort of connection issue occuring. This might fail as well :/

https://status.github.com/messages

I'll stay on top of this during the evening and see what's going on

**Comment by samclane** [comment]
Run test

**Comment by forslund** [comment]
There seem to be some intent collisions going on. (temperature seems to be picked up by the weather skill)

Also, do you think you could open a PR against the 18.08 branch instead?

**Comment by forslund** [comment]
The collision in `006.handle_toggle_context.intent.json` can be worked around by changing the utterance to "switch it off"

```json
{
  "utterance": "switch it off",
  "intent_type": "handle_toggle_intent",
  "intent": {
    "Turn": "switch",
    "Off": "off",
    "Target": "Bedroom"
  },
  "expected_dialog": "Switch",
  "set_context": {"_TestRunner": "data", "test": "", "Target": "Bedroom"}
}
```

The other Timer conflict looks weird and I'm not really sure about that one but I'll keep checking. Failing weather intent is on us (The test doesn't a forecast without rain, PR's pending for that issue)

**Comment by samclane** [comment]
I moved this over to 18.08 and [opened a new PR ](https://github.com/MycroftAI/mycroft-skills/pull/534). I'll close this one.

**Pull request closed without merging**
