### PR TITLE
Add Montgomery-radiocohost-trollbot-skill

### PR DESCRIPTION
**Pull request by Tebrion74**
## Info

This PR adds the new skill, [Montgomery-radiocohost-trollbot-skill](https://github.com/Tebrion74/Montgomery-radiocohost-trollbot-skill), to the skills repo.

## Description

This will be a collection of responses and python based macros to control aspects of obs streaming.   i hope.   i'm looking into how to do this.  if anyone knows..  frickin hit me up!  robert j. morris

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1347))

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

Based on your description, I'm assuming this is a work in progress? If so I'll tag it as such, and when it's ready for review let us know.

If you have any updates, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

**Comment by Tebrion74** [comment]
thank you sir, and yes it is an exploration and definite work in progress.
 I'm no stranger to coding, just rusty as a barnicled anchor. but I
digress.
THank you for the assist, and keep those assists coming as I meander and
wander about in this... I'm not completely sure what I'm doing but I have
an idea..   just don't want to break any rules of etiquette.   ;)

I want to get the very basic roughed out responses ready for an upcoming
feature podcast but I need to slowly introduce control for things like OBS,
and I only have a value idea where to start with that (sending key macros
out, which sounds basic enough if I know the libraries etc.   which I don't
at the moment.. lol.

THanks mate!
Robert J. Morris

**Comment by Tebrion74** [comment]
I'm only sending this to share..   It's just a wee video I made to promote
the upcoming podcast that is yet to be announced. It features Montgomery at
his worst so far.    :)

https://youtu.be/zE_HmUnwNNk

**Comment by Tebrion74** [comment]
How do I open up Montgomery's precise data to the community so that they
can add to his sampleset?

P.s. I had Montgomery and Christopher in a back and forth on two different
machines triggering each other.. It was epic   I wish I had recorded it. It
was accidental.

I was trying to get  Precise installed on my ubuntu  studio 20.04 but it
kept failing. so did mycroft-core, so I used the snap method, and I have no
idea how to edit anything because I'm locked out of the virtual drive.

Snap sucks AFAIK.

so I ended up with Christopher triggering Montgomery and vice versa, and
the timing was just right..  went on for about 5 exchanges before they both
shut up.     I was in tears.
I wanted to take advantage of my rtx 2060 and I cannot get precise or core
working properly under 20.04
any ideas?
RJM

**Comment by krisgesling** [comment]
Hey, you can add Montgomery data to this repo if you're happy to release it to the public domain:
https://github.com/MycroftAI/precise-community-data

Lol, maybe we should have a competition to see who can get the longest unintentional conversation between devices.

The Precise Snap was mostly a test run to understand the Snap packaging process. We still need to test all the development endpoints so some things may not operate as expected.

A key consideration is precise versioning. Currently mycroft-core uses v.0.2.0. So you need to either train with that version or update core to use v0.3.x. The two aren't compatible with each other.

If you've followed all the instructions on the Precise repo wiki about installation and training and still can't get it going then please open an issue on that repo that details what you've tried, where it's getting stuck, and be sure to include any errors that it's throwing.

**Comment by krisgesling** [comment]
I just realised you said core wasn't working either. That is strange. Do you get errors during installation? What's not working about it?

**Comment by Tebrion74** [comment]
Naw it's ok, I was trying to say I couldn't get it working on my
UBuntu/Amd/Nvidia rig.  But Montgomery is living on my RPI4, and that is
working mostly flawlessly.

pip3 failed trying to install the deps for tensorflow on my main Ubuntu rig
I'm running Ubuntu-studio 20.4 with the low-latency kernel, so sometimes
that has issues with the repos.   I'm not sure what it is, but until I
figure that out, I can run precise commands and core on the pi..

Core on my UBuntu only works with snap..   and I'd be damned if I can
figure out how to get the snap install to work with the system for edits..
I'm probably doing it wrong.

regards mate!!
RJM

**Comment by Tebrion74** [comment]
I'd be more than happy and excited to do that.   I'll do some reading and I
will absolutely add Monty to the Git.

Stand by for that.   thanks man!
RJM

**Comment by krisgesling** [comment]
The Snap uses a read-only file system so you can't edit core but you can read all it's source code.
I've added a page to the docs about the special locations Snap uses for things like Skills:
https://mycroft-ai.gitbook.io/docs/using-mycroft-ai/get-mycroft/snap

**Comment by Tebrion74** [comment]
well, I'm not too concerned about the snap thing, because I really try to
avoid using snap anyway.. but I am keeping my ear to the ground as I am
using the new(ish) ubuntu 20.04 LTS kernel and I reckon lots of updates and
meta packages will come out in the next while to back support old libs.
I can use the pi just fine for the moment..   I also have 4 years worth of
weekly podcasts to use as a model for Montgomery's voice.  It's the voice
of my dear friend Sean Maguire A radio host from Ireland.   Could ya by
chance give a little more direct route to how to start working on the
voice?  I did a little reading but made it a lower priority.   THanks man!

RJM

**Comment by Tebrion74** [comment]
Hello mate!!    I just launched my new tech channel on
youtube/vimeo/patreon..     Check it out!  Mycroft/Montgomery got some
special mention and I will be featuring it on my channel.    Here's the
link for the first introductory episode...
https://youtu.be/20tbo_GBsf4

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
