### PR TITLE
Upgrade auto-volume

### LINKED ISSUE #19: Genomics Skill
Genomics Skill for Mycroft.
Still requires modifying config files to direct pathing per each laboratory, but works for us!

Github link: https://github.com/TicklishGiraffe/mycroft_genomics

### PR DESCRIPTION
**Pull request by andlo**
This upgrades auto-volume to include the following new commits:

 - [change to use settingsmeta.yaml](https://github.com/andlo/auto-volume-skill/commit/d2519a92b01f9947a59d60ff012ab32ad5ec18d4)
 - [Merge pull request #22 from flozi00/master](https://github.com/andlo/auto-volume-skill/commit/8a26c312e34ec471d72361e9adc8c4fd4a5f75cd)
 - [Merge pull request #2 from flozi00/patch-1](https://github.com/andlo/auto-volume-skill/commit/0c2d1343aa421584b8e576861bd10c54d429f251)
 - [Merge pull request #1 from flozi00/patch-2](https://github.com/andlo/auto-volume-skill/commit/b5ce231bf6457d4d88d4e53dc2b49bfa4720fec1)
 - [Update reset.intent](https://github.com/andlo/auto-volume-skill/commit/add0c2cb562f495e7f0b6fbcf494a7ff5b072dd7)
 - [Update deactivate.intent](https://github.com/andlo/auto-volume-skill/commit/dba9ae4a885faab458ae19d60dd700aa955920e2)
 - [Update deactivate.intent](https://github.com/andlo/auto-volume-skill/commit/9b69aa0f42dc42120eb9beccf3a3c95006c77667)
 - [Update activate.intent](https://github.com/andlo/auto-volume-skill/commit/dc2b59b9b7cfbb6b2b3f91b59c04c6a2ef76df93)
 - [Merge pull request #20 from andlo/Fix#19](https://github.com/andlo/auto-volume-skill/commit/2955656b6af2957d93fbbfd4aa8b801d91be1b83)
 - [Fix #19](https://github.com/andlo/auto-volume-skill/commit/f3d1474e3e1cee4bfb76c672cda37eb72efac564)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by andlo** [comment]
It seems that there were a change some time back (maybe 19.8) that added mute to the mic_level file in the ipc directory. And the skill read the mic thresh from that file, but after changes it didnt read it right. Now it does :)

**Comment by andlo** [comment]
:( Cant figure out why Skill tester is failing....

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Thanks Andlo, this looks good. Merging :)

**Pull request merged**
