### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by TechSnazzy**
Added a link to Mycroft ecosystem to make it easier to read about it.

**Name of your skill**: _Name goes here_

## Description:

**Short description of your Skill and what it does**

## Checklist:
  - [ ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ ] Skill has been tested and works 
  - [ ] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [ ] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by KathyReid** [comment]
This link doesn't really "fit" here @TechSnazzy I'm afraid. 
Reviewing your GitHub profile, it seems that you're trying to make lots of very minor commits to a large number of repos - is there a strategy or objective with that approach?

**Comment by TechSnazzy** [comment]
Yes. The strategy is to win a Hacktoberfest T-shirt. Hey, at least I’m honest about it. 😜

**Comment by KathyReid** [comment]
Well, I'm sorry but I'm not accepting this as a Hacktoberfest PR I'm afraid. It's really overly simple. 

You can see our Hacktoberfest-tagged Issues here; 
https://github.com/search?l=&q=org%3AMycroftAI+label%3Ahacktoberfest+state%3Aopen&type=Issues

https://mycroft.ai/blog/hacktoberfest-2018/

**Comment by ggarnier** [comment]
@KathyReid closed PRs still count to Hacktoberfest. From https://hacktoberfest.digitalocean.com/details: `PRs reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt`

**Comment by KathyReid** [comment]
Thanks @ggarnier - so this needs to be marked as `invalid`?

**Comment by ggarnier** [comment]
Yes, you have to add an `invalid` label.

**Comment by TechSnazzy** [comment]
Yes. And make sure to report this to the github police and have this techsnazzy character thrown in GitHub prison. How dare he add a link to the text and try to claim that as a PR! What a horrible person he must be. Mark that as invalid immediately.

**Comment by KathyReid** [comment]
I think you're being very immature about this in general @TechSnazzy. You're clearly opening dozens of very minor PRs on as many projects as possible in the hope they get accepted, and you get your T-shirt. That's not the intent of Hacktoberfest at all.

**Comment by TechSnazzy** [comment]
Ok, fine. I’m just trying to point out how silly this is. If you don’t like what I did them simply dismiss it. But to make a federal case out of it seems silly to me. None of this is a big deal. Just a silly contest with silly rules. Not that big of a deal.

**Comment by penrods** [comment]
Hey @TechSnazzy, this isn't a federal case or anything.  And I love t-shirts too.  However I don't see how this is being silly at all.  Hacktoberfest isn't a *contest*, it is a campaign to raise awareness of the software being created by people around the world that is literally changing your life and laying the foundation of our collective future.  I'd encourage you to pay attention to this section of [Hacktoberfest](https://hacktoberfest.digitalocean.com):

> # Values
> Hacktoberfest guiding values:
> * Everyone is welcome
> * Quantity is fun, quality is key
> * Short term actions, long term impact

These aren't simple Rules, these are the core Values of open source software.  Open Source is "free", but ultimately everything comes at some cost.  Including t-shirts.  DigitalOcean is dropping at least $20 on sending out each t-shirt, so I want their money to be well-spent.  If you want to wear the t-shirt proudly, do something you are proud of and that makes the world better!

**Pull request closed without merging**
