### PR TITLE
Upgrade dice-skill

### PR DESCRIPTION
**Pull request by yvie-k**
This upgrades dice-skill to include the following new commits:

* Convert intent_handler to intent_file_handler
* Allow more advanced dice requests
* Add Range.intent to german translation

### CODE REVIEW

**Comment by yvie-k** [comment]
Because msk wasn't working properly for me, I've done it manually this time.

**Comment by krisgesling** [comment]
Thanks for keeping at it. I'm trying to track down the source of the MSK issue but can't replicate the behaviour. We've had a few others have the same trouble however it's the same version of MSK as those being successfully submitted against 19.02 which leads me to believe that it's something else in your development environment.

Wondering if you can give me some insight into the device you're using for development, where you store your skills when developing and testing, and how you create the PR when using MSK?

**Comment by yvie-k** [comment]
@krisgesling 
I'm developing on Debian 9 with the skill repo stored in /opt/mycroft/skills/dice-skill

I upgrade like this.
```sh
cd /opt/mycroft/skills/dice-skill
msk upgrade .
```

How does msk determine the branch to merge to? Maybe it uses some old config value in my environment.
Can I reset the config of msk?

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time:15 Apr 2019 6:50pm CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [x] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> yes

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> not constrained to a particular device

- [x] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes Entertainment

- [x] **Tags**
Are listed tags appropriate for this Skill?

> yes

- [x] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> GNU General Public License v3.0

**Comment by krisgesling** [comment]
Hey Florian,

I'm getting the same error as the skill test runner. For an utterance of "3 d20 +5", `handle_roll_dice_intent()` is extracting the type as: `d20 +5`

Seems to work better if I change `Dice.intent` to something like:
`roll ({count}|) d {type} (+|plus|) ({modifier}|)`

It was also causing errors trying to convert numbers as text eg twenty to integers, so I wonder if it's worth using `extract_number()` when assigning `dice_type` and `modificator` as you have with `dice_count`. You should then be able to remove the if else statement as extract_number returns False if no number is found, so `int(modificator)` should return 0 in that case.

**Comment by yvie-k** [comment]
I'm sorry that it took this long. I was busy and forgot to do it.

The tests did pass on my local machine, but I think I've fixed my environment now.

**Comment by krisgesling** [comment]
Works great for me now!

Thanks Florian!!

:tada: :tada: :tada: :tada: :tada: :tada: :tada:

**Pull request merged**
