### PR TITLE
Add Sonos-control

### PR DESCRIPTION
**Pull request by fortwally**
## Info

This PR adds the new skill, [Sonos-control](https://github.com/fortwally/sonos-control-skill), to the skills repo.

## Description

Allow control of Sonos speakers from Mycroft.
Assumes all speakers are in one group.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Hi, cool stuff.

I think the main issue the skill tester is reporting is that the skill can't be loaded.

Looks like it can't find any speakers during startup and throws an exception:

```
 =============== Captured Logs from loading ===============
ATTEMPTING TO LOAD SKILL: sonos-control.fortwally with ID test-sonos-control.fortwally
Failed to load skill: sonos-control.fortwally
Traceback (most recent call last):
  File "/app/mycroft-core/mycroft/skills/core.py", line 143, in load_skill
    raise e
  File "/app/mycroft-core/mycroft/skills/core.py", line 139, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/sonos-control.fortwally/__init__.py", line 53, in initialize
    coord = self.findspeakers()
  File "/opt/mycroft/skills/sonos-control.fortwally/__init__.py", line 148, in findspeakers
    if len(speakers) == 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by fortwally** [comment]
After making other changes I forgot to handle that case.  Will fix the problem and push again.

**Comment by fortwally** [comment]
After I have pushed the fix to my git repository, what do I do to re-test?

**Comment by el-tocino** [comment]
run test

**Comment by fortwally** [comment]
Sorry but I need some context on where to 'run test'

**Comment by forslund** [comment]
You need to rerun msk submit to update the PR if you haven't done that

**Comment by fortwally** [comment]
Thanks, That is what I needed to know

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
I'm fairly sure that the Auto Tester is failing here because it can't find any Sonos Speakers. 
I don't have any Sonos Speakers unfortunately, so I can't test this Skill; from what I can tell I don't think it's been through any Community testing yet. I've asked in Chat with our Skill Testing Team whether anyone has Sonos and can test this.

**Comment by gras64** [comment]
I just tested the skill connection to the sonos speaker OK. function louder, quieter, play, break successfully tested. can I use it with several speakers? NIce skill thank you

**Comment by fortwally** [comment]
Yes it works with several speakers. I have 4 speakers, but I have them in a group so they all play the same music at the same time.

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 Apr 2019 10:55am CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [ ] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> the ABOUT description is good.  The short description needs to be edited - there appear to be extra words.  I think the short description is meant to be "Control Sonos speakers from Mycroft".

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> not constrained to a particular device.   Tags and title indicate this is for sonos speakers

- [x] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes

- [x] **Tags**
Are listed tags appropriate for this Skill?

> yes

- [ ] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?


> (( No License included.  For instructions to add a license to a repo see https://help.github.com/en/articles/adding-a-license-to-a-repository))

**Comment by fortwally** [comment]
Added the LICENSE file, modified the __init__.py file to have the same license text.
Fixed the short description in the README.md file

**Comment by gador** [comment]
hi @fortwally and @GPVM,

what is the status on the sonos integration? I'd really would like to see sonos included in the skill set for mycroft.
Anyway I could help?

**Pull request closed without merging**
