### PR TITLE
Upgrade mycroft-alarm

### PR DESCRIPTION
**Pull request by penrods**
'This upgrades mycroft-alarm to include the following new commits:

 - [Better "on weekends" handling (#30)](https://github.com/MycroftAI/skill-alarm/commit/c26db777966ee2d97836e348f4ffe7819ac9e35f)
 - [Correct intent tests for Padatious change (#29)](https://github.com/MycroftAI/skill-alarm/commit/4205bde576094c84ab1382d17bf7d0ecf048316f)
 - [React to review feedback (#28)](https://github.com/MycroftAI/skill-alarm/commit/61a633f5f77f4595ad129d2819e7e8a50c8ff075)
 - [Fix settingsmeta, add missing LICENSE (#27)](https://github.com/MycroftAI/skill-alarm/commit/e102ffb6e3361174953d82b50b81c28b9d0329ac)
 - [Major overhaul of Alarm Skill (#26)](https://github.com/MycroftAI/skill-alarm/commit/2913d9749e39e57840d2caa0c35620192917f413)
 - [Adding alarm sounds for rework](https://github.com/MycroftAI/skill-alarm/commit/949025a7934380353d584a5d4f9453bf84e5b387)
 - [Merge pull request #25 from MycroftAI/bugfix/speak-variable](https://github.com/MycroftAI/skill-alarm/commit/3b9eb24ae5f95b41a3f6cabb92f4432b8f5abdb2)
 - [Fix local variable referenced before assignment](https://github.com/MycroftAI/skill-alarm/commit/337f2d54770955fdbed6d2eadb6a39b5741065ee)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
This is a DEFAULT Skill, bumping to top of review list

**Comment by KathyReid** [comment]
## `mycroft-alarm`

* Platform: Mark 1
* Device version: 18.2.12b, `stable` from `master`
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Friday 10 August  22:21:40 AEST 2018
* Language and dialect of tester: Native English speaker, Australian accent

### Validate Skill is updated before performing testing

```
pi@mark_1:~/skills/skill-alarm $ git log
commit e102ffb6e3361174953d82b50b81c28b9d0329ac
Author: Steve Penrod <github@gpll.org>
Date:   Thu Aug 9 15:06:23 2018 -0500

    Fix settingsmeta, add missing LICENSE (#27)
    
    Final changes to the settings interface didn't make it in to the last commit,
    goofing up the previews.
    
    Also added the standard LICENSE file for Apache 2.0
```
```
pi@mark_1:~/skills/skill-alarm $ git status
On branch 18.02
Your branch is up-to-date with 'origin/18.02'.
nothing to commit, working directory clean
```

### Test the four different alarm sounds

This test ensures the audio file is correctly downloaded and plays back correctly. 

I had to reboot my Mark 1 to find the Skill Settings in home.mycroft.ai but they loaded OK after that. 

* `Christopher, set an alarm for 30 seconds`
> "Alright, got it" => alarm played back using the default `Constant Beep` sound. 

Changed sound in Skill Settings to `Beep-Beep-Beep-Beep`, spoke `update config` to update settings. 

* `Christopher, set an alarm for 20 seconds`
> "Alarm set" => `Beep-beep-beep-beep` sound correctly played after 20 seconds

Changed sound in Skill Settings to `Escalating beeps`, spoke `update config` to update settings. 

* `Christopher, set an alarm for 20 seconds called Bob`
> "Alright, got it" => sound correctly played after 20 seconds

Changed sound in Skill Settings to `Bell`, spoke `update config` to update settings. 

* `Christopher, set an alarm for 30 seconds called Dave`
> "Alarm set" => bell sounded correctly

** Unexpected finding**: for each of the sounds, the alarm was "escalating" - ie the sound got louder the longer the alarm sounded - even though this was _not_ checked in my Skill Settings. 

**Unexpected finding**: every time the alarm sounded, I found it difficult to cancel the sounding of the alarm via voice - ie `cancel`, `stop`, `cancel alarm` had no effect. I'm not sure if this is intended behaviour or not, but it was a little frustrating. One of the alarms got so loud the sound distorted, and I _contemplated_ throwing the Mark 1 across the room. Deep breaths, Katherine, deep breaths ... I figured out that I had to press the button on the Mark 1 to stop the alarm, but that wasn't clear from the README.md - and if we're "voice first" I'm not sure this behaviour aligns with our _voice user interface_ principles - but I also think this would be difficult to implement in a Skill. 

**Question** - Is anything _supposed_ to display on the faceplate for this Skill - there was nothing displayed when I tested it. This might be the expected condition, but wanted to check. Interestingly when I was doing _later_ tests, I got an alarm icon. Is the alarm icon _supposed_ to display for each variant? 

### Test various configurations of the alarms

* `Christopher set an alarm for eleven thirteen`
> "For what time?" => `eleven thirteen P M`
> "I'm not sure I understood you"

* `Christopher set an alarm for eleven thirteen P M`
> "Alarm set" => alarm triggered successfully

* `Christopher, set an alarm`
> "For what time?" => `nine thirty A M`
> Time was not understood, no response. Might just be my croaky voice. Tried again, same issue. 

---
At this point, Mark 1 became unresponsive to the Wake Word so I `ssh`'d in to see what might be happening - ie thirty utterances of `Christopher` not triggering the Wake Word. Could not see anything amiss. Tried again, it triggered (!).
---

* `Christopher, set an alarm for weekdays at two in the afternoon`
> No response
Tried again, could not trigger Wake Word

---
At this point, Mark 1 became unresponsive to the Wake Word again. Thirty utterances, nothing triggered. Gah! He hates Australians! ;-) 
---

Triggered at about 35 utterances. 
* Christopher, set an alarm for two p m `
> "Alarm set"

* `Christopher set an alarm for weekdays at two in the afternoon`
> "For what time" => swear words that won't be repeated here. Not complimentary to Mycroft. 
repeated test
* `Christopher set an alarm for weekdays at two in the afternoon`
> No response
repeated test
* `Christopher set an alarm for weekdays at two in the afternoon`
> "For what time?" => More swearing on Kathy's part
 
_abandoned testing this Intent for repeating alarms, could not get it to work as expected_

**Set Wake Word back to Hey Mycroft because Christopher isn't triggering well for me. This didn't work, I couldn't trigger on Hey Mycroft either**. Rebooted Mark 1. Drank some alcohol (jk, jk). After reboot, tried 60 times to trigger Christopher / Hey Mycroft, did not trigger a single time. 

#### Test abandoned, I'm going to re-test this using the `mycroft-cli-client`, my voice is clearly too croaky for it to pick up the STT/Wake Word correctly.

**Comment by KathyReid** [comment]
### Retest after a reboot and switching Wake Word to `Hey Mycroft`

* `Hey Mycroft, set an alarm for weekdays for 2 in the afternoon`
> "Alarm set"

* `Hey Mycroft, set an alarm for ten A M August eleventh`
> "Alright, got it"

* `Hey Mycroft, set an alarm for two P M on Mondays`
> No response, repeated phrase. Picked it up second time around => "Alarm set"

* `Hey Mycroft, set an alarm for midnight every Friday`
> "For what time" => `midnight`
> "For when" => `every Friday` => "Alarm set"

---
At this point, Mark 1 became unresponsive to the Wake Word again
Possibly hanging due to Precise taking 50% of CPU?
screenshot from 2018-08-11 03-03-28
Rebooted. Still not responding to Wake Word. Going to manually trigger using button.
STT wouldn't pick anything up, not sure what is going on. Trying hard reboot.
Still can't pick up Wake Word or STT, it's probably my croaky voice.
---

Dropping to `mycroft-cli-client`

* `Are any alarms set`
> You have 6 alarms: today at nine forty a m., today at tend a.m., today at two p.m. and two p.m. on weekdays 
=> correct

* `cancel all alarms`
> "Do you wish to cancel four alarms"
> `yes`
> "All alarms have been removed

**Comment by MatthewScholefield** [comment]
While I'm not sure of the cause for the wake word not picking up, 50% CPU is actually normal. In the case of the pi, this means 50% of one CPU which is 12.5 % overall.

**Comment by penrods** [comment]
I updated the skill to deal with the two biggest review items:
* Snooze could leave system volume set low
* Alarm confirmations

Future iteration will add:
* Faceplate feedback (flashing time) for Mark 1
* A message protocol to show an indicator when the alarm is set and the clock is displayed
* Potentially other minor changes

**Comment by penrods** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
### Quick check

#### Prove I am on the correct version of the Skill

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git status
On branch 18.02
Your branch is up to date with 'origin/18.02'.

nothing to commit, working tree clean
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git log
commit 4205bde576094c84ab1382d17bf7d0ecf048316f (HEAD -> 18.02, origin/HEAD, origin/18.02)
Author: Steve Penrod <github@gpll.org>
Date:   Tue Aug 14 15:57:24 2018 -0500

    Correct intent tests for Padatious change (#29)
    
    This catches several test cases where a Padatious intent now matches instead of
    Adapt, or where the response includes a time now.
    
    Other minor changes:
    * Adjust the P character to match the standard Mark 1 font
    * Add and tweak several Padatious intent phrases
```

### Test functionality

* `Set an alarm for eight forty seven a m`
> "Alarm set for today at 8.47 am"
Alarm successfully sounded

* `Set an alarm`
> "What time shall I set it for"
> `eight forty eight a m`
> "Alright. I've set an alarm for 8 48 a m"
Alarm successfully sounded, I was using the `cli` client, and couldn't cancel the alarm without cancelling out of the CLI. 

* `Set an alarm for eight fifty five on august 15th`
> "I've created an alarm for today at eight fifty five p.m."

* `Set an alarm for two p.m. on Mondays`
> "Alarm set for monday, the twentieth at two p.m."

* `Set an alarm for three p.m. every Tuesday`
> "I've created an alarm for Tuesday, the twenty-first at three p.m."

* `Set an alarm for eleven a.m. on the weekends`
> "Alarm set for today at eleven a.m."
_retesting, possible bug, today is not the weekend_

* `Set an alarm for two p.m. on the weekends`
> "Alarm set for today at two p.m."
_retesting, looks like confirmed bug_

* `Set an alarm for four p.m. on the weekends`
> "I've created an alarm for today at four p.m."
_bug occurred three times out of three, bug identified_

**BUG**: Asking the Alarm Skill to create an alarm on the weekends sets it for today

### Testing the display in the last commit on a Mark 1

#### Prove on correct commit

```
pi@mark_1:~/skills/mycroft-alarm.mycroftai $ git log
commit 4205bde576094c84ab1382d17bf7d0ecf048316f
Author: Steve Penrod <github@gpll.org>
Date:   Tue Aug 14 15:57:24 2018 -0500

    Correct intent tests for Padatious change (#29)
    
    This catches several test cases where a Padatious intent now matches instead of
    Adapt, or where the response includes a time now.
    
    Other minor changes:
    * Adjust the P character to match the standard Mark 1 font
    * Add and tweak several Padatious intent phrases
```
#### Test for display of `p` character

* `Create an alarm at 2 p.m.`
> "Alarm set for today at 2 p.m`
_time shows of alarm then alarm clock graphic shown then moves off right of display_

* `Create an alarm at two forty p.m.`
> "Alarm set for today at 2.40 p.m`
_time shows of alarm then alarm clock graphic shown then moves off right of display_

* `Create an alarm at eleven a.m.`
> "Alarm set for today at eleven a.m."
_time shows of alarm then alarm clock graphic shown then moves off right of display_

_I am not seeing the 'p.m' to test the display because I use a 24hour clock, switching to 12 hour_

* Set to 12-hour time in home.mycroft.ai
* `Update config`
> "Your device configuration has been udpated"

* `Cancel all alarms`
> "Confirming, do you wish to cancel 3 alarms"
> `Yes`
> "All alarms have been removed"

* `Set an alarm for 2 p. m. `
> "I've created an alarm for 2 p. m."
_display of `P` character looks good, passing test_

Holding Skill pending investigation of the weekend/today bug.

**Comment by KathyReid** [comment]
### Re test of weekend intent

Tested OK in `cli`, screenshot att'd
screenshot from 2018-08-15 11-37-41
LGTM, merging w00t!

**Pull request merged**
