### PR TITLE
submit openhab skill to 18.08

### PR DESCRIPTION
**Pull request by mortommy**
**Name of your skill**: openhab

## Description:

This skill adds openHAB support to Mycroft.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works 
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] .gitmodules has been updated with the following:
  
```
+[submodule "openhab"]
+	path = openha.skill
+	url = https://github.com/openhab/openhab-mycroft.git
+ REAMDE.md
```

### CODE REVIEW

**Comment by mortommy** [comment]
Where can I find any hint about the test failure?
Thank you.

**Comment by el-tocino** [comment]
There's a "details" link to the right of the tests, click that to see the log of what happened.

**Comment by KathyReid** [comment]
Yes - click "Details" to the right of where "Skill tester" shows "Skill tests failed"
It will take you to: 
https://jenkins.mycroft.team/job/18.08-skill-tester/280/
and you can click on "Console output" to see
https://jenkins.mycroft.team/job/18.08-skill-tester/280/console

In this case I think it's the `Alarm Skill` which is causing the failure. I'm going to add a comment with `Run test` in it to execute the tests again.

**Comment by KathyReid** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by mortommy** [comment]
Great!
Thank you

**Comment by KathyReid** [comment]
This is just a README update; our policy is that if it's a README update that we don't do a full re-test. 
Reviewed the commits at https://github.com/mortommy/openhab-mycroft/commits/master
and there are no major changes. 

Will fix `.gitmodules` conflicts and merge.

**Pull request merged**
