### PR TITLE
Upgrade Emby skill

### PR DESCRIPTION
**Pull request by rickyphewitt**
**Emby Skill** 

Changes
- Translations!
- Common Play Framework
- Play by Artist/Album
- Non MP3 source files are now transcoded

### CODE REVIEW

**Comment by rickyphewitt** [comment]
Looks like the tests are not mocking out the response from the Emby server. I'll take a look.

**Comment by rickyphewitt** [comment]
Posted feedback request: https://community.mycroft.ai/t/emby-music-skill-update-testing-and-feedback/7122

**Comment by krisgesling** [comment]
Excellent, thanks Ricky, I'll flag it with the testing team as it looks like it should be a pretty quick review :)

**Comment by rickyphewitt** [comment]
While I didn't get a bunch of community testing/feedback, I did receive this gem that I'm hoping gets me merged: 'Works great plays from an Artist and Album.' 

I've added an issue based on community feedback however I don't consider it a bug, more of a feature. (Is that what all developers say)

**Comment by krisgesling** [comment]
Hey sorry for the delay on this. I just installed Emby and this is working beautifully! Pretty impressed with Emby too :)

Code looks good, just in terms of Travis - we officially support Python 3.5-3.7 with 3.8 being added soon so it might be worth adding these to your Travis config.

**Comment by krisgesling** [comment]
Damn, I didn't notice that this PR was against the 19.02 rather than 19.08 branch. 

Can you run `mycroft-msk submit` again, it should automatically open the PR against the new branch.

**Comment by rickyphewitt** [comment]
Will do!

**Pull request merged**
