### PR TITLE
Add Soundcloud-Player

### PR DESCRIPTION
**Pull request by AIIX**
## Info

This PR adds the new skill, [Soundcloud-Player](https://github.com/AIIX/soundcloud-audio-player), to the skills repo.

## Description

SoundCloud is a music and podcast streaming platform that lets you listen to millions of songs from around the world, This skill enables you to stream and search for your favorite soundcloud tracks on your device.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Note to the Skill Testing Team - this Skill requires a Mark 2 or the GUI running in KDE Neon Unstable for the functional review.

**Comment by krisgesling** [comment]
Hey AIIX, 

I'm running Mycroft-Core dev branch on Neon 2057 in a VM. 

It searches great, plays the track, displays the image and track name. However the control buttons appear blank.

Some errors that may be related:
```
QQuickItem::stackBefore: Cannot stack QQuickControl_QML_11(0x562ed9744370, parent=0x562ed9631310, geometry=0,0 1125x763) before QQuickRepeater(0x562ed93e0a50), which must be a sibling
```

Trying to use the skip button results in:
```
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Mycroft/AudioPlayer.qml:166: ReferenceError: triggerEvent is not defined
```

I'm assuming these are related to the track progress bar?
```
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Mycroft/ScrollableDelegate.qml:46:9: Unable to assign [undefined] to QQuickItem*
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Mycroft/ScrollableDelegate.qml:46:9: Unable to assign [undefined] to QQuickItem*
file:///usr/lib/x86_64-linux-gnu/qt5/qml/Mycroft/ScrollableDelegate.qml:46:9: Unable to assign [undefined] to QQuickItem*
```

Any suggestions?

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
