### PR TITLE
Add nevermind-skill

### PR DESCRIPTION
**Pull request by ChanceNCounter**
## Info

This PR adds the new skill, [nevermind-skill](https://github.com/ChanceNCounter/nevermind-skill), to the skills repo.

## Description

Allows you to dismiss Mycroft verbally, in case of accidental activation, or if you change your mind. By default, Mycroft will confirm
this action, but there is a setting to disable verbal feedback, accessible over the web interface.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Run test

**Comment by krisgesling** [comment]
Hey Chance, I just checked it out, working great but I noticed you don't have a `settingsmeta.json` file. This is what creates the settings block on Home.mycroft.ai

I've sent you a PR as I thought it would be the easiest way to describe what's needed.

Let me know if you have any questions :)

**Comment by ChanceNCounter** [comment]
@krisgesling the failed test appears to be related to the alarm skill.

**Comment by krisgesling** [comment]
run test

**Pull request merged**
