### PR TITLE
Add neato

### PR DESCRIPTION
**Pull request by AZAZ78**
## Info

This PR adds the new skill, [neato](https://github.com/AZAZ78/mycroft-neato-skill), to the skills repo.

## Description

This skill allows you to control your vacuum cleaner robot with your voice. Lay back on your coach and tell your Neato to start cleaning the house or single rooms.
Also room specific NoGo Lines are supported by persistend maps (can be configured in your corresponding vacuum cleaner app)

You have to provide the name of your robot, its serial number and its secret. You can get those information by executing credentials.py from the skill directory.
To persist your credentials you can directly tell the script to persist them.

If you want to clean explicit rooms with NoGo Lines, you have to specify them in the optional rooms setting in json format (example is already provided). To get the right map id for your persistent maps there is another helper-script in the skill directory called getmapid.py

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by AZAZ78** [comment]
Hi, i saw in the CI pipeline that the neato test is failing. This is obviously because of the missing configuration in the test environment. How can i manage this without coding my personal access credentials in the test?

**Comment by krisgesling** [comment]
Hey Azaz, unfortunately the mocking options are limited in our Voight Kampff test suite so far.

I had a quick look at the code and tbh the easiest option would be to expect the error dialog. This at least confirms that the Skill is loading, and the intent is triggering as expected.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1477)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1477/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1477/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1477/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1477/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1477/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
