### PR TITLE
Upgrade mycroft-alarm

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-alarm to include the following new commits:

 - [Merge pull request #119 from MycroftAI/feature/api-delete-alarms](https://github.com/MycroftAI/skill-alarm/commit/745e139219d41c6b15d53f3776033afedbe06b10)
 - [Remove scheduled event when deleting all alarms](https://github.com/MycroftAI/skill-alarm/commit/712c378ff3705b197a6b3c64c3ac6201064c7ac1)
 - [implement step to check that alarm has stopped](https://github.com/MycroftAI/skill-alarm/commit/37f0babb2aff1393935d6d294d9b43041064ad03)
 - [Add API method to check for currently expired alarm](https://github.com/MycroftAI/skill-alarm/commit/a903cfc152c14a8194d419d58bfa39ef2cb48703)
 - [Check that alarms were actually deleted](https://github.com/MycroftAI/skill-alarm/commit/74705a7bdaff0409e817185a004198fdbbceefef)
 - [Add API method to get list of current alarms](https://github.com/MycroftAI/skill-alarm/commit/5106bd80d5f936b85b450c1ab59f8f9b01b9114a)
 - [reduce wait time on creating expired alarm](https://github.com/MycroftAI/skill-alarm/commit/abd30e7c719d9d2a9e141605dc4899b854590570)
 - [Replace given step with new api method](https://github.com/MycroftAI/skill-alarm/commit/906b72599531e9b0f105cb97aea2b216aeaf9eb0)
 - [Add API method to delete all alarms](https://github.com/MycroftAI/skill-alarm/commit/0beb10c243191a846031f7397bcc483c1ee1758c)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1556)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1556/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1556/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1556/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1556/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1556/logs/enclosure.log)

**Comment by krisgesling** [comment]
:boom: test time for the Alarm Skill has dropped from 17:49 mins down to 6:19

Note: had a single weather skill failure that is happening intermittently. Working to fix these atm.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1556)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1556/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1556/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1556/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1556/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1556/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1556)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1556/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1556/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1556/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1556/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1556/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1556)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1556/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1556/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1556/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1556/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1556/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1556)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1556/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1556/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1556/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1556/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1556/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1556)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1556/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1556/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1556/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1556/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1556/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1556))

**Pull request merged**
