### PR TITLE
Bark Skill

### PR DESCRIPTION
**Pull request by davekuk**
**Name of your skill**: _Name goes here_

## Description:

**Short description of your Skill and what it does**

## Checklist:
  - [ ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ ] Skill has been tested and works 
  - [ ] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [ ] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi @davekuk, thanks for taking the time to create new Skills for Mycroft! 

Getting started with Skill development can be a daunting task, so I wanted to make sure you had a chance to read some of our [documentation](https://mycroft.ai/documentation/#mycroft-skills). The easiest way to get started is with our [Mycroft Skills Kit (MSK)](http://mycroft.ai/documentation/skills/msk/). This tool sets up a template skill with all the right pieces to build from. It is also how you can submit skills to the Marketplace. 

At the moment you have forked the `mycroft-skills` repository and added your skill in a folder inside of that. This will certainly work on your system, however with the number of skills we need to handle, this process of editing `mycroft-skills` directly just doesn't scale well. Instead we use what are called submodules, these allow developers to have their own repo for each skill, and we just point to that, rather than everyone working off the same tree. Thankfully you don't need to worry about the details of submodules etc, the MSK automates all this for you including setting up the repo, uploading it to Github, and generating the pull request to submit it to the marketplace.

I downloaded your skill folder and it worked for me, so you're on the right track however we can't merge this pull request straight in. If you want to chat with other developers or get some feedback from the community, you can [post in the Skill Feedback section of our Forums](https://community.mycroft.ai/c/skill-feedback), or [join the Skills live Chat](https://chat.mycroft.ai/community/channels/skills). I'm regularly in both of these if you want to chat.

Thanks again
Kris

**Comment by krisgesling** [comment]
Hi Dave,
I'm going to close this PR as it will be much easier to push a new update from the Mycroft Skills Kit. Please reach out to me or post in the [~skills chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions though.

**Comment by davekuk** [comment]
Hi Kris:
I apologize, I didn't mean to post my skill public. I was unsure of how to test and deploy my test project at the start. I later discovered the location for the skills on my raspberry pi filesystem - /opt/mycroft/skills, eliminating the need for github. If I come up with a good skill - I'll then use github to share it using the guidelines. Have a great weekend.

RegardsDave

    On Friday, January 25, 2019, 7:56:41 PM CST, Kris Gesling <notifications@github.com> wrote:  
 
 
Hi Dave,
I'm going to close this PR as it will be much easier to push a new update from the Mycroft Skills Kit. Please reach out to me or post in the ~skills chat if you have any questions though.

**Comment by krisgesling** [comment]
Hi Dave, no harm done at all, glad you are playing with the skills and hopefully having fun with it! :grinning:

**Pull request closed without merging**
