### PR TITLE
Upgrade fallback-aiml

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades fallback-aiml to include the following new commits:

 - [Add 18.08 Readme](https://github.com/forslund/fallback-aiml/commit/3489c093f38b0bb57125e712c926558db20d1220)
 - [Don't reset the brain constantly](https://github.com/forslund/fallback-aiml/commit/f390aa7cf9d86803bed95eb4d0c9c5076c9f7245)
 - [Update settings handling for changes in 18.08](https://github.com/forslund/fallback-aiml/commit/e305ecaca0aa9f462badb54678b5ff23dfb4b16d)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Hey I wonder if we need to add something to the readme to let users know they need to activate this in their home.mycroft.ai settings before they can use it?

Other than that it seems to work great!

**Comment by forslund** [comment]
Fixed and Opened a new PR against 19.02

**Pull request closed without merging**
