### PR TITLE
Submit skill

### PR DESCRIPTION
**Pull request by dmwilsonkc**
## Description:

Control a MagicMirror with Mycroft voice commands via MMM-Remote-Control module

You can use this skill to hide or show modules, update the mirror or individual modules, refresh or restart the mirror, list installed modules, install modules by name. It requires a working MagicMirror on a Raspberry Pi, MMM-Remote-Control module installed and working properly, and Mycroft must be installed on the same Raspberry Pi

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] README.md has been updated with the following:
  ```
  +[submodule "magic-mirror-voice-control-skill"]
	path = magic-mirror-voice-control-skill
	url = https://github.com/dmwilsonkc/magic-mirror-voice-control-skill
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi @dmwilsonkc 

I saw that there had been some more recent work on this than is included in this PR. Not to mention people actively using it which is awesome! 

I'm wondering if you think it's in a state where it could get added to the Marketplace?

**Comment by krisgesling** [comment]
run test

**Comment by dmwilsonkc** [comment]
@krisgesling There is still some minor code clean up that needs to be done I believe. I have not had a chance to work on this skill for several months. I need to do some testing (trying to break the skill and error handling). I can look at it this weekend maybe. I've been super busy at work. The only issue with adding to the marketplace that I can see is the MagicMirror installation must be up and running with the appropriate modules for the skill to work. If the skill cannot connect to the mirror it throws an error.

See [this post](https://community.mycroft.ai/t/testing-and-feedback-for-magic-mirror-voice-control-skill/4396/7):

**Comment by krisgesling** [comment]
No worries at all. 

At a very quick glance it looks like you're handling those exceptions and prompting the user to check the IP. Is that what you are referring to, or are these not catching everything?
In the readme, it looks like you have good instructions and a clear warning that the MM instance needs to be operational and accessible. 

When you feel like it's ready for review, let me know and we'll have someone check it out.

**Comment by dmwilsonkc** [comment]
@krisgesling Well, I had a chance to identify and correct a number of sections of code that were causing errors. So at this point I believe the magic-mirror-voice-control-skill should be ready for the marketplace.

**Comment by krisgesling** [comment]
Hey @dmwilsonkc if we're ready for the marketplace I will close this PR so you can generate a fresh one on the 19.02 branch. Just use `mycroft-msk submit /path/to/your/skill`

**Comment by dmwilsonkc** [comment]
Can you provide me a link with instructions? Or do I just do it from the cli? Path to my skill I assume is my github repository?

**Comment by krisgesling** [comment]
Yeah, from your terminal, not inside the Mycroft CLI. So would look something like:
`dmwilsonkc@computer:~$ mycroft-msk submit ~/Projects/magic-mirror-voice-control-skill`

I also just realised you have "Skill" in the title of the README. We are trying to be more consistent with not having the word "skill" in skill titles. It looks better in the Marketplace, and means if we are referring to skills anywhere we don't end up with "the 'Random Skill' skill". How would you feel about removing that before you hit submit?

**Comment by dmwilsonkc** [comment]
No problem removing the word “skill” from the readme, but I am unclear on how to submit. This project was developed on a windows machine using atom. I’d really prefer instructions to make sure I do this properly the first time. I’m new at this, barely familiar with github so and documentation would be fantastic.

**Comment by krisgesling** [comment]
Ah right, the [documentation for Mycroft Skills Kit is here](https://mycroft.ai/documentation/skills/msk/), but I need to update it as we've recently added the 'submit' command. It's also only ever been tested on Linux. 

The reason we use MSK is because we utilise Git Submodules for this Mycroft-Skills repo. So instead of pulling all the code from everyone's skills into a single repo, a submodule is created and points to your repo at a specific commit. You can manually setup the submodule and create a PR but it's a bit convoluted and easy to stuff up.

If you have the skill running on a Picroft it would probably be easier to submit from there either using a keyboard and screen directly on the device or by SSHing into it. I'm guessing you've done this before in order to manually install the skill on the Picroft? 

If so then from your Picroft you probably want to run:
```
mycroft-msm update     // pull the latest changes into all skills
ls /opt/mycroft/skills      // list everything in the skills directory to find your Skill
mycroft-msk submit /opt/mycroft/skills/magic-mirror-voice-control-skill.dmwilsonkc
```
That's my guess at the directory name for your skill at the moment.
This will then ask for your github credentials and automagically create the submodule and generate the PR.

If anything isn't clear, hit me up on [Chat](https://chat.mycroft.ai) and we can go through it in more real time. I'll only be around for another hour or so today though.

**Comment by dmwilsonkc** [comment]
I’ll take a stab at it tomorrow. Does the word “skill” also need to be removed from the name of the skill,or just the readme? As removing from the skill name would require a new repo.

**Comment by krisgesling** [comment]
Awesome, I might be around tomorrow but depends on what the two cyclones near me are doing... o_O

Just the readme should be fine too :)

**Comment by dmwilsonkc** [comment]
So, one other thing. I don't currently have Mycroft or the MagicMirror running because of an SD card failure. Can I complete the submission using a linux shell on a windows machine?

**Comment by penrods** [comment]
I do that all the time!  Just install mycroft-core (normal ```git clone https://github.com/mycroftai/mycroft-core.git``` followed by ```./dev_setup.sh```), then you should be able to cd into your skill and run ```mycroft-msk submit .```

**Pull request closed without merging**
