### PR TITLE
Add myepisodes

### PR DESCRIPTION
**Pull request by brezuicabogdan**
## Info

This PR adds the new skill, [myepisodes](https://github.com/brezuicabogdan/brezicode.myepisodes.mycroftai), to the skills repo.

## Description

You will be able to ask Mycroft to check the status of your shows list handled by [MyEpisodes.com](http://www.myepisodes.com).
Mycroft will be able to give you the number of episodes not acquired and optionally the number of episodes acquired but not watched.
Also you will be able to find out the unacquired seasons and episdes numbers

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
I tried to give this a quick run through but am getting a lot of errors. 

This is probably because I don't have episodes in all the required lists. I created an account and tried to add a few shows but still getting:
> Sorry I am unable to process the information from my episodes dot com
> I received malformed information form my episodes dot com

So possibly they've also changed their format since you originally made the Skill?

**Comment by brezuicabogdan** [comment]
> I tried to give this a quick run through but am getting a lot of errors.
> 
> This is probably because I don't have episodes in all the required lists. I created an account and tried to add a few shows but still getting:
> 
> > Sorry I am unable to process the information from my episodes dot com
> > I received malformed information form my episodes dot com
> 
> So possibly they've also changed their format since you originally made the Skill?

@krisgesling 
I finally got the time to get my Picroft setup up and running again and the issue you mention above is not reproducing for me. Did you setup the credentials? What was your skill configuration when you got this error?

Also is there anything else I need to do for this PR to get merged or is it just waiting?

Thank you.

**Comment by krisgesling** [comment]
Hey I just reinstalled this, and am not seeing any problems at all. It might have been something as simple as a short service outage for MyEpisodes.com at the moment I tried it.

So with the existing reviews I think we can merge this Skill :tada:

There does seem to be the Youtube Skill submodule mixed up in this PR, so I might close this and ask you to create a new one:
`mycroft-msk submit /opt/mycroft/skills/my-skill-directory`

Then we'll be on the latest 20.02 branch and have a clean PR to merge.


Oh and a final little nitpick, we've deprecated the top-level `name` attribute in the `settingsmeta.json`. This will instead get pulled from your README heading so that it's consistent everywhere. This won't affect the operation of your Skill but will show a warning in users logs, so please delete line 2 in `settingsmeta.json`:
```
    "name": "MyEpisodes",
```

**Comment by brezuicabogdan** [comment]
I created the new PR https://github.com/MycroftAI/mycroft-skills/pull/1325

**Pull request closed without merging**
