### PR TITLE
Skill: Relaxing Nature Soundscape

### PR DESCRIPTION
**Pull request by Hasinator7**
## Description:

This skill allows you to play some nice soundscapes for relaxation, sleeping, meditation or the likes featuring nature soundscapes like a stream, thunderstorm or songbirds in the morning

## Checklist:
  - [ ✔️ ] Used Meta Editor for README
  - [✔️ ] Skill has been tested and works
 
  +[submodule "Nature-Sound-Skill"]
  +	path = nature-sound-skill
  +	url = https://github.com/Hasinator7/nature-sound-skill.git
 - [✔️ ] README.md has been updated with your skill phrase and description

This is my first ever use of github, so I hope I didn't screw anything up in the repos

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
Thanks for submitting the skill. It looks like the contents of your skill got added to this PR. Could you try going through steps 3, 4, and 5 from [here](https://github.com/MycroftAI/mycroft-skills#how-to-submit-a-skill) again?

**Comment by Hasinator7** [comment]
I#m sorry if I'm doing things wrong, but this is my first time working with github

**Comment by MatthewScholefield** [comment]
@Hasinator7 Not a problem. It looks like you fixed the problem with the exception of one small change that I made.

@penrods Should be good to merge.

**Comment by TREE-Edu** [comment]
@Hasinator7 Thank you for your skill submission, I've been wanting something like this for a little while now :)

@penrods This skill LGTM as well for merging.

**Pull request merged**
