### PR TITLE
Upgrade mycroft-alarm

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-alarm to include the following new commits:

 - [Merge pull request #66 from krisgesling/patch-1](https://github.com/MycroftAI/skill-alarm/commit/fa0932a3ae5c48431d8ef276213f541567a8b7f8)
 - [add confirm response and other possible dialog](https://github.com/MycroftAI/skill-alarm/commit/8b1612c9f4e25be3b3785d7a825868ea89560655)
 - [Merge pull request #64 from MycroftAI/bugfix/alarm_for_past_time](https://github.com/MycroftAI/skill-alarm/commit/3c2e2be13f6d75c2e045ed83c2bf0afaa09260b3)
 - [Update alarm.past.dialog](https://github.com/MycroftAI/skill-alarm/commit/2e16f628b85674ac40a6ad0a63bd2d1f51cf90be)
 - [avoid creating alarms for the past time](https://github.com/MycroftAI/skill-alarm/commit/f84490da1b9277ce81fe55602f4991952f0850be)
 - [Properly delete alarms](https://github.com/MycroftAI/skill-alarm/commit/796b96e2126f1bcfaa35e357ae412eab3fe05207)
 - [Merge pull request #63 from devs-mycroft/translations](https://github.com/MycroftAI/skill-alarm/commit/f5c8aea140c05e6ec6a6c3dbed3ac9893b0e4d01)
 - [Update translations](https://github.com/MycroftAI/skill-alarm/commit/844d0e0c897c64f3b64d792b0efd7cb4bfbf591c)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
Working great for me. 

- Tried setting an alarm for earlier today, got correct response that it's not possible.
- set an alarm and cancelled
- set an alarm and deleted
- set multiple alarms, asked to delete and was properly prompted to select one
- created recurring alarm and asked to cancel the alarm at that time and was prompted that it would cancel all.
- created alarm at same time as recurring alarm and deleted the individual alarm at that time, not the recurring alarm.
- listed alarms that were set
- asked to cancel alarm and did not confirm, alarm not cancelled.
- deleted all alarms

The utterance that didn't work was "set an alarm for 5 p.m. yesterday" - it set an alarm for 5pm today. However I can't see why anyone would actually try to do this, and the response makes it very clear when the alarm has been set for, particularly with the "5 hours from now".

I'm wondering if the test will pass today?
run test

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
It looks like an error in the test. Have suggested a fix via PR.

**Comment by forslund** [comment]
Fix merged and passing successfully. Merging

**Pull request closed without merging**
