### PR TITLE
Include subsonic media skill in readme

### PR DESCRIPTION
**Pull request by ejstacey**
## Description:

Player for streaming media from Subsonic Media Player

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] .gitmodules has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by ejstacey** [comment]
I generally don't write python code, so I may have done some dumb coding tricks to detect None objects or similar.  Happy to take suggestions on improvements.  Thanks.

**Comment by KathyReid** [comment]
# Review of `skill-subsonic-media`

## Standard checks (non-code checks)
* Check name of Skill `skill-subsonic-media` is unlikely to conflict with other vocal `install Skill X` commands = there are no similar phonemes for `subsonic`, but several for `media`. This Skill would still be the only one picked up on an `install subsonic` Utterance => I'm OK with it
* Check `dialog` - from a voice user interface perspective the dialog works well. I ran the `.dialog` through `mimic` (https://mycroft.ai/documentation/mimic/) and would like to **recommend** changing `Playing the requested media from Subsonic` to `Now playing the requested media from sub sonic` - the 'now playing' is more in line with other dialogs, and the space in between `sub` and `sonic` means that Mimic adds a slight pause which makes the TTS just slightly nicer. 
* Check `vocab` - the `play` Intent, even though it uses fuzzywuzzy matching, is likely to conflict with other `play` Intents if the user has multiple playback Skills. This is part of a broader issue where we have Skills with overlapping Intents - I don't think it makes sense to hold up this Skill being accepted, but it's something we should be aware of. 
* Check `regex` - Skill does not use regex Intent matching, not checking
* Check README for completeness - This README gives me pure joy. It is one of the most complete READMEs we have for a Skill. **Recommend** minor wording change - `enter subsonic details under ..` looks like it's missing some words. 
* Check `requirements.txt` - no issues I can see
* Check `settingsmeta.son` - well structured, excellent placeholder text
* Check `__init__.py` - I'm not fluent with Python yet, so couldn't see any obvious Py issues. 

Now requesting Python code review from Skills Team. 

_Side comment: This is pretty awesome for a first Skill. Eric is cool._

**Comment by el-tocino** [comment]
Does requirements.txt need python-Levenshtein? I don't see anything using it?
Also, pprint may need to be added, I don't believe that's a default package.

**Comment by ejstacey** [comment]
Thanks for having a look!

python-Levenshtein is an optional dependency for fuzzywuzzy.  It speeds up the string matching.  If it isn't on the system, running fuzzywuzzy matching warns about using a slower python based string matching system.  More details here: https://pypi.python.org/pypi/fuzzywuzzy

pprint is for when I was debugging.  I'll take it out.  It comes with python, I believe.

Thanks!
-Eric

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Pull request merged**
