### PR TITLE
Add wikiquote-skill

### PR DESCRIPTION
**Pull request by danielwine**
## Info

This PR adds the new skill, [wikiquote-skill](https://github.com/danielwine/wikiquote-skill), to the skills repo.

## Description

Gives quotations from notable people using wikiquote.

supported languages are: english, german, spanish, french, italian

other languages may work, but additional changes may be required in the wikiquote package

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Review by KathyReid — CHANGES_REQUESTED** [review]
### Meta

* Platform: Linux 18.04 LTS ubuntu
* Device version: 18.08.5, stable
* Who: @kathy-mycroft / @kathyreid 
* Datestamp: Wed 14 Nov 18:47:12 AEDT 2018
* Language and dialect of tester: Native English speaker, Australian accent

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.
> Check for voice installation - ie transcription works well in Speech to Text
`~~~~0 - __main__:handle_utterance:61 - INFO - Utterance: ['install wiki quotes']`
> This is a new Skill, voice installation or Market installation not possible, using manual installation
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/danielwine/wikiquote-skill
INFO - Downloading skill: https://github.com/danielwine/wikiquote-skill
INFO - Installing requirements.txt for wikiquote-skill
INFO - Successfully installed wikiquote-skill
```
=> Installed OK

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

* Ran the `locale` directory through `mimic` - speaks well

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Intents are well designed, should not overload existing Intents

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> There are several issues with the README - it's missing an icon, Categories and Tags. Please ensure that the README is generated using the [Meta editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html). 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> There is only a single dependency - `wikiquote`. This took a while (> 3 minutes) to install here, but I have a poor internet connection. Passing.

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> `settingsmeta.json` not used, skipping check

### Python code checks

* Inline documentation - is the code documented in line?
> There's no inline documentation, but the Skill is reasonably straightforward

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> Only one dependency

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a, skipping check

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> Code does graceful degradation if quotes aren't found

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes, autotest passes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> n/a skipping check 

_NOTE: We do not enforce PEP8 Checks on Skills_

### Functional tests

* `Hey Mycroft, give me a quote`
> random quote received

* `Hey Mycroft, tell me a quote from Lincoln`
> Abraham Lincoln quote received

* `Hey Mycroft, I need some wisdom`
> Random quote received

* `Hey Mycroft, I need some Buddhist wisdom`
> Buddhist quote received

* `Hey Mycroft, give a quote from Winston Churchill`
> Churchill quote received

=> functional tests are OK 

### Summary

This Skill is really well written, thank you so much for your contribution!
There are a couple of minor things that require some changes before I can accept this into the `mycroft-skills` repo`:

**ACTION REQUIRED**: 

* README needs to be regenerated 
* The Skill needs to have an appropriate LICENSE file added - we recommend Apache 2 or GPL

**Comment by danielwine** [comment]
OK, I'm ready with the changes you requested. But unfortunately I can't figure out how these submodules work, so I'm stuck. What is the right way of pushing the commits? Sorry, this is my first pull request. Can you help me out?

**Comment by KathyReid** [comment]
Run test

^^ this string triggers a CI rebuild, I'm trying to see why the autotest is failing. 
Your commits look good - ie the `git push` to this repo has worked well :+1:

**Comment by KathyReid** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
Hi there @danielwine, my colleague @forslund and I have been looking at this tonight, we think that the best approach here is for us to close this PR and get you to open a new one - if that's OK? 

The reason the autotest is failing is that it can't find the original git commit.

**Comment by KathyReid** [comment]
Closing this in favour of #662  ;-)

**Pull request closed without merging**
