### PR TITLE
updating home assistant module

### PR DESCRIPTION
**Pull request by btotharye**
## Description:
Updated the Homeassistant submodule skill

**Short description of your skill and what it does

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [X] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by btotharye** [comment]
Not sure why this is failing on your end, works fine for me:

```
coverage run -a --source=ha_client --omit=unittests/test_haclient.py --include=~/Documents/Github/mycroft-homeassistant/unittests unittests/test_haclient.py 
Coverage.py warning: --include is ignored because --source is set (include-ignored)
{'id': 'light.kitchen_lights', 'dev_name': 'Kitchen Lights', 'state': 'on', 'best_score': 67}
....
----------------------------------------------------------------------
Ran 5 tests in 0.556s

OK
```

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
There we go, the unittests shouldn't be run anyways.

**Pull request merged**
