### PR TITLE
Add play-jeopardy

### PR DESCRIPTION
**Pull request by BRinvelt**
## Info

This PR adds the new skill, [play-jeopardy](https://github.com/BRinvelt/jeopardy-skill-D-D-D-D-D---C-C-C-C-C-C-), to the skills repo.

## Description

"This Adaptable Assistant is the world's leading open source voice assistant"
"Who is Mycroft"

Mycroft will ask a trivia question and let the user know if their answer was correct.
Questions can be answered following jeopardy rules, but it is not required.

Jeopardy questions are served by jService a set of trivia services by [@sottenad](https://github.com/sottenad)

"Learning something new is fun." - Alex Trebek

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1536))

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1536)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1536/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1536/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1536/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1536/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1536/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
