### PR TITLE
Add desktop-control

### PR DESCRIPTION
**Pull request by TREE-Ind**
## Info

This PR adds the new skill, [desktop-control](https://github.com/TREE-Ind/desktop-control), to the skills repo.

## Description

A skill that allows voice control over your mouse and keyboard using natural language.  This skill should be compatible with any Mycroft instance that is installed on a system with display drivers / screen.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Joshua, 

Did I read somewhere that this won't work on Wayland? I'm running Wayland on Debian and it doesn't seem to work however it looks to be working better in a Ubuntu VM. Still not fully functional but hard to know how much of that is due to the environment. 

I'm going to try find another member of our skill testing team to review this one so it can be done properly. Looks promising though!

**Comment by TREE-Ind** [comment]
> 
> 
> Hey Joshua,
> 
> Did I read somewhere that this won't work on Wayland? I'm running Wayland on Debian and it doesn't seem to work however it looks to be working better in a Ubuntu VM. Still not fully functional but hard to know how much of that is due to the environment.
> 
> I'm going to try find another member of our skill testing team to review this one so it can be done properly. Looks promising though!

Greetings Gez,

It looks like Wayland is not supported by PyAutoGui yet.  Though the skill should should work under any GUI environment that is compatible with Pyautogui (with small caveats for certain features).  That is quite a few and really wouldn't be feasible to test all possible combinations.  Hopefully that won't keep the skill from being approved, it technically was on the official skills repo under a different name before the skill branches were created.

Here is the most relevant issue on Github I could find. - [https://github.com/asweigart/pyautogui/issues/111](url)

If needed we can add a disclaimer that X11 is currently the only supported Linux GUI environment.  Hopefully at some point Wayland can be supported later, but this isn't really a bug with the skill itself, but a lack of support for Wayland in PyAutoGUI as I mentioned.

Hope this helps, let me know if there is anything else we need to do in order to get the skill approved.

Thanks!

**Comment by bluemage** [comment]
So I'm on ubuntu 18 with gnome 3. type worked select all, copy, paste worked. move mouse did not work. neither did scrolling or press up/down(example enter) or hold. didn't try screen resolution. i think this is an awesome project I hope it comes further. Also it might be cool to have a move mouse left/right up/down and "stop" command. maybe say click to press mouse button.

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 5 Apr 2019 11:28CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [ ] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> Missing a short description of approximately 49 characters.  This will appear in the Marketplace on the Skill Card. This is entered above "About" and below the horizontal line below title "Desktop Control".  Consider something like this short description: "Control your mouse and keyboard using natural language"
> Title and About are good.  No use of the word "skill" 

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes.  For example "type Mycroft is awesome"

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> platform_plasmoid platform_mark2

- [x] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes

- [x] **Tags**
Are listed tags appropriate for this Skill?

> yes

- [x] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?


> yes Apache License 2.0

**Comment by krisgesling** [comment]
Thanks for reviewing the README @GPVM, and great suggestions!

**Comment by TREE-Ind** [comment]
> 
> ## Meta
> 
>     * Who: [@GPVM](https://github.com/GPVM) / @GPVM
> 
>     * Date and time: 5 Apr 2019 11:28CST
> 
>     * Language and dialect of tester: English (Canada)
> 
> 
> ## 2. Information Review - accurate and understandable
> 
> This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?
> 
>     * [x]  **Icon**
>       Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?
> 
> 
> > yes
> 
>     * [ ]  **Description**
>       Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.
> 
> 
> > Missing a short description of approximately 49 characters.  This will appear in the Marketplace on the Skill Card. This is entered above "About" and below the horizontal line below title "Desktop Control".  Consider something like this short description: "Control your mouse and keyboard using natural language"
> > Title and About are good.  No use of the word "skill"
> 
>     * [x]  **Examples**
>       Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?
> 
> 
> > yes.  For example "type Mycroft is awesome"
> 
>     * [x]  **Supported Devices**
>       If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.
> 
> 
> > platform_plasmoid platform_mark2
> 
>     * [x]  **Categories**
>       Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
>       Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.
> 
> 
> > yes
> 
>     * [x]  **Tags**
>       Are listed tags appropriate for this Skill?
> 
> 
> > yes
> 
>     * [x]  **License**
>       Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?
> 
> 
> > yes Apache License 2.0

Thanks for reviewing @GPVM, we've updated the README and added the short description as well as cleaning up the examples.

@bluemage, thanks for trying out the skill! We've updated the skill to use Padatious almost exclusively.  Make sure to restart your Mycroft after install, that will ensure all of the intents and entities get trained.  We tested on the latest Ubuntu 18 with Gnome and the functionality you mentioned seemed to work for us so not sure exactly why they weren't working for you.  On a more positive note the features you mentioned (relative mouse movement, mouse click) are on our roadmap for the next phase of this skill, we may also include a "swipe" intent that will pair well with the Mark II GUI hopefully.

@krisgesling Since we've updated the README on the master branch of the Git repo do I need to do anything with MSK again?  Thanks.

**Comment by krisgesling** [comment]
Yep you can add any updates by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill`
Since this PR is on the 18.08 branch I'll close it and MSK should create the new one against the 19.02 branch.

**Pull request closed without merging**
