### PR TITLE
Add myepisodes

### PR DESCRIPTION
**Pull request by brezuicabogdan**
## Info

This PR adds the new skill, [myepisodes](https://github.com/brezuicabogdan/myepisodes-skill), to the skills repo.

## Description

You will be able to ask mycroft to check the status of your shows list handled by [myepisodes.com](http://www.myepisodes.com).

mycroft will be able to give you the number of episodes not acquired and optionally the number of episodes acquired but not watched.

also you will be able to find out the unacquired seasons and episdes numbers

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1325))

**Comment by brezuicabogdan** [comment]
I will update the PR as soon as possible.

**Comment by krisgesling** [comment]
No the test failure is unrelated to your Skill. I've pushed a fix for it. So should pass now :crossed_fingers:

**Comment by brezuicabogdan** [comment]
> No the test failure is unrelated to your Skill. I've pushed a fix for it. So should pass now 🤞

Thank you.

**Comment by brezuicabogdan** [comment]
Run test

**Comment by brezuicabogdan** [comment]
@krisgesling  How do I re-trigger the failed tests?

**Comment by forslund** [comment]
I triggered a build, but we may have an issue with the script that runs the voight kampff test not updating the default skills correctly so don't worry if it fails.

**Comment by brezuicabogdan** [comment]
> I triggered a build, but we may have an issue with the script that runs the voight kampff test not updating the default skills correctly so don't worry if it fails.

I am just a perfectionist :)
So waiting for the merge then - thank you!

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1325))

**Comment by krisgesling** [comment]
Overriding as it's unrelated to this Skill and don't have an immediate fix available.

Merging :)

**Pull request merged**
