### PR TITLE
Add repeat-recent

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [repeat-recent](https://github.com/MycroftAI/skill-repeat-interactions), to the skills repo.

## Description

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1381))

**Comment by ChanceNCounter** [comment]
I think this should strip its dialog from repeated utterances before storing them. Otherwise it becomes Foghorn Leghorn 😛 

```
>> hello
what did you say 
>> I just said, hello       
repeat that
>> I just said, I just said, hello
what did you say?
>> I just said, I just said, I just said, hello

**Comment by krisgesling** [comment]
I probably had too much fun with Foghorning it - I saw it as a feature not a bug :laughing: 

I'll leave this PR open, if someone reviews the Skill and it's accepted before the dialog stripping is implemented then I'll merge it and we can do an update. Otherwise we can update the PR.

**Comment by ChanceNCounter** [comment]
It *is* pretty funny. Could be a config flag.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1381))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1381))

**Comment by forslund** [comment]
Did a [PR](https://github.com/MycroftAI/skill-repeat-interactions/pull/6) to remove the dialog from it's own speech.

**Comment by forslund** [comment]
Opened #1393 with the latest update removing the foghorning. Closing this PR

**Pull request closed without merging**
