### PR TITLE
Upgrade mycroft-spotify

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-spotify to include the following new commits:

 - [Merge pull request #58 from forslund/bugfix/post-play-framework-fixes](https://github.com/forslund/spotify-skill/commit/87cf92d4e68e1784923e086ddd678c2c2eb8a703)
 - [Disable librespot logging by default](https://github.com/forslund/spotify-skill/commit/4b864f36b822d0412d7c8bf5745f6853839a1002)
 - [Restore restarting of spotify](https://github.com/forslund/spotify-skill/commit/370003bb482b330ee15474cdf9942fec85bd56de)
 - [Increase default volume](https://github.com/forslund/spotify-skill/commit/acb0e18206ffa409aacb3c7713abb14298b87d07)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Review by KathyReid — APPROVED** [review]
### Ensure on correct commit for testing
> I had trouble checking out the specific branch, I removed the Skill in `/opt/mycroft/skills` then did a `git clone` from the `forslund:upgrade-mycroft-spotify` branch. 
```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/spotify-skill$ git log
commit 87cf92d4e68e1784923e086ddd678c2c2eb8a703 (HEAD -> 18.08, origin/HEAD, origin/18.08)
Merge: 2106631 4b864f3
Author: Åke <ake.forslund@gmail.com>
Date:   Sun Oct 14 21:41:54 2018 +0200

    Merge pull request #58 from forslund/bugfix/post-play-framework-fixes
    
    Bugfix/post play framework fixes
```

### Test case for Play framework
> The best thing I could think of here for test cases was to use other methods of invoking 'Play' and ensure they worked as anticipated. 
* `Hey Mycroft, play something by The Whitlams on spotify`
> "Now listening to the Whitlams"
=> test OK as expected

* `Hey Mycroft, play the news`
> Correctly played NPR news

* `Hey Mycroft, play adventure cave`
> Now playing Cave Adventure by TrollingLikeABoss on Spotify
=> not expected, but Adventure Cave Skill is not in the Play framework. 
`Hey Mycroft, play a game of adventure cave`
> Now playing Magik Four by Tiesto
=> My conclusion here is that the Adventure Cave Skill, and possibly others like it, may need to be added to the Play framework - under some sort of "play a game" type option

But in general is is working as expected

### Test case for `librespot` logging
> What I expected to see here based on a desk check of the code was a Skill Setting for whether to log or not. This was not shown in my Skill Settings on home.mycroft.ai. I refreshed the Skill which essentially deleted the Skill setting from home.mycroft.ai, but it did not re-appear. 
=> Not going to hold the Skill back on this, but noting as an observation

### Test case for `librespot` not starting locally and restarting
> I couldn't find `librespot` on my system - weird. Part of Ubuntu already? 
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ pip3 uninstall librespot
Skipping librespot as it is not installed.
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ which librespot
```
Again, not going to hold this commit back, but I thought it was weird - the test I was doing was to remove `librespot` to see if the Skill could try to restart it. 

### Default volume
Tested this by setting volume to 7, which reduced volume. 
Then tried again, set volume to 9, which increased volume. 
This means the new default volume of `80` is in effect. 

LGTM, merging

**Comment by forslund** [comment]
Just a clarification about librespot, that's by default only used on the Mark-1. On desktop linux an external Spotify client is expected. (Librespot is currently not in an offical ubuntu repo, and needs to be built manually)

**Comment by KathyReid** [comment]
Ah, that makes sense, tack sa mycket

**Pull request merged**
