### PR TITLE
Added Number Guess game skill

### PR DESCRIPTION
**Pull request by Arc676**
## Description:

Allows the user to play Number Guess with Mycroft. The user is prompted for a lower and upper bound, then is asked to guess the randomly generated number between those bounds.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by samclane** [comment]
Your `README` and `.gitmodules` both look fine, so you should be able to check those off. 

I installed and tested the game. It seems to work fine. (Mycroft for Linux on `master` branch). I was even able to give a negative lower bound and an upper positive one [-100, 100], and the Speech-to-text was able to parse the phrase "negative 50" into -50, so it seems to be stable and well implemented.

**Comment by Arc676** [comment]
Thanks for the response!

I should note that STT doesn't do the same with "minus 50," so "minus" anything doesn't get parsed correctly. Any tips? Maybe Mycroft already has an API call for something like this? Alternatively, I could try splitting the guess into words and flipping the sign if "minus" is the first word and the second is a number.

**Comment by samclane** [comment]
Ah yes. I did try "minus", and I think it works for lower numbers, but not higher ones. There are 2 systems at play that could be affecting how the phrase is parsed. The first is Mycroft's STT engine, which parses words like "negative" into "-" and "percent" into "%". Then there's the Adapt parser engine, which "normalizes" the text by removing definite articles such as "the" and handling some english->integer translation. 

**I think you're right in just checking if "minus" is in the utterance and negating the extracted number if it is.** I've tried fighting the system as well (I didn't pull that "percent" example from nowhere), and it's not worth it. The changes will probably come from upstream as Mycroft and Adapt mature.

**Review by KathyReid — CHANGES_REQUESTED** [review]
## Test of `numberguess` Skill

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.8.1
* Who: @kathyreid @kathy-mycroft 
* Datestamp: Thu 27 Sep 23:09:38 AEST 2018
* Language and dialect of tester: Native English speaker, Australian accent

## Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is a brand new Skill, so it's not able to be installed using voice yet, using manual installation with `msm`.

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/Arc676/Number-Guess-Mycroft-Skill
INFO - Downloading skill: https://github.com/Arc676/Number-Guess-Mycroft-Skill
INFO - Successfully ran requirements.sh for Number-Guess-Mycroft-Skill
INFO - Installing requirements.txt for Number-Guess-Mycroft-Skill
INFO - Successfully installed Number-Guess-Mycroft-Skill
```
> Validated by inspecting on filesystem => OK

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all `dialog` files through `mimic` => all pronounced OK

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> The `play` Intent is already used by several Skills, this _may_ cause problems - for instance - Play the news, play music and so on. I won't hold the Skill back on this, but something to be aware of. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> This is not a default Skill, skipping check. 

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, Skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> Looks good

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> **`requirements.txt` and `requirements.sh` are not used, could you please remove them?** 

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

`settingsmeta.json` not used, skipping check

## Python code checks of the Skill

* Inline documentation - is the code documented in line?
> Not documented inline, but Skill is pretty straightforward

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> No deps used

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> `try ... except` loops used throughout to catch exceptions

* Automatic tests - do automatic tests of the **Skill** pass?
> yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

## Functional tests

For the Functional Tests, I ran several rounds of the game and made the following observations: 

* The Skill generally works very well, and I used large ranges ie 1-1000
* I didn't use any negative ranges (per @samclane's comments), because I don't think this is a likely scenario in practice. 
* There was one error I identified; 

```
00:02:08.952 - mycroft.skills.core:wrapper:716 - ERROR - An error occurred while processing a request in Number Guess Skill
  File "/opt/mycroft/skills/number-guess-mycroft-skill.arc676/__init__.py", line 55, in handle_start_game_intent
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

This error was thrown when I was trying to guess the number, but I couldn't seem to replicate it. Is it worth doing a check to see that the value being passed is an `int`?

## Summary

* Please remove `requirements.txt` and `requirements.sh` as they are not used
* Please have a look at the error; additional type checking may be required

Kind regards, 
Kathy

**Comment by Arc676** [comment]
Thanks for the reply! I've removed the unneeded files.

I don't know how to reproduce the `TypeError`, but to be safe, I added an extra catch block to handle any input errors.

**Comment by KathyReid** [comment]
Thanks so much for looking at this so quickly! 
Those changes look great, merging :+1:

**Comment by Arc676** [comment]
Likewise!

Is there a difference between merging into the branch 18.02 or 18.08?

**Comment by penrods** [comment]
Indeed there is.  WIth this PR you are merged into the 18.02 repo and available for anyone that has stayed in the 18.02 world.  But the majority of the world is now in 18.08, so you will need to create an independent PR to request that.

There are a few API differences on MycroftSkills between being in 18.02 and 18.08, but that really is minimal.  However there is a big difference in the presentation of your skill for the Mycroft [Marketplace](https://markplace.mycroft.ai).  The [README Editor for 18.08](https://rawgit.com/MycroftAI/mycroft-skills/18.08/meta_editor.html) helps with creating an appropriately formatted README.md for presentation in the Marketplace.

**Comment by KathyReid** [comment]
Apologies, I missed that this was for 18.02 not 18.08, I should have checked.

**Comment by Arc676** [comment]
Oops, my bad. Checking `mycroft/version/__init.py__` it would seem that I'm also on 18.08. Should I open new PRs for this skill and also #525 ?

**Comment by Arc676** [comment]
@penrods Opened a new PR #590 in the correct branch. Should I rebuild the READMEs for these skills merged into 18.02 using the 18.02 editor or will the Mycroft team just delete these skills from this branch?

**Pull request merged**
