### PR TITLE
Add useridentification

### PR DESCRIPTION
**Pull request by alonyomtov123**
## Info

This PR adds the new skill, [useridentification](https://github.com/alonyomtov123/useridentification-skill), to the skills repo.

## Description

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi there,

It's great to see you are exploring Mycroft Skill development.

The submission process you used is how you can submit your completed Skills to the public Skills Marketplace. Any Mycroft user will then be able to install the Skill either by tapping a button or saying "install name-of-your-skill".

For testing purposes you don't need to submit the Skill, you can install it on any Mycroft device by running:
mycroft-msm install https://github.com/alonyomtov123/useridentification-skill

It looks like the Skill you've submitted today is probably for your own testing and not quite ready for prime time, is that right? If that is the case, I will close the PR until you're ready to have it reviewed by our Skill Testing Team. You can read more about that [review process in our documentation](https://mycroft.ai/documentation/skills/skills-acceptance-process/)

Also if you haven't already please join our Community [Chat](https://chat.mycroft.ai/community/channels/skills) or [Forums](https://community.mycroft.ai/) if you have any questions or just want to chat with other developers and users.

**Comment by alonyomtov123** [comment]
My skill is having a problem loading. Can you please help?
Thank You

**Comment by krisgesling** [comment]
Hey there, from a quick glance it looks like the changes suggested in the Forum are working out. 

Let me know if you run into any other problems :)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
