### PR TITLE
Support edit of README directly

### PR DESCRIPTION
**Pull request by penrods**
When the README markdown is edited, it now gets parsed and repopulates the form editor
and the various previews.

Also tweaked the big preview a tiny bit, but it still needs a lot of work to
look like the newest Marketplace cards.

Finally, fixed a couple minor bugs:
* Newlines were appearing before the skill name
* Category warnings were appearing all the time
* Special sections are at created at the bottom now

### CODE REVIEW

**Comment by krisgesling** [comment]
Seems to be working well though I found some odd edge case behaviour.

If a non-standard section is present in between the standard sections ie not below the tags, the parser strips that out. Not a problem for testing as the content won't be visible in the marketplace anyway, but could cause confusion if people paste in, edit and then go to copy it back out without realising content has been removed. Is it worth trying to leave these in place or parse and shift them below tags?

Second, it seems to stop accepting changes from the README tab if I:
- completely fill out the Edit form
- modify the README text
- return to preview or edit tabs - the modification is lost.

Also, do we want to warn people that the special sections won't necessarily be visible in the Marketplace? eg [HomeAssistant Configuration](https://market.mycroft.ai/skill/homeassistant)

Doesn't functionally change anything but you might be interested in the [forEach() method for arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach). Just a cleaner way to do for loops and makes it easier to access the current item without worrying about the index.

**Comment by penrods** [comment]
I pushed a change to use a button instead of it being automatic.  I'm not sure if that is better, to be honest.  Let me know what you think. 

Maybe I can split the difference and show a message in that area when you make a change instead of showing the button.  Something along the lines of "Updated from README changes".  I could also add a note that changes might not survive a round-trip.  Thoughts?

**Comment by penrods** [comment]
P.S.  The syntax of forEach() bugs the old C++ guy in me.  Plus it is way slower and I don't think you can implement a "break" in it.

**Comment by krisgesling** [comment]
Yeah I think it needs to be more verbose with the message.

You can throw an exception from foreach but it's not pretty. You really only want to use it if you genuinely want to execute something forEach, not "forMost". 

I hadn't seen the actual performance metrics on it before. I think I'd heard it was slower but figured it was likely such a small difference that it wouldn't matter unless you were working on quite a massive scale. That was quite an inaccurate assumption!

**Comment by penrods** [comment]
Give this version a shot and let me know what you think.

**Comment by krisgesling** [comment]
Yeah I think that's better. As long as people know to look for changes as that's kind of the point of putting stuff in there in the first place.

Happy for it to be merged?

**Comment by krisgesling** [comment]
Just set overflow hidden on the container rather than the span to cut off the heading.

Going to merge

**Pull request merged**
