### PR TITLE
Upgrade mycroft-installer

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-installer to include the following new commits:

 - [Merge pull request #38 from spagy/query-installed](https://github.com/MycroftAI/skill-installer/commit/10b70979e64be9b88a2eca3f59433988ce31d3c5)
 - [Merge pull request #46 from MycroftAI/feature/marketplace-improvements](https://github.com/MycroftAI/skill-installer/commit/85dcae47defcaf84bd2885837d076f3acec72719)
 - [Do not run marketplace installation on init](https://github.com/MycroftAI/skill-installer/commit/93d33e88342720d392e7057e850df70b9ea6a872)
 - [Don't install skills tagged for removing](https://github.com/MycroftAI/skill-installer/commit/f2b081de340053f48e27a3d04dbe817d714dcbd9)
 - [Merge pull request #44 from devs-mycroft/translate-2018-11-11](https://github.com/MycroftAI/skill-installer/commit/8cd785826d0f71dca2c2a88b15ed31bccb1ea2d2)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
This is a default Skill and has several dependencies with the Mycroft Marketplace, bumping to the top of the Skill review queue

**Comment by KathyReid** [comment]
### check on current commit

I couldn't merge this in to my local install to test

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-installer.mycroftai$ git pull https://github.com/forslund/mycroft-skills.git upgrade-mycroft-installer
warning: no common commits
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 3020 (delta 2), reused 7 (delta 2), pack-reused 3013
Receiving objects: 100% (3020/3020), 7.92 MiB | 401.00 KiB/s, done.
Resolving deltas: 100% (1563/1563), done.
From https://github.com/forslund/mycroft-skills
 * branch            upgrade-mycroft-installer -> FETCH_HEAD
fatal: refusing to merge unrelated histories
```

So I did a thorough desk check, and will do post-verification testing instead.

**Comment by KathyReid** [comment]
This has failed post-verification testing. 

```
 is mycroft installer installed                                                *        
 >> I don't know what that means. 
```
(this was the Intent used in the tests for Skill - it should work - but is not being recognised as an Intent)

@forslund should I revert this merge or will that cause problems for the Marketplace?

**Comment by forslund** [comment]
I don't think a revert is necessary since there is no loss of functionality, just no gain in functionallity

**Pull request merged**
