### PR TITLE
Upgrade mycroft-personal

### PR DESCRIPTION
**Pull request by penrods**
'This upgrades mycroft-personal to include the following new commits:

 - [Merge pull request #16 from MycroftAI/feature/update-tests](https://github.com/MycroftAI/skill-personal/commit/41684a82fad7a7b3a83dcca5a538d4a4157fb939)
 - [Update example text to match intent](https://github.com/MycroftAI/skill-personal/commit/cf7017714f86256b771dcafcae8628368d5d769e)
 - [Merge pull request #15 from MycroftAI/feature/update-tests](https://github.com/MycroftAI/skill-personal/commit/0894e6773ac125330a5252269487e89340d73e46)
 - [Add gitignore file](https://github.com/MycroftAI/skill-personal/commit/cda62d24fbef452167505dbb1fb9a543eb50ad44)
 - [Update tests for Padatious intents](https://github.com/MycroftAI/skill-personal/commit/0263bc042c7443e545916a0dc54a65549142bae7)
 - [Merge pull request #14 from MycroftAI/feature/modernize-contest](https://github.com/MycroftAI/skill-personal/commit/2aaecbca8dfa046724a218595a78b8b1aa472eca)
 - [Tweak README](https://github.com/MycroftAI/skill-personal/commit/b3e6fb1b0fd8cf59caf44205b206636e36470e07)
 - [Update and add contest winner](https://github.com/MycroftAI/skill-personal/commit/d8eba937928d5ba8a8fc11b7d03e85448c190394)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by penrods** [comment]
It looks like the autotest is failing due to intermittent Reminder and Weather test failure, not this skill.

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by LearnedVector** [comment]
tested and looks good to me

**Pull request merged**
