### PR TITLE
Add habit automation system skills

### PR DESCRIPTION
**Pull request by Nuttymoon**
## Description:

These 3 skills are part of the ["Habit automation system"](https://github.com/PFE1718/mycroft-habits-automation#readme):
- The skill-listener logs the user activity. It is also responsible for launching the 2 other skills when needed.
- The habit-miner extracts the habits of the user from the logs.
- The automation-handler interacts with the user to offer habits automation. It is also responsible for launching the different commands of the automated habits.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skills README
  - [x] Skills has been tested and work
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by el-tocino** [comment]
Is there a reason you're doing the pip bits in here instead off using requirements.txt?
https://github.com/PFE1718/PFE1718-habit-miner/blob/9162a9b2ef34673e62660bb72a55e491ded9e1be/requirements.sh
If you need a minimum version of a py module, might be better to use >= instead of ==.  Other skills could potentially different releases.  

The directory structure you're making is outside of the skill homes.  This should, for best practice, ease of cleanup, upgrading, migration, etc., be included within the repo itself.  Changing permissions to world read/writeable may not sit well with multi-user systems, and keeping it within the skill repo would also allow for it to be usable without having to alter those.  While you have three repos, this could be problematic, but checking for the existence of the listener(?) skill might be a useful variation?  The miner seems like it wouldn't do much without data from the listener; same with the automator.  You can also pre-stage the files if it's part of your repo as well.

**Comment by Nuttymoon** [comment]
Thanks for your quick feedback!
We used `requirements.sh` to install the pip packages because we had some errors when using `requirements.txt` only. We will try to use `requirements.txt` as much as possible and report any error we might encounter.
We can move our files into the listener skill folder as you suggested. However, concerning the multi-user systems concern, would it be reasonable to create a folder in the home directory of the user? (e.g. `"~/.mycroft-habits/"`). This would enable each user to have its own habits.
For the existence of the skills folders, we already offer the user to install the missing skills (e.g. the `skill-listener` if it is missing and that the user tries to use the `automation-handler`). We use the skill installer via utterance in the message bus (it is not working yet as they are not registered in `mycroft-skills`).

**Comment by el-tocino** [comment]
If you're looking to do multi-user habit forming, I believe there's some work on individual accounts coming soon for that. Check the chat to verify.  However, a ~/.mycroft/habits/ may not account for each of those users in any case, ie, a picroft that has pi and mycroft system users, and a house full of people using picroft.  Where would all their files hang out?  In my mind it seems like a repo-homed repository would work best for now.

Curious about the errors in using requirements.txt, that seems like something that might need looking into.

**Comment by JarbasAI** [comment]
if you want to have 3 skills then have a main one to submit, and in requirements.sh do 

`msm install url_to_repo`

then msm should install the other 2 skills automatically :)

**Comment by Nuttymoon** [comment]
So I spent quite some time trying to use `requirements.txt` to install the packages and got errors like that one:
```
Command "/home/gauthier/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-SR93lO/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-e5ZsQ8-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gauthier/.virtualenvs/mycroft/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-build-SR93lO/scipy
```
I finally figured out that if pip is updated to the last version (9.0.1) with `pip install --upgrade pip`. The thing is we can't upgrade pip within `requirements.sh` because it doesn't run in the virtualenv. Do you know how to solve that?

For the storage of the habits, we decided to use `~/.mycroft/skill/ListenerSkill` after discussing on the chat (storing in the skill directly would cause a hot reload of the skill which lead to problems). This is currently working.

Thanks for the advice @JarbasAI! We thought about it but want to stay transparent with the users and warn them about the installing of other skills!

**Comment by el-tocino** [comment]
Have you tried pip>=9.0.1 in the requirements.txt?

**Comment by Nuttymoon** [comment]
I just tried and pip 7.1.2 gets uninstalled but pip 9.0.1 doesn't get installed...
```
Found existing installation: pip 7.1.2
  Uninstalling pip-7.1.2:
    Successfully uninstalled pip-7.1.2
Running setup.py install for numpy
```
I eventually end up with the same error as before.
Other people like [this guy](https://github.com/pypa/pip/issues/1656) already encounter this problem and it doesn't seem like there is a solution.

**Comment by el-tocino** [comment]
One issue is that mycroft-core currently requires 7.1.2: https://github.com/MycroftAI/mycroft-core/blob/154dc18ec5383821eac77d6153f6968d85387006/dev_setup.sh#L157

**Comment by el-tocino** [comment]
What are you calling that requires pip to be on 9?  A quick check of the requirements.txt doesn't show anything obvious to me.

**Comment by Nuttymoon** [comment]
The package responsible is scipy:
```
(mycroft) ####@ubuntu:~/mycroft-core$ pip install scipy>=0.13.3
  Failed building wheel for scipy
Command "/home/gauthier/.virtualenvs/mycroft/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/pip-build-SJEI__/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-fQj3Z0-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/gauthier/.virtualenvs/mycroft/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-build-SJEI__/scipy
```
This problem disappears with pip 9.0.1. Not sure that pip 9 is needed tho. 
I can still run Mycroft after upgrading pip but maybe it's not a good idea to force it for everyone...

**Comment by JarbasAl** [comment]
i have had this trouble before also with scipy, i have been using the latest pip for a while now without trouble in mycroft, have not tried in raspberry pi

**Comment by el-tocino** [comment]
Looks like this shouldn't be a go-forward issue.  https://github.com/MycroftAI/mycroft-core/pull/1410

**Comment by Nuttymoon** [comment]
Great! We will test again after this fix and do another PR I guess.

**Comment by el-tocino** [comment]
If we can test it against that fix and verify it's working, then I don't think you'd need to do a new PR and we can just merge this one.

**Comment by Nuttymoon** [comment]
I will have to commit the changes first but yes.

**Comment by el-tocino** [comment]
Hm...this one still ready to be merged? If so can you update the git modules and readme and I'll get on that?

**Pull request merged**
