### PR TITLE
Add Wikidata

### PR DESCRIPTION
**Pull request by AIIX**
## Info

This PR adds the new skill, [Wikidata](https://github.com/AIIX/skill-wikidata), to the skills repo.

## Description

Get Current and Historic Facts & Information About A Person From Wikidata

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey AIIX, some very nice Skills to start the week. 

Especially excited for Soundcloud, thanks!

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Note to the Skill Testing Team - this Skill requires a Mark 2 or the GUI running in KDE Neon Unstable for the functional review.

**Comment by LinusSkucas** [comment]
# Skills test for Wikidata

## Meta
*   Platform: Picroft
*   Mycroft-core version: 19.02
*   Who: [@LinusS1](https://github.com/linuss1) Mattermost/forum: brrn
*   Datestamp:  `2019-08-27_19:28:12_UTC`
*   Language and dialect of tester: (American) English

## 0. Automated tests
Are all automated tests passing?
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable
- [ ]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

> Looks ok. I do see usage of `self.speak` consider putting that into a dialog file, and just using speak_dialog, to make this skill translation friendly.
I also suggest that you make this a commonqa skill, because this fits in along with the common qa purpose, and the commonqa skill might get the utterance and not your skill.


- [x]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

> This is error handling.

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

>Good.

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.
Also check to see if `requirements.txt` and `requirements.sh` are empty, if they are, they can be deleted.

>Good

- [x]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

>No settings.

- [x]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

>Yes, tests are complete.


- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

>Nope.


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x]   **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

>Yes

- [ ]   **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

>You probably want to update the short description with something other than "Skill Wikidata".

- [x]   **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

>yes

- [x]   **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

>just mark 2 and plasmoid.

- [x]   **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

>Information

- [x]   **Tags**
Are listed tags appropriate for this Skill?

>yes

- [x]   **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

>GNU General Public License v3.0


## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method:
> Output:
> ```
(.venv) pi@picroft:/opt/mycroft/skills/email-skill $ msm install https://github.com/AIIX/skill-wikidata
INFO - building SkillEntry objects for all skills
INFO - Downloading skill: https://github.com/AIIX/skill-wikidata
INFO - Installing system requirements...
INFO - Installing requirements.txt for skill-wikidata
INFO - Successfully installed skill-wikidata
INFO - invalidating skills cache

> ```



- [x]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

>No settings

- [ ]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> No dialog directory, consider using speak_dialog to make things translatable.

#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described. Also check that the sample utterances activate the skill

- [x]   **"How old is Steve Jobs"**

> The age of Steve Jobs is 64

- [x]   **"Where was Bill Gates born"**

> Bill Gates was born in Seattle

- [x]   **"What is the occupation of Linus Torvalds"**

> programmer

- [x]   **"What is Linus Torvalds date of birth"**

> Linus Torvalds was born on day 28 of month 12 in the year 1969

- [x]   **"What is Abraham Lincoln date of death"**

> Abraham Lincoln died on day 15 of month 04 in the year 1865

Looks good.

## Summary
 - [ ] I'm not sure if Wikidata offers non-english pages/info but if it does, it would be nice if the skill was translatable.
 - [ ] Make the short description longer, and more descriptive.
 - [ ] Perhaps make this a common qa skill.

> Thanks for making this skill!

I don't have a gui system, so I wasn't able to test that part of the skill, though.

**Comment by krisgesling** [comment]
Hey @AIIX just following up on Linus's comments. I've submitted two PR's with suggestions as I know you're busy. 

Edit: Also on point 3 in the summary above, I think the vocab is focused enough not to make it a QA Fallback. Maybe if we are pulling in more data from wikidata in the future though.

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
