### PR TITLE
Add deezer-skill

### PR DESCRIPTION
**Pull request by Y0ngg4n**
## Info

This PR adds the new skill, [deezer-skill](https://github.com/Y0ngg4n/deezer-skill), to the skills repo.

## Description

Play song from deezer

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1396))

**Comment by Y0ngg4n** [comment]
Can somebody merge this?

**Comment by krisgesling** [comment]
Hey Yonggan, sorry for the delay, we're focused on getting the Mark II shipped at the moment so have put a lot of other non-essential items on the backburner. 

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

A particular challenge with Deezer might be whether anyone has an account for it. Will see who I can drum up to try it out.

**Comment by devops-mycroft** [comment]
I have a deezer acct.  I'll try when we get the sound stable on the Mark II
dev kit.

Are you using the common play framework?

--

*Joshua Montgomery |* Founder *|* *Mycroft AI*
300 E 39th Street, Ste 4I, Kansas City, MO 64111
p 785-840-6155 <7858406155> *| *joshua.montgomery@mycroft.ai
https://mycroft.ai <http://mycroft.ai/>

**Comment by Y0ngg4n** [comment]
@krisgesling No Problem ;)
@devops-mycroft Yes i use the common play Framework ;)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
