### PR TITLE
Upgrade mycroft-alarm

### PR DESCRIPTION
**Pull request by penrods**
'This upgrades mycroft-alarm to include the following new commits:

 - [Add gentle chime alarm (#39)](https://github.com/MycroftAI/skill-alarm/commit/4545504930f86813a9a9937ff0e47c8237c1f87b)
 - [Fix failing alarm test](https://github.com/MycroftAI/skill-alarm/commit/ef165bd771d1046df8ba9df803288cb0d984f6ba)
 - [update german Transtation (#33)](https://github.com/MycroftAI/skill-alarm/commit/1075afdf1a3b6ab6d4dcc9ee323f7fe67b7a7fd5)
 - [Add "add" to Set vocab (#35)](https://github.com/MycroftAI/skill-alarm/commit/5dac520c938b13811d00061ff50c28672ce516f3)
 - [More usability changes (#38)](https://github.com/MycroftAI/skill-alarm/commit/795d83ed5ec66a2f519368e978350310aca2925a)
 - [Tweaks after first round of usability reports (#37)](https://github.com/MycroftAI/skill-alarm/commit/51159bb3acbe3133979c9fc603f338ec5119fea6)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Review by KathyReid — CHANGES_REQUESTED** [review]
## Test environment

* Linux Ubuntu 18.04 LTS Git install
* running 18.08.00 of `mycroft-core`

## Ensure on correct commit

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git checkout 18.08
Branch '18.08' set up to track remote branch '18.08' from 'origin'.
Switched to a new branch '18.08'
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git pull
Already up to date.
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git log
commit 4545504930f86813a9a9937ff0e47c8237c1f87b (HEAD -> 18.08, origin/18.08)
Author: Steve Penrod <github@gpll.org>
Date:   Fri Sep 14 16:03:13 2018 -0500

    Add gentle chime alarm (#39)
    
    New chime sound thanks to Herman Schmidt at Freesound.org
    https://freesound.org/people/HermanSchmidt/sounds/254749/
    
    Also tweaked the README
```
```
Regenerated mycroft-alarm.mycroftai:query.next.alarm.intent.
Regenerated mycroft-alarm.mycroftai:alarm.status.intent.
```

### Test case to ensure new sound is selectable in home.mycroft.ai

*  Ensured Intents were reloaded, and then checked home.mycroft.ai to ensure that Gentle Chimes was selectable. It's beautiful, and selectable

> test case passed

* set an alarm using Gentle Chimes to ensure that the sound file was installed with the Skill

* `Set an alarm for 5 minutes`
> "I've set an alarm for 1.56, 10 hours from now"

_The current time is just after 1.50am in my time zone, and the alarm *should* be set for 1.56am, but it is not 10 hours from now - this is a possible but in the Dialog - not adjusting for the time zone. The current time zone is UTC +1000hrs. 

*Bug Identified* - dialog does not match the time the alarm is being set for, UTC offset suspected as root cause. 

*Bug identified* - during playback of Gentle Chimes, it is only playing the sound for a fraction of a second, then repeating the sound, so it sounds like this: 
https://instaud.io/2GN3

### Test case to fix failing alarm test

* not tested, @forslund has already tested this

###  Test case for update German translation

* I don't know enough German to accurately test, entschuldigung

### Addition of `add` to vocab

* `Add an alarm for two minutes`
> "Alarm set for 2.24am, in 10 hours"

Passing this test, even though the previous bugs - ie with the dialog confirmation being 10 hours out, and the mp3 playback being faulty. The alarm played back  at the correct system time - ie 2.24 am

### Test cases for usability changes

* `Set a recurring alarm on Tuesdays at 1.50pm`
> Alarm set for midnight on Tuesdays, beginning in 31 hours

Go home Mycroft, you're drunk. Or you will be in 31 hours. Or you are and you will be sober in 31 hours. I give up. Failing test. Do not pass go, do not collect $200. 

* I could see in the code handling of the user requesting `stop` but because of the mp3 playback bug I could not actually get Mycroft to hear me say "stop". 

* Test case for ordering of dialog in recurring alarms
`Set an alarm every Monday at 8pm`
> "Alarm set for 8pm on Mondays, beginning in 27 hours" - the beginning in 27 hours part is incorrect, but the 8pm on Mondays part is. Test passing

* `When is the next alarm`
> "Your next alarm is 8pm on Monday, 27 hours from now"
The beginning part of the dialog is correct, but the 27 hours part is wrong. 


---

Test case to see if the mp3 playback bug is **just** for Gentle Chimes - I had not heard this playback bug on other sounds when testing, so this test tries to differentiate if playback bug is _specific_ to Gentle Chimes

* Set playback sound to something other than Gentle Chimes in home.mycroft.ai, then `Set an alarm for two minutes`
> "Alarm set for 2.30am, in 10 hours"

The 2.30am part was correct, the 10 hours part was not. The alarm triggered correctly at 2.30am, and the "Bell" sound was played back in the same manner - a small timeslice of the audio - about half a second - was continually played. 

_Conclusion_ this bug is not specific to Gentle Chimes, it's a broader issue with mp3 playback in this Skill.

**Comment by penrods** [comment]
Thanks, I am guessing the issue is the base timezone.  The Mark 1 and Picroft both operate on an is setting of UTC+0 and I convert from there.  Let me examine this on an Ubuntu system.

**Comment by KathyReid** [comment]
No worries, here is my `date` output
`kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/fallback-wolfram-alpha.mycroftai$ date
Mon 17 Sep 03:27:37 AEST 2018`

AEST is UTC +1000hrs

**Comment by KathyReid** [comment]
### Ensure on correct commit
```
(.venv) kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-alarm.mycroftai$ git log
commit e6ccee38f67a3eaa4f3d50ea0963b7d70a485c4c (HEAD -> 18.08, origin/18.08)
Author: Steve Penrod <github@gpll.org>
Date:   Mon Sep 17 04:09:16 2018 -0500

    Fix to deal with systems that aren't in UTC timezone (#40)
    
    The Alarm only worked correctly when the base OS was in UTC timezone.  This
    fixes it for all timezones.
    
    Also improved the reporting of nice_relative_time() by rounding the chosen unit.

```

### Re test of test cases that had erroneous time zone

* `Set an alarm for 2.05am`
> "Alarm set for today at two oh five a.m., in 89 seconds"
 
Alarm triggered at correct time at 2.05am

* `Set an alarm every Tuesday at 1.30pm`
> "Alarm set for one thirty p.m. on tuesdays, beginning in 11 hours"

This is exactly what I was looking for, the "beginning in ..." is correct

*  `Add an alarm for 2.14am`
> "Alarm set for today at two fourteen a.m., in 2 minutes"

Alarm triggered at correct time, and correctly escalated the volume over time. 

The bug with the mp3 file not playing correctly was also not present. 

---

Skill works beautifully now, merging.

**Pull request merged**
