### PR TITLE
Add Crystal Ball skill

### PR DESCRIPTION
**Pull request by Arc676**
## Description:

Randomly answers yes/no questions

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by Arc676** [comment]
For the last two items in the checklist, is it referring to adding the submodule in `.gitmodules`? I don't see skill descriptions in `README`.

**Comment by samclane** [comment]
@Arc676 For the first one you're correct, it actually should go in submodules. In `mycroft-skills/` run `git submodule add <SUBMODULE URL ENDING IN .git> [optional name; otherwise uses repo name]`. This will clone your skill into the folder and add the correct entries in `.gitmodules` and `.git/config`. For example, to add my "homeseer-mycroft" skill to my forked repo, I run `git submodule add https://github.com/samclane/homeseer-mycroft.git`

As for the actual Skill README, you generate one using this: (https://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html)

**Comment by Arc676** [comment]
Ah, OK. Thanks for the response. In that case, both those items are done.

**Comment by samclane** [comment]
I tested all example phrases, which worked. I tried to throw it a loop by asking what the weather would be like "tomorrow" and "in the future", which triggered the Weather skill as intended. 

I think the skill is functional and vouch for it.

**Review by KathyReid — CHANGES_REQUESTED** [review]
## Test of `crystalball` Skill

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.1
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Fri 28 Sep 00:53:18 AEST 2018
* Language and dialect of tester: Native English speaker, Australian accent

## Non-code checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is a new Skill, so it's not yet available for voice install. Using `msm` install instead. 
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/Arc676/Crystal-Ball-Mycroft-Skill
INFO - Downloading skill: https://github.com/Arc676/Crystal-Ball-Mycroft-Skill
INFO - Successfully ran requirements.sh for Crystal-Ball-Mycroft-Skill
INFO - Installing requirements.txt for Crystal-Ball-Mycroft-Skill
INFO - Successfully installed Crystal-Ball-Mycroft-Skill
```
Checked filesystem to validate => OK

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> pronunciation ok (only one dialog file)

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> These look like they won't conflict with other Intent keywords :+1: 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> This Skill is not a default Skill, skipping check

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> regex not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README looks good, adheres to the meta-editor format

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> **please remove `requirements.txt` and `requirements.sh` as they are not used. 

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> not used, skipping check

## Code checks

* Inline documentation - is the code documented in line?
> No inline documentation, however the code is very basic; not required

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> no dependencies

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> not required

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> Skill is very basic; not required

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a, `settingsmeta.json` not used

## Functional testing

Noting that @samclane has done functional testing - many thanks Sawyer, adding validated tag

## Summary

If you could please remove the `requirements.txt` and `requirement.sh` files then we can merge this Skill :+1:

**Comment by Arc676** [comment]
Thanks for the reply! I have removed the relevant files.

**Comment by KathyReid** [comment]
Thanks @Arc676 for removing those files, merging! :-)

**Pull request merged**
