### PR TITLE
[18.08] lifx-mycroft: Skill allowing interaction with LIFX brand smart-bulbs.

### PR DESCRIPTION
**Pull request by samclane**
## Description:

Allows users to interact with the [LIFX-brand smart-bulbs](https://www.lifx.com/) on their home network through Mycroft. Can change power, brightness, color, and color-temperature of individual Lights and predefined Groups.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by samclane** [comment]
Still no clue on this one. It goes straight through to Wolfram fallback, which makes no sense to me. It's not like I'm using the "turn" keyword here. It's not mistaking it for anything; the Intent just falls right through.

**Comment by KathyReid** [comment]
@samclane quick note to say we hear you, we're going to dig into this, give us a day or so :+1:

**Comment by KathyReid** [comment]
It's actually the Reminder Skill Intent that's failing here, _not_ the LIFX test Intents. Scheduling this Skill for testing and I can manually override the autotester if needed. 

Taking ownership of this PR, I have lots of LIFX equipment here on my home network to test with.

**Comment by samclane** [comment]
Looks like the 2 fails are Reminder and Weather.

**Comment by forslund** [comment]
Yes, your skill looks clean.

I've seen the delete alarm one on occasion before.

**Comment by forslund** [comment]
Run test

**Comment by samclane** [comment]
Same other skills fail I think. I don't think it's my Skill's fault, as none of the words in the test phrases match any of my Vocab/Regex.

**Comment by forslund** [comment]
Yes none of the issues are related to your skill so this is good to go.

- The alarm skill fails every Wednesday (due to a bad test)
- The weather skill has a weather dependent test (which is also bad).

**Comment by forslund** [comment]
Run test

**Comment by samclane** [comment]
Looks good. No more changes from me here.

**Comment by KathyReid** [comment]
Quick note to say I haven't forgotten this, it's on my list! Apologies for the delay, I've been head down on our Languages platform.

**Comment by samclane** [comment]
Thanks for the update. I was a little bit concerned, but I know you guys have a lot on your plate.

Side note, `.gitmodules` is now failing in the merge. I assume that's because of other skilling being pushed to the 18.08 branch. Should I leave it or try and "resolve conflicts" myself?

**Review by KathyReid — APPROVED** [review]
# Review of `lifx-mycroft`

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.1
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Thu 27 Sep 21:28:20 AEST 2018
* Language and dialect of tester: Native English speaker, Australian accent

## Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is a new Skill, and is not currently in the repo. This means that you can't install it via voice yet. Instead, I did an `msm` install: 
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/samclane/lifx-mycroft
INFO - Downloading skill: https://github.com/samclane/lifx-mycroft
INFO - Installing requirements.txt for lifx-mycroft
INFO - Successfully installed lifx-mycroft
```
Validated successful installation by observing files on filesystem, => OK

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/lifx-mycroft.samclane$ ls -las
total 92
 4 drwxr-xr-x  7 kathyreid kathyreid  4096 Sep 27 21:23 .
 4 drwxr-xr-x 34 kathyreid kathyreid  4096 Sep 27 21:23 ..
 4 drwxr-xr-x  3 kathyreid kathyreid  4096 Sep 27 21:23 dialog
 4 drwxr-xr-x  8 kathyreid kathyreid  4096 Sep 27 21:28 .git
 4 -rw-r--r--  1 kathyreid kathyreid  1203 Sep 27 21:23 .gitignore
12 -rw-r--r--  1 kathyreid kathyreid  9296 Sep 27 21:23 __init__.py
36 -rw-r--r--  1 kathyreid kathyreid 35148 Sep 27 21:23 LICENSE.md
 4 -rw-r--r--  1 kathyreid kathyreid  1120 Sep 27 21:23 README.md
 4 drwxr-xr-x  3 kathyreid kathyreid  4096 Sep 27 21:23 regex
 4 -rw-r--r--  1 kathyreid kathyreid   101 Sep 27 21:23 requirements.txt
 4 -rw-r--r--  1 kathyreid kathyreid   569 Sep 27 21:23 settingsmeta.json
 4 drwxr-xr-x  3 kathyreid kathyreid  4096 Sep 27 21:23 test
 4 drwxr-xr-x  3 kathyreid kathyreid  4096 Sep 27 21:23 vocab
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all the `dialog` files through `mimic` => all pronounced well, no changes recommended

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> In `Decrease.voc`, consider `turn down` as an option. Not going to hold the Skill up on that though ;-) Same for `Increase.voc`, consider `turn up` as an option. All the other `voc` files look good. I noted that the `Temperature.voc` didn't have the word `temperature` in - as this would likely trigger the Weather Skill. A side note that we're working on an approach for the "Play" keyword, which is heavily loaded across multiple Skills, that may also work for Temperature in the future. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> This is not a DEFAULT Skill, and shouldn't be due to the dependency on third party hardware, skipping check. 

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Very nice use of `regex` for percent. Nicely done. 

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README follows the meta-generator guidelines. Recommend adding the #IoT tag as well for easy findability - you'll probably want to update the README once the Skill is pulled into `mycroft-skills` to remove the `msm` line - you may want to make the change then? 

> You may also wish to make a comment around the User Settings required for the Skill - I was expecting to have to enter in my LIFX account credentials in home.mycroft.ai, but I'm guessing the `lifxlan` library allows commands to be sent to bulbs that are on the same network? You may want to make that clear in the README. 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> `requirements.txt uses appropriate libs, no versions specified

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> looking good :+1: 

**Outcome: minor suggestions, nothing I would hold the Skill back on**

## Code checks

* Inline documentation - is the code documented in line?
> There isn't a lot of inline documentation, but it's pretty straightforward

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> Deps are fine

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> error handling is done well, checks major errors, fails gracefully

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes, the autotester is being pesky, but not the fault of this Skill

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> Python Booleans not used in Skill Settings

_NOTE: We do not enforce PEP8 Checks on Skills_

**Outcome: minor suggestions, nothing I would hold the Skill back on**

## Functional checks

* `Turn of the Study light` (my Study is called Study)
> "Turning off Study" => Study LIFX turned off

* `Turn on the Study light`
> "Turning on Study" => Study LIFX turned on

* `Set it to purple` (testing contexts)
> "Setting Study to purple" => Study turned to purple

* `Set it to green` 
> "Setting Study to green" => Study turned to green

* `Set it to 25 percent brightness`
> Setting Study to 25 => Study turned to green, 25% brightness

* Tested a range of colors in `webcolors` - all were recognized successfully 

**Passing functional tests with flying colors ;), very nicely done**

**Pull request merged**
