### PR TITLE
Add routine

### PR DESCRIPTION
**Pull request by ChristopherRogers1991**
## Info

This PR adds the new skill, [routine](https://github.com/ChristopherRogers1991/mycroft_routine_skill), to the skills repo.

## Description

Create named rountines, which are lists of Mycroft commands, that can be run by name, and scheduled to run at particular times.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
I tested this previously in #411 and #431; it was well written so just going to give it a quick check 

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/ChristopherRogers1991/mycroft_routine_skill
INFO - Downloading skill: https://github.com/ChristopherRogers1991/mycroft_routine_skill
INFO - Installing requirements.txt for mycroft_routine_skill
INFO - Successfully installed mycroft_routine_skill
```

### Functional test
* created routine => worked OK, it tripped on some transcriptions, but I have a cold :(
* scheduled routine => worked OK
* describe routine => worked OK

## Summary

* Please redo the `README` file using the new [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html). The new format is required to support the [Mycroft Marketplace](https://market.mycroft.ai)

**Comment by ChristopherRogers1991** [comment]
Hey @KathyReid,

I started working through the README changes and hit a couple snags (see https://github.com/MycroftAI/mycroft-skills/issues/678 and https://github.com/MycroftAI/mycroft-skills/issues/677). The second issue I can work around if necessary, but the first makes it pretty challenging to feel confident that the README I'm generating will look decent once fully rendered. Not wanting to make multiple submissions to get the formatting right, I'm going to hold off. Feel free to close this out for now if you want to keep your queue clean, and I can open a new PR when I've got the file generated.

**Comment by KathyReid** [comment]
Hey @ChristopherRogers1991 are you OK with me closing this off or did you want to push the README you have and I can take a look at it?

**Comment by ChristopherRogers1991** [comment]
You can close this. I'll open a fresh one when I've got something ready.

- Chris

**Comment by KathyReid** [comment]
Thanks for confirming @ChristopherRogers1991. Closing as requested :-)

**Pull request closed without merging**
