### PR TITLE
Add decide-skill

### PR DESCRIPTION
**Pull request by lhannon**
## Info

This PR adds the new skill, [decide-skill](https://github.com/lhannon/decide-skill), to the skills repo.

## Description

about

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
This was previously tested by myself in #520, with one minor change requested. 
Change made, am merging.

**Comment by KathyReid** [comment]
Run test

**Comment by KathyReid** [comment]
The Skill Tester errors are not related to this Skill, I am overriding and merging.

**Pull request merged**
