### PR TITLE
updating to add home assistant skill

### PR DESCRIPTION
**Pull request by btotharye**
## Description:

**Short description of your skill and what it does
It manages the Home Assistant api and allows control of IoT and smarthome devices

## Checklist:
  - [X] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [X] Skill has been tested and works
  - [X] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [X] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by forslund** [comment]
run test

**Comment by forslund** [comment]
The error here is not due to the skill, it seems there's some instability in the weather skill intents.

**Comment by btotharye** [comment]
ok the regex was fixed and this should be good to be merged now

**Comment by KathyReid** [comment]
@btotharye we altered our [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/#what-happens-if-the-skill-management-team-cant-test-the-skill) last week to cater for exactly this case - where a Skill has multiple external dependencies. The Skills Team can't always test a Skill like this, because we're not familiar with the external deps - in this case, HASS.

So in the interests of practicality, we'd like to get a community member to validate that the update is working and post a comment to that effect in the PR.

Do you know of anyone and I can reach out to them?

**Comment by btotharye** [comment]
I guess anyone in the home-automation channel, this is rather annoying as a community developer that has gone out of his way to test every aspect he could locally in his own setup to only have to keep waiting for now more to test, but yet mycroft skills get pushed right on through.  Just saying there needs to be a better process for this, I hope I don't have to do this everytime I update my skill....

**Comment by btotharye** [comment]
You can also per the instructions in the readme test against http://167.99.144.205:8123 to prove the skill works per design

**Comment by TREE-Edu** [comment]
Skill Validation For Home Assistant Skill:

Tested on latest dev Git installation of Mycroft and pip install of HA.

Skill Settings Working: Passed
Skill loaded correctly: Passed
Skill responded to expected phrases: Passed
All intents were able to be triggered as expected: Passed

This skill seems to install and work perfectly in a real word test, and therefore has our vote for this PR to be merged.

**Pull request merged**
