### PR TITLE
Add tmdb-skill

### PR DESCRIPTION
**Pull request by builderjer**
## Info

This PR adds the new skill, [tmdb-skill](https://github.com/builderjer/tmdb-skill), to the skills repo.

## Description

This skill uses tmdbv3api avaliable on GitHub at [tmdbv3api](https://github.com/AnthonyBloomer/tmdbv3api.git)
This product uses the TMDb API but is not endorsed or certified by TMDb.  Information avaliable at [TMDb](https://www.themoviedb.org/)
Easily find information, such as a description, or cast from a movie or tv show with your voice.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Yeah this one looks better, thanks.

The failed test doesn't appear to be related to this skill either, but I'll have a deeper look when I get some time later in the week.

**Comment by builderjer** [comment]
It appears to be with the alarm skill.  It seems that there is not a response in the test cases when Mycroft asks which alarm to cancel.

**Comment by krisgesling** [comment]
Run test

**Comment by builderjer** [comment]
Still seems to be a problem with the alarm skill.

**Comment by krisgesling** [comment]
Hi builderjer, 

Sorry for the delayed response. I just realised your PR has also been made against the 18.08 branch. We've had a few come up like this recently and it's the same version of MSK as those being submitted against 19.02 which leads me to believe that it's something else in your development environment.

Wondering if you can give me some insight into the device you're using for development, where you store your skills when developing and testing, and how you create the PR?

**Comment by builderjer** [comment]
@krisgesling, I believe that what happened is when the 19.2 version was released, I didn't realize that it pushed my skill to the new version, and I force pushed to the 18.08 version.  I am still learning github and think that I have it down on how to submit my skills with MSK.  I will close the 18.08 pull request.

Thank you for your response and review.

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 Apr 2019 9:35pm CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> The icon can be used per the site's guidelines (https://www.themoviedb.org/about/logos-attribution)

- [ ] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> The short description should be re-worked since it will be truncated to approximately 50 characters in the marketplace.  Would something like this work?  "Find details about movies, actors and productions"

> The 'Description' heading needs to be named About.

> About is where I would recommend placing the additional details such as the TMDB website address, the version of the API, any additional information that users should know and the fact this is not endorsed by TMDB if a disclaimer is needed.

> The heading 'Instalation' is missing a letter: 'Installation'

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> not constrained to a particular device

- [ ] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> none listed.  May I suggest the category Entertainment?

- [ ] **Tags**
Are listed tags appropriate for this Skill?

> no tags listed - please add tags such as #TMDB #movies #actors

- [x] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> GPL-3.0

**Comment by builderjer** [comment]
@GPVM, thank you for your input.

According to the tmdb api website, the logo that I am using is appropriate as per this page on the TMDb API Logos & Attribution page (https://www.themoviedb.org/about/logos-attribution)

I believe I have made all the other changes necessary to the README.md file.
If there is anything else, please let me know

**Comment by GPVM** [comment]
I updated my review to reflect the attribution of the icon - thank you for pointing that out to me.

I proposed 2 Readme file changes.  

I still think the Short Description needs to be reworked as mentioned in my review.

You need to add Categories and tags to your Readme - perhaps these will come with your next update.

**Comment by krisgesling** [comment]
Hi @builderjer 

The short description is completely up to you, we're just trying to make people aware of it as it will be cut off when displayed in the card view of the [Marketplace](https://market.mycroft.ai/skills).

The category on the other hand is required otherwise the Skill won't show up at all. You would just need to add the following to the end of your readme:
```
## Category
**Entertainment**
```

**Comment by builderjer** [comment]
I updated the README.md to where I think it is acceptable.  It didn't pass the tests, but I think that is the alarm skill.

**Comment by krisgesling** [comment]
Ah I just realised this PR is made against the 18.08 branch again. We've had a few coming in like this recently and I haven't yet been able to track down what's causing it.

Are you running 19.02 locally?

We've also replaced msk's upload and update with just `msk submit /opt/mycroft/skills/your-skill`
Is that what you've been using already?

**Comment by builderjer** [comment]
@krisgesling thank you for being so responsive.  Yes, I have been running 19.2, but I used msm update to submit my skill..  I just resubmitted using the suggested msm submit.  I guess we will see how that one goes.

**Comment by builderjer** [comment]
It still is going against 18.2.  Maybe I will try a different name and resubmit that way.  I think it will create a new PR though won't it?

**Comment by builderjer** [comment]
@krisgesling, I ended up doing a fresh clone of mycroft-core, running ./dev_setup, and then mycroft-msk submit moviemaster.  The name has changed and the new PR is [https://github.com/MycroftAI/mycroft-skills/pull/926](url).

I will close this PR

Thank You

**Pull request closed without merging**
