### PR TITLE
Add national-parks

### PR DESCRIPTION
**Pull request by richhowley**
## Info

This PR adds the new skill, [national-parks](https://github.com/richhowley/national-parks-skill), to the skills repo.

## Description

Get listings of us national parks by state, have mycroft read descriptions of national parks and even test your knowledge of where national parks are located.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Review by KathyReid — CHANGES_REQUESTED** [review]
### Meta

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.8.5 stable
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Wed 14 Nov 22:57:25 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> Check that voice install correctly transcribes the name of the Skill
`~~~~ __main__:handle_utterance:61 - INFO - Utterance: ['install national parks']`
> This is a new Skill, it won't be available for voice install, using manual install
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/richhowley/national-parks-skill
INFO - Downloading skill: https://github.com/richhowley/national-parks-skill
INFO - Successfully installed national-parks-skill
```
=> installed without error

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all the `dialog` files through `mimic` -> they all sounded good

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Looked through Intents, there shouldn't be any Intent collisions. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

>  Looked through the `regex`, they're using match all (*) which may match _more_ than intended, but I will test this functionally. 

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> README looks good, primary category defined. 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> No requirements defined, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> `settingsmeta.json` not used, no user-defined settings

### Code checks

* Inline documentation - is the code documented in line?
> Well documented; this Skill is very well structured

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> No libraries used, this hits an API

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a not required

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> failures are handled gracefully

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes, autotests pass

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

_NOTE: We do not enforce PEP8 Checks on Skills_

### Functional tests

* `Hey Mycroft, list national parks in Utah`
> correct listing of national parks in Utah

* `Hey Mycroft, list national parks in Missouri`
> correct listing of national parks in utah

* `Hey Mycroft, describe Yellowstone national park`
> correct info for Yellowstone

* `Hey Mycroft, quiz me on national parks`
> good use of questions, answer response working well

### Summary

Thanks so much @richhowley for taking the time to create this Skill. You've clearly put a lot of thought and effort into this Skill, and we really appreciate it. 

Before we can accept this into the `mycroft-skills` repo there are some aspects that we should work through. 

* License - Please choose an appropriate License for your repo - we suggest Apache 2 or GPL
* The API key for the National Parks API is hard coded into your Skill - which means that anyone using your Skill is essentially using your API key. It's likely that there is some form of rate limit on this API key so if lots of people use the Skill, it's going to hit the API limit. What I'd suggest here instead is using `settingsmeta.json` to have a user-configurable value for the API key. This means that each Skill user would need their own API key for the National Parks API; but this is a better way of architecting the Skill and avoiding rate limiting.

**Comment by richhowley** [comment]
Hello @KathyReid, thanks for taking the time to review my skill.  

I have made the two requested changes: 

* the skill now requires an API key entered through settings 
* GNU license was added.

The readme file was also updated to explain the API key requirement.

You may use my API key listed below for testing.  Requests are limited to 1,000 per hour and there are no costs involved (exceeding the limit only causes a 1 hour timeout).

> k9RwPfwCIelpFrKpVWL04jR6BnUgzfQggFjjtdgB

**Comment by KathyReid** [comment]
Thank you so much for the edits, @richhowley!
Looks fantastic :+1:, merging!

**Comment by richhowley** [comment]
I don't what happened but the repo merged to the Mycroft skills repo is a full 11 commits behind my repo and does not include the changes made to get the skill approved.

I was going to try to use msk to fix this myself but now if I use msm to install the skill from my own repo it also installs an old version.

Please help.

**Comment by KathyReid** [comment]
Ah no trouble at all. 

So, the easiest way to do this is to use `msk upgrade`. Just run this from where you have your Skill installed, this will usually be in `/opt/mycroft/skills`; 

```bash
msk upgrade .
```

The `msk` script will use the GitHub API to create a new PR with the new commits. 

https://mycroft.ai/documentation/skills/msk/

**Comment by richhowley** [comment]
Does this assume that the local repo is in /opt/mycroft/skills?

My local repo is on my Mac, maybe I need to clone it on the RPI?

Since msm installs the version that is on Mycroft skills repo, even though I pass it my github URL, the wrong files are in /opt/mycrfot/skills.

I tried downloading the files from my github repo and copying them to the RPI then running msk upgrade but it seems to not have worked, below is the traceback.  Sorry to bother you with this but I feel if I keep trying to fix it I’ll messing things up even worse.


Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 882 bytes | 0 bytes/s, done.
Total 3 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: 
remote: Create a pull request for 'upgrade-national-park' on GitHub by visiting:
remote:      https://github.com/richhowley/mycroft-skills/pull/new/upgrade-national-park
remote: 
To https://github.com/richhowley/mycroft-skills
 * [new branch]      upgrade-national-park -> upgrade-national-park
Branch upgrade-national-park set up to track remote branch upgrade-national-park from fork.
Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/bin/msk", line 11, in <module>
    sys.exit(main())
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/msk/__main__.py", line 67, in main
    return console_actions[args.action](args).perform()
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/msk/actions/upgrade.py", line 80, in perform
    title, body = self.create_pr_message(self.skill.git, self.skill.hub)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/msk/actions/upgrade.py", line 70, in create_pr_message
    ).split('\n')
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/msk/actions/upgrade.py", line 68, in <genexpr>
    for sha in skill_git.rev_list(
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git show --format=%s -s 
  stderr: 'fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]''

**Comment by richhowley** [comment]
Ignore above - was able to create new pull request #663.

**Pull request merged**
