### PR TITLE
Upgrade picroft-google-aiy-voicekit

### PR DESCRIPTION
**Pull request by andlo**
'This upgrades picroft-google-aiy-voicekit to include the following new commits:

 - [Code cleanup](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/380021e735b7bbbd96a5a4f4bd1ad5c26c2b85b0)
 - [added info about install_AIY.sh](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/47fb569be82700a8f9fce39df5e83c84eb3736aa)
 - [small change](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/b6c6d929ab8311c85c96e0b5039184d5ddc92917)
 - [Added script to help intlalling the kit, as the skillonly uses the kit.](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/235771915531f67e7061eb17072e302df5ced22d)
 - [... Merge branch 'master' of https://github.com/andlo/picroft-google-aiy-voicekit-skill](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/25ec71983054bc3328ae6bb65da8e1cad2aa378c)
 - [small error correction](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/38ea62ec34c3cd8e6dcf250838c4eff7ebd7f9b3)
 - [added german translation](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/2027e6cb0991d250dccd0c4cdc094b74d9d0aab5)
 - [Merge branch 'master' of https://github.com/andlo/picroft-google-aiy-voicekit-skill](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/4a4c04d0f8f9370fbc6f12adeb2cb904c140caf5)
 - [Merge pull request #7 from KathyReid/patch-1](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/3714a31df047dbeb9f2cda322891eabe5d34dc5e)
 - [Update error.initialize.dialog](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/1fb697b4d85f372e85981de2aa941fc6bbc9cd6f)
 - [Merge pull request #6 from andlo/Dev](https://github.com/andlo/picroft-google-aiy-voicekit-skill/commit/030e785276829a048128391b9808007260ad3abb)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by andlo** [comment]
Hmmm I wondr why Skill tester failed…..Did I do something wrong? The skill does install OK, but maybe the skilltester fails becase of missing rpi.GPIO ?

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
The credentials for the server had been invalidated causing these issues. Probably a dual usage issue. I'll be looking into it...

In other news, your tests have passed :)

**Comment by KathyReid** [comment]
Hey @andlo, have these changes been vetted / validated by the Community at all?

**Comment by andlo** [comment]
No validatioN from comunity - shall I ask for a skill reviev for the update ?

**Comment by KathyReid** [comment]
The Community is validating this at; 
https://community.mycroft.ai/t/update-to-picroft-google-aiy-voicekit-skill-feedback/5
Awaiting Community validation

**Comment by KathyReid** [comment]
Hi @andlo - how are the Community going with validating this one?

**Comment by andlo** [comment]
hej @KathyReid 
Got one to tell that it is working :) There were issues regarding how to installand test - msm install githhub repo did not install the latest version as we talked about on Matermost. 
But after I got hin to git clone - it went smooth.

And ofcause it shold, as there isnt changet anything in the code - ecept the small bug :)

**Comment by KathyReid** [comment]
No problem, I'm going to merge this request then :-) 
Thank you so much for all your efforts in keeping this Skill up to date - we really appreciate it. 
Best, Kathy

**Comment by andlo** [comment]
It is me that say thanks. I have been workong whith computers for ever, and everytime I had an idea, someone alreddy had made it :) and suddently there is something that I can make hat isnt made before :) and in a good comynity where right helt is when needed.

**Comment by el-tocino** [comment]
I'll try and upgrade this later tonight locally.

**Pull request merged**
