### PR TITLE
Add emby

### PR DESCRIPTION
**Pull request by rickyphewitt**
## Info

This PR adds the new skill, [emby](https://github.com/rickyphewitt/emby-skill), to the skills repo.

## Description

about

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Hi @rickyphewitt, as part of our [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/), if a Skill uses a third party piece of software, what we ask is that you get someone in the Community who uses that third party software or hardware to "vouch" for the Skill. 
You can ask for Skills to be vouched at; 
* https://community.mycroft.ai/c/skill-feedback
* https://chat.mycroft.ai/community/channels/skills

**Comment by rickyphewitt** [comment]
Will do!

**Comment by LinusSkucas** [comment]
@KathyReid I have tested this skill and can “vouch” for this skill. It works very well! [Discussion in the forums](
https://community.mycroft.ai/t/testing-and-feedback-for-emby-skill/4672)

**Comment by KathyReid** [comment]
## Skills acceptance process for `emby-skill`


### Validation
This Skill was validated by @LinusS1 and is documented here; 
https://community.mycroft.ai/t/testing-and-feedback-for-emby-skill/4672/6

As a side note, the instructions for installing this posted in the Forum were really well written, thank you. 

Now running standard non-functional checks. 

### Standard checks

* Platform: Mycroft for Linux, Ubuntu 18.04 LTS
* Device version: 18.02.2
* Who: @KathyReid / @kathy-mycroft
* Datestamp: Thu  4 Oct 23:11:06 AEST 2018
* Language and dialect of tester: Native English speaker, Australian accent

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is a new Skill, so it's not yet available for voice install. using manual install. 

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/rickyphewitt/emby-skill
INFO - Downloading skill: https://github.com/rickyphewitt/emby-skill
INFO - Installing requirements.txt for emby-skill
INFO - Successfully installed emby-skill
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ ls -las /opt/mycroft/skills/emby-skill.rickyphewitt/
total 56
4 drwxr-xr-x  6 kathyreid kathyreid 4096 Oct  4 23:13 .
4 drwxr-xr-x 36 kathyreid kathyreid 4096 Oct  4 23:13 ..
4 drwxr-xr-x  3 kathyreid kathyreid 4096 Oct  4 23:13 dialog
8 -rw-r--r--  1 kathyreid kathyreid 4809 Oct  4 23:13 emby_client.py
4 -rw-r--r--  1 kathyreid kathyreid 2678 Oct  4 23:13 emby_croft.py
4 drwxr-xr-x  8 kathyreid kathyreid 4096 Oct  4 23:13 .git
4 -rw-r--r--  1 kathyreid kathyreid   63 Oct  4 23:13 .gitignore
4 -rw-r--r--  1 kathyreid kathyreid 1500 Oct  4 23:13 __init__.py
4 -rw-r--r--  1 kathyreid kathyreid 1527 Oct  4 23:13 README.md
4 -rw-r--r--  1 kathyreid kathyreid    8 Oct  4 23:13 requirements.txt
4 -rw-r--r--  1 kathyreid kathyreid 1491 Oct  4 23:13 settingsmeta.json
4 drwxr-xr-x  4 kathyreid kathyreid 4096 Oct  4 23:13 test
4 drwxr-xr-x  3 kathyreid kathyreid 4096 Oct  4 23:13 vocab
```
=> installed successfully

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran `emby.dialog` through `mimic` => all good

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Because this uses the Play keyword, this keyword is heavily loaded - ie news, other media players and so on. Generally p[eople will only use one media player - ie Supersonic, emby, Spotify and so on, so this _may not_ be an issue, but it might be. @penrods is working on a new confidence-framework for Intents with the Play framework. I'm not going to hold this Skill back because it uses the Play keyword, but it's something to be aware of. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README looks good

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> Looks sensible

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> checked how this rendered on home.mycroft.ai => rendered well, fields have sensible names

### Python code checks of the Skill

* Inline documentation - is the code documented in line?

> some, but the Skill is straightforward, doesn't need a lot of documentation

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> deps are straightforward

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> not required

* Error handling - are there any specific checks we make for error handling or graceful degradation?

> Error handling is fine

* Automatic tests - do automatic tests of the **Skill** pass?

> Yes, autotester passes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> Not used

## Summary

Has been validated by another Community member, passes standard checks, merging.

**Pull request merged**
