### PR TITLE
Add tmdb-skill

### PR DESCRIPTION
**Pull request by builderjer**
## Info

This PR adds the new skill, [tmdb-skill](https://github.com/builderjer/tmdb-skill), to the skills repo.

## Description

Uses the TMDb api to call information about movies, actors, production companies and the like.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by builderjer** [comment]
The error does not seem to be associated with my skill, but with the carstena-the-cows-lists.carstenagerskov

Any input on this skill would be great!!

**Comment by krisgesling** [comment]
Hi builderjer, 

This PR seems to have pulled in some other commits. Are you using the Mycroft Skills Kit aka `mycroft-msk submit` command to create the PR or doing it manually?

If you haven't seen it, this makes generating PR's much simpler as it automagically handles all the git submodule mayhem. Just enter:
`mycroft-msk submit /path/to/your/skill`
and MSK will handle the rest :)

Best to close this PR first, and generate a fresh one. Though if that's how you generated this PR let us know as it shouldn't be pulling in those other commits.

**Comment by builderjer** [comment]
yes, I have been using msk to submit this skill.  I think what happened is when Mycroft updated to 19.2, it made a new PR, and I didn't delete the old one.  I hope this one works for you.  Please let me know if there is any thing that I need to add or remove.  Thank you

**Comment by krisgesling** [comment]
New PR #926

**Pull request closed without merging**
