### PR TITLE
Add remember

### PR DESCRIPTION
**Pull request by LinusSkucas**
## Info

This PR adds the new skill, [remember](https://github.com/LinusS1/remember-skill), to the skills repo.

## Description
With this skill, Mycroft will be able to remember thoughts for you. You will then be able to ask Mycroft to tell you want you were thinking about.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by LinusS1** [comment]
Not sure what went wrong with the test.
Could someone help me?

**Comment by penrods** [comment]
Hmm, looks like this is an issue with the testing infrastructure itself.  We'll look in to it and get back to you in a few days.   I don't see anything obvious wrong that you need to address.

However, I would ask you to get rid of the empty requirements.txt and requirements.sh files.  No need to have them around.

**Comment by LinusS1** [comment]
I deleted the files. Not sure how to update the PR, though...

**Comment by KathyReid** [comment]
Hi there @LinusS1 - the [Mycroft Skills Kit]() helped with doing the PR the first time around. To update the PR now that you've removed the empty files (thank you!), use `msk` like this: 

```
msk upgrade SKILL_FOLDER
```
Can you please let me know how you go?

**Comment by LinusS1** [comment]
@KathyReid I’m getting an error when upgrading the skill:
`NotUploaded: The skill remember-skill has not yet been uploaded to the skill store`

**Comment by MatthewScholefield** [comment]
@LinusS1 I actually thing for skills being uploaded for the first time, you have to rerun the same command which would be:
```
msk upload SKILL_FOLDER
```
Making sure to enter the same skill name etc.

**Comment by LinusS1** [comment]
Okay. I’ve uploaded and added that to the pull request.
The test is still failing though...

**Comment by LinusS1** [comment]
@KathyReid do you have a status update on this PR?

**Comment by forslund** [comment]
Hi Linus, the failure here could be related to the regex you're using. It matches anything and adapt currently doesn't handle these cases very well since it generates a whole bunch of matches and upsets the scoring/selection of all regexes. Maybe you can make it a bit more precise with something like

`(that|to) (?P<Thought>.*)`

which should match anything with a "remember that " or a "remember to"

**Comment by LinusS1** [comment]
@KathyReid the tests finally seem to be passing! 😃

**Comment by LinusS1** [comment]
Run test.

**Comment by LinusSkucas** [comment]
I am going to close this as I need to change a few things as to how the skill works and fix the tests.

**Pull request closed without merging**
