### PR TITLE
Upgrade emby

### LINKED ISSUE #6: mycroft - poetry skill
make poems/lyrics

### LINKED ISSUE #13: mycroft-skill - facebook
https://github.com/JarbasAI/mycroft-facebook-skill

work in progress but usable

### PR DESCRIPTION
**Pull request by rickyphewitt**
This upgrades emby to include the following new commits:

 - [Adding in mocks for intent integration tests](https://github.com/rickyphewitt/emby-skill/commit/fc094b23a2bdd62f48dc03c2b145143183eea6d5)
 - [Updating .dialog file name to match expected filename for integration tests](https://github.com/rickyphewitt/emby-skill/commit/a20900ff4728449b7753ef6cdb5c3139b24a1c4a)
 - [Adding diagnostic option](https://github.com/rickyphewitt/emby-skill/commit/e2b6d0aba3ca9bbda98374eca8a51861912125ab)
 - [fixing json to yaml setttingsmeta change](https://github.com/rickyphewitt/emby-skill/commit/53d9ce53848287e2e5918db95e7c850418eb0f75)
 - [Change to YAML](https://github.com/rickyphewitt/emby-skill/commit/b215b6d8fe4ac8c6908f0ef85b3cf6d2af515769)
 - [Adding additional logging for common play path](https://github.com/rickyphewitt/emby-skill/commit/8827f3535351e2ebb8e9e943015f17ec21a4f839)
 - [Updating intent test mocking](https://github.com/rickyphewitt/emby-skill/commit/94854e9b2dcba2795fc038a2ac71f2c40b3da2e3)
 - [Setting a default if host does not include a protocol (#32)](https://github.com/rickyphewitt/emby-skill/commit/2d81be10003dad6c8cfb427998b5940ce69f7244)
 - [Allow non-MP3 source files to get transcoded (#30)](https://github.com/rickyphewitt/emby-skill/commit/05438b21e664778037962c4b1a85e7846d06de33)
 - [Unable to load settings](https://github.com/rickyphewitt/emby-skill/commit/15d223c33327ad3d351131518da0018ea3184f3c)
 - [fixing spoken_name attribute error in common play path](https://github.com/rickyphewitt/emby-skill/commit/197b6b67c53a39e9e877124eca3aeffcbf06d94e)
 - [Adding unique device id(hashed) and versioning to emby client auth](https://github.com/rickyphewitt/emby-skill/commit/0d8102eaddbcba52296a2edb3a9916931e5e670a)
 - [Adding support for playing an album](https://github.com/rickyphewitt/emby-skill/commit/9213a8d084bcef58308a61d158d767b854ca3237)
 - [Adding play songs by artist support](https://github.com/rickyphewitt/emby-skill/commit/4f2dbc83f97ed8455b3116de6f4f676e7a05360e)
 - [CommonPlayFramework](https://github.com/rickyphewitt/emby-skill/commit/8fb3d68c4fc3bd1e05e6109acd10fe7e78cb8cf6)
 - [Update translations](https://github.com/rickyphewitt/emby-skill/commit/9fd37a2f383df01331f0569f4c3dd880a3053665)
 - [Update translations](https://github.com/rickyphewitt/emby-skill/commit/1be93e4721d0f7a5a44ecb5f469f0ea10e916afa)
 - [Moving the auth check to when the skill is invoked. This fixes #13](https://github.com/rickyphewitt/emby-skill/commit/5b103a5e3cb2fb1f18d9a079d66fada64b454b5b)
 - [Merge pull request #12 from devs-mycroft/translate-2018-12-31](https://github.com/rickyphewitt/emby-skill/commit/b2ef18306ac4f2917b5d7c784c1e6a24350f6b88)
 - [Update translations](https://github.com/rickyphewitt/emby-skill/commit/3ffc8657ed5d218606ee00fe0c43d04243d4ff98)
 - [Merge pull request #9 from rickyphewitt/dev](https://github.com/rickyphewitt/emby-skill/commit/f40ae61d3114b9e6066cd9500de706d70dd8098c)
 - [Updated mocked unit tests, used response.json() instead of json.loads()](https://github.com/rickyphewitt/emby-skill/commit/c88088077224ca4e7e19845e05730a1f6519c68f)
 - [Adding better 1st run experience, commit fixes #6](https://github.com/rickyphewitt/emby-skill/commit/a69e873ab4948828c824f3720f1541eaa4eca95c)
 - [Adding Travis CI support](https://github.com/rickyphewitt/emby-skill/commit/be0d5a72e8fa0916aebaf3b157d01eb70d5bfd1b)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by rickyphewitt** [comment]
It looks like the mycroft-msk submit pulled master instead of the local checked out branch I had. I have tested the minor additional changes, but this is not the same as the prior submission ( even though the list of changes in the above stop at the same commit) When viewing the files and commits included it does show more commits.Also it appears it didn't pass the skills testing so I'll take a look. Also looks like the msk tool can take a branch as a param so i'll look into submitting the skill again with the correct branch.

**Comment by rickyphewitt** [comment]
The mycroft-msk help appears to denote that the branch option is for setting the 'Branch of skills repo to upload to' and not specifying the branch of the skill.

**Comment by rickyphewitt** [comment]
And the error that is seen in jenkins I can repro locally so I'll look fixing that and update this PR when I've got a fix.

**Comment by krisgesling** [comment]
Thanks Ricky, 

Just flagging for myself that this is following on from #1071 

Let me know if you run into any trouble with the fixes. I'm a total Emby convert now :grinning:

**Comment by rickyphewitt** [comment]
Great to hear @krisgesling!

I hope to have some time this weekend to work on the test issues. Once I stated using Emby I havn't looked back. If you have any feature requests/recommendations on changes to the skill I"m all ears :)

**Comment by rickyphewitt** [comment]
@krisgesling,

I've updated the integration tests/mocks for them so now its passing :). The only real change that came in over the last merged version is that you can now check your connection to the emby server. This will hopefully be used to help users troubleshoot any config issues during setup.

**Comment by krisgesling** [comment]
Looks good, thanks Ricky!

These don't affect the running of the Skill at all, just noticed them:
- in `connect_to_emby` there's a typo in the `diagnostic` variable name, but it's consistent.
- my personal preference is to use keyword arguments when calling a method, particularly with a boolean eg `self.connect_to_emby(diagnostic=True)`. I find it gives readers of the code a little clue as to what is `True` about this particular call without having to jump to the function definition. I think this only relates to [line 65](https://github.com/rickyphewitt/emby-skill/blob/9363d25e8f5a7c00c2437939dd032d60960ebe18/__init__.py#L65)

Anyway, neither are necessary changes so merging this now :)

**Comment by krisgesling** [comment]
To provide a concise description of changes for promoting this update, is this list accurate?
- Added support for playing an album
- Added support for playing a shuffled list of all songs by an artist
- Updated to use the Common Play Framework allowing the Skill to operate nicely alongside other media Skills
- Improved experience during first use of the Skill
- Fixed loading of Skill settings
- Added default protocols to handle variations of host settings
- Added transcoding of non-MP3 source files
- Updated unit and integration tests

**Comment by rickyphewitt** [comment]
@krisgesling,

Thanks for noticing the type issue :face_with_head_bandage: I do agree with the keyword args sentiment and I'll make the change shortly so the next update into the skills repo has the fixes.

The concise description all looks good. Thanks for you help with this!

**Pull request merged**
