### PR TITLE
Upgrade mycroft-spelling

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-spelling to include the following new commits:

 - [Update test cases](https://github.com/MycroftAI/skill-spelling/commit/73a706b68e2ab6ace8d8789fddfdbc2534f759fd)
 - [Regex fix for spelling of the word FAVORITE_WORD](https://github.com/MycroftAI/skill-spelling/commit/0c667957edb8a563ba4c21c65fb450c41dee15c7)
 - [Merge pull request #19 from MycroftAI/bugfix/regex-fix](https://github.com/MycroftAI/skill-spelling/commit/cc32de54a56614f1884b8b7b69678a80568ee542)
 - [Fix for handling the new "the" from adapt](https://github.com/MycroftAI/skill-spelling/commit/444333bb0447ef459903386c421a8ff16c2346a2)
 - [Merge pull request #18 from devs-mycroft/translations](https://github.com/MycroftAI/skill-spelling/commit/3e49568d7f98f041672d30f33ef26a88c2e0b379)
 - [Update translations](https://github.com/MycroftAI/skill-spelling/commit/689840266af62dcc346db1631bf58da1bcfb27c9)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Having a problem with one utterance:
"spelling of the word aardvark"
returns
> T; H; E

Do you get the same?

**Comment by forslund** [comment]
No "spell the word aardwark" returns
`>> A; A; R; D; W; A; R; K`

I had some trouble initially and needed to restart the skills service for the regex update to take effect.

**Comment by krisgesling** [comment]
Yeah I got the same for "spell the word aardvark" and a restart resolved that, however it looked like the regex was also trying to match "spell**ing of** the word aardvark" which is still returning >> T; H; E

**Comment by forslund** [comment]
Oh sorry, I can read I promise...

Will add a test for that and see if I can improvify. Ett ögonblick...

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
I'm merging this since it's needed to upgrade the skill tester and it doesn't do anything worse. If you still have issues Gez I can rework it a bit more to make it more stable. There is a test case for your issue so it shouldn't be popping up...

**Pull request merged**
