### PR TITLE
Add email

### PR DESCRIPTION
**Pull request by LinusSkucas**
While I’m fixing my remember skill I decided to submit this one.
## Info

This PR adds the new skill, [email](https://github.com/LinusS1/email-skill), to the skills repo.

## Description

With this skill, Mycroft can check your email. When you ask him, he can list your new emails. He will say the sender and the subject of each email.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
@LinusS1 I am deliberately holding off on testing this Skill for a day or so - the Skills Team is meeting tomorrow and one of our topics is around the secure storage of credentials for thinks like IMAP and SMTP and I want to review your Skill submission _after_ we've had that discussion. 
Best, Kathy

**Comment by KathyReid** [comment]
Just a note to say that the Skills Team meeting didn't happen as expected today, we're rescheduling so I should have an update available in a few days, apologies for the delay.

**Comment by LinusSkucas** [comment]
Okay, thanks for the update

**Comment by KathyReid** [comment]
Skills Team met yesterday; we are comfortable storing credentials on home.mycroft.ai but have had some discussions about more mature ways to handle sensitive credentials, and applying encryption to credentials going forward. 

NEXT ACTION: Kathy to test this Skill as per Skills Acceptance Process and accept into 18.08 branch if passes Acceptance checks

**Review by KathyReid — CHANGES_REQUESTED** [review]
## Test of email Skill 

### Platform information

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.08.01
* Who: @kathyreid / @kathy-mycroft
* Datestamp `Tue 18 Sep 03:03:07 AEST 2018`
* Language and dialect of tester: English native speaker, Australian Accent

#### Review of `skill-name`

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> Skill is not yet in repository, so will not install via voice. Using `msm` to install. 

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/LinusS1/email-skill
INFO - Downloading skill: https://github.com/LinusS1/email-skill
INFO - Successfully installed email-skill
```

Checked to make sure that the Skill Settings were loaded into home.mycroft.ai successfully => Yes, the Skill Settings allowed me to enter in my email credentials. 

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran each of the `dialog` files through `mimic`. There was only one minor issue identified - in `setup.dialog` when the user is instructed to go to Mycroft.ai - the AI part is not spelled out as `A I` so is pronounced as "aye". 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> No intent conflict is likely

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README has been generated using README generator, looks good

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> not used, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Yes, this is well laid out

### Functional checks

* `Check my emails`
> This correctly checked my emails and read them back. However, I had about 250 unread in my Inbox, so it took a while to start reading. This Skill works better for smaller amounts of unread email, so I'd *recommend* that in future iterations you do a check for a lot of mail - say more than 10 unread - and only then read them out. 

But yes, functionally passing 

### Check code

* License check

> There is no LICENSE file - we usually recommend the Apache license, however you are free to choose whichever license best suits your purpose and allow sus to distribute the Skill. 

* Check for code commenting

> There aren't a lot of code comments, suggest adding commentary. 

* Check for graceful error handling 

> If IMAP server cannot be contacted, feedback is provided. 

--- 

Summary: requires license file before we can merge.

**Comment by LinusSkucas** [comment]
@KathyReid thanks for reviewing my skill.
I’ve changed:
 - [x] the dialog file
 - [x] added comments 
 - [x] added a license 
 - [x]  saying 10 emails then asking a question if the user wants to hear more.

I just realized that this pr would merge this skill into the 18.02 branch not the 18.08 branch. Should I change that?

Update: Not sure why the tests are failing. They work perfectly on my computer.

**Comment by KathyReid** [comment]
I've examined the Skills Tester output; the tests that are failing are not related to this Skill. 
Overriding Skills Tester and merging.

**Pull request merged**
