### PR TITLE
Add openhab-skill

### PR DESCRIPTION
**Pull request by mortommy**
## Info

This PR adds the new skill, [openhab-skill](https://github.com/mortommy/openhab-mycroft), to the skills repo.

## Description

This skill adds [openHAB](http://www.openhab.org/) support to [Mycroft](https://mycroft.ai).
The skill takes advantage of the openHAB REST API, so it works both with the v1.x and v2.x of openHAB.

In order to make openHAB Items accessible to Mycroft, they need to be [tagged](https://www.openhab.org/addons/integrations/homekit/).
Device names recognized by Mycroft are matched against openHAB Item Labels.

The above examples would all work with the following set of openHAB Item definitons:

```java
Color DiningroomLight "Diningroom Light" <light> (gKitchen) [ "Lighting" ] {channel="hue:0200:1:bloom1:color"}
Color KitchenLight "Kitchen Light" <light> (gKitchen) [ "Lighting" ] {channel="hue:0200:1:bloom1:color"}
Switch GoodNight "Good Night"	[ "Switchable" ]

Number MqttID1Temperature "Bedroom Temperature" <temperature> [ "CurrentTemperature" ] {mqtt="<[mosquitto:mysensors/SI/1/1/1/0/0:state:default]"}
Number MqttID1Humidity "Bedroom Humidity" [ "CurrentHumidity" ] {mqtt="<[mosquitto:mysensors/SI/1/0/1/0/1:state:default]"}

Group gThermostat "Main Thermostat" [ "gMainThermostat" ]
Number MainThermostatCurrentTemp "Main Thermostat Current Temperature" (gMainThermostat) [ "CurrentTemperature" ]
Number MainThermostatTargetTemperature "Main Thermostat Target Temperature" (gMainThermostat) [ "TargetTemperature" ]
String MainThermostatHeatingCoolingMode "Main Thermostat Heating/Cooling Mode" (gMainThermostat) [ "homekit:HeatingCoolingMode" ]
```

If items are modified in openHAB, a refresh in Mycroft is needed by the command:

- *"Hey Mycroft, refresh openhab items"*

If you've forgotten what items have been identified, you can ask Mycroft:
- *"Hey Mycroft, list openhab items"*

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
## Meta  
* Platform: Debian Linux
* Mycroft-core version: 19.8.4
* Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft  
* Datestamp: 2019-12-18_16:47_ACST  
* Language and dialect of tester: English, Australian accent

## 0. Automated tests  
Are all automated tests passing?  
- [x] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
_NOTE: We do not enforce PEP8 Checks on Skills_

> No security or stability concerns. The following are just suggestions to consider.
>
> Shift Skill settings fetching to initialize and modify the dialog if they aren't yet present. PR submitted.
>
> checkout the [`voc_match` method](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#mycroft.MycroftSkill.voc_match). This allows you to match against a `.voc` file and would remove the need for the replication of language. For example
> `if ((command == "set") or (command == "imposta") or (command == "setze") or (command == "pone")):`
> could be rewritten as:
> `if self.voc_match(command, 'Set'):`
> new vocab and new languages can then be added to your vocab directory without needing to modify the code.
>
> Alternatively for specific values, you can use the [`translate`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html?highlight=named#mycroft.MycroftSkill.translate) and [`translate_namedvalues`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html?highlight=named#mycroft.MycroftSkill.translate_namedvalues) methods. Will send an example PR.
>
> Should the `unitOfMeasure` for `infoType` of `status` be an empty string or the status keyword? Seems like English has one, and the other languages have the other.
>
> A logger is now provided with the MycroftSkill class so you can simplify these to `self.log.xxxx` if you wish. [Some new docs on this](https://mycroft-ai.gitbook.io/docs/skill-development/introduction/logging).


- [x] **Error Handling**  

- [x] **Appropriate Libraries**  

- [x] **Required Dependencies defined and install correctly**  

- [x] **Settings well laid out**  

- [ ] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test/intent` folder?

> No tests included.

- [x] **Other Files**

**Comment by krisgesling** [comment]
## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  

- [x] **Description**  

- [ ] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

_Action required: I don't believe that "Hey Mycroft, brighten kitchen" will trigger. Currently only "bright" is available as vocab for this intent handler. Please add this as vocab in the Skill or modify the example._

> Suggestion: Would recommend removing "Hey Mycroft" from each example. The first example in particular will get cut off on the card preview.


- [x] **Supported Devices**  

- [x] **Categories**  

- [x] **Tags**  

- [x] **License**  

> EPL v2.0 accepted by OSI and FSF as a free software license.

**Comment by krisgesling** [comment]
## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Working great: `mycroft-msm install https://github.com/openhab/openhab-mycroft`
>  
> Checking that STT transcribes correctly
> Utterance: ['install openhab']
> STT transcribing name perfectly.

- [x] **Settings**  
If skill includes a `settingsmeta` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

- [x] Skill Functions  
I did a quick setup of openHAB, added a few lights and interacted with them fine. However I'm going to defer the functional testing to the Community given there are already a number of people using the Skill.

## Summary  
Thanks for submitting this for inclusion in the Marketplace. It will be great to have it back in the official mix so we can encourage more people to use it.

The only required changes are to: 
- add one or more integration tests - I'll shoot through a PR with an example that you can use or not.
- handle "brighten" or change that in the list of examples.

Thanks for a great Skill, and for all your work on OpenHAB itself!

**Comment by mortommy** [comment]
> ## Meta
> * Platform: Debian Linux
> * Mycroft-core version: 19.8.4
> * Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft
> * Datestamp: 2019-12-18_16:47_ACST
> * Language and dialect of tester: English, Australian accent
> 
> ## 0. Automated tests
> Are all automated tests passing?
> 
> * [x]  Skill tester - Jenkins
> * [x]  Continuous Integration - Travis-CI
> 
> ## 1. Code Review - secure and stable
> * [x]  **Code Quality**
>   _NOTE: We do not enforce PEP8 Checks on Skills_
> 
> > No security or stability concerns. The following are just suggestions to consider.
> > Shift Skill settings fetching to initialize and modify the dialog if they aren't yet present. PR submitted.
> > checkout the [`voc_match` method](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html#mycroft.MycroftSkill.voc_match). This allows you to match against a `.voc` file and would remove the need for the replication of language. For example
> > `if ((command == "set") or (command == "imposta") or (command == "setze") or (command == "pone")):`
> > could be rewritten as:
> > `if self.voc_match(command, 'Set'):`
> > new vocab and new languages can then be added to your vocab directory without needing to modify the code.
> > Alternatively for specific values, you can use the [`translate`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html?highlight=named#mycroft.MycroftSkill.translate) and [`translate_namedvalues`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.html?highlight=named#mycroft.MycroftSkill.translate_namedvalues) methods. Will send an example PR.
> > Should the `unitOfMeasure` for `infoType` of `status` be an empty string or the status keyword? Seems like English has one, and the other languages have the other.
> > A logger is now provided with the MycroftSkill class so you can simplify these to `self.log.xxxx` if you wish. [Some new docs on this](https://mycroft-ai.gitbook.io/docs/skill-development/introduction/logging).
> 
> * [x]  **Error Handling**
> * [x]  **Appropriate Libraries**
> * [x]  **Required Dependencies defined and install correctly**
> * [x]  **Settings well laid out**
> * [ ]  **Integration Tests**
>   Does the skill include sufficient integration tests, included in the `test/intent` folder?
> 
> > No tests included.
> 
> * [x]  **Other Files**

Thank you! That's very useful!

**Comment by mortommy** [comment]
handle "brighten" or change that in the list of examples. -> Done: changed in the list of examples

**Comment by krisgesling** [comment]
Thanks Tommy, can you run `msk submit` again to update this PR?
If you have the helper commands on your $PATH this would be:
`mycroft-msk submit /opt/mycroft/skills/openhab-mycroft.openhab`

**Comment by mortommy** [comment]
Done

**Comment by krisgesling** [comment]
Looks great, glad the new localization methods were helpful :)

**Comment by krisgesling** [comment]
Hey Tommy, the commit referenced by the submodule doesn't appear to be on any branch in your repo. Did you pull this across to the main openhab repo and delete your branch or has the Mycroft Skills Kit done something funky?

To fix it we just need to replace the submodule to point at the right repo, however I'm keen to work out how it happened so we can prevent similar issues in the future.

**Comment by krisgesling** [comment]
This has been reverted, so when you get a chance if you can run `msk submit` again that would be great.

I checked in on MSK and it defaults to using the `origin` remote. So something to be mindful of if you are working across multiple remote repo's.

**Comment by mortommy** [comment]
Sorry for the issue. To avoid any problem, could be better to: delete the skill, download again from the correct repository, and run `msk submit`?

**Comment by krisgesling** [comment]
All good, I also thought I'd save you the trouble and generated a [new PR](https://github.com/MycroftAI/mycroft-skills/pull/1162) as long as you're ok with that?

Otherwise yeah I'd do a fresh clone just from the primary repo

**Pull request merged**
