### PR TITLE
Upgrade email-skill

### PR DESCRIPTION
**Pull request by LinusSkucas**
Email skill
---
Update

Changelog: 
Added many translations! 🎏
Fixed a local config getting issue 🐛
Made the card in the Mycroft home have color! 🌈
Added an enquire intent. Now you can say thing like: Do I have email from Bob? 🎉
Added a notification service: 📬
You can ask Mycroft to tell you of all emails
You can ask Mycroft to tell you to only tell you when you receive a email from a certain person.
You can tell Mycroft to stop notifying you of new emails 😄
Added/fixed so you can put all your email information in to the config file! 🗄
Added "prettiness" when reporting back emails. Now when report back Mycroft will say: 🔢
Your second email is .... Instead of number 1 is...
Note: this is only for English as it uses a module which only supports English.
Not a noticeable feature, but I've refactored init.py a lot ♻️

### CODE REVIEW

**Comment by LinusSkucas** [comment]
Has already gotten the info test in #848 
@krisgesling I've updated the skill so hopefully the auth works now.

**Comment by LinusSkucas** [comment]
Hi @krisgesling Just a little reminder on reviewing this one. This needs to be merged before the 19.08 release so the skill can continue working. The current version of the skill in the marketplace uses a depreciated feature that will be removed in 19.08. This update removes the need for the skill to use the depreciated feature.
Thanks,
Linus

**Comment by krisgesling** [comment]
Thanks for the bump Linus :)
I'll make some time for a full review, but a couple of quick things:
- Should [this line](https://github.com/LinusS1/email-skill/blob/e77b6fc64009db1c5af5378036404504d00b58d9/__init__.py#L84) be `self.account`?
- It looks like lines 94+ are improperly indented, need to bump them over to bring them back into the Skill Class.
- best not to include punctuation in your intent files - "check my email." is triggering but not without the period "check my email"

**Comment by krisgesling** [comment]
Also have you seen [`util.format.pronounce_number()`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.util.format.html?highlight=pronounce#mycroft.util.format.pronounce_number) might remove the need for `i_engine`

**Comment by krisgesling** [comment]
## Meta  
* Platform: Mark 1
* Mycroft-core version: 19.2.14
* Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft  
* Datestamp: 2019-08-26_14:19:46_UTC  
* Language and dialect of tester: English, Australian accent

## 0. Automated tests  
Are all automated tests passing?  
- [x] Skill tester - Jenkins  
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable  
- [ ] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

>
_Action required: Might need to double check [line 73](https://github.com/LinusS1/email-skill/blob/7b9c54c34851b2f1996939b88ec9639227346734/__init__.py#L73).  Should it be something like: `config = fs.open("email_conf.yml", "r").read()`
_Action required: Seems that [`self.folder = config.get("port")`](https://github.com/LinusS1/email-skill/blob/7b9c54c34851b2f1996939b88ec9639227346734/__init__.py#L78) should be `self.folder = config.get("folder")`.
The folder paramater currently isn't listed on the [config file page of the wiki](https://github.com/LinusS1/email-skill/wiki/Email-Security)_
Also just FYI:
- Saw that `_nice_number` is for speaking ordinals. This is coming to `pronounce_number`, but it's not merged yet.
- [line 192](https://github.com/LinusS1/email-skill/blob/7b9c54c34851b2f1996939b88ec9639227346734/__init__.py#L192) shouldn't need localizing, as `ask_yesno()` already checks for a range of localized "yes" or "no" like responses and returns "yes", "no", or the users response if it's neither.

- [x] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

- [x] **Settings**  
Is the `settingsmeta` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

- [x] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test` folder?

> Minimal but challenging Skill for tests.

- [x] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

- [x] **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> Good updates.

- [x] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

- [x] **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

- [x] **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

- [x] **Tags**  
Are listed tags appropriate for this Skill?

- [x] **License**  
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> Apache 2.0

## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method: `mycroft-msm -l install https://github.com/LinusS1/email-skill`
> Output:  
> ```  
> INFO - Downloading skill: https://github.com/linuss1/email-skill
> INFO - Reading from manifest.yml
> INFO - Installing system requirements...
> INFO - Installing requirements.txt for email-skill
> INFO - Successfully installed email-skill
> ```  
>  
> Checking that STT transcribes correctly:  install email skill
> ```  
>  msm.mycroft_skills_manager - INFO - Best match (1.0): email-skill by linuss1
> ```

- [x] **Settings**  
If skill includes a `settingsmeta` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> `stop.poll.emails.last.email.removed.dialog` - should maybe start with "I'm"
> `poll.emails.not.started.dialog` - typo = "nott"

## Summary  
Primarily just check lines 73 & 78 as mentioned up in the code review section. A few tiny dialog typo suggestions above. I will go through the intents tomorrow to double check it's all firing, but I haven't had problems with it before. Right now I need some sleep :zzz: 

Once you have completed any updates, you can update this pull request by running `mycroft-msk submit /path/to/skill/directory`

Thanks for updating such a quality Skill!!!!

**Comment by LinusSkucas** [comment]
Thanks for the review Gez!
I’ve fixed everything that you mentioned :)

**Comment by krisgesling** [comment]
#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

_Add settings to email_conf.yml_

- [x] **"Check my email"**

> Reads emails

- [x] **"Notify my of new email"**

>  I'm starting to look for new email
>  Do you want to hear your 3 emails

_Send email to account_

>  You have 1 new email, do you want to hear them
>  Your first email.. etc

_Mark all email read_

- [x] **"Do I have any new emails?"**

> There's no new email

- [x] **"Do not notify me of new email"**

> Alright, I'm not going to look for new email anymore

_Mark one email unread_

- [x] **"Do I have any new emails?"**

> Your first email is...

- [x] **"Do I have any email from Chris?"**

> The first email's...

_Remove local email config_

- [ ] **"Do I have any new emails?"**

> To set the email skill up....
> Throws errors


_Add remote config in skill settings_

- [x] **"Do I have any new emails?"**

> The first email's...


## Summary  
Working great once I get my password right :stuck_out_tongue: 

The failing integration test doesn't seem related to this Skill at all. I found one edge case that would be good to tidy up. 

Line 320 checks the len(new_emails) which can be None. Perhaps add a similar check to your other intents?
```
if not new_emails: 
    return`
``` 
Might also be worth testing `new_emails` at the start of `report_email()` to make sure it exists before attempting to enumerate the list._


Another suggestion that is not required, but up to you. For the `stop.intent`, I wonder if some additional utterances might be:
- stop email notifications
- stop notifying my of mail


Then we are good to merge!!

**Comment by LinusSkucas** [comment]
Alrighty, I fixed those. Thanks again, Gez!

**Pull request merged**
