### PR TITLE
Add Youtube-Player

### PR DESCRIPTION
**Pull request by AIIX**
## Info

This PR adds the new skill, [Youtube-Player](https://github.com/AIIX/youtube-skill), to the skills repo.

## Description

Play and Stream Youtube Videos

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Note to the Skill Testing Team - this Skill requires a Mark 2 or the GUI running in KDE Neon Unstable for the functional review.

**Comment by TREE-Ind** [comment]
# Meta

    Platform: KDE dev
    Mycroft-core version: Latest dev. version
    Who: @TREE-Ind
    Datestamp: run date +%Y-%m-%d_%H:%M:%S_%Z
    Language and dialect of tester: English

## 0. Automated tests

Are all automated tests passing?

[X] Skill tester – Jenkins
[X] Continuous Integration – Travis-CI

## 1. Code Review – secure and stable

[X] Code Quality
    Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
    NOTE: We do not enforce PEP8 Checks on Skills

[X] Error Handling
    Are there any specific checks we make for error handling or graceful degradation?

[X] Libraries
    Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

[X] Required Dependencies
    Check requirements.txt and requirements.sh – are the required dependencies listed? If requirements.sh is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a specific version is needed.

[X] Settings
    Is the settingsmeta file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called “Options << Name of section”. >
[X] Integration Tests
    Does the skill include sufficient integration tests, included in the test folder?

[ ] Other Files
    Are there any other files included that are unnecessary or you are unsure of their function?

Actions Required:
None

**Comment by TREE-Ind** [comment]
When starting the functional test there were errors with Gstreamer.  I had to install Gstreamer manually using apt, but once that was sorted the skill functioned as described.

@AIIX wondering how you want to proceed with this skill.  KDE 15.6.8 seemed to be missing some of the Gstreamer libraries required to run the skill properly.  Is the full Gstreamer package supposed to be included with KDE?  If not a requirements.sh may be needed to get the skill installed without extra user effort.

Great work overall as always :)

**Comment by AIIX** [comment]
> When starting the functional test there were errors with Gstreamer. I had to install Gstreamer manually using apt, but once that was sorted the skill functioned as described.
> 
> @AIIX wondering how you want to proceed with this skill. KDE 15.6.8 seemed to be missing some of the Gstreamer libraries required to run the skill properly. Is the full Gstreamer package supposed to be included with KDE? If not a requirements.sh may be needed to get the skill installed without extra user effort.
> 
> Great work overall as always :)

Gstreamer will be a requirement to play any audio/video on any platform running Mycroft-GUI especially with the newer Mycroft.AudioPlayer and Mycroft.VideoPlayer wrappers, rather than handling this per skill wise I'd like to see it as a part of Mycroft-GUI dependency and should be added there.

**Comment by krisgesling** [comment]
Hey @AIIX, apologies I missed that Josh also verified the functionality. 

The README looks good too, only thing we need is a license on the repo, then we can merge away :)

**Comment by AIIX** [comment]
> Hey @AIIX, apologies I missed that Josh also verified the functionality.
> 
> The README looks good too, only thing we need is a license on the repo, then we can merge away :)

License file has been added

**Comment by krisgesling** [comment]
Closing in favour of #1099

**Pull request closed without merging**
