### PR TITLE
Upgrade mycroft-npr-news

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-npr-news to include the following new commits:

 - [Merge pull request #82 from MycroftAI/bugfix/conf-none](https://github.com/MycroftAI/skill-npr-news/commit/2e8bf4d35f6d6e2380685a1d998e3deb76eb95a9)
 - [do not return any data on low-conf match](https://github.com/MycroftAI/skill-npr-news/commit/0bc6b4d688a8f80b121fde89e8ba28a264394697)
 - [change step vocab to avoid conflict](https://github.com/MycroftAI/skill-npr-news/commit/efde76167566ff2467ded7f0855ed7158a208134)
 - [Merge pull request #81 from MycroftAI/bugfix/temp-vk-test](https://github.com/MycroftAI/skill-npr-news/commit/9a9d02c6dc99a9022ebe01fb829ab2dd08a9acba)
 - [add pending vk test until included in core](https://github.com/MycroftAI/skill-npr-news/commit/9af0db59e6ec512110d3759f437309aa1ebed7c4)
 - [Merge pull request #80 from MycroftAI/bugfix/over-matching](https://github.com/MycroftAI/skill-npr-news/commit/d9ef95e84e9d5cd24ba7bb9c0c9b94b88da1a1ff)
 - [switch method for detecting audio service messages](https://github.com/MycroftAI/skill-npr-news/commit/8fb065b488e7864762b1d09ff7b6d4aa3f497a34)
 - [fix ask for specific station in normal intent](https://github.com/MycroftAI/skill-npr-news/commit/1aecc37f1bec783017bb3c2cda6bb3fd1cfff46b)
 - [fix news translation; add extra match type](https://github.com/MycroftAI/skill-npr-news/commit/51f172825f3edface3eed8f486a073282e891383)
 - [fix default station; tweak confidence levels](https://github.com/MycroftAI/skill-npr-news/commit/115d511060ad3038ac659d6aadf6dd2857becd7d)
 - [fix short utterances through common play](https://github.com/MycroftAI/skill-npr-news/commit/c0dd4ff2fd7bf7a5647a740e3b75f797640af925)
 - [update tests](https://github.com/MycroftAI/skill-npr-news/commit/0d0bf10a254765efa2fb6eeb469ccc53eab81c34)
 - [increase conf requirement; add extra match levels](https://github.com/MycroftAI/skill-npr-news/commit/9ff5bdf1f32d4fac1e4ccd8e75622eade27fc7c7)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1351))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1351))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1351))

**Comment by krisgesling** [comment]
Tests all passing, merging!

**Pull request merged**
