### PR TITLE
Add parrot

### PR DESCRIPTION
**Pull request by JarbasAl**
## Info

This PR adds the new skill, [parrot](https://github.com/JarbasAl/skill-parrot), to the skills repo.

## Description

about

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by JarbasAl** [comment]
same as https://github.com/MycroftAI/mycroft-skills/pull/603  , accidentally delete my fork of skills repo and can not update previous PR

**Review by KathyReid — COMMENTED** [review]
### Meta
* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.08.5 stable
* Who: @kathy-mycroft ? @kathyreid
* Datestamp: Wed 14 Nov 17:56:31 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> Check that voice installation will work 
`~~~~49.280 - __main__:handle_utterance:61 - INFO - Utterance: ['install parrot']`
> voice install understood OK. Because this is a new Skill, voice won't work, using `msm`
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/JarbasAl/skill-parrot
INFO - Downloading skill: https://github.com/JarbasAl/skill-parrot
INFO - Successfully installed skill-parrot
```
* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> there are no `vocab` or `dialog`, skipping check
                                    
* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Intents not used, skipping check

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> README looks good, primary category defined

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> No dependencies specified, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> `settingsmeta.json` not used, skipping check

### Python code checks of the Skill

* Inline documentation - is the code documented in line?
> Basic skill, inline documentation is good

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> no deps specified, skipping

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> check not required

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> basic skill, not required

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes, auto test is passed

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> Not required

_NOTE: We do not enforce PEP8 Checks on Skills_

### Functional check

I had a lot of problems using this Skill - I couldn't get Mycroft to recognise the Intent `start parrot` - it kept reconising my voice as `stop parrot`. Att'd is my Skills log, grepped for `parrot`. 

@JarbasAI - is this Skill working OK for you?

[parrot-skills.log](https://github.com/MycroftAI/mycroft-skills/files/2579614/parrot-skills.log)

**Comment by KathyReid** [comment]
G'day @JarbasAI, I'm not sure what to do with this Skill - I can't get it to function correctly with the `expect_answer()` functionality. Is there something else I should try?

**Comment by krisgesling** [comment]
Hi @JarbasAl, nice skill to illustrate the converse() method. 

I think it may be our Australian accents as I can get it to work if I make a really conscious effort to pronounce the 'R' in 'start'. I might see if some other community members can test this too just to make sure it's an Aussie thing.

I also saw you had some new commits to update the README and include "start parrot" in the intent file. Did you want to add those to this PR before it gets merged?

**Comment by krisgesling** [comment]
Hi Jarbas,

As with the other PR - I know you're super busy so not expecting you to get back to this skill now, but I'm going to close the PR for now as it is against the 18.08 branch. 

Whenever you're ready to do updates, just do the standard `mycroft-msk submit /opt/mycroft/skills/your-skill-directory` and MSK will generate a new PR against the latest branch.

Thanks

**Pull request closed without merging**
