### PR TITLE
Upgrade mycroft-installer

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-installer to include the following new commits:

 - [Add hide attribute to to_install / remove](https://github.com/MycroftAI/skill-installer/commit/b6166780d6097cb4f34939c918d759e7ee35c007)
 - [Add updated information for voice installations](https://github.com/MycroftAI/skill-installer/commit/5c52807ec1e252e152a0029b90c5b9368b228775)
 - [Add failure information](https://github.com/MycroftAI/skill-installer/commit/738da11ceeccc36180ab65604648fbe52351c818)
 - [Add safety around the skill-store installation](https://github.com/MycroftAI/skill-installer/commit/7c962dca780275111e0015c296a516d9b9698700)
 - [Add to_install and to_remove to the settingsmeta](https://github.com/MycroftAI/skill-installer/commit/34d3aec993f9fdc6cb2cf7ef567fdb28b63b04e3)
 - [Re-enable confirm dialog](https://github.com/MycroftAI/skill-installer/commit/9d3b782aed51073f6376bd2fc59c2655bf29f249)
 - [Add missing json import](https://github.com/MycroftAI/skill-installer/commit/b4b182220a94d58110a8255efef60210bbf27ae5)
 - [Merge pull request #42 from MycroftAI/simple-marketplace](https://github.com/MycroftAI/skill-installer/commit/ced818edf2b0085d066cd29b3ad790de236df9ec)
 - [install from to_install in settings](https://github.com/MycroftAI/skill-installer/commit/147418897b9be8b121e927bb6417236c1dfd18f3)
 - [Revert "Add market place support"](https://github.com/MycroftAI/skill-installer/commit/233f01b6ae0a9538775e4ae886528f5e7bb7c499)
 - [Merge pull request #41 from MycroftAI/feature/marketplace](https://github.com/MycroftAI/skill-installer/commit/15d89a5c67c9984211e039a72a7c44378ca4adee)
 - [Add market place support](https://github.com/MycroftAI/skill-installer/commit/104161da73017231845b36b314bd943571577c37)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
This is a default Skill, bumping to top of list for testing.

**Comment by KathyReid** [comment]
### Ensure I am on correct commit for testing

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-installer.mycroftai$ git log
commit 104161da73017231845b36b314bd943571577c37 (HEAD -> feature/marketplace, origin/feature/marketplace)
Author: Åke Forslund <ake.forslund@gmail.com>
Date:   Tue Oct 23 22:59:24 2018 +0200

    Add market place support
    
    - lock msm while doing changes
    - write skills manifest through msm
    - handle to_install and to_remove fields in settings
```

### test case for hide/remove attribute
> I'm not sure how to test for this, skipping test case

### test case for voice installations
* attempted to install crystal ball skill - `Hey Mycroft, install crystal ball`
> Sorry I don't understand (intent failure)
* tried with another phrase - `Hey Mycroft, install crystall ball skill`
> I don't understand, but I'm learning new things every day (intent failure)

**Question: Should the voice installation be failing like this, or is my test case wrong?**

### test case for add failure information
The only way I can think of to test for this is to try and install something from the Marketplace which doesn't work properly on say Linux. 
* I tried to install the AIY skill and it failed with 
```
polyfills.2f4a590….js:1 PUT https://market.mycroft.ai/api/skill/install 500 (INTERNAL SERVER ERROR)
```
in the Javascript console. 
So I'm not sure how to test for this use case without actually tailing the Selene logs (which I don't have access to)

### test case for add safety around the skill-store installation
I wasn't sure again how to test this; I _did_ check my `skills.log` to see if the previous test had written anything to the logs on my device, but it had not; 
```
kathyreid@kathyreid-Oryx-Pro:/var/log/mycroft$ cat skills.log | grep -i error | grep -i market
```
So, I'm not sure how to test this one as well. 

### Test case for re-enable confirm dialog
I _think_ this one is for when a Skill is being installed using voice, and Mycroft needs to confirm the Skill installation. To test this I tried to install a Skill using voice. 
* `Hey Mycroft, install piano bar`
> "I'm sorry, I don't understand" (intent failure)
So again I'm not sure how to test for this because the 'install' intent is failing

### test case for install from `to_install`
I _think_ I get what the Skill is trying to do here - the `to_install` is written to by the `marketplace` and then the Installer Skill handles the actual installation. So, let me try another Skill from the Marketplace and see if I can get it to install. 

I keep getting
`polyfills.2f4a590….js:1 PUT https://market.mycroft.ai/api/skill/install 500 (INTERNAL SERVER ERROR)`
Trying to install Skills from the Marketplace. 

### test Skills manifest
* Can't test this until I can get marketplace actually installing Skills

=> not comfortable merging this without a second opinion

**Comment by KathyReid** [comment]
Discussed with @forslund; I am going to merge, then we can hotfix if necessary. 
This is blocking installations from the [Mycroft Marketplace](https://market.mycroft.ai).

**Pull request merged**
