### PR TITLE
Upgrade mycroft-support-helper

### PR DESCRIPTION
**Pull request by forslund**
This upgrades mycroft-support-helper to include the following new commits:

 - [Merge pull request #29 from krisgesling/19.02](https://github.com/MycroftAI/skill-support/commit/0c854509a9077eb4baa01fa004f92270042e4064)
 - [Resolve SSL issue on Picroft](https://github.com/MycroftAI/skill-support/commit/3fc699749b9799e9869f12dff18d330d71359069)
 - [Mock ThreadedRecorder](https://github.com/MycroftAI/skill-support/commit/d5993fb7a73a9ee1e3deca7283d692a3683111a4)
 - [Merge pull request #27 from MycroftAI/bugfix/test](https://github.com/MycroftAI/skill-support/commit/4bb82b04516896c35bd4cb8d5eceabe295183b72)
 - [Remove mocking of subprocess](https://github.com/MycroftAI/skill-support/commit/4596f366e6beb842de51abfd0bb055ca18cdd5bd)
 - [Merge pull request #25 from MycroftAI/feature/stability](https://github.com/MycroftAI/skill-support/commit/86463db04e82f4fdb9d96d5cabbd25a982177c13)
 - [Use sample rate in configuration](https://github.com/MycroftAI/skill-support/commit/f3a45079f8ccb6bd828ea5446ca6250d1e0f06c2)
 - [Change archive format to zip It's more common](https://github.com/MycroftAI/skill-support/commit/c550cad008e4ba30063798a44b63c7c5b4aee417)
 - [Add audio recording and change service to 0x0 This changes to support package to an actual zip file containing all logs and a sample audio file The audio recording is used to debug microphone issues The service has been changed to 0x0.st since termbin only supports text and we now need to upload raw data](https://github.com/MycroftAI/skill-support/commit/3f5fc5b0f6fcecfadbbf092c2a00b4cbe2af01fe)
 - [Remove empty constructor](https://github.com/MycroftAI/skill-support/commit/fa6c4c576367bb50337403f0d1302a45467e921b)
 - [Add get_log_files method that looks for specific log files This check is in case something is wrong with the file listing the moment it is called so that it will still try to grab the essential logs](https://github.com/MycroftAI/skill-support/commit/950bf8ae2390e5a12001ded399555cbca557a6bc)
 - [Merge pull request #24 from devs-mycroft/translate-2019-01-27](https://github.com/MycroftAI/skill-support/commit/68f1f64483d96e689d6925b57ee439f180e541a1)
 - [Update translations](https://github.com/MycroftAI/skill-support/commit/0849cc4f746f053b927961e65c2324b5ba42046e)
 - [Merge pull request #23 from devs-mycroft/translate-2019-01-21](https://github.com/MycroftAI/skill-support/commit/a1ef75a0f4f35535b593477033efe3847e3efda0)
 - [Update translations](https://github.com/MycroftAI/skill-support/commit/7494abe80e907d2bbb0ca5bae213926b5240cc4d)
 - [Merge pull request #15 from MycroftAI/update-log-location](https://github.com/MycroftAI/skill-support/commit/a1e02a87344284a53a3fcd2d874640b865289f54)
 - [Merge pull request #19 from devs-mycroft/translate-2018-11-11](https://github.com/MycroftAI/skill-support/commit/ca0997ca23aeda10f9f772ba3e0240fd356399db)
 - [Merge pull request #21 from MycroftAI/bugfix/icon-404](https://github.com/MycroftAI/skill-support/commit/01b7d6e90a917b00603602743247d6c9c73c546b)
 - [Fix icon 404'ing](https://github.com/MycroftAI/skill-support/commit/d9508065b253ecd591eb1102f8bb682faec46d6b)
 - [Correct file path](https://github.com/MycroftAI/skill-support/commit/201a2fe83dd6020db0535f442e64eb407447de98)
 - [Correct the log paths that this Skill is looking for](https://github.com/MycroftAI/skill-support/commit/0b25cafe0c3d42818d4cffd23a696c45f04f64cf)
 - [Merge pull request #20 from devs-mycroft/translate-2018-12-31](https://github.com/MycroftAI/skill-support/commit/6670be4e2f7f881e43da0594a5d427cd9558d419)
 - [Update translations](https://github.com/MycroftAI/skill-support/commit/5121b2875dec8517ac786fb71b9cfcc562f01b41)
 - [Update translations](https://github.com/MycroftAI/skill-support/commit/31298a7d6b3689aef6137988f92105d08817a7b4)
 - [Merge pull request #18 from devs-mycroft/translate-2018-10-29](https://github.com/MycroftAI/skill-support/commit/0f6f54cc28bd3735196e79e98650996d7de59b66)
 - [Update translations](https://github.com/MycroftAI/skill-support/commit/25b5a3dc62b150b3e343d45ca2d6cfaf4323c799)
 - [Merge pull request #17 from MycroftAI/feature/update-readme](https://github.com/MycroftAI/skill-support/commit/7eddefdc33f51d53f959ff490e5a9f798def9abb)
 - [Update readme](https://github.com/MycroftAI/skill-support/commit/7f449e50ed78ba1165b51945b3f4859999910540)
 - [Merge pull request #16 from akuataja/patch-1](https://github.com/MycroftAI/skill-support/commit/938188ad1d7ba42dc9c1b2d70ffab2f858c8419d)
 - [Changed icon color to Mycroft orange](https://github.com/MycroftAI/skill-support/commit/3837d3529dff417c268444472714ffbc74da043e)
 - [Update __init__.py](https://github.com/MycroftAI/skill-support/commit/f4f4d12389e732cbabbc72b667f1960fa0d55e6e)
 - [Merge pull request #12 from MycroftAI/update-skill-meta-data-for-skill-store](https://github.com/MycroftAI/skill-support/commit/b2e586dad751a2565e7c2fef430b700ad2c887ee)
 - [Fix icon url](https://github.com/MycroftAI/skill-support/commit/3c69af614de796ec647a143de01fe328c68b19b6)
 - [Update README.md](https://github.com/MycroftAI/skill-support/commit/01480a4094d553a94cb4dd672ce9ff7f87fd0557)
 - [Create 18.08 branch](https://github.com/MycroftAI/skill-support/commit/ad82278279f1efb325ff6e4fdf3f8a6b527463c3)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 May 2019
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable  
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**  
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [x] **Description**  
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> yes

- [x] **Examples**  
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**  
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> no constraints listed

- [x] **Categories**  
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).  
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> Configuration

- [x] **Tags**  
Are listed tags appropriate for this Skill?

> support support-request help assistance logs troubleshooting system

- [x] **License**  
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> Apache-2.0

**Comment by krisgesling** [comment]
Looking great, and significantly better debug package. Have however run into two issues.

### Linux + Mark 1
On the first test on both Debian and a Mark 1 I got the same behaviour but haven't been able to replicate it.
Process
- install via `msm -l repo` 
- say "create a support ticket"
- get_response was triggered after the first sentence of the dialog ie "Would you like to create a troubleshooting package? *mic triggers* This will upload logs to the zero ex zero dot S T service and email a link to you with more information."
- This results in get_response not receiving a clear "yes" and abandoning. 

Subsequent attempts to create a support ticket proceed flawlessly. Even when uninstalling and reinstalling the Skill.

### Picroft
On a fresh Picroft install (starting with stable 2018-09 and upgrading to 19.2.12) failed with: 
`OSError: [Errno -9996] Invalid input device (no default output device)`
- Microphone immediately stopped working.
- The Picroft is using a PS Eye mic and headphones for output.
- All logs linked here, but I'll keep looking at this through the week.
  - audio.log - https://termbin.com/i4h7
  - bus.log - https://termbin.com/ccko
  - enclosure.log - https://termbin.com/9jry
  - skills.log - https://termbin.com/am9d
  - voice.log - https://termbin.com/troa5

**Comment by krisgesling** [comment]
Having another look at this it turns out the issue is the post request to 0x0.st failing with:

```
04:24:40.944 - mycroft.skills.core:wrapper:1083 - ERROR - An error occurred while processing a request in Support Skill
Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 849, in _validate_conn
    conn.connect()
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connection.py", line 356, in connect
    ssl_context=context)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/util/ssl_.py", line 359, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    _context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in __init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='0x0.st', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 1072, in wrapper
    handler()
  File "/opt/mycroft/skills/mycroft-support-helper.mycroftai/__init__.py", line 185, in troubleshoot
    url = self.upload_debug_package([audio_file])
  File "/opt/mycroft/skills/mycroft-support-helper.mycroftai/__init__.py", line 145, in upload_debug_package
    url = self.upload_file(package_fn)
  File "/opt/mycroft/skills/mycroft-support-helper.mycroftai/__init__.py", line 128, in upload_file
    r = requests.post('https://0x0.st', files={'file': f})
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='0x0.st', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:720)'),))
```


Same result after:
- updating `openssl` via apt.
- pip installing `requests[security]` - this added a few packages - cryptography, pyOpenSSL, asn1crypto, cffi, pycparser
- after reimaging the picroft - installing `python-requests` via apt 
- after reimaging the picroft - setting the environment variable REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt - [suggested here](https://github.com/mopidy/mopidy-gmusic/issues/103#issuecomment-160415798)

Any other ideas? Can anyone with a Picroft replicate this issue? 

Switching to `http://0x0.st` works without a problem.

**Comment by krisgesling** [comment]
So it works by installing `pyopenssl` without first updating openssl.

[Apparently](https://stackoverflow.com/a/29081240) Debian dropped SSLv3 support from OpenSSL and [urllib3 had to add a work around](https://github.com/urllib3/urllib3/commit/b9b3b0102ead7ad8ad086c39737f22ddefa7e626)

To validate on a Picroft run:
python -c "import requests; print(requests.get('https://0x0.st'))"
_should throw error_
Then in venv:
`pip install pyopenssl`
and rerun
`python -c "import requests; print(requests.get('https://0x0.st'))"`
> <Response [200]>

@forslund or @penrods - any objection to adding this in a requirements.txt?

**Comment by forslund** [comment]
That's a quick work-around. lets to it....It's weird that Picroft has this issue while the Jessie-based Mark-1 image has not since that issue was around in Debian 8...

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
Picroft did need a restart after installing `pyopenssl` however this should get installed on first boot and rarely change. I am also pretty confident that Picroft's get restarted much more regularly than Mark 1's, and if they haven't restarted the device before trying to solve the problem that's basically a mandatory first step!

Merging.

**Pull request merged**
