### PR TITLE
Fix Voight kampff runs of PR's from different repos

### PR DESCRIPTION
**Pull request by forslund**
Create a test branch on a test repo to handle non-local pullrequests

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1308))

**Comment by forslund** [comment]
Fix issue missed in review.

**Comment by devops-mycroft** [comment]
Your personal GitHub account is hardcoded in the Jenkinsfile as a result of this PR.  Is this leftover test code?

Chris Veilleux
Mycroft.AI <https://mycroft.ai/> | Software Architect | 816.550.6615 <tel:816-550-6615>
300 E. 39th Street, Kansas City, MO 64111

**Comment by forslund** [comment]
No it's as intended. Ut's the repo that's used for the older skills tester. It's kept on my account for simplicity and to keep the official repo clean from temporary branches.

**Pull request merged**
