### PR TITLE
Add today-in-history

### PR DESCRIPTION
**Pull request by austin-carnahan**
## Info

This PR adds the new skill, [today-in-history](https://github.com/austin-carnahan/days-in-history-skill), to the skills repo.

## Description

Provides historical events for today or any other calendar day using information pulled from [Wikipedia](https://www.wikipedia.org).

This Skill uses the [Wikimedia API](https://en.wikipedia.org/w/api.php).

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by el-tocino** [comment]
Do you need a specific version of wikipedia in requirements.txt?

**Comment by austin-carnahan** [comment]
@el-tocino, thanks for the feedback! wikipedia==1.4.0 is specified in the requirements.txt. I usually consider it best practice to pin 3rd party dependencies to specific versions. It's not a necessity, but since I can't guarantee the backwards compatibility of future versions of that package, this keeps an unexpected update from causing breaking changes.

That's my logic behind having it there, but this is my first time contributing to this project and I'd be happy to make any changes needed to conform to repo standards and styles

**Comment by krisgesling** [comment]
Hi again :)

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have push any updates in the meantime be sure to run `mycroft-msk submit /opt/mycroft/skills/your-skill-dir` to update this pull request. Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by austin-carnahan** [comment]
@krisgesling, hello again! Looking forward to the review process - if there are any improvements that need to be made, let me know and I'll be happy to implement them

**Comment by krisgesling** [comment]
Hey Austin, just taking a closer look at your Skill, nice one!

A couple of things:
1. Please delete the `settingsmeta.json` file. This is included in the template but if it's not needed should be deleted as it will add a settings block to the users Home.mycroft.ai/skills
2. Instead of a regex, you could use [`self.extract_datetime(utterance)`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.util.html?highlight=extract_datetime#extract-datetime) to see if any date or date-like strings exist. This will be more versatile than a regex and will also catch things like "tomorrow" or "historical events from July 1st". If it doesn't find anything it will return None and you could serve something for today, else it returns a datetime object, and the remainder of the string.
3. Just a suggestion, you can replace `robot` with `history`, `calendar-day` or [something else](https://fontawesome.com/icons?d=gallery) in the first line of your README to get a more relevant icon.

I'm getting a conflict on some utterances too, but I think it might be my own local edits. Will do some more testing tomorrow but wanted to send you the above.

Once you have made the necessary updates you can update this pull request by running MSK submit again. Most likely:
`mycroft-msk submit /opt/mycroft/skills/days-in-history-skill.austin-carnahan`

**Comment by krisgesling** [comment]
Yep disregard the intent conflict comment, it was a rogue Skill on my machine.

Just to clarify only number 1 above is required. Items 2 and 3 are up to you :)

We're also going to do a short freeze on Skills while we release the new Mycroft-core. So if you have a chance to do this by Friday we can sneak it in, otherwise it will be at least another week until we start merging Skills again.

**Comment by austin-carnahan** [comment]
Thanks for the feedback - especially the recommendation for `mycroft.util.extract_datetime`. Changes made and pushed above.

**Comment by krisgesling** [comment]
run test
This test failing is not your Skill, don't worry :)

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
Hey Austin, 
Test 002 seems to be failing. I think it's expecting the `Day` entity but this no longer exists.

**Comment by austin-carnahan** [comment]
@krisgesling  thanks again for all the feedback throughout this process - it's been great and really helpful! I fixed that broken test and updated. Let me know if there's anything else

**Comment by krisgesling** [comment]
Very happy to help, this all looks good now!

**Pull request merged**
