### PR TITLE
Add fallback-query

### PR DESCRIPTION
**Pull request by forslund**
## Info

This PR adds the new skill, [fallback-query](https://github.com/MycroftAI/skill-query), to the skills repo.

## Description

Negotiates handling of questions by calling all registered Common Query Skills. This is done by sending a `question:query` message with the utterance to give the skills the posibility to report back if they can answer the question and at which confidence.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by penrods** [comment]
run

**Comment by penrods** [comment]
run test

**Comment by penrods** [comment]
run test

**Comment by penrods** [comment]
run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Updated to include the Readme updates

**Pull request merged**
