### PR TITLE
Upgrade mycroft-configuration

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-configuration to include the following new commits:

 - [Merge pull request #29 from MycroftAI/refactor/remove-scheduled-skill](https://github.com/MycroftAI/skill-configuration/commit/9c312fadf4eba5db397f647871aaff299ba122cb)
 - [Replace ScheduledSkill with repeating event](https://github.com/MycroftAI/skill-configuration/commit/9801f2d114cc862a2dfc97ac4de37348eb53391d)
 - [Merge pull request #28 from MycroftAI/feature/swedish](https://github.com/MycroftAI/skill-configuration/commit/ce7c748f8e3b6f612b1506bf39a535690786f41d)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
This is a test upgrade, it should not be merged

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
Assigning to me, noting that this **should not** be merged.

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
hi @forslund should I close this PR?
Best, Kathy

**Comment by forslund** [comment]
Good idea! Closing

**Pull request closed without merging**
