### PR TITLE
Upgrade mbta-bus-tracking

### PR DESCRIPTION
**Pull request by richhowley**
This upgrades mbta-bus-tracking to include the following new commits:

 - [Add Voight Kampff test](https://github.com/richhowley/mbta-bus-tracking-skill/commit/17a2cef95570af060926dd9f0673a556f07812cd)
 - [re-work contexts](https://github.com/richhowley/mbta-bus-tracking-skill/commit/5215d6bd8bf9caf83f3600504baa02b7b54e58c5)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1610)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1610/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1610/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1610/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1610/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1610/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1610)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1610/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1610/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1610/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1610/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1610/logs/enclosure.log)

**Comment by richhowley** [comment]
Voight Kampff Integration Test Failed (Results)  link comes up 404. Passes locally, cannot figure out why it's marked as failing without seeing the results.

**Comment by richhowley** [comment]
run test

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1610)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1610/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1610/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1610/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1610/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1610/logs/enclosure.log)

**Comment by richhowley** [comment]
When I run the test runner locally I get:

> 1 feature passed, 0 failed, 0 skipped
1 scenario passed, 0 failed, 0 skipped
9 steps passed, 0 failed, 0 skipped, 0 undefined
Took 0m23.015s

When I click the Details link under "All checks have failed" I see errors in docker build:

> ERROR: python-coveralls 2.9.1 has requirement coverage==4.0.3, but you'll have coverage 4.5.4 which is incompatible.

and docker run:

> Unable to find image 'voight-kampff-skill:PR-1610' locally docker: Error response from daemon: pull access denied for voight-kampff-skill, repository does not exist or may require 'docker login': denied: requested access to the resource is denied. See 'docker run --help'.

and Extended email:

> Warning: github@gpll.org is not a recognized user, but sending mail anyway
> 
> Warning: cleese@monty.com is not a recognized user, but sending mail anyway
> 
> Warning: github@gpll.org is not a recognized user, but sending mail anyway
> 
> Sending email to: dev@mycroft.ai github@gpll.org cleese@monty.com
> 
> script returned exit code 1

As near as I can tell the Voight Kampff test was not even run. I could be wrong about that, it's not very clear to me what all this means but under the Tests tab is says "There are no tests archived for this run". Is there a way for me to fix docker errors? 

Also, it it still valid to type "run test" in the github conversation for the new test system? I tried it but it just gives me a 404 link.

**Comment by krisgesling** [comment]
Hey Rich, sorry I was away last week. From a glance it looks like bad credentials have been cached in our Jenkins instance. I'll try clear these out and see if we can get it unstuck.

Edit: no we don't use the "run test" command at the moment - but should probably add it to the new system.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1610)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1610/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1610/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1610/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1610/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1610/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1610))

**Review by krisgesling — APPROVED** [review]
Huzzah :tada:

Thanks for the update - and nice work splitting out the API code too

**Comment by richhowley** [comment]
Thanks so much Kris.

**Pull request merged**
