### PR TITLE
Add podcast-skill

### PR DESCRIPTION
**Pull request by JamesPoole**
## Info

This PR adds the new skill, [podcast-skill](https://github.com/JamesPoole/podcast-skill), to the skills repo.

## Description

Select your favourite podcasts in the home.mycroft.ai settings and listen to episodes from those podcasts.
You can also check with Mycroft if there are any new episodes available from your chosen podcasts.

You can now also scroll through all episodes of your chosen podcasts.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
@forslund when you have a moment, not urgent, could I get some assistance figuring out why one of the tests is failing for this Skill? 
https://jenkins.mycroft.team/job/18.08-skill-tester/198/console
Each of the Podcasts should have a "new episode", so I don't understand why the assertions are failing.

**Comment by forslund** [comment]
I've just had a quick look and it seems like the common play framework is triggered but doesn't resolve the podcast skill.

**Comment by KathyReid** [comment]
I'm checking internally to see how we can bake `CommonPlay` support into this Skill :+1:

**Comment by KathyReid** [comment]
Hi @JamesPoole just a quick note to say that we now have documentation available on the `Common Play Framework` and how to construct a **Skill** to take advantage of the Framework. In order to use the `play` keyword in an `Intent`, the Skill will need to be altered slightly to use the `Common Play Framework`. 

I also apologize for this rework as well - we're still "changing the ground" a little bit with some of these things.

**Comment by JamesPoole** [comment]
@KathyReid Checking out the documentation and working on this now! Will keep ye posted. :)

**Comment by KathyReid** [comment]
Awesomeness ;-)

**Comment by KathyReid** [comment]
Hi @JamesPoole just checking in to see how you went with this one?

**Comment by KathyReid** [comment]
Hi @JamesPoole just checking in to see how you went with this one?

**Comment by krisgesling** [comment]
Hi @JamesPoole, I've taken over from Kathy and wanted to introduce myself in case you had any questions about the new `Common Play Framework` that we could help with?

Having the framework change is one of the unfortunate challenges of working on things while they are still in heavy development, but it's a great skill so I hope we can get it up in the Marketplace sometime.

Please let me know if there's any way we can help :slightly_smiling_face:

**Comment by krisgesling** [comment]
Hi @JamesPoole, I wanted to check in and see how you were going. Is this a Skill you'd be interested in getting support from the broader Community on? 

I know podcasts are a pretty popular use case for voice assistants, so I think there would be interest from the community in helping out if you're open to receiving pull requests. Let me know what you think.

**Comment by JamesPoole** [comment]
@krisgesling Apologies for my lack of contact on this. I wish I could give this more time but I just don't have the time to give this the proper attention. I can close out the request for now and when I get a chance to get this up to date with the current frameworks, I will resubmit it!

**Comment by krisgesling** [comment]
No worries at all, I know how life is!!

@domcross has also said he might take a look :slightly_smiling_face:

**Comment by domcross** [comment]
I already implemented basic CommonPlay support and I only need to add fuzzy matching for podcast names. PR is coming soon...

**Comment by domcross** [comment]
@krisgesling & @JamesPoole 
please look into my [PR](https://github.com/JamesPoole/podcast-skill/pull/8) at James' podcast-skill repository.

**Comment by penrods** [comment]
@krisgesling, would it make sense for us to offer services of the [Community Skills Taskforce](https://github.com/orgs/MycroftAI/teams/community-skill-taskforce) to @JamesPoole for things like this?  I.e. James could potentially allow read/write access to that team and then they can pull in PRs on his behalf.  This, of course, would require your consent, James, and then some involvement from that team.

**Pull request closed without merging**
