### PR TITLE
Add animal-sounds

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [animal-sounds](https://github.com/krisgesling/animal-sounds-skill), to the skills repo.

## Description

Learn what sounds different animals make. A fun skill for the little ones.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1418))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1418))

**Comment by krisgesling** [comment]
This is a test PR for CI jobs.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1418))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1418)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1418/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1418/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1418/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1418/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1418/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1418)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1418/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1418/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1418/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1418/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1418/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1418)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1418/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1418/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1418/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1418/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1418/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1418))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1418))

**Pull request closed without merging**
