### PR TITLE
Add horoscope

### PR DESCRIPTION
**Pull request by samhithatarra**
## Info

This PR adds the new skill, [horoscope](https://github.com/samhithatarra/horoscope-skill), to the skills repo.

## Description

The user can ask about the horoscope for a particular zodiac sign and will recieve the prediction for that day.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1315))

**Comment by krisgesling** [comment]
Hi Samhitha,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by samhithatarra** [comment]
Hello!
I was just wondering on the status of my skill being accepted? Is there any
other information you need from me?

Regards,
Samhitha Tarra

**Comment by krisgesling** [comment]
Hi Samhitha, 

Sorry for the slow response, we're down some team members right now so Skill approvals have had to be de-prioritized for the moment. I've given a bump to our Community Skill Testing Team to see if someone has time to take a look.

Thanks

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
