### PR TITLE
Add iss-tracker

### PR DESCRIPTION
**Pull request by andlo**
## Info

This PR adds the new skill, [iss-tracker](https://github.com/andlo/iss-tracker-skill), to the skills repo.

## Description

This skill allows mycroft to tell you where the International Space Station (ISS) is in orbit, realtive
to the earth in latitude and longitude. it uses reverse geocoding to translate these coordinates
into the country or body of water it is over.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
Run test

**Comment by krisgesling** [comment]
## Meta

*   Platform: Linux - Debian Buster
*   Device version: 18.8.11
*   Who: [@KrisGesling](https://github.com/KrisGesling) / @gez-mycroft
*   Datestamp: 2019-01-24_11:02:12_ACST
*   Language and dialect of tester: Native English speaker, Australian accent

## Standard checks

*   Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This is the first time the Skill has been submitted; not available for voice install.
> Checking that STT transcribes correctly;
> `__main__:handle_utterance:62 - INFO - Utterance: ['install iss tracker']`  
> Using `msm install`

```
(.venv) kris@bigBench:~/mycroft-core$ msm install https://github.com/andlo/iss-tracker-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/andlo/iss-tracker-skill
INFO - Successfully installed iss-tracker-skill
```

_Successfully installed_

*   Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran each of the `dialog` files through `mimic`. Some dialog could be broken up with short pauses using a comma, but all is understandable.

*   Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> "Where is iss" returns the location of the Mycroft offices.

_ACTION REQUIRED: Please consider removing "where is i s s" as an intent, then push to `mycroft-skills` again_

*   Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

*   Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> Change examples in line with changes to intent vocab. Minor spelling error - consider changing About to:
>> This skill allows mycroft to tell you where the International Space Station (ISS) is in orbit, relative to the earth in latitude and longitude. it uses reverse geocoding to translate these coordinates into the country or body of water it is over.

_ACTION REQUIRED: Please consider changes to README.md then push to `mycroft-skills` again_

*   Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> not used, skipping check

*   Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> not used, skipping check

## Python code check

*   Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL?

> Yes, GPL-3.0 license used

*   Inline documentation - is the code documented in line?

> Clear inline documentation

*   Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> appropriate library usage, no external dependencies
> uses the free API of geonames.org

*   Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> n/a

*   Error handling - are there any specific checks we make for error handling or graceful degradation?

> error handling implemented for unknown location 
> no error handling if web service is unavailable

*   Automatic tests - do automatic tests of the **Skill** pass?

> No integration tests included  

_ACTION REQUIRED: Please add integration tests then push to `mycroft-skills` again_  

*   Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4\. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> N/A

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional tests

*   "Where is the international space station"

> position provided correctly

* "Locate i s s"

> position provided correctly

* "Where is i s s"

> position provided correctly if I carefully add spaces between "i s s" in my request


## Summary

*   Please modify "where is i s s" as an intent or address intent conflict
*   Please consider minor changes to the README file as described
*   Please add functional tests - these can be generated using the [Mycroft Skills Kit](https://mycroft.ai/documentation/skills/msk/)

Other than that, this Skill is well written and a fun addition - thank you!

**Comment by andlo** [comment]
"Please modify "where is i s s" as an intent or address intent conflict"
Changed to where is I S S but cant tricker an intent conflict

"Please consider minor changes to the README file as described"
Done

Please add functional tests - these can be generated using the Mycroft Skills Kit
Done


I did add language support, so geolocation uses correct language and added de-de and da-dk

**Comment by krisgesling** [comment]
Hi @andlo, sorry to come back with another request, however I was wondering if you knew about the `pronounce_number()` function?

Currently "115.8453" is sometimes read out as: 
_"one hundred and fifteen, eight thousand four hundred and fifty three"_

`pronounce_number(115.8453, places=4)` will ensure that it is read as: 
_"one hundred and fifteen point eight four five three"_

To use it you just need to make sure it's imported
`from mycroft.util.format import pronounce_number`

It has been fun to be able to use this skill and find out where the ISS is, yesterday it was only a few thousand kms north of me!

**Comment by andlo** [comment]
yah I just learned about that function while trying to trranslate core to Danish :) 
I will try add that function to the skill.
Were also thinking of adding a function that could anounse when ISS is entering home contry and exiting again.
And maybe a more human way of saying where ISS is like "ISS is now over China" or "ISS has just entered space over China", "ISS is leaving space over Portugal and soon entering soon space over spain" etc. More human like way to say where ISS is. 
But that would be much more difficult. but a fun challange :)

**Comment by andlo** [comment]
added pronounce_number and made sure it works using different language aswell :)

**Comment by krisgesling** [comment]
Hi @andlo, I think the test is failing because you have one English and one Danish test. Unfortunately there's not yet a way to specify the language for tests so the Danish utterance is being evaluated in English and hence not being understood.

I've flagged this use case with the team, but in the meantime if you delete that test then I think we're good to merge this into the Marketplace :smile:

**Comment by andlo** [comment]
done :)

**Comment by krisgesling** [comment]
Beautiful! It's sounding great!! 
Over Canada at the moment :)

**Pull request merged**
