### PR TITLE
Add moviemaster

### PR DESCRIPTION
**Pull request by builderjer**
## Info

This PR adds the new skill, [moviemaster](https://github.com/builderjer/moviemaster), to the skills repo.

## Description

Easily find information, such as a description, or cast from a movie with your voice.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by builderjer** [comment]
This skill is an update to [https://github.com/MycroftAI/mycroft-skills/pull/926](url).  It would only test against the 18.08.

It is now using the correct 19.02 version.

Thank you @krisgesling for pointing that out.

And @GPVM  for the suggestions on the README.md file.  I believe that I addressed all of them.

Please feel free to test and comment.

**Comment by krisgesling** [comment]
Hi there, the changes look good, however are on the [add-tmdb-skill branch](https://github.com/builderjer/tmdb-skill/tree/add-tmdb-skill) however I believe that MSK by default uses the master branch.
Are you able to merge that into master and rerun `msk submit`?

Is `v2.py` for your next iteration of the Skill? This would probably work better on a separate branch and keeping it out of the v1.

Have you had a look at our [testing documentation](https://mycroft.ai/documentation/skills/automatic-testing/)?

**Comment by builderjer** [comment]
Thank yoi @krisgesling for being so quick to check this out.  I will see what I can do with merging.  I will also look at the [testing documentation](https://mycroft.ai/documentation/skills/automatic-testing/) see what I can do.

**Comment by ConorIA** [comment]
Hi there, first test here, so bear with me. 

## Meta  
* Who: [@ConorIA](https://github.com/ConorIA)
* Datestamp: 2019-05-04_18:42:41_EDT
* Language and dialect of tester: en_CA, but picroft configured to en_GB

## 3. Functional Review - intuitive and expected  
- [X] **Installation**

Install method:  msm (no skill found for "movie master" or "tmdb", but might be my own fault).
Output:  
```  
pi@picroft:~ $ mycroft-msm install https://github.com/builderjer/tmdb-skill.git
INFO - Downloading skill: https://github.com/builderjer/tmdb-skill.git
INFO - Installing system requirements...
INFO - Installing requirements.txt for tmdb-skill
INFO - Successfully installed tmdb-skill
```  

Checking that STT transcribes correctly:  
```  
install skill movie master                                                                 DEBUG output                                                                            
>> Multiple skills found, which would you like... bedtime stories, number guess, plasma    skills.log, other                                                                       
    activities, openhab or dice
```

- [X] **Settings**  
The settings are fairly simple, but the "API V3 key" setting could use some explanation and perhaps a link to the API sign-up page. It also seems to be optional, so you could specify that.

- [X] **Dialog**
- Mycroft could be better at pronouncing "genre" (not "jen re"). 
- _movie.genre.multiple.dialog_ -> "concider" should be "consider", though the pronouciation is the same with mimic2.
- _movie.genre.single.dialog_ -> ibid
- _movie.info.response.dialog_ -> ~~released "on" {year} should be "during" {year} or "in" {year}~~ ... _Nevermind, it seems these are dates in the return, not years_
- _movie.year.dialog_ -> ibid
- _no.info.general.dialog_ -> "right not" should be "right now"

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [X] what is the movie _____ about                                     
```
what is the movie the departed about                                     
 >> The Departed is a 2006 American crime thriller film                                                            
    directed by Martin Scorsese and written by William                                                             
    Monahan. It is a remake of the 2002 Hong Kong film 
    Infernal Affairs.
```
**WORKS**

- [X] tell me about the movie _____        
```
 tell me about the movie titanic                                                                                                                         
 >> Just a moment while I look up the movie titanic                                                                  
 >> Titanic is a 1997 American epic romance and disaster film directed, written, co-                                                                           
    produced and co-edited by James Cameron.
```
**WORKS**, but Mycroft read 1997 as one thousand, nine hundred ...

- [ ] who plays in the movie _____        
```
 who plays in the movie the boondock saints            
>> The cast of The Boondock Saints includes: Willem 
Dafoe->Paul Smecker as Sean Patrick Flanery->Connor
MacManus and Billy Connolly-> as Julie Benz->
```
**This comes out as a jumbled mess**

- [ ] what genres does the flick _____ belong to
```
what genres did the flick star wars belong to                                  
 >> Have you tried a web search?                                                                                   
 what genres does the flick star wars belong to                                                                    
 >> That's an interesting question. I'll come back to
    that in a minute.
 what is the genre of titanic the movie                                                                            
 >> Does it have anything to do with genre of star wars ?                                                          
 what is the genre of the movie titanic
 >> I will try to find out.                                                                                        
```
**No luck**

- [ ] look for information on the movie _____
```
look for information on the movie avatar
>> Sorry my eye is not attached right now. 
look for information for the movie titanic
>> Sorry my eye is not attached right now. 
```
**No luck**

- [ ] what company made the movie _____
```
what company made the movie kill bill
>> I will try to find out.             
what company made the movie titanic                                      
>> That's an interesting question. I'll come back to 
     that in a minute.  
```
**No luck**

- [X] when was the movie ______ made 
```                                                               
 when was the movie kill bill made                                                                                 
>> Kill Bill Volume 1 was first released on October 10
     2003
```
**WORKS**

The skills above are from the readme. Tried to guess at this one:

- [ ] what movies are popular right now
```
what movies are popular right now                             
 >> I liked , Titanic, and Steven Spielberg's A. I.                             
 what are the top movies                                      
 >> Is that a rhetorical question?                                                                                 
 what are the top movies playing right now                                                                         
 >> I don't know anything about the top movies playing
    right now 
```

### Actions Required

I'm getting a lot of unhandled functions in the skills. I am not sure why this is, but I certainly will be disabling the snarky chatbot skill! 

Anyway, happy to give more feedback if I missed something. 

**EDIT: Just noticed all of those answers came from question answer skill and wolfram alpha. Nothing from moviemaster. Going to try again after adding an API key**.

**Comment by builderjer** [comment]
@ConorIA, thank you for testing.  Yes, this skill DOES require an API key to work correctly.  I hope that it works better after adding.  Please test and let me know

**Comment by ConorIA** [comment]
@builderjer, I can't get the skill to load (duh). Any hints: 

```
~~~~kills.core:load_skill:121 - INFO - ATTEMPTING TO LOAD SKILL: tmdb-skill.builderjer with ID tmdb-skill.builderjer
19:40:35.624 - mycroft.skills.core:load_skill:168 - ERROR - Failed to load skill: tmdb-skill.builderjer
Traceback (most recent call last):
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 148, in load_skill
    raise e
  File "/home/pi/mycroft-core/mycroft/skills/core.py", line 144, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/tmdb-skill.builderjer/__init__.py", line 38, in initialize
    self.AvalGenres = self.getAvalGenres()
  File "/opt/mycroft/skills/tmdb-skill.builderjer/__init__.py", line 42, in getAvalGenres
    "movies": TMDB["genre"].movie_list(),
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/tmdbv3api/objs/genre.py", line 11, in movie_list
    return self._get_obj(self._call(self._urls['movie_list'], ''), key='genres')
  File "/home/pi/mycroft-core/.venv/lib/python3.5/site-packages/tmdbv3api/tmdb.py", line 64, in _get_obj
    [arr.append(AsObj(**res)) for res in result[key]]
KeyError: 'genres'
```

**Comment by builderjer** [comment]
@ConorIA , what branch are you using?  Make sure you are on the master branch.  I just tried reloading it on my machine and it loaded fine.  Did it install tmdbv3api correctly?  It is required to run.

**Comment by ConorIA** [comment]
No luck! I'm getting the same error on desktop. 

```
20:05:25.303 - mycroft.skills.core:load_skill:166 - ERROR - Failed to load skill: tmdb-skill.builderjer
Traceback (most recent call last):
  File "/usr/share/mycroft-core/mycroft/skills/core.py", line 146, in load_skill
    raise e
  File "/usr/share/mycroft-core/mycroft/skills/core.py", line 142, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/tmdb-skill.builderjer/__init__.py", line 38, in initialize
    self.AvalGenres = self.getAvalGenres()
  File "/opt/mycroft/skills/tmdb-skill.builderjer/__init__.py", line 42, in getAvalGenres
    "movies": TMDB["genre"].movie_list(),
  File "/usr/share/mycroft-core/.venv/lib/python3.7/site-packages/tmdbv3api/objs/genre.py", line 11, in movie_list
    return self._get_obj(self._call(self._urls['movie_list'], ''), key='genres')
  File "/usr/share/mycroft-core/.venv/lib/python3.7/site-packages/tmdbv3api/tmdb.py", line 64, in _get_obj
    [arr.append(AsObj(**res)) for res in result[key]]
KeyError: 'genres'
```

**EDIT: It looks like the error is in the tmdbv3api package, am I reading that right?**

**Comment by builderjer** [comment]
@ConorIA, I am working on it, but it is working fine for me.  Maybe @krisgesling would be willing to install and see if it works for him?

**Comment by emattei** [comment]
I think this skill is very useful!

## Meta
* Platform:  Mark I
* Mycroft-core version: 19.2.6
* Who: [@emattei](https://github.com/emattei) / @polumechanos
* Datestamp: run `date +%Y-%m-%d_%H:%M:%S_%Z`  
* Language and dialect of tester: en_US but locale set to en_GB

## 1. Code Review - secure and stable  
- [ ] **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> The code doesn't have inline documentation but it is easy to understand what the code is doing.
> Why is the line `"movie": tmdbv3api.Movie(),` repeated twice on lines 19 and 20?
> Encapsulation should be improved too with proper getter and setter methods. Right now there are get methods setting values of the class without returning anything. Get methods that set values of the class and return the newly updated values and then get methods which act like a normal getter. I am pointing this out not for a matter of mere style but because separating getter and setter helps with security but also with error handling. More details in the next section

- [ ] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> Error handling is missing. Some checks are present and catching some errors. However, the API calls to the external libraries should be surrounded by try-and-catch statements. Indeed, I found cases in which errors are not caught properly:
```
who plays in the movie toilet?
>> An error occurred while processing a request in Tmdb
```
>In the above example, the external API catches the tmdb api error generated by a non existing title. But the skill should catch this and return "I am sorry I cannot find your movie" or something along this line.
>Moreover the behavior is not predictable for example
```
who plays in the tv show toilet?
>> I don't understand
```
>This different behavior happens because is the external API catching the errors in different ways. While also in the skill code there should be some error handling. Another example:
```
who plays in the show 4325
>> Sorry, I didn't catch that.
who plays in the movie 4325
 >> I'm sorry. I can not find any information on the film 4325
```

- [ ] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> It requires only one dependency and all the libraries required are part of the Mycroft related. However, I have a major concern to raise here. After a search on GitHub I found two repos from [2010](https://github.com/alberanid/imdbpy) and [2013](https://github.com/celiao/tmdbsimple) with 457 and 231 stars respectively offering tmdb API wrappers. Both those repos have recent commits so they are actively maintained. I am pointing this out because you want to be sure that the library that will be maintained in the future and also will keep up with possible modifications to the official tmdb APIs.
>Also the library imported here requires 17 dependencies. The 2010 library requires 13 and the 2013 1.

- [X] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> Correctly referenced

- [X] **Settings**  
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

>Correctly set up

- [ ] **Integration Tests**  
Does the skill include sufficient integration `tests`, included in the test folder?
>The skill does not include a test folder

- [ ] **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?
>Is it necessary to keep the 'OLDda-dk' folders( does not really represent a security issue, just to clean the repo)

### Actions Required:
* Improve the error handling

## 2. Information Review - accurate and understandable 
>This section has been covered in the previous pull request so I will skip it. I just want to mention two typos: 
>`Fill out API key on https://home.mycrof.ai` should be `Fill out API key on https://home.mycroft.ai`
> `Listen to the awesome responce!!` should be `Listen to the awesome response!!`

## 3. Functional Review - intuitive and expected 
@ConorIA review it above but since he encountered problems I am adding my impressions. 

- [X] **Installation**
Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method:  `mycroft-msm install https://github.com/builderjer/tmdb-skill.git`
> Output:  
> ```  
>INFO - Downloading skill: https://github.com/builderjer/tmdb-skill.git
>INFO - Installing system requirements...
>INFO - Installing requirements.txt for tmdb-skill
>INFO - Successfully installed tmdb-skill  
> ```  
>  
> Checking that STT transcribes correctly:  
> ```  
> Mycroft recognise it as tmdb-skill.builderjer which is really unconenient. It should be able to recognize > it as tmdb alone 
> ```

- [X] **Settings**  
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> Yes, but I agree that the readme should be more clear about the API. Maybe adding a section called "Post-installation configuration" or something like taht. Right now it seems that you need to configure the API when manually installing

- [ ] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

> Agree with the above review

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behavior of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [ ] **"List of comedy movies"**
```
>> the movies with the genre comedy are;
>> Shazam!
>> Fighting with My Family
>> Thor: Ragnarok
>> Fall in Love at First Kiss
>> Cars
```
> Why there are some movies from 2019, some form 2017 and one from 2006? In what ordered are the movie returned? Score?

- [X] **"what is the movie the blues brother about?"**
>here is a synopsis of the film the blues brother.
> Jake Blues is just out of jail, and teams up with his brother, Elwood on a 'mission from God' to raise funds for the orphanage in which they grew up
>The only thing they can do is do what they do best: play music
> So they get their old band together, and set out on their way—while getting in a bit of trouble here and there.

- [ ] **"Tell me about the movie____"**
>Also for me this answer goes through Wolfram and not the Skill...But technically give the correct answer :)

- [X] **"Who plays in the movie Ghostbuster "**
>Here is the cast of ghostbuster; Bill Murray as Dr. Peter Venkman, Dan Aykroyd as Dr. Raymond Stantz, Sigourney Weaver as Dana Barrett, Harold Ramis as Dr. Egon Spengler, and Rick Moranis as Louis Tully

- [X] **"When wad the movie the last jedi made"**
>the film Star Wars: The Last Jedi was made on wednesday, december thirteenth, twenty seventeen

- [X] **"What genre does the movie John Wick belong to"**
>The flick can be found in one of the genres; Action, and Thriller

-[X]*"who plays in the movie Mad Max fury road"*
>The following people act in the movie Mad Max fury road; Tom Hardy as Max Rockatansky,Charlize Theron as Imperator Furiosa, Nicholas Hoult as Nux, Hugh Keays-Byrne as Immortan Joe, and Josh Helman as Slit

### Actions Required
* It would be nice to have examples of questions that can be asked about  tv shows. Also there are functionalities that are present but not included in the readme.
*Overall the skill works and I would definitely install on my Mycroft

**Comment by builderjer** [comment]
@emattei, thank you for your testing and review.  I am trying to get to some of the suggestions and spelling errors, but life has been busy.  I am glad that it installed correctly for you, maybe @ConorIA could remove and try again.

As far as the name being tmdb-skill, this is getting changed soon, but not quite yet.  I will do some updates soon.

Thank you again for your suggestions and testing.

**Comment by emattei** [comment]
@builderjer I totally understand. Let me know if you have doubts or need clarification about the review. Good luck!

**Comment by krisgesling** [comment]
Thanks for the reviews Conor and Eugenio!

I just tried the install and got the same `KeyError` as Conor until I entered the API key in settings. Will need to check to see if the key is present before attempting any calls to the API. This would be particularly important once it's in the Marketplace as users will be able to install this via voice eg "Hey Mycroft, install movie master". 

It's probably also worth adding dialog in the event of an error connecting to the API. This might be that the API key is invalid or the service is down temporarily.

This is a great Skill though, be sure to shout out in [Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions or want to see how others have handled similar situations :)

**Comment by builderjer** [comment]
Hello!! And welcome back!!  I just pushed an updated version that I believe to be much cleaner.  If @emattei, @ConorIA and @krisgesling  would like to try again, that would be great.  I think I addressed everything that was mentioned in the previous comments.

**Comment by builderjer** [comment]
Run Tests

**Comment by builderjer** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by builderjer** [comment]
I think this skill is working well, @krisgesling made some suggestions in the forum [here](https://community.mycroft.ai/t/moviemaster-please-test/6652/2?u=builderjer),  If anybody has a suggestion on where to go from here, please let me know.

@andlo maybe you can do a Danish translation with the updated intents and dialog?  That would be great.  Thank you everybody!!

**Comment by builderjer** [comment]
Ok, another update.  I eliminated the need for the user to get an account through TMDb

**Comment by krisgesling** [comment]
Hey @builderjer I just noticed that at least on a Mark 1, the Skill fails to load after installation due to the `try` blocks not having associated `except` blocks on your last two intent handlers.

Verified that this resolves the problem by dropping in a quick 
```
except:
    pass
```
though I see you've got some nice error messages on the other handlers, so thought something similar for these might also be good.  Even if it's a very generic "something went wrong. If this keeps happening, please get in touch"

**Comment by builderjer** [comment]
Sorry, I deleted the last except that checked for an API without paying
much attention. I will get that fixed.

**Comment by builderjer** [comment]
I don't believe this error is my skill?

**Comment by krisgesling** [comment]
No not your skill, it's just Wednesday :)
_There's a bug in one of the existing skill tests that fails on Wednesdays_

**Comment by builderjer** [comment]
Mondays are better!!

**Comment by krisgesling** [comment]
Hi @builderjer 

I've just sent you a small PR to suggest some simple integration tests. 
For TV show queries, I've considered them non-blocking given the title of the skill is now MovieMaster.
I think the rest of the points raised by our reviewers have been addressed. 

So if you can add some integration tests, either the ones I've suggested or your own, we will be ready to merge it in :grinning:

**Comment by builderjer** [comment]
I merged them this morning.  Looks good to me.!!  I could probably add TV Shows to it pretty easy if you would like.

**Comment by krisgesling** [comment]
Looks great! I'll merge this in, and if you want to add TV shows we can do it as an update. 

I think because TMDB does TV too, if it's presented as a "TMDB Skill" then users might have the expectation that it will include TV. But being a "MovieMaster Skill" it's clearly only about movies, and uses the TMDB API to do that.

**Pull request merged**
