### PR TITLE
Add Plasma User Control Skill

### PR DESCRIPTION
**Pull request by AIIX**
## Description:

This skill integrates Plasma 5 Desktop Internals with Mycroft which enables users to Lock Screen, Switch Users, Logout, Control Brightness, Control Panel Positions, Control Klipper, Control Work-spaces, Control Compositor, Add Widgets on Plasma Desktop.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
After discussion with @forslund I am merging.

**Pull request merged**
