### PR TITLE
add new fallback skill

### PR DESCRIPTION
**Pull request by flozi00**
**Name of your skill**: awareFallback

## Description:

Send question to aware cloud if needed

## Checklist:
  - [x ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x ] Skill has been tested and works 
  - [x ] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [ x] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi Flozi,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

I took a quick look at your Skill, and am wondering if we can include some more information about the Aware server that the Skill needs to connect to. Is this referring to https://awareframework.com/ or something else?

If you have any updates that you want included in this pull request, you can update it by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by flozi00** [comment]
https://github.com/flozi00/AWare-Skill-Server

It's the cloud we spoke about in telegram chat

**Comment by krisgesling** [comment]
Oh of course, somehow I had not linked your two usernames in my head, despite their similarity.

Is the server ready for testing also? Interested to test out what you've been working on :)

**Comment by flozi00** [comment]
The basics are finished, the nlu is working and more skills are in progress.
You can train and run the server.
The translator is only for testing we will implement more, like deepl.

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
