### PR TITLE
Reload test cases for default skills

### PR DESCRIPTION
**Pull request by forslund**
This updates the docker file to try to pull in new test cases from any updated default skills.

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1328))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1328))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1328))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1328))

**Comment by forslund** [comment]
This should fix issues such as the ones seen in #1323 where the skill failed due to a test that was changed in the common query skill but wasn't updated in the test runner.

**Comment by krisgesling** [comment]
Took me a while, but looks good

**Pull request merged**
