### PR TITLE
Feature/allure report missing

### PR DESCRIPTION
**Pull request by forslund**
This is a test for separate comment if allure report is missing.

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed and no report was generated. A manual check will follow.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed and no report was generated. A manual check will follow.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed and no report was generated. A manual check will follow.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1318))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed and no report was generated. A manual check will follow.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1318))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1318))

**Comment by forslund** [comment]
Are you redoing this or is it no longer useful to generate a response if the allure report wasn't created correctly?

**Comment by krisgesling** [comment]
Sorry I may have misunderstood what this PR is for. If you're still working on it we can definitely keep it open.

**Comment by forslund** [comment]
This improved the failure message if an allure report wasn't created for some reason (skill couldn't be cloned, build collision, cosmic rays, etc.)

Basically only added the message with the link to the allure result if it was generated. otherwise a message that a manual check will be needed.

**Pull request closed without merging**
