### PR TITLE
Added Angry Beanie Skill

### PR DESCRIPTION
**Pull request by purserj**
## Description:

**Short description of your skill and what it does

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ ] Skill has been tested and works
  - [ ] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by btotharye** [comment]
@purserj did you use the Meta editor for the readme other than that everything else looks good, we are looking for the readme's to be in the format of the meta editor for some future stuff we have planned for consistency and automation.

thanks

**Comment by purserj** [comment]
@btotharye yep used the meta editor and copy/pasted the results

**Comment by btotharye** [comment]
looks good merging

**Comment by purserj** [comment]
Awesome thanks

**Pull request merged**
