### PR TITLE
Upgrade mycroft-ip

### PR DESCRIPTION
**Pull request by forslund**
This upgrades mycroft-ip to include the following new commits:

 - [Fix error when wlan exist but isn't connected](https://github.com/MycroftAI/skill-ip/commit/66ceb56411fb1273cb2ec669927ac2cca40c25e3)
 - [Merge pull request #19 from MycroftAI/bugfix/ssid](https://github.com/MycroftAI/skill-ip/commit/5fe73c45525870476b4af3c7ec406249c71007f5)
 - [Fix pylint issues](https://github.com/MycroftAI/skill-ip/commit/4f48cb00ad7ae066e6b87707cfefe5834ce22052)
 - [Add error handling for ssid query](https://github.com/MycroftAI/skill-ip/commit/1e55b97b109e6c67ab745eaf9f9c27a9f3e2250d)
 - [Merge pull request #18 from MycroftAI/test/fix](https://github.com/MycroftAI/skill-ip/commit/0011ff36add8de3f3ca3e58d7fae53a91e6d26d6)
 - [Fix testcases to work with the new lowercasing](https://github.com/MycroftAI/skill-ip/commit/b27206db7667a31d6fdb65dbba5264b8d2089c97)
 - [Update README](https://github.com/MycroftAI/skill-ip/commit/98a27b6b0e69209f6e42eef0251fa3a949813dd8)
 - [Add ability to report connected wifi name](https://github.com/MycroftAI/skill-ip/commit/267bd1d3dabe5e363d90066cb343687e235d6305)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
It seems that if no wlan0 connection exists but other connection types do exist, the Skill does not assign the ssid variable then attempts to reference it causing an uncaught error.

[Line 110](https://github.com/MycroftAI/skill-ip/blob/5fe73c45525870476b4af3c7ec406249c71007f5/__init__.py#L110) checks the len(addr) and reports if no network connection exists. However if connected on eth0 this is false and the handler continues. 

scanoutput on line 115 then evaluates to "wlan0 No scan results" but no CalledProcessError is thrown so the exception doesn't assign the ssid variable.

**Comment by forslund** [comment]
So do I understand this correct: if there is a wifi network but not under the device `wlan0` this reports a wired connection?

**Comment by krisgesling** [comment]
No wifi at all, only eth0
`get_ifaces()` returns
> {'eth0': '192.168.xxx.xxx'}

**Comment by krisgesling** [comment]
Looks good. Merging.

**Pull request merged**
