### PR TITLE
Add cave-adventure

### PR DESCRIPTION
**Pull request by JarbasAl**
## Info

This PR adds the new skill, [cave-adventure](https://github.com/JarbasAl/cave_adventure_skill), to the skills repo.

## Description

about

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
## Test of `cave-adventure`

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.2.2
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Fri 12 Oct 03:51:38 AEDT 2018
* Language and dialect of tester: Native English speaker, Australian accent

## Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> Skill is new, it won't respond to voice yet. Using `msm` for installation instead

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/JarbasAl/cave-adventure-game-skill
INFO - Downloading skill: https://github.com/JarbasAl/cave-adventure-game-skill
INFO - Installing requirements.txt for cave-adventure-game-skill
INFO - Successfully installed cave-adventure-game-skill
```

> Nice message on install, nice touch!

> Check that voice install will work - does STT pick up the name => Yes

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Always play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Played all `dialog` through `mimic` - nice use of the new `locale` structure. 
_One query - the file `not.playing.dialog` - I think this may have incorrect dialog in it - it says "restored to last save point"_

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> There is a risk that the `play.intent` may overlap with the 'Play' command used in media and news Skills. Flagging with @penrods in case we should consider the Play framework for use in this Skill. 

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README is lovely

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> versions not specified => OK

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Not used, skipping check

## Python code checks of the Skill

* Inline documentation - is the code documented in line?

> Excellent in line documentation

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Only one Python dep

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> No, skipping check

* Error handling - are there any specific checks we make for error handling or graceful degradation?

> error handling working well

* Automatic tests - do automatic tests of the **Skill** pass?

> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> Skill settings not used, skipping check

## Functional check

I had all sorts of issues with the Conversational Context - log attached
[cave-skills.log](https://github.com/MycroftAI/mycroft-skills/files/2469974/cave-skills.log)


## Summary

Could you please take a look at the Skills log - I just want to make sure Conversation Context is working.

**Comment by JarbasAl** [comment]
thank you for the excellent feedback! 

well spotted with the not.playing.dialog file

i will investigate the converse method errors

even with the logs troubles, are you able to play? i see your utterances there but assume you don't get a response back?

**Comment by KathyReid** [comment]
Hey @JarbasAl, I was able to play, but had a lot of difficulty with the converse method picking up my _utterance_ each turn. It *may* just be my voice, but the turn-by-turn structure of the game was difficult to play using voice. It worked, it didn't work _well_.

**Comment by penrods** [comment]
I just saw this thread.  Even though this uses the word "play", it is OK.  A more-specific match, like "play Colossal Cave Adventure" will match over the wildcard catch, so it doesn't have to be part of the CommonPlaySkill.

I've been suspecting there is a problem with the get_response() method catching the "beep" sound.  Does it work better for you if you turn off the beep?

**Comment by KathyReid** [comment]
Good question. I configured `mycroft.conf` to have `confirm listening` set to `false`, then re-ran. Unfortunately it was the same behaviour as observed on the first run - lots of failed intents, and it appeared that the Wake Word listener was listening at the same time as `get_response()` was active, which resulted in lots of `I don't know what that means`. 

[cave-skills-errors.log](https://github.com/MycroftAI/mycroft-skills/files/2516185/cave-skills-errors.log)

**Comment by krisgesling** [comment]
Hi @JarbasAl 
I'm spending some time reviewing all the existing PR's and wondered if you had further ideas about what was happening with the converse method in this skill?
I had a go and it's certainly working however I'm also getting the duplicate prompts for responses. Any chance it relates to the `expect_response` in the loop on [L74](https://github.com/JarbasAl/cave-adventure-game-skill/blob/5b2f2a03a4c76549703717c0422d4b3e0318f0da/__init__.py#L74)?

**Comment by penrods** [comment]
There have been some improvements to the underlying converse() mechanisms.  I'd be interested in knowing if this fixes the issues referred to here.

Also, I'm curious if turning off the "listening beep" makes it behave any better.

**Comment by krisgesling** [comment]
Just gave it another quick try.

The first prompt asking if the user wants instructions gets handled by the intent parser so a "yes" or "no" response gets directed to the QandA fallbacks and results in "I don't know what you mean". If you repeat "yes"/"no" outside of this, then you can get into the game. 

As the dialog is split into multiple lines and it's expecting a response after each line of dialog, it banks up response requests. Modifying L74 to something like the following reduces this to once per set of instructions and it becomes much more usable:
```
for line in lines[:-1]:
    self.speak(line.strip())
self.speak(lines[-1].strip(), expect_response=True, wait=True)
``` 
However if more than one line is uttered it still ends with an "I don't understand" before triggering `record_begin` and allowing you to continue.

I also found some of my spoken responses (eg go east) were still being passed through to the QandA fallback.

**Comment by krisgesling** [comment]
Hi Jarbas,

I know you're super busy so not expecting you to get back to this skill now, but I'm going to close the PR for now as it is against the 18.08 branch. 

Whenever you're ready to do updates, just do the standard `mycroft-msk submit /opt/mycroft/skills/your-skill-directory` and MSK will generate a new PR against the latest branch.

Thanks

**Pull request closed without merging**
