### PR TITLE
Update mycroft-version-checker

### PR DESCRIPTION
**Pull request by forslund**
This updates mycroft-version-checker with update instructions for each platform.

### CODE REVIEW

**Comment by krisgesling** [comment]
Worked fine on a linux install. On Picroft I've run into some TTS problems.

### From 18.8.13
- checkout commit 040a78c
- Updated skill-version-checker to 19.02 HEAD
- Ask Mycroft - "What version are you running"
Output:
```
01:22:30.968 - mycroft.audio.speech:mute_and_speak:122 - INFO - Speak: I am running mycroft-core version 18 oh 8, release 13
01:22:30.974 - mycroft.tts:execute:325 - DEBUG - TTS cache hit
01:22:31.000 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
Playing WAVE '/tmp/mycroft/cache/tts/531423b25afa5cb44dc127f20258e0a8.wav' : Signed 16 bit Little Endian, Rate 22000 Hz, Mono
01:22:32.358 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/814c3f97-3d0a-41b0-aaf6-cc20f1e230aa/metric/timing HTTP/1.1" 200 303
01:22:34.677 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
01:22:34.705 - mycroft.audio.speech:mute_and_speak:122 - INFO - Speak: Your version is outdated. To upgrade picroft to 19 oh 4, release 1. please restart the device, if you have updates set to manual you need to run "git pull" in the mycroft-core folder.
01:22:35.461 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): mimic-api.mycroft.ai:443
01:22:36.118 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/814c3f97-3d0a-41b0-aaf6-cc20f1e230aa/metric/timing HTTP/1.1" 200 223
01:22:37.665 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=%20To%20upgrade%20picroft%20to%20nineteen%20oh%20four%2C%20release%20one.&visimes=True HTTP/1.1" 200 164807
01:22:37.672 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=Your%20version%20is%20outdated.&visimes=True HTTP/1.1" 200 94223
01:22:39.883 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=%20please%20restart%20the%20device%2C%20if%20you%20have%20updates%20set%20to%20manual%20you%20need%20to%20run%20%22git%20pull%22%20in%20the%20mycroft-core%20folder.&visimes=True HTTP/1.1" 200 294505
Playing WAVE '/tmp/mycroft/cache/tts/4576af8b8340655927f578b8c1078b61.wav' : Signed 16 bit Little Endian, Rate 22000 Hz, Mono
```

- [x] First wav file complete
- [ ] Second wav file "please restart the device, if you have updates set to manual you need to run "git pull" in the mycroft-core folder."


### From 19.2.0
- checkout commit 7398e96
- Updated skill-version-checker to 19.02 HEAD
- Ask Mycroft - "What version are you running"
```
01:40:44.088 - mycroft.audio.speech:mute_and_speak:122 - INFO - Speak: I am running mycroft-core version 19 oh 2, release 0
01:40:44.101 - mycroft.tts.mimic2_tts:get_tts:253 - DEBUG - Generating Mimic2 TSS for: ['I am running mycroft-core version 19 oh 2, release 0.']
01:40:44.118 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): mimic-api.mycroft.ai:443
01:40:45.844 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=I%20am%20running%20mycroft-core%20version%2019%20oh%202%2C%20release%200.&visimes=True HTTP/1.1" 200 199966
01:40:46.493 - mycroft.audio.speech:mute_and_speak:122 - INFO - Speak: Your version is outdated. To upgrade picroft to 19 oh 4, release 1. please restart the device, if you have updates set to manual you need to run "git pull" in the mycroft-core folder.
Playing WAVE '/tmp/mycroft/cache/tts/c98d515196883162125708353983b326.wav' : Signed 16 bit Little Endian, Rate 22000 Hz, Mono
01:40:46.513 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
01:40:46.517 - mycroft.tts.mimic2_tts:get_tts:253 - DEBUG - Generating Mimic2 TSS for: ['Y.', 'o.', 'u.', 'r.', ' .', 'v.', 'e.', 'r.', 's.', 'i.', 'o.', 'n.', ' .', 'i.', 's.', ' .', 'o.', 'u.', 't.', 'd.', 'a.', 't.', 'e.', 'd.', 'T.', 'o.', ' .', 'u.', 'p.', 'g.', 'r.', 'a.', 'd.', 'e.', ' .', 'p.', 'i.', 'c.', 'r.', 'o.', 'f.', 't.', ' .', 't.', 'o.', ' .', '1.', '9.', ' .', 'o.', 'h.', ' .', '4.', ',.', ' .', 'r.', 'e.', 'l.', 'e.', 'a.', 's.', 'e.', ' .', '1.', 'p.', 'l.', 'e.', 'a.', 's.', 'e.', ' .', 'r.', 'e.', 's.', 't.', 'a.', 'r.', 't.', ' .', 't.', 'h.', 'e.', ' .', 'd.', 'e.', 'v.', 'i.', 'c.', 'e.', ',.', ' .', 'i.', 'f.', ' .', 'y.', 'o.', 'u.', ' .', 'h.', 'a.', 'v.', 'e.', ' .', 'u.', 'p.', 'd.', 'a.', 't.', 'e.', 's.', ' .', 's.', 'e.', 't.', ' .', 't.', 'o.', ' .', 'm.', 'a.', 'n.', 'u.', 'a.', 'l.', ' .', 'y.', 'o.', 'u.', ' .', 'n.', 'e.', 'e.', 'd.', ' .', 't.', 'o.', ' .', 'r.', 'u.', 'n.', ' .', '".', 'g.', 'i.', 't.', ' .', 'p.', 'u.', 'l.', 'l.', '".', ' .', 'i.', 'n.', ' .', 't.', 'h.', 'e.', ' .', 'm.', 'y.', 'c.', 'r.', 'o.', 'f.', 't.', '-.', 'c.', 'o.', 'r.', 'e.', ' .', 'f.', 'o.', 'l.', 'd.', 'e.', 'r.', '.']
01:40:46.563 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (2): mimic-api.mycroft.ai:443
01:40:46.846 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=Y.&visimes=True HTTP/1.1" 200 35323
01:40:47.161 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=u.&visimes=True HTTP/1.1" 200 35323
01:40:47.474 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=r.&visimes=True HTTP/1.1" 200 35323
01:40:47.940 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/814c3f97-3d0a-41b0-aaf6-cc20f1e230aa/metric/timing HTTP/1.1" 200 301
01:40:49.360 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=%20.&visimes=True HTTP/1.1" 500 291
01:40:49.655 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=o.&visimes=True HTTP/1.1" 200 35308
01:40:49.673 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=v.&visimes=True HTTP/1.1" 200 23591
01:40:49.699 - mycroft.audio.speech:mute_and_speak:129 - ERROR - TTS execution failed (JSONDecodeError('Expecting value: line 1 column 1 (char 0)',))
01:40:49.707 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
01:40:49.973 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=e.&visimes=True HTTP/1.1" 200 23576
01:40:49.986 - urllib3.connectionpool - DEBUG - https://mimic-api.mycroft.ai:443 "GET /synthesize?text=r.&visimes=True HTTP/1.1" 200 35323
etc etc
```
- [x] First wav file complete
- [ ] No second wav file

**Comment by forslund** [comment]
I figured out the issue(s) behind the weird picroft result see [mycroft-core PR #2061(]https://github.com/MycroftAI/mycroft-core/pull/2061)

**Comment by krisgesling** [comment]
Yep, just tested #2061 on this environment and it's all resolved.

Merging now

**Comment by krisgesling** [comment]
Soz, wrong button...

**Pull request merged**
