### PR TITLE
Adding new skill: speedtest

### PR DESCRIPTION
**Pull request by Sujan4k0**
**Repo URL:** https://github.com/ChristopherRogers1991/mycroft-speedtest.git
**Name:** speedtest
**Description**: This skill runs a speedtest with an output of ping, download, and upload speeds.
**Development Status:** working

### CODE REVIEW

**Comment by forslund** [comment]
Thanks for submitting this! Could you add the skill to the list in the Readme under the community contributed skill list?

**Comment by Sujan4k0** [comment]
It has been added.

**Comment by forslund** [comment]
Thank you, looks good! Merging!

**Comment by forslund** [comment]
And then, apparently I forgot merging!

**Pull request merged**
