### PR TITLE
Upgrade national-park

### PR DESCRIPTION
**Pull request by richhowley**
'This upgrades national-park to include the following new commits:

 - [Remove unused regex files](https://github.com/richhowley/national-parks-skill/commit/3503ad4b01b1bec4ac3cbb322ae59e6d8cad0b7d)
 - [Move loacation from regex to voc](https://github.com/richhowley/national-parks-skill/commit/63c1beb8956f0f21a9274cabe75749ab0a1d5b36)
 - [convert total returned by API to int](https://github.com/richhowley/national-parks-skill/commit/be433729762087403f15cf1dd7eedc4f896e9762)
 - [Merge pull request #4 from devs-mycroft/translate-2019-01-27](https://github.com/richhowley/national-parks-skill/commit/708fa52220661792f92f6b41d6f74aed9dcc47d5)
 - [Merge pull request #3 from devs-mycroft/translate-2019-01-21](https://github.com/richhowley/national-parks-skill/commit/34b8d5f33c4b6692c61cb8fac8886804e1cef0e5)
 - [Merge pull request #2 from devs-mycroft/translate-2018-12-31](https://github.com/richhowley/national-parks-skill/commit/53cf8379453def9df2f5d4c6c359bb73bc00daf7)
 - [Update translations](https://github.com/richhowley/national-parks-skill/commit/bb98b0b423caee11d2a37697f237bf4b9afa396b)
 - [Update translations](https://github.com/richhowley/national-parks-skill/commit/5620280e49a1b3ab728625224c05c100f34485bc)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey Rich,

With the shift to use a single API key, is it worth removing settingsmeta.json and updating the README?

Don't worry about the alarm skill test failure but it looks like your 000 test utterance isn't being caught either.

**Comment by richhowley** [comment]
HI Kris,

My tests worked locally but failed on upload.  I see the problem is with a regex file.  There is a note here: https://github.com/MycroftAI/mycroft-core/releases
under “merge vocal expansion” that looks suspeciously like the issue I”m having even though regex is not mentioned.

If I change (in) (?P<Location>.*) to just   (?P<Location>.*) it works.  

Should be easy enough to rearrange, I’ll look at it over the weekend.  19.02 is kicking my butt.

Please send a link to the API shift info.

- Rich

**Comment by forslund** [comment]
Run test

**Comment by krisgesling** [comment]
The API shift I mentioned was just in reference to you adding a fixed API key, rather than fetching this from the users settings.  Am I reading that correctly?

I saw that the National Parks API rate limit is 1000 queries per hour which is quite unlikely to be exceeded for the moment, so this seems like a good move to reduce the amount of configuration required by Mycroft Users.

The vocab expansion change was because there was an inconsistent approach in some file types for the (a|b) syntax, but that shouldn't have had any effect on regex files.

This is passing on my local machine too...

@forslund - the Jenkins build doesn't seem to be giving Padatious or Adapt an attempt to handle the utterance and is instead jumping straight to Fallbacks.
The Jenkins integration test outputs:
```
Rule created  [['and', ['or', ['endsWith', 'intent_type', 'ParkListIntent'], ['endsWith', '__type__', 'ParkListIntent']], ['equal', 'List', 'list'], ['equal', 'National.Parks', 'national parks'], ['equal', 'Location', 'nevada']]]
UTTERANCE: list national parks in nevada
1
2
3
4
07:28:48.019 - mycroft.skills.padatious_service:handle_fallback:142 - DEBUG - Padatious fallback attempt: list national parks in nevada
07:28:50.038 - mycroft.skills.padatious_service:handle_fallback:142 - DEBUG - Padatious fallback attempt: list national parks in nevada
```
If the intents failed, shouldn't there be two additional lines? eg
```
mycroft.skills.intent_service:handle_utterance:349 - DEBUG - Padatious intent: None
mycroft.skills.intent_service:handle_utterance:350 - DEBUG -     Adapt intent: None
```

**Comment by richhowley** [comment]
I would rather get this working version released and concern myself with the fixed API key later.

**Comment by krisgesling** [comment]
Hi @richhowley with the API key, I only meant that the settingsmeta.json now seems redundant since users don't need to enter their own API key. Can we remove that and the second paragraph of the long description before we push this to the Marketplace?

**Comment by richhowley** [comment]
Hi Kris, that’s fine but I don’t understand where the API key lives or what I have to do in code.

**Comment by krisgesling** [comment]
No worries, 

The API_Key is defined on [line 19](https://github.com/richhowley/national-parks-skill/blob/3503ad4b01b1bec4ac3cbb322ae59e6d8cad0b7d/__init__.py#L19) of your `__init__.py`. This is your personal API key. It looks like you removed this [in November last year](https://github.com/richhowley/national-parks-skill/commit/da91ca57db81faf9d106f91937eede0e7689c39a#diff-743b1adbf37db12e16e01ef62a6f7d72) in favour of Mycroft users setting their own API Key in settings. Then re-added it [in April](https://github.com/richhowley/national-parks-skill/commit/be433729762087403f15cf1dd7eedc4f896e9762#diff-743b1adbf37db12e16e01ef62a6f7d72).

This means that anyone using your Skill will be using your API key to query the NPS. It also means that key is publicly available on Github so people may use it for other purposes. Given the NPS API is free and there doesn't seem to be any way to make money from it, I think it's unlikely people will do this. Worst case scenario they use it inappropriately and exceed the rate limits set by NPS. The key would then get blocked either temporarily or permanently. I assumed this was why you shifted it to the user settings in the first place?

I can see two options:
#### 1. You are happy to have your API Key used and publicly available
The Skill is then working as intended. Simply delete `settingsmeta.json` as it's no longer required and delete line 7 in your README.md that starts: "To use this skill you will need to obtain an API key..."

#### 2. This was unintentional and you want to remove that
If this is the case you will want to go back to the NPS, revoke this key and create a new one as there's no way to put a secret back in the box once it's out on Github. You'd then need to refactor the Skill to go back to using settingsmeta.json. We can provide some further suggestions on how to do this if this is the case.

Does that make sense?

**Comment by richhowley** [comment]
Hi Kris,

Now I understand.  I don’t know how that old code got back in the repository, might be an artifact of my Picroft with AIY hat ceasing to work and juggling code between one working unit, one non-working unit and my Mac.

I will go through it carefully, update the repository and run msk again.  Thanks.

**Comment by krisgesling** [comment]
Closing this due to the new PR #1002

**Pull request closed without merging**
