### PR TITLE
Update skill template to use manifest.yml

### PR DESCRIPTION
**Pull request by MatthewScholefield**
## Description:
Updates the skill template to provide an example manifest.yml for use in 19.02.

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey wonder if we can add a short comment at the top like:
`# This file details all external dependencies required by your skill. If your skill does not require any dependencies, please delete this file before submitting a pull request.`

I will update the documentation for this and of course everyone reads the manual first, but just an extra nudge :)

**Comment by MatthewScholefield** [comment]
Great idea! I'll add this.

**Comment by penrods** [comment]
I also asked in the Chat about the idea of using several files called something like:
* example-pip-requirement__manifest.yml
* example-package-dependency__manifest.yml
* example-skill-dependency__manifest.yml
* example-combo__manifest.yml

They would be full examples, with only legit comments and not commented-out lines.  Would this be useful / less confusing?  The mycroft-skills acceptance could scan for these filenames and reject them.  Thoughts?

**Comment by krisgesling** [comment]
My first thought is that it would be more confusing rather than less, but worth getting more perspectives. What Chat channel did you post it in, I can't seem to find it?

**Comment by penrods** [comment]
I was the mycroft-core-dev-team channel.  I added you to it.

**Comment by MatthewScholefield** [comment]
I've updated this with a comment at the top and the section for skill dependencies.

**Review by penrods — APPROVED** [review]
LGTM!

**Review by penrods — COMMENTED** [review]
LGTM!

**Pull request merged**
