### PR TITLE
new skill person detection

### PR DESCRIPTION
**Pull request by patilaum**
## Description:

This skill detects the number of persons in front of a webcam. It uses tensorflow for object detection.
The object detection module is to be downloaded from [(https://github.com/tensorflow/models/tree/master/research/object_detection)]
Checklist:

  [x ] Used Meta Editor to generate the skill README
  [x ] Skill has been tested and works
 [ x] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  [x ] README.md has been updated with the following:

    +[submodule "person detector"]
    +	path = person-detector
    +	url = https://github.com/patilaum/mycroft-person-detect-skill.git

- [x ] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by patilaum** [comment]
I don't why the skill tester is failing. I've tested the skill in my python console. Can anyone tell me any better ways to test the skill using mycroft core?

**Comment by btotharye** [comment]
@patilaum I have some info https://geekedoutsolutions.com/mycroft-skill-creation-lifecycle-using-msk about running tests locally 

As far as your issue here if you click on the Skill Tester Details that takes you to the jenkins console output here https://jenkins.mycroft.team/job/skill-tester/253/console which shows the below error

```
+ msm -u https://github.com/forslund/mycroft-skills.git -b skill_CpJ0Au install person
INFO - Best match (0.66): person detector by patilaum
INFO - Downloading skill: https://github.com/patilaum/mycroft-person-detect-skill.git
INFO - Installing requirements.txt for person detector
PipRequirementsException: 
Pip returned code 1:

Invalid requirement: 'install object_detection from tensorflow'
Traceback (most recent call last):
```

So this seems to be a typo in your requirements.txt file

```
tensorflow > =1.4.0
```
this should be

```
tensorflow >=1.4.0
```

I just think you have an unnecessary space.

**Comment by patilaum** [comment]
wow...all checks have passed. Now how do I install this skill. I typed 'install mycroft-person-detector' in command but it is asking me to chose between mycroft-release-test or mycroft mark1 demo'. I dont understand.

**Comment by MatthewScholefield** [comment]
This has to be merged in before you can install it

**Comment by patilaum** [comment]
@MatthewScholefield how do I merge it?

**Comment by MatthewScholefield** [comment]
Someone on the skills team has to approve and then merge it

**Pull request merged**
