### PR TITLE
Upgrade dice-skill

### PR DESCRIPTION
**Pull request by yvie-k**
'This upgrades dice-skill to include the following new commits:

 - [Add die to vocabulary and change example for range intent](https://github.com/Dragoncraft89/dice-skill/commit/7feddc9c23a07390254f82df313b6b7870b7b655)
 - [Reenable random number generation](https://github.com/Dragoncraft89/dice-skill/commit/70e7ab9013532cf38737c52132ff8a3b3c519948)
 - [Fix for non en-us languages](https://github.com/Dragoncraft89/dice-skill/commit/a599a9c4d2719abe80f7e91fddf53bdda62dfaff)
 - [Slight rework of the regex handling](https://github.com/Dragoncraft89/dice-skill/commit/f175f4248aa97d7e47e285214e4d3bbe24308f78)
 - [Fix crash when processing "Roll a die"](https://github.com/Dragoncraft89/dice-skill/commit/eba36fade8c920947eae36f3b0af04ffd3dcb281)
 - [Merge pull request #4 from devs-mycroft/translate-2019-01-27](https://github.com/Dragoncraft89/dice-skill/commit/7d2997a8fe57c13d56a2379ffc42ef1d08257c8d)
 - [Merge branch 'master' into translate-2019-01-27](https://github.com/Dragoncraft89/dice-skill/commit/d6a41c650c9129c50547462b0c4a603e7a37df0d)
 - [Merge pull request #2 from devs-mycroft/translate-2019-01-21](https://github.com/Dragoncraft89/dice-skill/commit/ca33e646f96621ac6eb30e208da092357653a57d)
 - [Update translations](https://github.com/Dragoncraft89/dice-skill/commit/38391f947d8b9ab134ba43aef407feb749508858)
 - [Update translations](https://github.com/Dragoncraft89/dice-skill/commit/f6289131b687cb5e8eb4f4fcf6860b364c1dd8f3)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Not sure why this skill interferes with skill-ip. The only thing I can see is that it registers an invalid regex: `(?P<Dice>(.*)?\s*d\s*.*|dice)` [pythex](https://pythex.org/?regex=(%3FP%3CDice%3E(.*)%3F%5Cs*d%5Cs*.*%7Cdice)&test_string=&ignorecase=0&multiline=0&dotall=0&verbose=0)

I will try to test more locally to see if I can reproduce the issue.

**Comment by yvie-k** [comment]
The regex is now fixed

**Comment by forslund** [comment]
The regex is not updated in this PR

**Comment by forslund** [comment]
Tried a different version, basically splitting the handling of "dice" and "dX" into separate methods which simplifies the regex slightly. Which works (see https://github.com/MycroftAI/mycroft-skills/pull/875)

My changes can be seen here: https://github.com/forslund/dice-skill/tree/test-fixes

**Comment by yvie-k** [comment]
I've merged your changes into the repository if you're okay with it.

The submodule should be updated correctly this time.
Thanks for your time :+1:

**Comment by forslund** [comment]
Just Noticed I removed the Range.rx regex by mistake :(

**Comment by yvie-k** [comment]
Yeah I've disabled it for now, because the old way was very hacky and I can't seem to find a good way to properly get a range with regex that works in all languages

**Comment by forslund** [comment]
Ok!

In the future you might want to look at padatious for that, it might be easier to work with.

And also: Yey! the tests are passing now :)

**Comment by LinusSkucas** [comment]
# Skills test for the Dice skill

## Meta
*   Platform: Picroft
*   Mycroft-core version: 18.08
*   Who: [@LinusS1](https://github.com/linuss1) Mattermost/forum: brrn
*   Datestamp: 2019-02-21_16:02:01_PST
*   Language and dialect of tester: (American) English

## 0. Automated tests
Are all automated tests passing?
- [x] Continuous Integration - Travis-CI
- [x] Skill tester - Jenkins

## 1. Code Review - secure and stable
- [x]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

>The code looks all good.

- [x]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

>If no type of die is specified, then skill defaults to a single 6 sided die.

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

>Skill uses the `random` library.

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.
Also check to see if `requirements.txt` and `requirements.sh` are empty, if they are, they can be deleted.

>No dependencies needed.

- [x]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

>`settingsmeta.json` not used

- [x]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

>Integration Tests now included

~__Action Required: Add some simple tests using `msk create-test` for rolling dice.__~


- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

>No random files.


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x]   **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

>Icon is hosted on githack.com

- [x]   **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

>Descriptions look good.

- [x]   **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

>Examples give a clear understanding.

- [x]   **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

>All devices supported

- [x]   **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

>"Entertainment" category present and is bolded.

- [x]   **Tags**
Are listed tags appropriate for this Skill?

>3 tags: all look good.

- [x]   **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

>Using the GNU General Public License v3.0


## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method:
> Output:
> ```
>  msm install https://github.com/Dragoncraft89/dice-skill.git
>  INFO - Downloading skill: https://github.com/Dragoncraft89/dice-skill
>  INFO - Installing system requirements...
>  INFO - Successfully installed dice-skill
> ```

> Checking that STT transcribes correctly:
> ```
>- INFO - Utterance: ['install dice skill']
> ```

- [x]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

>`Settingsmeta.json` not used.

- [x]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

>Sounds good.

#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described. Also check that the sample utterances activate the skill.

- [x]   **"roll some dice"**

>Your number is 4

- [x]   **"roll a d20"**

>Your number is 7

- [x]   **"generate a random number between negative 5 and 5"**

>The Result is 4

>Working perfectly now, thank you!

~_Action Required: maybe normalize words like negative and minus to -. The STT returned negative when I read -._~

- [x]   **"Roll 3 d20"**

>the result is 8, 2 ,11

Nice!

- [x]   **"roll a die"**
> Sorry, I don't understand.

_Action required: Add "die" to `Dice.voc`_

## Summary
 - [x] ~Add some tests for the autotester~
 - [x] ~Normalize negative or minus to -.~
 - [x] Add "die" to `Dice.voc`

Thanks for updating this skill. It's really great!

After you do the above just do `msk submit /path/to/skill/directory`

**Comment by yvie-k** [comment]
Well, the generate random number from range is currently disabled, because the input handling is buggy. I'll retry with padatious as @forslund suggested. Will implement some tests too.

> * [ ] "roll a die"
> > Sorry I don't understand
>
>*Action required: Add "die" to `Dice.voc`*

Why? The request "roll a die" doesn't make sense.

**Comment by krisgesling** [comment]
Hi Florian,

Dice is the plural of "die" though many English speakers just use "dice" when they mean singular so it's easy to miss it.

Strangely "roll a die" is working for me on a Mark 1 but not on Debian, I haven't looked into why this is the case, but adding "die" it to the vocab in `Dice.voc` sorted it out fine.

The range intent seemed to worked fine for all positive integers. So it feels like there are three possible ways forward:
1. specify positive only numbers and change the example phrase in the readme
2. disable the intent and remove the example phrase for the moment
3. keep working on a solution to support negative integers

What do you think?

**Comment by yvie-k** [comment]
Ah, I didn't know that. Will add that.

For the range intent, it seems like padatious omits the "-" before numbers when passing it to the skill. I'll edit the example phrase and keep working on a solution for negative numbers.

**Comment by krisgesling** [comment]
Looks good to me :)

Thanks for the great Skill Florian!

**Comment by forslund** [comment]
Included in 19.02. Closing.

**Pull request closed without merging**
