### PR TITLE
Add todoist

### PR DESCRIPTION
**Pull request by gravesjohnr**
## Info

This PR adds the new skill, [todoist](https://github.com/gravesjohnr/todoist-skill), to the skills repo.

## Description

Interaces with the todoist application to add items to project lists.  this was created to replace wunderlist.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by gravesjohnr** [comment]
Updated with test case.

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! I'm particularly excited for this being a Todoist user myself. :tada:



To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by AZAZ78** [comment]
Hi John, i wanted to test your skill and was wondering why you do not use the existing Python libraries?

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
