### PR TITLE
Add jellyfin

### PR DESCRIPTION
**Pull request by tuxfoo**
## Info

This PR adds the new skill, [jellyfin](https://github.com/tuxfoo/jellyfin-skill), to the skills repo.

## Description

Stream music from your Jellyfin server using Mycroft! Play all songs by an artist or an instant mix of any artist/album/song in your Jellyfin library.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by tuxfoo** [comment]
If some one at mycroft needs access to a jellyfin server to test this for approval then send me a PM and I will create a temp account and API key.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1408)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1408/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1408/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1408/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1408/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1408/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1408)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1408/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1408/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1408/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1408/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1408/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hey @tuxfoo,

I just took a quick glance and thought I'd throw a few tips out there. You may or may not be aware of them already
- `self.log.log(20, string)` is the same as `self.log.info(string)`
- If you don't need a method like `initialize()` it can be deleted from your Skill.

With the tests, I'm not sure why they are being executed by Voight Kampff when no VK tests are included. The tests in `test/intent` are in the format of the old integration test runner. @chrisveilleux can you shed some light on this?

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1408)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1408/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1408/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1408/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1408/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1408/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1408)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1408/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1408/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1408/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1408/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1408/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
