### PR TITLE
Upgrade mycroft-spotify

### PR DESCRIPTION
**Pull request by forslund**
This upgrades mycroft-spotify to include the following new commits:

 - [Simple VK tests](https://github.com/forslund/spotify-skill/commit/f9b9045baa1fa80c49b070503d885172ec355ce3)
 - [Merge pull request #177 from osheroff/21.02](https://github.com/forslund/spotify-skill/commit/b321c772e0ec11c4f9c6d6a128ab5498aacb5d11)
 - [add pointer to install beta version](https://github.com/forslund/spotify-skill/commit/77ad488db74955ddef922604b31c44b0bbb48ccb)
 - [Add pmulh to the contributors list](https://github.com/forslund/spotify-skill/commit/9140b41a0486520fc1075131e776fa913b6b55b7)
 - [Merge pull request #173 from pmulh/feature/allow_master_control](https://github.com/forslund/spotify-skill/commit/c59b3feffd20bc380284f29b97f1fc550bd8595c)
 - [Reworking of how functionality for allowing control of other devices works](https://github.com/forslund/spotify-skill/commit/8bb7d6d2ec14d2b8c724cfb05751e85ee9079e7c)
 - [Tidy-up of comments](https://github.com/forslund/spotify-skill/commit/aefc2b74407c345c313d68dadd27aa0912934065)
 - [Removing unnecessary logging call](https://github.com/forslund/spotify-skill/commit/ef137def861252ff5efbbb325513f60364972710)
 - [Updates to handling of Now Playing intents, based on PR comments](https://github.com/forslund/spotify-skill/commit/98e62cf693994310f04d317e1dff9284dfe57849)
 - [Add auth instructions for Mark-1](https://github.com/forslund/spotify-skill/commit/3f59f2ebf28ce8ae18b3b88345dd96594e6626bb)
 - [Updates to how "what song is this"-type intents work when allow_master_control is true](https://github.com/forslund/spotify-skill/commit/c70bc2b9eebb58951673f7edb26fa2cc5a763731)
 - [Merge branch 'forslund:21.02' into feature/allow_master_control](https://github.com/forslund/spotify-skill/commit/2d542a169fc42beb9228ab5b2ea4d42cea7c6882)
 - [Update README.md](https://github.com/forslund/spotify-skill/commit/e68162364769da91de48f471b0887c6f69b7cc2b)
 - [Merge branch 'forslund:21.02' into feature/allow_master_control](https://github.com/forslund/spotify-skill/commit/d9c1f06774dda5baaaf2072172db6605bd4d0a82)
 - [Merge pull request #170 from forslund/feature/custom-auth-storage](https://github.com/forslund/spotify-skill/commit/b6903fd85f05ef944b828b66d4a85289db8b8faf)
 - [Update readme with auth storage information](https://github.com/forslund/spotify-skill/commit/b4ad9a98dcdb6bfa65f8091aca5cff81d8c6de70)
 - [Allow override of default auth location](https://github.com/forslund/spotify-skill/commit/050cfa4f45c53180838104d56e9eeeb59578355f)
 - [Refactor to reuse auth better](https://github.com/forslund/spotify-skill/commit/5b53d8e9f12af38a687d8dcdd01b50e329eec644)
 - [Update Copyright](https://github.com/forslund/spotify-skill/commit/12360d7173d7a5c673a671ca698d5d2103cdc6e8)
 - [Add now playing info, and ability to control playback started elsewhere](https://github.com/forslund/spotify-skill/commit/c461c4e0d7e2e1be5fa1c316f7bdda6beb1d0bf3)
 - [Remove instructions to hit non-existing connect button](https://github.com/forslund/spotify-skill/commit/eacff8ae9b0ae0a73c325a32eba2e1a48a03c990)
 - [Handle missing device-name (unpaired)](https://github.com/forslund/spotify-skill/commit/7d3526dc535ec2ddf81363d5e63acf396b872b7b)
 - [Don't require username to try to authorize](https://github.com/forslund/spotify-skill/commit/fd1f8ad996b19676a0a33bd8b4e238f425451cf9)
 - [Remove Connect button frome websettings](https://github.com/forslund/spotify-skill/commit/f8e196c28c34809304402ac6115fd6ac3081d7bc)
 - [Make sure that the link is shown and not opened](https://github.com/forslund/spotify-skill/commit/e495ea5bd3176f618d00bad6cfbeb6bfa446bd1d)
 - [Merge pull request #162 from forslund/feature/local-api-key2](https://github.com/forslund/spotify-skill/commit/47848d1ee656b37e652fecf607e6530a454df40c)
 - [Reactivate loading of personal playlist](https://github.com/forslund/spotify-skill/commit/ee47726e50a9cd328c41e2ddf4f566560255b7b5)
 - [Update readme after feedback from @fermulator](https://github.com/forslund/spotify-skill/commit/6d0ed3e90ecd77de38946bf150c08c3175a35abc)
 - [Add helper and instructions for authenticating](https://github.com/forslund/spotify-skill/commit/bf260707e1f7a838b63eb30a3eb1ae00af95c26b)
 - [Update spotipy to 2.17.1](https://github.com/forslund/spotify-skill/commit/05cb3ffe55822591d7f996c0d798a8b0101a70d0)
 - [Add support for using a local API key](https://github.com/forslund/spotify-skill/commit/0019d6a4bc2afa41822bea1e0802dcc270ceebd7)
 - [Merge pull request #156 from devs-mycroft/translations](https://github.com/forslund/spotify-skill/commit/d62242a7f8cb145c77f2c30a24b4d363d94d2d2e)
 - [Merge pull request #161 from rickoooooo/Issue160](https://github.com/forslund/spotify-skill/commit/5b62c40d1c654a60bb1e4177fce693203b8c3119)
 - [Updated device_by_name function to remove case-sensitivity (Issue #160)](https://github.com/forslund/spotify-skill/commit/49db13d3f7f90b0af78506600c7807dec6e909be)
 - [Merge pull request #158 from forslund/feature/device-instructions](https://github.com/forslund/spotify-skill/commit/d24f5ef5826fe297225e307047899571121fbdb8)
 - [Update translations](https://github.com/forslund/spotify-skill/commit/a0c27167d28246b0dac7436ad6619fb87d9ce405)
 - [Add fermulator and joshuajaharwood to CONTRIBUTORS](https://github.com/forslund/spotify-skill/commit/0d40e6bb7576bc521f524539802373b2659c8ccd)
 - [Improve information for Picroft and Desktop user](https://github.com/forslund/spotify-skill/commit/c623fbff554bf22b2b937b8399bcde775ce71189)
 - [Merge pull request #154 from forslund/feature/re-ignore-case](https://github.com/forslund/spotify-skill/commit/7a4876a8d620adedc3d4a9036b3f47b1882945ae)
 - [Add ignore case to regexes](https://github.com/forslund/spotify-skill/commit/d5eb84576bba926382d986c1672d4ab88cf23040)
 - [Add info about API key issues](https://github.com/forslund/spotify-skill/commit/f48352974e3690cff543919995cd896098df13bc)
 - [Use built-in version of CPS_send_status()](https://github.com/forslund/spotify-skill/commit/9a5f7ee2144f619e2e775ccc4413ec3edbaaf6b2)
 - [Move from mock to unittest.mock in test environment](https://github.com/forslund/spotify-skill/commit/596510c669755d5869e1d2ff73492152a1cbc4f4)
 - [Merge pull request #148 from forslund/bugfix/es-es](https://github.com/forslund/spotify-skill/commit/edb479efaa660b8524826e4f16a952ee663df969)
 - [Remove extra ')' from spanish regex translation](https://github.com/forslund/spotify-skill/commit/49087561028607693723dd5dab7b1f84f4f4d7e6)
 - [Merge pull request #143 from forslund/feature/podcast](https://github.com/forslund/spotify-skill/commit/fc14a5274540e1a1c80d333a3cebd9c6a891cc5e)
 - [Add basic support for podcasts](https://github.com/forslund/spotify-skill/commit/8da6db9b58887d2d366fb6c24086c8c4d92d8383)
 - [Update heading](https://github.com/forslund/spotify-skill/commit/342f31b832ae15f96698969918b2c496ba27e1c9)
 - [Merge pull request #134 from krisgesling/bugfix/typo](https://github.com/forslund/spotify-skill/commit/0689a16ff106c5e04954109b83507b1dad415bfe)
 - [typo on Coventant; standardise on play vocab](https://github.com/forslund/spotify-skill/commit/f105ae186a57704257d94c96ce94afb0f12f8ffd)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1529)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1529/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1529/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1529/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1529/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1529/logs/enclosure.log)

**Comment by forslund** [comment]
This will allow people to use the Spotify using their own developer credentials.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1529))

**Comment by forslund** [comment]
Oh this uses a botched version of #1530 and shouldn't be merged before that is removed from this branch.

**Pull request closed without merging**
