### PR TITLE
Add quiet-hours

### PR DESCRIPTION
**Pull request by brezuicabogdan**
## Info

This PR adds the new skill, [quiet-hours](https://github.com/brezuicabogdan/quiet-hours-skill), to the skills repo.

## Description

Set a time frame during which your mycroft will be quiet. if enabled the volume of your mycroft will automatically be lowered to specified value when the quiet hours start and will automatically return to normal once quiet hours end.
This is very usefull if you also use Mycroft for verbal notifications and you do not want to be disturbed at night.
You can also enable or disable teh quiet hours manually, very nice to have when you are watching a move and do not want to be disturbed.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by brezuicabogdan** [comment]
It looks the intent tests fail because of this
`Couldn't allocate mixer, ALSAAudioError('No such file or directory [default]',)`
Any idea why the skill cannot access the Mixer?

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1333))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1333))

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
