### PR TITLE
added play some music skill

### PR DESCRIPTION
**Pull request by normandmickey**
## Description:

**Short description of your skill and what it does

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by normandmickey** [comment]
What does this error mean?  How do I fix it?

**Comment by TREE-Edu** [comment]
@normandmickey Firstly thank you for your skill contribution.  If you are referring to the Travis CI error check, that is not a strict standard for your skill to be included in the official repo.

I checked your PR and it mostly looks good to me, except for the block that you added to the README file.  Here is what you have currently.

`+| :heavy_check_mark:  | [home-assistant](https://github.com/normandmickey/play-some-music-skill#readme)| Listen to internet radio station<br>```play some music``` `

Looks like you need to edit the name for your skill really quick as it says "home-assistant".  Once that is done I think we are good to merge your PR.

**Comment by normandmickey** [comment]
Try again, I fixed the README.md file

**Comment by normandmickey** [comment]
Thanks!

**Pull request merged**
