### PR TITLE
Add camera

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [camera](https://github.com/MycroftAI/skill-camera), to the skills repo.

## Description

Take singleshot photographs with the Camera Skill.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1497)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1497/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1497/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1497/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1497/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1497/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1497))

**Comment by krisgesling** [comment]
oh :facepalm: I forgot about the script hacking for a second

PSA: Don't merge PR's sitting on your desktop from the night before everyone!

**Pull request merged**
