### PR TITLE
Upgrade game-zork

### PR DESCRIPTION
**Pull request by forslund**
This upgrades game-zork to include the following new commits:

 - [Move fetching of zork data into the skill.](https://github.com/forslund/white-house-adventure/commit/c01168fb4a715a99caeab1d976eead14228b194a)
 - [Add "Goto the white house" command to README](https://github.com/forslund/white-house-adventure/commit/02de878f27ab3e182a37d0452edad9b565d92995)
 - [Split zork code into separate file](https://github.com/forslund/white-house-adventure/commit/369082f9fa803671c340d57340f4bd5255affb8b)
 - [Add voight kampff test file](https://github.com/forslund/white-house-adventure/commit/ab01cc5abf6b1989812638be377839cebd01971d)
 - [Fix some code-style issues](https://github.com/forslund/white-house-adventure/commit/3602f81e966b1e759466a838ad57f969f70ad9ae)
 - [Upgrade converse to latest Mycroft standard](https://github.com/forslund/white-house-adventure/commit/17e8ffc6f23d255aafd5c750ff81acd1188938c4)
 - [Merge pull request #15 from CryptedSystem/patch-1](https://github.com/forslund/white-house-adventure/commit/bc6eb51412262ecc67a4285e69d7286247f21625)
 - [Change converse method second argument](https://github.com/forslund/white-house-adventure/commit/861507c80a064e3ff1e7ec9dad4a4f9d0d6f9adb)
 - [Merge pull request #14 from devs-mycroft/translations](https://github.com/forslund/white-house-adventure/commit/a248266c543574fc079970ee616fb8f045fe405d)
 - [Update translations](https://github.com/forslund/white-house-adventure/commit/8c57027bf8bed49ea0944459dfb5a44b4f2640ac)
 - [Merge pull request #13 from andlo/add_license](https://github.com/forslund/white-house-adventure/commit/576b5e2ead2c60f35e197de56dfc7d013c1cf139)
 - [Merge pull request #12 from devs-mycroft/translations](https://github.com/forslund/white-house-adventure/commit/d35e7742986cc37cbeeb4ebcef89b1e7699e5f09)
 - [add_license](https://github.com/forslund/white-house-adventure/commit/4c4ec5def66c5fb9de61062a7a493dbe25da8705)
 - [Update translations](https://github.com/forslund/white-house-adventure/commit/cb62786c0576ef51209dede90b625f7988a8a0a6)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1523)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1523/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1523/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1523/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1523/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1523/logs/enclosure.log)

**Comment by forslund** [comment]
This handles an issue with the changes in converse allowing the skill to work in 21.02

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1523)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1523/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1523/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1523/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1523/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1523/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1523)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1523/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1523/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1523/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1523/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1523/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1523)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1523/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1523/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1523/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1523/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1523/logs/enclosure.log)

**Pull request closed without merging**
