### PR TITLE
Upgrade game-zork

### PR DESCRIPTION
**Pull request by forslund**
This upgrades game-zork to include the following new commits:

 - [Fix bad log statement](https://github.com/forslund/white-house-adventure/commit/80f65b9df262bb4b28c62e416faacc44e304e076)
 - [Move fetching of zork data into the skill.](https://github.com/forslund/white-house-adventure/commit/c01168fb4a715a99caeab1d976eead14228b194a)
 - [Add "Goto the white house" command to README](https://github.com/forslund/white-house-adventure/commit/02de878f27ab3e182a37d0452edad9b565d92995)
 - [Split zork code into separate file](https://github.com/forslund/white-house-adventure/commit/369082f9fa803671c340d57340f4bd5255affb8b)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1531)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1531/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1531/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1531/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1531/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1531/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1531)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1531/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1531/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1531/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1531/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1531/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1531))

**Comment by krisgesling** [comment]
Nice update!

**Pull request merged**
