### PR TITLE
Add events

### PR DESCRIPTION
**Pull request by pointbazaar**
## Info

This PR adds the new skill, [events](https://github.com/n9v9/events-skill), to the skills repo.

## Description

Events in krefeld

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
### Meta information

* Platform:Ubuntu Linux 18.04 LTS
* Device version: 18.8.6 stable branch
* Who: @kathy-mycroft / @kathyreid 
* Datestamp: Tue 27 Nov 22:30:18 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> This Skill is not yet in the `mycroft-skills` repo and so is not installable using voice commands yet. Checking that the phrases `krefeld` and `events` are understood well by STT: 
`~~~~n__:handle_utterance:61 - INFO - Utterance: ['install krefeld']`

> STT understands the phrase well, now doing manual installation

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/n9v9/events-skill
INFO - Downloading skill: https://github.com/n9v9/events-skill
INFO - Successfully installed events-skill
```

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all the `dialog` through `mimic` TTS, all was played back correctly. There was one query I had about a phrase; `events.problem.nothing.dialog`. This says "I did not say anything", but I'm not sure that that is the correct phrase for this situation? 

ACTION REQUESTED: Can you confirm this is the right phrasing? 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> The Intent files don't distinguish between "general" events and "krefeld" events - so if another Skill in the future had a similar sort of Intent, then we would need some form of disambiguation. I strongly recommend using a disambiguation word, for example; 

* `Give me a random Krefeld event`
* `Provide me with information about a random Krefeld event`
* `Which Krefeld events are available`
* `Which Krefeld events are happening soon`

ACTION REQUESTED: Please amend the Intents so that they are specific about Krefeld events

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> The README has not been generated using the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html). It needs to be in this specific format so that it will display properly in the [Mycroft Marketplace](https://market.mycroft.ai). The table of phrases is very well done - thank you!

ACTION REQUESTED: Please ensure that the README file is generated using the Meta Editor. This ensures that it displays correctly in the Mycroft Marketplace. 

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> requirements are not used, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> `settingsmeta.json` is not used by the Skill - it currently has no user-configurable settings. This file should be removed from the repo. 

ACTION REQUESTED: Please remove this file from the repo if there are no user-configurable settings. 

### Python code checks 

* Inline documentation - is the code documented in line?

> there is some inline documentation

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> doesn't use any dependencies

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> not required

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> error handling is done well, it fails with an appropriate message

* Automatic tests - do automatic tests of the **Skill** pass?

> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)

> Not required

_NOTE: We do not enforce PEP8 Checks on Skills_

### Changes required before this Skill can be added to the `mycroft-skills` repo

Firstly @pointbazaar I'd really like to thank you for the time and effort you've put into this Skill. It's clear that you know Python and that you're used to working with open data. 

* README - the README needs to be generated using the Meta Editor so that the formatting in the Mycroft Marketplace is consistent. 

* At the moment the API key for Meetup is held in the Skill - this should be configurable by the end user using [Skill Settings](https://mycroft.ai/documentation/skills/skill-settings/) - this is what `settingsmeta.json` is for. 

Once you've made these changes, please add the commits to this PR and I can re-review. 

Again, many thanks for your contribution!

**Comment by KathyReid** [comment]
Hi there @pointbazaar just wondering how you're going with the requested changes for this Skill?

**Comment by pointbazaar** [comment]
@KathyReid i'm currently doing other things so i'll just close it.

**Pull request closed without merging**
