### PR TITLE
Add notification-skill

### PR DESCRIPTION
**Pull request by gras64**
## Info

This PR adds the new skill, [notification-skill](https://github.com/gras64/notification-skill), to the skills repo.

## Description

Other skills can save notifications here and have them called up later. As soon as there is a hint, the LED ring lights up orange and a notification bell sounds every few minutes

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1339))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1339))

**Comment by gras64** [comment]
i have add a gui picture for mark 2

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1339))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1339))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1339))

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
