### PR TITLE
Add patrick-lights-on-skill.mycroft

### PR DESCRIPTION
**Pull request by legend-patrick**
## Info

This PR adds the new skill, [patrick-lights-on-skill.mycroft](https://github.com/legend-patrick/patrick-lights-on-off-skill), to the skills repo.

## Description

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1356))

**Comment by krisgesling** [comment]
Hi Patrick,

Welcome to Mycroft. It's great to see you are exploring Mycroft Skill development.

The submission process you used is how you can submit your completed Skills to the public Skills Marketplace. Any Mycroft user will then be able to install the Skill either by tapping a button or saying "install name-of-your-skill".

For testing purposes you don't need to submit the Skill, you can install it on any Mycroft device by running:
```
mycroft-msm install https://github.com/legend-patrick/patrick-lights-on-off-skill
```

It looks like the Skill you've submitted today is probably for your own testing and not quite ready for prime time. I will close the PR until you're ready to have it reviewed by our Skill Testing Team. You can read more about that [review process in our documentation](https://mycroft.ai/documentation/skills/skills-acceptance-process/)

Also if you haven't already please join our Community [Chat](https://chat.mycroft.ai/community/channels/skills) or [Forums](https://community.mycroft.ai/) if you have any questions or just want to chat with other developers and users.

**Comment by legend-patrick** [comment]
Hello!
Sorry about that.  Not sure why or how I submitted that.

Mycroft is awesome!  We are using it to create a voice-activated smart
classroom!

Thank you for this platform.

**Comment by krisgesling** [comment]
No worries at all. 

For the education space, you might also be interested in the work Tree Industries do with Mycroft: https://www.tree.industries/products/ezra

**Comment by legend-patrick** [comment]
Will do.  Thanks!

**Comment by legend-patrick** [comment]
Hi Kris,
Just wanted to share how much we are enjoying integrating mycroft into the
classroom.

We were featuring a former student starting his own attendance management
system.  Parts of the video show mycroft being used to turn the lights off
and on.

****Check it out:*
https://www.youtube.com/watch?v=2CaaFAp24uY


Take Care,
Derek

**Comment by krisgesling** [comment]
Hey Derek, that is great to see how you're using Mycroft in the classroom, and amazing to see your students growing their own enterprises!

We'd love to give this a broader shoutout too :)

**Comment by legend-patrick** [comment]
Thanks!

Sure!  That would be great!

**Comment by legend-patrick** [comment]
Oh, and we’re coding Mycroft to turn on and off the LED lights added to the
ceiling!!!

**Pull request closed without merging**
