### PR TITLE
Add web-launcher

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [web-launcher](https://github.com/krisgesling/web-launcher-skill), to the skills repo.

## Description

A simple Skill to open web pages in your default browser.

Currently Sites must be included in the `sites.value` file, or added to the Skill settings as a custom url.

Contributions to this list are welcomed, as are suggestions for better ways to translate natural language into the correct url.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360))Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/${BRANCH_ALIAS}/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/${BRANCH_ALIAS}/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/${BRANCH_ALIAS}/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/${BRANCH_ALIAS}/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/${BRANCH_ALIAS}/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1360/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1360/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1360/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1360/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1360/logs/enclosure.log)

**Comment by krisgesling** [comment]
To anyone watching this repo, apologies for the notifications. I'm testing fail scenario's in our CI, not trying to get this to pass. But thanks for the suggestions all the same :)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1360)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1360/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1360/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1360/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1360/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1360/logs/enclosure.log)

**Pull request closed without merging**
