### PR TITLE
Upgrade skill-aircrack with suggested inline comments, built in wordl…

### PR DESCRIPTION
**Pull request by JonStratton**
## Description:

**Upgrade skill-aircrack with suggested in-line comments, built in wordlist, and a bug fix.

### CODE REVIEW

**Comment by JonStratton** [comment]
Also went about "sudo" access a little differently. Now it should refer back to project page with simple note on granting sudo accesses. I feel this is much better than possibly prompting for a password...

**Comment by KathyReid** [comment]
Thanks @JonStratton for submitting this update - very much appreciated. 

I'm a little concerned about the "crack" functionality that is in this update - I know that `aircrack` is designed for this sort of activity, but from a Mycroft point of view, we need to be cautious about providing Skills that could be used to breach security policies of the networks they're used on. 

How do you feel about putting a disclaimer or similar on the Skill - putting the onus on the user to use it responsibly?

**Comment by JonStratton** [comment]
@KathyReid , I cannot believe I spaced off adding the normal Disclaimer... Thanks!

Ive added one to the README.md, and in the skill in a get_intro_message() so its ttsed to the user on first launch. If you have any suggestions on how its phrased, let me know.

**Comment by KathyReid** [comment]
### `skill-aircrack` acceptance test

* Platform: Ubuntu Linux 16.04 LTS, running `mycroft-core` 18.2.11
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Friday 3 August  19:11:16 AEST 2018
* Language and dialect of tester: native English speaker, Australian accent

--- 

`list interfaces`

> "Error, I cannot seem to sudo the aircrack commands without a password. Please see ... for notes on sudo access"

`list wireless networks`

> "Error, I cannot seem to sudo the aircrack commands without a password. Please see ... for notes on sudo access"

Referred to notes on `sudo` access; 

```

sudo access
This skill must be able to sudo some programs without password prompting. To set up, please visudo and grant the user access like the following:

Cmnd_Alias AIRCRACK = /usr/sbin/airmon-ng, /usr/sbin/airodump-ng, /usr/sbin/aireplay-ng, /sbin/iwlist
my_mycroft_user ALL = NOPASSWD: AIRCRACK

```

Used `visudo` to make suggested changes, re-ran `Intents`

---

**Comment by KathyReid** [comment]
I did not see a disclaimer `tts`'d to me at all

**Comment by KathyReid** [comment]
I want to get some advice from my colleagues on the Skills Management Team around this one.

**Comment by KathyReid** [comment]
Hi @JonStratton, I just wanted to provide you with an update on some of the conversations the Skill Management Team has had around this one - essentially we're a little uncomfortable with the `crack` Intent in this PR. We understand that the intention of the Skill is _not_ to be used for nefarious purposes, however it _could_ be. 

Before we merge this PR, we'd really appreciate if you were able to put a `get_response()` mechanism into the `crack` intent, with phrasing along the lines of: 

`Accessing a wifi network you are not authorized to use can be illegal.  Please confirm that you have permission to connect to this network by saying YES, otherwise say NO to cancel.`

The `crack` Intent could only then be activated if the user explictly confirms they are authorized to use that function on that network. 

Would you be comfortable with this? 

Kind regards, 
Kathy

PS Thanks for your patience on this one!

**Comment by JonStratton** [comment]
@KathyReid , I am fine with putting a sane amount of additional warning in this skill if it will get it approved. 

However, based on the phrasing of the yes/no prompt example you've given, my understanding is you are most concerned about permission in the initial connection to a network(which is totally valid). If this is the case, this would be more appropriate to put this warning when the network is selected (handle_select_network_intent()) or when the interface is put into monitor mode (handle_start_monitor_intent()) for a selected network (this is when the connection happens). 

Also, putting the warning at just the "crack" part might give people a false since of confidence that everything up to that point is fine, permission or no permission. The "De-auth Clients", is very much not something someone should be doing against networks they don't have permission to access and test as it will disconnected everyone on the network.

Let me know if you would like the warning re-phrased or moved to one of the spots mentioned above. In the meantime, I will put your exact suggestion in a branch(pr462_suggestion) but not roll it into master yet.

**Comment by KathyReid** [comment]
Thanks so much @JonStratton for such a quick response. I've talked this over with @penrods and we really like your suggestion of having the confirmation _before_ the initial connection to the network. This means that _anything_ the user does after that point is something that they have had to confirm they have the right to do. 

Thanks again for being so flexible!

**Comment by JonStratton** [comment]
@KathyReid , the suggestions have been rolled into my branch. Thanks again for your help with this.

**Comment by KathyReid** [comment]
## Re-testing

* Platform: Ubuntu Linux 18.04 Bionic Beaver, GitHub based install
* Device version: 18.2.12b
* Who: @kathyreid / @kathy-mycroft
* Datestampa; Wed 15 Aug 09:48:46 AEST 2018
* Language and dialect of tester: English native speaker, Australian accent

### Installing Skill from scratch, I'm on a new system

```
kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ source venv-activate.sh 
Entering mycroft-core virtual environment.  Run 'deactivate' to exit
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/JonStratton/skill-aircrack
INFO - Downloading skill: https://github.com/JonStratton/skill-aircrack.git
[sudo] password for kathyreid: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  locate
0 to upgrade, 1 to newly install, 0 to remove and 3 not to upgrade.
Need to get 52.3 kB of archives.
After this operation, 181 kB of additional disk space will be used.
Get:1 http://au.archive.ubuntu.com/ubuntu bionic/universe amd64 locate amd64 4.6.0+git+20170828-2 [52.3 kB]
Fetched 52.3 kB in 1s (42.7 kB/s)                         
Selecting previously unselected package locate.
(Reading database ... 185047 files and directories currently installed.)
Preparing to unpack .../locate_4.6.0+git+20170828-2_amd64.deb ...
Unpacking locate (4.6.0+git+20170828-2) ...
Setting up locate (4.6.0+git+20170828-2) ...
Processing triggers for man-db (2.8.3-2) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  ethtool ieee-data
The following NEW packages will be installed:
  aircrack-ng ethtool ieee-data
0 to upgrade, 3 to newly install, 0 to remove and 3 not to upgrade.
Need to get 4,361 kB of archives.
After this operation, 14.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://au.archive.ubuntu.com/ubuntu bionic/main amd64 ethtool amd64 1:4.15-0ubuntu1 [114 kB]
Get:2 http://au.archive.ubuntu.com/ubuntu bionic/universe amd64 aircrack-ng amd64 1:1.2-0~rc4-4 [2,707 kB]
Get:3 http://au.archive.ubuntu.com/ubuntu bionic/main amd64 ieee-data all 20180204.1 [1,539 kB]
Fetched 4,361 kB in 6s (760 kB/s)      
Selecting previously unselected package ethtool.
(Reading database ... 185060 files and directories currently installed.)
Preparing to unpack .../ethtool_1%3a4.15-0ubuntu1_amd64.deb ...
Unpacking ethtool (1:4.15-0ubuntu1) ...
Selecting previously unselected package aircrack-ng.
Preparing to unpack .../aircrack-ng_1%3a1.2-0~rc4-4_amd64.deb ...
Unpacking aircrack-ng (1:1.2-0~rc4-4) ...
Selecting previously unselected package ieee-data.
Preparing to unpack .../ieee-data_20180204.1_all.deb ...
Unpacking ieee-data (20180204.1) ...
Setting up ieee-data (20180204.1) ...
Processing triggers for man-db (2.8.3-2) ...
Setting up ethtool (1:4.15-0ubuntu1) ...
Setting up aircrack-ng (1:1.2-0~rc4-4) ...
rockyou.txt not found. Please find a copy and download it.
INFO - Successfully ran requirements.sh for skill-aircrack
INFO - Installing requirements.txt for skill-aircrack
INFO - Successfully installed skill-aircrack
```

_Noting that my password was required to install `requirements.sh`_

### Testing functionality

* `List interfaces`
> "Here are the available interfaces: 0: wlp110s0

* `Select interface number zero`
> "Selected the wlp110s0 interface"

* `List wireless networks`
> "0: {{correct SSID}}, 1: {{correct SSID}}"

* `Select network number zero`
> "Selected the {{correct SSID}} network"

* `Start monitor`
_was initially STT translated as `scott monitor` then `sauce monitor` before I said it in an American accent. The "aa" sound in the middle is different in an Australian accent_
> There was no output to screen from this Intent, nothing spoken

* `Stop monitor`
> "Stopping monitor"

* `Disconnect clients`
> "Deauthing clients connected to the {{SSID}} network"

(Ran through the identify and select interfaces, identify and select networks then attempted the below)

* `Crack password`
> No password found

_BUG: There was no warning or confirmation provided at all_

I'm guessing this _may_ be related to the install message with `rockyou.txt not found`. 

---

@JonStratton are you able to show me where the confirmation happens, it seems I couldn't trigger it

**Comment by JonStratton** [comment]
P.S. I think by the references to "rockyou.txt", you might be testing against an old version of this skill...

**Comment by KathyReid** [comment]
You were exactly right, @JonStratton, I was on an old version of the Skill! I did a fresh install, so not sure how that happened. But at least it made it easy to update and test. 

### Confirm commit that the Skill under testing is on

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/skill-aircrack.jonstratton$ git log
commit 7390bcc834c05edbb358104fcca3394d6f1cd4b4 (HEAD -> master, origin/pr462_suggestion, origin/master, origin/HEAD)
Author: jgstratton <jgstratt@sdf.org>
Date:   Tue Aug 14 17:44:48 2018 -0500

    Moved warning per pull request suggestion

```
### Set up `visudo`
Edited `sudo` using `visudo` to add passwordless access for my mycroft user. Straightforward.

### Test intents
Tested all the Intents, and specifically the one where the user joins the network. The confirmation was shown correctly, and the user had to confirm that they were authorised to access the network. 

_One minor nitpick found during this process was that because in the `dialog`, the confirm is written in capitals like `YES` and `NO`, the `mimic` TTS reads them back as `N O` - ie `en oh` and `Y E S` - ie `why ee ess` - spells them out_
**Recommendation**: minor change to dialog to lower-case the dialog for this. I will raise PR on `master` for it. https://github.com/JonStratton/skill-aircrack/pull/4

I'm not going to hold the Skill back on this though, this looks good and I am merging.

**Pull request merged**
