### PR TITLE
meta_editor.html: improve JS & CSS library

### PR DESCRIPTION
**Pull request by rizdaprasetya**
## Description:
The meta editor haven't been updated for a while, this PR do the following
- Update font awesome CSS lib version to v5.15.0, latest stable, which also includes [new icons](https://fontawesome.com/changelog/latest) including Covid-related icons
- Lock version on color pickr lib to avoid accidental breaking changes if the library CDN got updated
- The [original lib package name has been changed](https://github.com/Simonwep/pickr/) from `npm/pickr-widget/` to `npm/@simonwep/pickr`, so the CDN url is changed according to that
- Also add SRI tag to ensure integrity 

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README

Thanks! feel free to review

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1394))

**Comment by rizdaprasetya** [comment]
Weird that the CI fails, this PR has nothing to do with the failing tests to be clear.

**Comment by krisgesling** [comment]
Selamat malam, and thanks for these updates. 

We will have to hold the Font Awesome update until we get that bumped in the [Selene-UI](https://github.com/MycroftAI/selene-ui/blob/master/projects/market/src/index.html#L11) as well. If you're on a hacktoberfest push, feel free to throw a PR in for that too :)

**Comment by rizdaprasetya** [comment]
Selamat siang! 🙂 

Wonderful. Thanks for pointing out there is other dependency to make it in-sync.
Opened PR:
https://github.com/MycroftAI/selene-ui/pull/36

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1394))

**Comment by krisgesling** [comment]
Merging now that it's included in Selene-UI

Makasih lagi

**Pull request merged**
