### PR TITLE
Evil skill

### PR DESCRIPTION
**Pull request by JarbasAI**
## Description:

Closed source skill, i could just be lying,

makes mycroft evil

## Checklist:
  - [ ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x ] Skill has been tested and works
  - [x ] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x ] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by el-tocino** [comment]
I'm going to close this pr.  You've gotten a response in the forums as well as in matter most to your concerns.  Feel free to bring up other issues you have there, where we can productively work together to address them.

**Comment by JarbasAI** [comment]
the answer i got said nothing about not accepting closed source skills, why is this closed and not accepted?

it's a skill, doesnt go against any guidelines, my idea was to create discussion not to brush this off, if this cant be merged, link me to a policy saying why that is

**Comment by el-tocino** [comment]
You have other, better, avenues available for discussion as mentioned above.

**Comment by JarbasAI** [comment]
first time a skill is refused, please clarify the reason

even tough i wanted to create discussion, no discussion was had and an action was taken

this is a valid skill, that does something, even if something very simple

it also is the first example of running C compiled code in a mycroft skill, does this mean i can never again submit a skill of this kind?

I have a few skills to push to this repo, i hate making the PRs so i keep delaying.... do i have to open up all their sources? those are skills with "real" functionality, will they be banned? i will not waste time pushing things without knowing the rules by which they are accepted....

**Comment by JarbasAI** [comment]
i think this discussion should be here, because here is where actions are being taken about it, but as requested moved discussion to the forums: https://community.mycroft.ai/t/skills-repo-consideration/2305/4

**Pull request closed without merging**
