### PR TITLE
Upgrade mycroft-npr-news

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-npr-news to include the following new commits:

 - [Merge pull request #34 from devs-mycroft/translate-2018-11-11](https://github.com/MycroftAI/skill-npr-news/commit/05586c5c9840b843124e29b3c1baaadcf3881321)
 - [Update translations](https://github.com/MycroftAI/skill-npr-news/commit/e61ad65ae77897b55b2f11f659156ddff95d0600)
 - [Merge pull request #33 from westfalenyeti/18.08](https://github.com/MycroftAI/skill-npr-news/commit/bf144b302c2e2013c2248ad2faac6496fba81e4f)
 - [Added finish YLE News (Kudos to juhi24)](https://github.com/MycroftAI/skill-npr-news/commit/3bbc82fc775a7f8fa03b95e8d91c4a5de2418498)
 - [Removed CNN because of outdated, no longer working CNN link](https://github.com/MycroftAI/skill-npr-news/commit/aa6f94afac0333fecd194e2acc2b27ce90b7871d)
 - [Layout correction](https://github.com/MycroftAI/skill-npr-news/commit/506899e510f4790fd4891fadac72ab2813ca98a2)
 - [Added log entry for played news url](https://github.com/MycroftAI/skill-npr-news/commit/c17bef07cdf048ec970da0f6426e523278e1a862)
 - [Removed outdated CNN link, didn't find a working one](https://github.com/MycroftAI/skill-npr-news/commit/fd007bd42367e9aabaf2e7d1e502229f13560b0e)
 - [Strip possibly leading and trailing spaces from url](https://github.com/MycroftAI/skill-npr-news/commit/85c4d766b28a015143d5c1f0a5b262fd44a3c3b1)
 - [Added german stations](https://github.com/MycroftAI/skill-npr-news/commit/a1b48fd422e55133bfd7aca55e428b12375e3dd3)
 - [Improved german dialog text](https://github.com/MycroftAI/skill-npr-news/commit/9706bb72061d3bf87c943866725176b73272dab4)
 - [Added german news to list](https://github.com/MycroftAI/skill-npr-news/commit/445a9ac49e6300a1df6921f48b1e3eb175278c14)
 - [Manual merge into 18.08](https://github.com/MycroftAI/skill-npr-news/commit/3fece3baaf6f747a4c4fb7f6a6d5d76ee9d4e68b)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by KathyReid** [comment]
This is a default Skill for all platforms, bumping to the top of the to-be-reviewed list.

**Comment by KathyReid** [comment]
### Ensure on current commit

```

**Comment by KathyReid** [comment]
### Ensure on current commit

```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/skill-npr-news$ git log
commit 05586c5c9840b843124e29b3c1baaadcf3881321 (HEAD -> 18.08, origin/HEAD, origin/18.08)
Merge: bf144b3 e61ad65
Author: Åke <ake.forslund@gmail.com>
Date:   Mon Nov 26 16:05:13 2018 +0100

    Merge pull request #34 from devs-mycroft/translate-2018-11-11
    
    Updated translations: ['sv-se', 'de-de', 'ru-ru', 'hu-hu']
```

### test case for new news feeds in German, Finnish

* Changed my News selection to the new feeds, told Mycroft to `update configuration` then `play the news` and they played well

TEST PASSED

### test case for custom URLs

* Changed my News selection to a custom RSS feed 
`https://www.abc.net.au/am/rss/amrss.xml`
and it played perfectly

TEST PASSED

### other test cases

Did a desk check of the other changes, they look good. Merging.

Many thanks to @westfalenyeti and @juhi24 for your excellent contributions, hugely appreciated.

**Pull request merged**
