### PR TITLE
Upgrade mycroft-date-time

### PR DESCRIPTION
**Pull request by forslund**
This upgrades mycroft-date-time to include the following new commits:

 - [Merge pull request #100 from devs-mycroft/translations](https://github.com/MycroftAI/skill-date-time/commit/abeb5e43750f7726c76c38f45cd5ec7dd8ab8f86)
 - [Update translations](https://github.com/MycroftAI/skill-date-time/commit/94ed3d44bec459aa62c1132e397e12ccb305c8e9)
 - [Merge pull request #99 from MycroftAI/bugfix/langcodes](https://github.com/MycroftAI/skill-date-time/commit/f0404140d7459aa96953d65b3d865709bb7bd32e)
 - [Explicitly use 4 letter codes](https://github.com/MycroftAI/skill-date-time/commit/8be79f1c000271bb77a11651506bab76b8ba7bae)
 - [Merge pull request #98 from devs-mycroft/translations](https://github.com/MycroftAI/skill-date-time/commit/8b2f793196f560c249b360f2eb224033d755859b)
 - [Update translations](https://github.com/MycroftAI/skill-date-time/commit/42308531c3391041700103b15ff1e5349ce8d272)
 - [Merge pull request #96 from MycroftAI/feature/landscape-date](https://github.com/MycroftAI/skill-date-time/commit/caa283da85695d695aba75f6098434be080b05e3)
 - [Merge pull request #94 from AIIX/fix/scaling-time-ui](https://github.com/MycroftAI/skill-date-time/commit/31df877132fa459c434623faf98aea651b844f4f)
 - [make minutes font bold](https://github.com/MycroftAI/skill-date-time/commit/a3390debdd20070e4813d74a4a44c49629179f07)
 - [fix centering](https://github.com/MycroftAI/skill-date-time/commit/088849a34d5306c8a619ebda12795b92f14d82ae)
 - [remove non property](https://github.com/MycroftAI/skill-date-time/commit/2df6e119f3f5d0e77b9b72fc8cd8471fe8d9d80c)
 - [update as per latest figme, remove colons, center everything](https://github.com/MycroftAI/skill-date-time/commit/04193bf85687452d4d60405146af9ad3ad7df4b8)
 - [Add comments to the date QML file.](https://github.com/MycroftAI/skill-date-time/commit/d159665b8a19a94404b0d3cf2efdb4ee26c0b0da)
 - [update the date screen to fit on a landscape orientation screen](https://github.com/MycroftAI/skill-date-time/commit/3346e353542fcb4c8800907151ed3ea6806d593a)
 - [renamed background idle screen file name to be more descriptive](https://github.com/MycroftAI/skill-date-time/commit/d6e5a2072606ccdaf51781ee49795430eca167ad)
 - [remove QML file that is not referenced in the skill](https://github.com/MycroftAI/skill-date-time/commit/b4ddf4a722e2da2c4faafb0854ecb62ebba49106)
 - [add buffer for single digits in horizontal mode](https://github.com/MycroftAI/skill-date-time/commit/8c17dfad1ca29238e442be820a2eb0d0b6ff3287)
 - [change layouts for horizontal mode and vertical mode and fix margins](https://github.com/MycroftAI/skill-date-time/commit/b3a4dc799531fc79487de5e4e02bacb3d553dfe1)
 - [Merge pull request #93 from thorstenMueller/20.08](https://github.com/MycroftAI/skill-date-time/commit/21eea850b0fc16cba05084148d947fd1790af4ae)
 - [Merge pull request #92 from AIIX/fix/scaling-time-ui](https://github.com/MycroftAI/skill-date-time/commit/cda36c7bcd150e03136306ca4dfe9f2b65debe07)
 - [Adjusted intent handling according best practice](https://github.com/MycroftAI/skill-date-time/commit/c628403adee8cfd78f5fdad713c67286a4d8805f)
 - [Make it responsive for vertical or horizontal screen orientation](https://github.com/MycroftAI/skill-date-time/commit/24b212d8e995904d2cfd52a1068e94188dfaa711)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1424)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1424/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1424/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1424/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1424/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1424/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1424)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1424/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1424/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1424/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1424/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1424/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1424))

**Comment by krisgesling** [comment]
Creating new PR to resolve conflicts.

**Pull request closed without merging**
