### PR TITLE
Civicus Monitor Skill

### PR DESCRIPTION
**Pull request by DerekCaelin**
## Description:

**Skill scrapes the CIVICUS Monitor and returns an overview of the civic space status of the selected country.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x ] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by KathyReid** [comment]
Firstly @DerekCaelin thank you so much for submitting a Skill. I'm running this through our [Skills Acceptance Process](https://mycroft.ai/documentation/skills/skills-acceptance-process/) for the first time :-) 

## Summary
Test failed; could not install dependencies from `requirements.txt` via `pip`, log included below. 

#### Review of `civicus-monitor`

* Platform: Mark 1
* Device version: Version 18.2.4b
* Who: @kathyreid
* Datestamp: Tuesday 24 April  03:08:37 AEST 2018
* Language and dialect of tester: English native speaker, Australian accent

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. 
> Attempting to install using voice commands failed, but _only_ because the Skill is not yet in the repo. The `Utterance` is being interpreted  by STT correctly: 
`17:09:45.037 - mycroft.client.speech.main:handle_utterance:61 - INFO - Utterance: [u'install civicus monitor']`
So when the Skill is pulled into the repo, the voice installation _should_ work. 
No `Intent` collisions identified; there are no similar phonemes of existing Skills. 

> Installed Skill manually by doing: 
`msm install https://github.com/DerekCaelin/skill-civicus-monitor`

```
pi@mark_1:~ $ msm install https://github.com/DerekCaelin/skill-civicus-monitor
Searching for for 'https://github.com/DerekCaelin/skill-civicus-monitor'...installing
Installing from: https://github.com/DerekCaelin/skill-civicus-monitor
17:14:33.557 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
17:14:33.704 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
17:14:34.645 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-18.2.4-py2.7.egg/mycroft/configuration/mycroft.conf loaded
17:14:34.652 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-18.2.4-py2.7.egg/mycroft/configuration/mycroft.conf loaded
17:14:34.660 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
17:14:34.665 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/pi/.mycroft/mycroft.conf' not found
17:14:34.676 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
17:14:36.128 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/ HTTP/1.1" 301 106
17:14:36.134 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): api.mycroft.ai
17:14:37.061 - requests.packages.urllib3.connectionpool - DEBUG - http://api.mycroft.ai:80 "GET /v1/device HTTP/1.1" 302 0
17:14:37.065 - requests.packages.urllib3.connectionpool - DEBUG - Resetting dropped connection: api.mycroft.ai
17:14:38.781 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device HTTP/1.1" 401 38
17:14:38.795 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
17:14:40.768 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
17:14:40.782 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /opt/mycroft/web_config_cache.json loaded
17:14:40.786 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
17:14:40.790 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/pi/.mycroft/mycroft.conf' not found
Cloning into 'skill-civicus-monitor'...
remote: Counting objects: 52, done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 52 (delta 19), reused 52 (delta 19), pack-reused 0
Unpacking objects: 100% (52/52), done.
Checking connectivity... done.
  Setting up native environment...
  Installing requirements...
Collecting gensim (from -r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/04/a6/82ee7b14c204b82ec00e91fc6b67331cc7b28460ad72b2214384abd0e0a3/gensim-3.4.0.tar.gz (22.2MB)
    100% |████████████████████████████████| 22.2MB 10kB/s 
Collecting html5lib==1.0.1 (from -r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl (117kB)
    100% |████████████████████████████████| 122kB 520kB/s 
Collecting titlecase (from -r requirements.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/3b/78/5b9faa7b9288c9fa5a4fdb6989f5e675744511ab6cff0489a0c7744a4f6b/titlecase-0.12.0.tar.gz
Collecting bs4 (from -r requirements.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting numpy>=1.11.3 (from gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/0b/66/86185402ee2d55865c675c06a5cfef742e39f4635a4ce1b1aefd20711c13/numpy-1.14.2.zip (4.9MB)
    100% |████████████████████████████████| 4.9MB 5.3kB/s 
Collecting scipy>=0.18.1 (from gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/bd/f4/3882758754dc083fea6ea66a6e8ceef55e7df173d06a12a074612958800f/scipy-1.0.1.tar.gz (15.5MB)
    100% |████████████████████████████████| 15.5MB 15kB/s 
Requirement already satisfied: six>=1.5.0 in /usr/local/lib/python2.7/site-packages (from gensim->-r requirements.txt (line 2))
Collecting smart_open>=1.2.1 (from gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/4b/69/c92661a333f733510628f28b8282698b62cdead37291c8491f3271677c02/smart_open-1.5.7.tar.gz
Collecting webencodings (from html5lib==1.0.1->-r requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/site-packages (from bs4->-r requirements.txt (line 5))
Collecting boto>=2.32 (from smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/bd/b7/a88a67002b1185ed9a8e8a6ef15266728c2361fcb4f1d02ea331e4c7741d/boto-2.48.0-py2.py3-none-any.whl (1.4MB)
    100% |████████████████████████████████| 1.4MB 135kB/s 
Collecting bz2file (from smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/61/39/122222b5e85cd41c391b68a99ee296584b2a2d1d233e7ee32b4532384f2d/bz2file-0.98.tar.gz
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
Collecting boto3 (from smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/be/f4/f31ab2238dbeaeade9b7fd73fa663c7443f01395e544915b1d47f9a3dbd2/boto3-1.7.6-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 495kB/s 
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3->smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/d7/14/2a0004d487464d120c9fb85313a75cd3d71a7506955be458eebfe19a6b1d/s3transfer-0.1.13-py2.py3-none-any.whl (59kB)
    100% |████████████████████████████████| 61kB 556kB/s 
Collecting jmespath<1.0.0,>=0.7.1 (from boto3->smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/b7/31/05c8d001f7f87f0f07289a5fc0fc3832e9a57f2dbd4d3b0fee70e0d51365/jmespath-0.9.3-py2.py3-none-any.whl
Collecting botocore<1.11.0,>=1.10.6 (from boto3->smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/bd/7b/c4436ba14adda753c77cccb11c9ea200ada0f44b8b10ff6b3247d2de5041/botocore-1.10.6-py2.py3-none-any.whl (4.2MB)
    100% |████████████████████████████████| 4.2MB 9.9kB/s 
Requirement already satisfied: futures<4.0.0,>=2.2.0; python_version == "2.6" or python_version == "2.7" in /usr/local/lib/python2.7/site-packages (from s3transfer<0.2.0,>=0.1.10->boto3->smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
Requirement already satisfied: python-dateutil<3.0.0,>=2.1; python_version >= "2.7" in /usr/local/lib/python2.7/site-packages (from botocore<1.11.0,>=1.10.6->boto3->smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
Collecting docutils>=0.10 (from botocore<1.11.0,>=1.10.6->boto3->smart_open>=1.2.1->gensim->-r requirements.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/50/09/c53398e0005b11f7ffb27b7aa720c617aba53be4fb4f4f3f06b9b5c60f28/docutils-0.14-py2-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 317kB/s 
Building wheels for collected packages: gensim, titlecase, bs4, numpy, scipy, smart-open, bz2file
  Running setup.py bdist_wheel for gensim ... done
  Stored in directory: /root/.cache/pip/wheels/2a/5f/2d/04fe5cffea90fbba14c8eab40f519096c8558cceaaa6777048
  Running setup.py bdist_wheel for titlecase ... done
  Stored in directory: /root/.cache/pip/wheels/9f/fb/8f/4d61939e2447b1b8c13f6ceeca035383c14d4228e88b174402
  Running setup.py bdist_wheel for bs4 ... done
  Stored in directory: /root/.cache/pip/wheels/a0/b0/b2/4f80b9456b87abedbc0bf2d52235414c3467d8889be38dd472
  Running setup.py bdist_wheel for numpy ... done
  Stored in directory: /root/.cache/pip/wheels/bc/ba/1b/fc08644c866eeabad7ed3f5b8c5a0cfa93f6cc49e85831c1e9
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZvryKo/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpQnlobDpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-ZvryKo/scipy/setup.py", line 418, in <module>
      setup_package()
    File "/tmp/pip-build-ZvryKo/scipy/setup.py", line 398, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named numpy.distutils.core
  
  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZvryKo/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  
  `setup.py clean` is not supported, use one of the following instead:
  
    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)
  
  Add `--force` to your command to use it anyway if you must (unsupported).
  
  
  ----------------------------------------
  Failed cleaning build dir for scipy
  Running setup.py bdist_wheel for smart-open ... done
  Stored in directory: /root/.cache/pip/wheels/b1/9e/7d/bb3d3b55c597e72617140a0638c06382a5f17283881eae163e
  Running setup.py bdist_wheel for bz2file ... done
  Stored in directory: /root/.cache/pip/wheels/81/75/d6/e1317bf09bf1af5a30befc2a007869fa6e1f516b8f7c591cb9
Successfully built gensim titlecase bs4 numpy smart-open bz2file
Failed to build scipy
Installing collected packages: numpy, scipy, boto, bz2file, jmespath, docutils, botocore, s3transfer, boto3, smart-open, gensim, webencodings, html5lib, titlecase, bs4
  Running setup.py install for scipy ... error
    Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZvryKo/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-J5vlk4-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/site/python2.7/scipy:
    
    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:
    
      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)
    
    
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/arm-linux-gnueabihf
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/arm-linux-gnueabihf
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    /usr/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:624: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/arm-linux-gnueabihf']
      NOT AVAILABLE
    
    /usr/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE
    
    /usr/local/lib/python2.7/site-packages/numpy/distutils/system_info.py:624: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE
    
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ZvryKo/scipy/setup.py", line 418, in <module>
        setup_package()
      File "/tmp/pip-build-ZvryKo/scipy/setup.py", line 414, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-ZvryKo/scipy/setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 1024, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 993, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python2.7/site-packages/numpy/distutils/misc_util.py", line 930, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 19, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
    
    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ZvryKo/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-J5vlk4-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/site/python2.7/scipy" failed with error code 1 in /tmp/pip-build-ZvryKo/scipy/
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR: Unable to install requirements for 'skill-civicus-monitor', it may not work
18:16:23.255 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
18:16:23.414 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
18:16:24.710 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-18.2.4-py2.7.egg/mycroft/configuration/mycroft.conf loaded
18:16:24.722 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-18.2.4-py2.7.egg/mycroft/configuration/mycroft.conf loaded
18:16:24.727 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
18:16:24.732 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/pi/.mycroft/mycroft.conf' not found
18:16:24.747 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
18:16:26.546 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/ HTTP/1.1" 301 106
18:16:26.553 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): api.mycroft.ai
18:16:32.463 - requests.packages.urllib3.connectionpool - DEBUG - http://api.mycroft.ai:80 "GET /v1/device HTTP/1.1" 302 0
18:16:32.468 - requests.packages.urllib3.connectionpool - DEBUG - Resetting dropped connection: api.mycroft.ai
18:16:39.011 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device HTTP/1.1" 401 38
18:16:39.030 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
18:16:40.620 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
18:16:40.637 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /opt/mycroft/web_config_cache.json loaded
18:16:40.641 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
18:16:40.644 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/pi/.mycroft/mycroft.conf' not found
18:16:41.368 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
18:16:41.513 - root - INFO - Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
18:16:42.446 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-18.2.4-py2.7.egg/mycroft/configuration/mycroft.conf loaded
18:16:42.453 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /usr/local/lib/python2.7/site-packages/mycroft_core-18.2.4-py2.7.egg/mycroft/configuration/mycroft.conf loaded
18:16:42.458 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
18:16:42.463 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/pi/.mycroft/mycroft.conf' not found
18:16:42.475 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
18:16:44.967 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/ HTTP/1.1" 301 106
18:16:44.973 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): api.mycroft.ai
18:16:46.403 - requests.packages.urllib3.connectionpool - DEBUG - http://api.mycroft.ai:80 "GET /v1/device HTTP/1.1" 302 0
18:16:46.407 - requests.packages.urllib3.connectionpool - DEBUG - Resetting dropped connection: api.mycroft.ai
18:16:48.871 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device HTTP/1.1" 401 38
18:16:48.887 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
18:16:50.343 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/auth/token HTTP/1.1" 401 38
18:16:50.356 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /opt/mycroft/web_config_cache.json loaded
18:16:50.360 - mycroft.configuration.config:load_local:128 - DEBUG - Configuration /etc/mycroft/mycroft.conf loaded
18:16:50.364 - mycroft.configuration.config:load_local:133 - DEBUG - Configuration '/home/pi/.mycroft/mycroft.conf' not found
msm: error 121
```
 `msm: error 121` is 

```
121 Unable to install requirements for skill ${name} 
Each Skill is able to define pre-requisite software that has to be installed - requirements - in the files requirements.txt in the Skill directory. This error indicates that the requirements could not be installed. Dependencies in requirements.txt use pip, whereas dependencies in requirements.sh use bash. 

Identify why the requirements could not be installed, and if necessary, install them manually.
```
> Testing abandoned at this point because Skill failed to install, no functional testing undertaken. 

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`. 

> Check of the `dialog` directory indicates all dialogs are OK

* Check the **Intents** defined in the `vocab` directory. Determine if the **Intents** are likely to conflict with those from other **Skills**, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this. 

> Check of the `vocab` directory indicates a number of swap files - `swp` files - these should be cleaned up before a PR is made. Also, the `vocab` file could be simplified to use a `regex` instead of having "for" and "of" on separate lines - ie `{for|of}`. 

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this. 

> No regular expressions used

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? 

> README is complete

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros?

> The requirements, specified in `requirements.txt`, failed to install on my Mark 1 device, reason unknown. *This should be addressed*

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense? 

> no `settingsmeta.json` settings used.


FUNCTIONAL TEST ABORTED, CANNOT INSTALL

#### Python code checks of the Skill

* Linting - does the code pass Codacy PEP8 checks? 
* Inline documentation - is the code documented in line? 
* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies? 
* Callback check - do we need to do a check for the callback error that was in the Spotify Skill? 
* Error handling - are there any specific checks we make for error handling or graceful degradation? 
* Automatic tests - do automatic tests of the **Skill** pass?

^^^ Python code checks not done, I'm not a Python programmer

**Comment by DerekCaelin** [comment]
Hi Kathy,

Thanks for reviewing! I understand your feedback about the dialog files and
regex - will edit.

I'm surprised that it took so long to install 3 libraries - titlecase,
html5lib, and bs4. On my own raspberry pi each installed via pip in just a
few seconds. On reflection, gensim was a library from a sample skill and
can be removed!

Will adjust and resubmit.

D

**Comment by KathyReid** [comment]
Thanks so much @DerekCaelin, thank you for taking the feedback so positively!
Just let us know when the requirements are altered, and I'll run through again. 

Best, K.

**Comment by DerekCaelin** [comment]
Hi Kathy, thanks for this! Appreciate you working with me to improve this skill. I have:

- removed the swap files in vocab
- modified the phrase in monitor.voc using a regex
- removed the unused dialogs (you didn't mention this but it will be cleaner for other people looking at the code).
- updated requirements.txt to remove "gensim" which was leftover from a template

That last point is the bigee! I hope that removing gensim will make the other skills install.

**Comment by el-tocino** [comment]
This needs to be resubmitted without the other 100+ alterations attached.  Can you close this one and once you have that sorted send it back over?

**Comment by DerekCaelin** [comment]
OK. Will close and start again.

**Comment by DerekCaelin** [comment]
Hi,

Sorry, I'm not sure I know how to complete this request. I've attempted [to follow the instructions](https://mycroft.ai/documentation/skills/skill-submission/) for submitting my skill as a submodule, but everytime I do so I end up with 100+ revisions as the reviewer says because it removes the other files from the repo. I'm not sure how to avoid this. Couldn't it be possible only to accept the revisions pertaining to the skill-civicus-monitor skill and ignore the other changes?

Best Wishes,

Derek

**Comment by KathyReid** [comment]
Åke @forslund, would you mind reviewing the below to make sure my advice is correct? I'd like a second opinion on this one before we get @DerekCaelin to do another commit. 
------------------------
### Summary

@DerekCaelin submitted this Skill to `mycroft-skills` repo. I started the Skills Acceptance Testing process, but there were issues. Derek fixed the issues and added extra commits (thank you Derek). 
The PR now contains 104 modified files. 

### What Kathy thinks has happened
What I **think** has happened here is that the `mycroft-skills` version that Derek has cloned to submit against is out of date by several commits, hence why there are 104 modified files. 

### What is the way forward for this PR? 
I think that Derek needs to: 
* Close this PR
* Do a `git pull origin master` on the `mycroft-skills` repo that he has cloned
* Then push this to _his_ fork of `mycroft-skills`, and include the `civicus-skill` code in that push
* Open a PR from his fork of `mycroft-skills` against the MycroftAI/mycroft-skills repo

---------------------------------------

Or is there an easier way?

**Comment by DerekCaelin** [comment]
OK, I'll try following these instructions, Kathy.

**Pull request closed without merging**
