### PR TITLE
Add deckchair-cinema

### PR DESCRIPTION
**Pull request by krisgesling**
## Info

This PR adds the new skill, [deckchair-cinema](https://github.com/krisgesling/deckchair-cinema-skill), to the skills repo.

## Description

Deckchair Cinema is a unique outdoor cinema experience in Darwin, Australia. We are fully independent and screen films that are often unavailable to local audiences. For more information see deckchaircinema.com

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 18 Apr 2019 11:45am CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [ ] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> there is one minor error in the About section "... We are fully independent and screens films " screens should be screen.

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes.  Do you intend to use contracted words such as What's instead of What is?

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> not constrained to a particular device

- [x] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> yes

- [x] **Tags**
Are listed tags appropriate for this Skill?

> yes

- [ ] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> I do not see a license listed

**Comment by krisgesling** [comment]
Thanks Glen, can't believe I missed that!

Exactly why we have this process :)

**Comment by krisgesling** [comment]
`lxml` is failling to install on some devices

Investigating

**Comment by LinusSkucas** [comment]
@krisgesling One of the dependencies in my calendar also depends on `lxml`, and it takes a super long time to install. Also, to get `lxml` to install I had to add a requirements.sh file to install some packages:
```bash
#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install libxml2-dev libxslt-dev python-dev -y
sudo apt-get install python3-lxml -y
```
Just a little suggestion, hope that helps :smile:

More info about `lxml` installation: https://lxml.de/installation.html

**Comment by krisgesling** [comment]
Going to rewrite with beautiful soup and make it easier to replicate for other businesses.
Thanks for the comments all :)

**Pull request closed without merging**
