### PR TITLE
Upgrade moviemaster

### PR DESCRIPTION
**Pull request by builderjer**
This upgrades moviemaster to include the following new commits:

 - [Added new dialog](https://github.com/builderjer/moviemaster/commit/761b66c1708edc6d489beec0b58efc65524dacd1)
 - [Bug fix - API fallback](https://github.com/builderjer/moviemaster/commit/d7d48c761c4924c7fec79022cf1160f8fe57c952)
 - [Bug fix - Auto load default API on error](https://github.com/builderjer/moviemaster/commit/9299d079dff0566813ba2178d9e52b894010e210)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Am I right that this is only triggered if a user has input an API key in their settings and that key is invalid - presumably incorrect or expired?

**Comment by builderjer** [comment]
Yes, that is correct

**Comment by krisgesling** [comment]
Does this need to be added to line ~61 so that this also occurs in `on_web_settings_change`?
To test, I installed the skill, then changed the API key in settings to 'invalid', triggered an intent and it failed. 

I didn't pick this up before, but when you get a chance it would also be good to shift the phrase: "Falling back to the default A P I" to a dialog file so that it can get translated. Looks like TMDb have reasonable language support and you're already passing the device language along so I can see this Skill getting plenty of use globally :)

**Comment by builderjer** [comment]
Both are done.

**Comment by krisgesling** [comment]
Working great, thanks!

**Pull request merged**
