### PR TITLE
Add skill-openhab

### PR DESCRIPTION
**Pull request by mortommy**
## Info

This PR adds the new skill, [skill-openhab](https://github.com/openhab/openhab-mycroft), to the skills repo.

## Description

This skill adds [openHAB](http://www.openhab.org/) support to [Mycroft](https://mycroft.ai).
The skill takes advantage of the openHAB REST API, so it works both with the v1.x and v2.x of openHAB.

In order to make openHAB Items accessible to Mycroft, they need to be [tagged](https://www.openhab.org/addons/integrations/homekit/).
Device names recognized by Mycroft are matched against openHAB Item Labels.

The above examples would all work with the following set of openHAB Item definitons:

```java
Color DiningroomLight "Diningroom Light" <light> (gKitchen) [ "Lighting" ] {channel="hue:0200:1:bloom1:color"}
Color KitchenLight "Kitchen Light" <light> (gKitchen) [ "Lighting" ] {channel="hue:0200:1:bloom1:color"}
Switch GoodNight "Good Night"	[ "Switchable" ]

Number MqttID1Temperature "Bedroom Temperature" <temperature> [ "CurrentTemperature" ] {mqtt="<[mosquitto:mysensors/SI/1/1/1/0/0:state:default]"}
Number MqttID1Humidity "Bedroom Humidity" [ "CurrentHumidity" ] {mqtt="<[mosquitto:mysensors/SI/1/0/1/0/1:state:default]"}

Group gThermostat "Main Thermostat" [ "gMainThermostat" ]
Number MainThermostatCurrentTemp "Main Thermostat Current Temperature" (gMainThermostat) [ "CurrentTemperature" ]
Number MainThermostatTargetTemperature "Main Thermostat Target Temperature" (gMainThermostat) [ "TargetTemperature" ]
String MainThermostatHeatingCoolingMode "Main Thermostat Heating/Cooling Mode" (gMainThermostat) [ "homekit:HeatingCoolingMode" ]
```

If items are modified in openHAB, a refresh in Mycroft is needed by the command:

- *"Hey Mycroft, refresh openhab items"*

If you've forgotten what items have been identified, you can ask Mycroft:
- *"Hey Mycroft, list openhab items"*

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.14</sub>

### CODE REVIEW

**Comment by mortommy** [comment]
Hi,
I changed something after the last [suggestions](https://github.com/MycroftAI/mycroft-skills/pull/1163#issuecomment-574180034)

**Comment by mortommy** [comment]
any help?
thank you.

**Comment by ChanceNCounter** [comment]
I don't have openHAB to help test, but [this](https://jenkins.mycroft.team/job/20.02-skill-tester/427/console) is your culprit. It appears that the skill requires a boatload of configuration that Jenkins can't do/isn't doing (depends on the nature of the config and whether it requires third-party utilities.)

Your test expecting "item not found" is giving you, `Please add your open hab server details in the Skill settings at home dot mycroft dot AI` 

You might have to mock those tests - instead of asking it to check for data that doesn't exist in the tester's config files, feed it several instances of known-valid input *in place* of the normal function call.

This can have the unfortunate effect of modifying your actual code to accommodate tests, but it has the very desirable effect of ensuring full test coverage, even when CI can't. The vagaries of integrating software.

Alternatively, if there's some kind of public test-the-API server for openHAB (I really wouldn't know) then you could semi-mock the tests by setting the default value to the public test server *if and only if* you're invoking it via pytest.

---

Mycroft is also trying to move to a new test suite (see docs) but you'd still have the same problem, since it comes back to the absence of an openHAB server to access.

---

Currently, your skill is following "please add your open hab server details" with "okay, I found 0 items," rather than "I couldn't find that list," which is also something to address.

**Comment by mortommy** [comment]
Ok,
I understand it is difficult to test the skill with no openHAB instance, but for that limit in testing you are not providing the skill in the solution, people is using it and it is supposed to install the skill when you have openHAB installed. I wonder if the homeassistant skill got all those steps validated.

**Comment by ChanceNCounter** [comment]
The HomeAssistant skill appears to be mocking those tests, which is probably what you'll have to do as well.

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
