### PR TITLE
Add pokemon-skill

### PR DESCRIPTION
**Pull request by retrodaredevil**
## Info

This PR adds the new skill, [pokemon-skill](https://github.com/retrodaredevil/pokemon-skill), to the skills repo.

## Description

With this skill, you can ask Mycroft many different facts about Pokemon. The things you can ask it range from useful statistics such as when a Pokemon evolves or how effective a move is to a Pokemon's weight.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by penrods** [comment]
Nice skill idea!

At a glance I see a few things:

* The artwork is copyrighted and likely so is the character.  
See:  https://archives.bulbagarden.net/wiki/File:001Bulbasaur_AG_anime.png

May I recommend you instead use a more generic image, such as:  https://newvitruvian.com/explore/pokeball-clipart-transparent-tumblr/#gal_post_155_pokeball-clipart-1.png

Also, once you find appropriately (freely) licensed you should place it within your repo, otherwise the image you are referring to might disappear on you.

* Skill name
There is a bug in the Meta editor and it added a carriage return before "Pokemon Skill".   Place the name on the same line as the icon.

Also, we try to avoid "Skill" in a name because it is obviously a skill and looks odd when you have a list of skills.  Just "Pokemon" should work great.

* Requirements.sh
Please remove the unnecessary requirements.sh.  Although it technically is safe, I'd rather not leave the all-comment file to raise questions later.

**Comment by retrodaredevil** [comment]
Thanks for the reply @penrods.

I believe I fixed all the issues you said above and I think I merged it correctly.

To be clear about the name, is how I have it right now OK? The only thing I changed is the line: `super(PokemonSkill, self).__init__(name="Pokemon")`
If you'd like, I can rename my repo as well.

EDIT: No, I didn't merge it correctly, I'll try to fix it. It looks like the pokemon-skill module still exists.

**Comment by penrods** [comment]
The name within the code isn't a big deal, I was just talking about the user-visible one which comes from the README.md.  I created a PR on your repo with what I'm talking about.  The actual repo name is fine, just that presentation name.

**Comment by retrodaredevil** [comment]
Thanks for the PR. I've got it all merged in now. I've been using msk submit and submitting the changes to my fork. I forgot that msk update exists. I'll try that next time and hopefully the commits don't look as ugly as this.

**Comment by retrodaredevil** [comment]
@penrods is there anything else I should fix so this has a better chance of being accepted? If you'd like I can submit a new pull request so there's only one commit shown instead of 7. I'm not very experienced with pull requests but `msk submit` made it pretty easy.

Also is the fact that the Skill tester fails OK? I didn't create any tests for skill because I didn't want to rely on a database in a test.

**Comment by el-tocino** [comment]
The number of commits isn't a big deal.  If the tester fails against a different skill in its testing then it's not something for you to worry about.  If it is showing a problem with yours, then hopefully easily fixable and a new commit.

**Comment by retrodaredevil** [comment]
It looks like my skill is having some collisions with "how tall is Abraham Lincoln" and "spell happiness". I'll try to fix these collisions. So it's not really a problem with my skill, but I should still to fix these collisions as I'm assuming people might want to know how tall something other than a Pokemon is.

**Comment by el-tocino** [comment]
Abraham Lincoln isn't a pokemon?

**Comment by retrodaredevil** [comment]
No, he is. He's just not in the Pokedex. No one has ever caught him.

**Comment by retrodaredevil** [comment]
OK, all the tests are passing now. The first problem was with a fallback skill that tested for Abraham Lincoln's height. I got around this by making sure that the user also says either "Pokemon", or the Pokemon's name in the Intent. This isn't too big a deal, but for very few Pokemon, in order for that intent to trigger, you'll also have to say "Pokemon".

The other collision was was with the spelling skill. It's kind of a coincidence that one of the two tests in the spelling skill spelled out happiness.

Along with the two collisions I fixed, I believe I also made my skill a little bit more future proof, but not completely. Some words such as attack and defense will still trigger the skill. 

I'd be happy to change any Intents if you think they might cause collisions in the future. I also added a test to check for happiness. The test uses "What's Pikachu's base happiness" and gets data from the pokebase api. I'm not sure if it's frowned upon to use the internet in tests, but the test passed and it worked correctly.

Anyways, let me know if there's anything I can change.

**Comment by GPVM** [comment]
## Meta
* Who: [@GPVM](https://github.com/GPVM) / @gpvm
* Date and time: 15 Apr 2019 7:07pm CST
* Language and dialect of tester: English (Canada)

## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [x] **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

> yes

- [x] **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

> yes

- [x] **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

> yes

- [x] **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

> not constrained to a particular device

- [x] **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

> this passes but I wonder if this is more an Entertainment category (primary) than Information.  It is your choice but I would have looked first under Entertainment

- [x] **Tags**
Are listed tags appropriate for this Skill?

>

- [x] **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> Apache-2.0

**Comment by retrodaredevil** [comment]
Thanks. I'm going to add some commits to this pull request tomorrow. I'll make the primary category Entertainment and the commit will also make this a CommonQuerySkill.

**Comment by retrodaredevil** [comment]
I've finally added the commits to this pull request. If necessary, I can try to resolve the merge conflicts in my branch, but I figured I could leave that up to whoever merges this. If you'd like me to handle this on my branch, let me know.

The updates in that commit (or more specifically in the pokemon submodule's commit) make the skill a lot different because instead of using IntentBuilders like before, it uses the CommonQuerySkill. Just letting you know in case you tested the old version.

**Comment by krisgesling** [comment]
## Meta
*   Platform: Mark 1
*   Mycroft-core version: 19.2.4
*   Who: [@krisgesling](https://github.com/krisgesling) / @gez-mycroft
*   Datestamp: 2019-04-24_13:33_ACST
*   Language and dialect of tester: English with Australian accent

## 1. Code Review - secure and stable  
- [x] **Code Quality**  
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?  
_NOTE: We do not enforce PEP8 Checks on Skills_

> Excellent skill!
> I'm assuming the '. ' after and on [Line 200](https://github.com/retrodaredevil/pokemon-skill/blob/e767152c28d7225315c6020e4a4912b5352604ab/__init__.py#L200) is for verbal spacing?

- [x] **Error Handling**  
Are there any specific checks we make for error handling or graceful degradation?

> Yes, connection errors, pokemon not found etc.

- [x] **Libraries**  
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> Yes - Appropriate

- [x] **Required Dependencies**  
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.

> Yes - Pokebase

- [x] **Settings**  
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section". >

> NA

- [ ] **Integration Tests**  
Does the skill include sufficient integration tests, included in the `test` folder?

> No, recommend they be added.

_Action Required: Add some simple integration tests_

- [x] **Other Files**  
Are there any other files included that are unnecessary or you are unsure of their function?

> No

## 3. Functional Review - intuitive and expected  
- [x] **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Created fork to test install after removing requirements.sh and updating requirements.txt as above.
> Install method: `mycroft-msm -l install https://github.com/retrodaredevil/pokemon-skill`
> Output:  
> ```  
> INFO - Downloading skill: https://github.com/retrodaredevil/pokemon-skill
> INFO - Installing system requirements...
> INFO - Installing requirements.txt for pokemon-skill
> INFO - Successfully installed pokemon-skill
> ```  
>  
> Checking that STT transcribes correctly:  
> ```  
>  INFO - Utterance: ['install pokemon']
>  INFO - Best match (0.51): pokemon-skill.retrodaredevil by retrodaredevil
> ```

- [x] **Settings**  
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> NA

- [x] **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say ` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Extensive, well structured and clear dialog. Well done!

#### Skill Functions  
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described.

- [ ] **"what type is pikachu"**

> _WolframAlpha answered_
> >> Pikachu is an Electric‐type Pokémon
> `WARNING - pokemon-skill.retrodaredevil Answered too slowly,will be ignored.`

- [x] **"how tall is pikachu"**

> >> Pikachu is 0.4 meters

- [x] **"what is bulbasaur's base happiness"**

> >> Bulbasaur's base happiness is 70
> Great skill, but I'm also impressed that the STT is properly parsing Bulbasaur!

- [x] **"what is eevee's first evolution"**

> >> Eevee is in it's simplest evolution

- [x] **"what is eevee's final evolution"**

> >> Eevee's final evolution is...

- [x] **"how much does pikachu weigh in kilograms"**

> >> Pikachu weighs 6.0 kilograms

- [x] **"what are charizards evolutions"**

> >> Charizard evolves into Mega Charizard X and Mega Charizard Y

- [x] **"what is bulbasaurs base attack"**

> >> Bulbasaur's base attack is 49

- [x] **"What does Bulbasaur evolve into"**

> >> Bulbasaur evolves into Ivysaur at level 16

- [x] **"What does Charizard evolve from"**

> >> Charizard evolves from Charmeleon at level 36

- [x] **"How effective is a ground move against Pikachu"**

> >> Ground is super effective against

- [x] **"what generation was pichu introduced in"**

> >> Spiky-eared Pichu was introduced in...

- [x] **"what generation was pichu introduced in"**

> >> Spiky-eared Pichu was introduced in...

- [ ] **"what abilities does bulbasaur have"**

Text returns
> >> Bulbasaur has ability: Overgrow. and hidden ability: Chlorophyll

However is read by Mycroft as:
> "Bulbasaur has ability: . and hidden ability: "

This should not be happening but the quickest fix would be replace the colons with comma's in your dialog file. This doesn't seem to happen on responses from other dialog files.
_Action required: replace colons with commas in dialog file._

- [x] **"What is Static's flavor text in emerald"**

> >> Static: Paralyzes on contact.

- [x] **"What is Intimidate's flavor text in diamond"**

> >> Intimidate: Lowers the foe’s Attack stat.

- [x] **"Give me some info about the ability Static"**

> >> Static: Has a 30% chance of paralyzing attacking Pokémon on contact.

- [x] **"Give me some detailed information about the ability Static"**

> Detailed response provided.

- [x] **"What generation was Static first introduced"**

> >> Static was introduced in generation 3

## Summary  
Excellent Skill, there is clearly a lot of work and care that has gone into this!

* The only real bug I found was the abilities not always being read after a colon in `pokemon.abilities.hidden.non-hidden.dialog`. As the string is displayed correctly in the CLI it is clearly a speech synthesis bug, however I'd suggest changing those colons for comma's at least until we can track it down.
* WolframAlpha did answer the first query of what type Pikachu is, but only because it had the answer and was quicker. So no changes required there.
* Not sure if you intended to have a full-stop in line 200 or not.
* Would encourage you to add some simple [integration tests](https://mycroft.ai/documentation/skills/automatic-testing/). These will help during development, but also allow our automated tools to prevent intent conflicts as more Skills are added to the Marketplace. Please shout out if you want a hand understanding the structure of tests.

Once you have completed any updates, you can update this pull request by running 
`mycroft-msk submit /path/to/skill/directory`

Thank you for a fantastic Skill, I look forward to pushing this up to the Marketplace :)

**Comment by retrodaredevil** [comment]
Yes, line 200 was for verbal spacing. Now that you mention it, I will check that out and look at the difference from just replacing it with a comma. I'll see if I can replicate the `pokemon.abilities.hidden.non-hidden.dialog` bug you were talking about. I believe when I tested this, I used the new premium voice or the google assistant voice. Each voice sounds different from one another and has different verbal spacing.

So, I think I looked at creating tests, but I'm not really sure how to do tests for a skill based off of the CommonQuerySkill base class. I remember trying to create some, but I couldn't figure it out because it doesn't answer until after a message goes out to the messagebus, which that message is what the test picks up, not the answer that comes after that answer.

Thanks for the in depth feedback. I'll have some more commits on here in a few days.

**Comment by krisgesling** [comment]
Yeah apologies, that was the end of a looong day, you are right about the tests being a challenge for CQ skills at the moment so don't worry about that for now.

**Comment by retrodaredevil** [comment]
Sorry this took a week. I was working on another project and never got around to this. Anyway, I just fixed the verbal spacing and confirmed that yes, the ":" doesn't work on the "British Male (Default)" voice. Once that gets fixed I'd probably like to add back the colons so it sounds better. I was using a different voice so I didn't notice that. I also removed the full stop and it sounds fine. 

Let me know if there are any more changes I can do. Hopefully I'll get around to do them quicker this time.

EDIT: I just realized that the checks failed. It doesn't look like this is a problem on my end. Let me know if I have to do something about it.

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
Looks great, thanks @retrodaredevil!

**Pull request merged**
