### PR TITLE
Add mycroft-skill-allergy

### PR DESCRIPTION
**Pull request by mofadashi**
## Info

This PR adds the new skill, [mycroft-skill-allergy](https://github.com/mofadashi/mycroft-skill-allergy), to the skills repo.

## Description

With this skill users will be able to inquire what the allergy level will be for either today or tomorrow.
The results are pulled from pollen.com
The skill uses the mycrofts IP Address to determining the zip code(if you use VPN, it doesn't provide the correct reults)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by mofadashi** [comment]
Please advise why this build is failing.
Skill tester works successfully on my local dev box.
From travis ci log
`Failed to recurse into submodule path 'mycroft-skill-allergy'

The command "eval git submodule update --init --recursive " failed. Retrying, 2 of 3.

fatal: No url found for submodule path 'mycroft-skill-allergy/src/adapt-parser' in .gitmodules

Failed to recurse into submodule path 'mycroft-skill-allergy'`

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Hi, may I ask why you include adapt as a submodule to this skill? it should always be available to the skill since it's included in Mycroft.

**Comment by mofadashi** [comment]
I just deleted the adapt, but I have the same issue as last time

**Comment by forslund** [comment]
Hnmm, the submitted version of the skill still has the adapt-parser submodule: https://github.com/mofadashi/mycroft-skill-allergy/tree/2debe1ec64b3895d9de9c4fede446bf71c06050e

**Comment by mofadashi** [comment]
can you point out where is the adapt-parser submodule ? I didn't figure it out, thankyou

**Comment by krisgesling** [comment]
under the `src` directory
https://github.com/mofadashi/mycroft-skill-allergy/tree/2debe1ec64b3895d9de9c4fede446bf71c06050e/src

**Comment by mofadashi** [comment]
thank you for your help, I checked it, and delete it and resubmit my skill

**Comment by mofadashi** [comment]
@krisgesling  does everything look good to be merged?

**Comment by krisgesling** [comment]
Hi there, 

To be included in the Marketplace the Skill goes through three reviews by our Skill Testing Team. You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

This can take some time as we have a limited number of Community testers and the internal team have been focused on the Mark II. 

If you are interested in helping out, we always need more testers on the team. You can read more about the process in [our docs](https://mycroft.ai/documentation/skills/skills-acceptance-process/) or sign up to the Skill Testing Team here:
https://mycroft.ai/contribute/#suggest-and-test-skills

Anyone that helps out by reviewing other peoples Skills gets bumped to the top of the queue for a review of their Skill :slightly_smiling_face:

**Comment by LinusSkucas** [comment]
# Skills test for Allergy 🤧 

## Meta
*   Platform: Picroft
*   Mycroft-core version: 19.08
*   Who: [@LinusS1](https://github.com/linuss1) Mattermost/forum: brrn
*   Datestamp: `2020-01-05_17:28:33_PST` First skill test of 2020! 🎉 
*   Language and dialect of tester: (American) English

## 0. Automated tests
Are all automated tests passing?
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable
- [ ]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

>Instead of using the IP address to find a zip code, consider using the api which gets the location of the mycroft unit from mycroft home. This way it is more accurate, and users in the future may be able to grant location access as they wish.

- [ ]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

> No error handling - Maybe a bit more here for when a request does not go through, or when something breaks.

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

>Just requests

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.
Also check to see if `requirements.txt` and `requirements.sh` are empty, if they are, they can be deleted.

>Good. Consider using a manifest file, which can be more versatile, but just a suggestion.
Docs for manifest file: https://mycroft-ai.gitbook.io/docs/skill-development/dependencies/manifest-yml

- [ ]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

>Please delete the unneeded settingsmeta.yml file, as it is unneeded.
Also, please delete the settings.json file.

- [x]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

>Decent tests


- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

>All good - Files are a bit spread out, but that's better than cramming it into on `__init__.py` file! 😄 


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

- [ ]   **Icon**
Does the Skill have an appropriate icon that is either included in the repo or linked from an appropriate place (eg raw.githack.com not privateicons.com or rawgit.com)?

>Instead of using the default robot icon, go to fontawesome.com and pick a new icon.

- [x]   **Description**
Are the title, short description, and long description (under 'About') clear and concise? Do they provide enough information to understand what the Skill does? Does the title have the word "skill" included? This is strongly discouraged.

>Okay description, maybe make it a bit longer(?)

- [x]   **Examples**
Do the examples give you a clear understanding of how you can use the Skill? Is there a single example per dot-point?

>Good

- [x]   **Supported Devices**
If relevant, are the supported devices listed? An example might be a Skill that requires the screen of the Mark II. If the section is not present, all devices are considered supported.

>all

- [x]   **Categories**
Is there at least one category listed? At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai).
Is the bolded category the most appropriate for this Skill? The bold category is considered the primary category and will be used for display in the [Marketplace](https://market.mycroft.ai/), all others are secondary and used for search results.

>daily, information

- [x]   **Tags**
Are listed tags appropriate for this Skill?

>allergy

- [ ]   **License**
Is an appropriate LICENSE file used in the repo - such as Apache-2.0 or GPL-3.0?

> 🛑 ⚠️ All skills (and software) **need** a license to be used. At mycroft, we use apache, but you can choose whatever license you want: choosealicense.com


## 3. Functional Review - intuitive and expected
- [x]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> My microphone is broken right now, but I'm pretty sure `"Install allergy skill"` works 😄 

- [ ]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

> Please delete the settings.json file and the settingsmeta.jsom file

- [x]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

>Sounds good

#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described. Also check that the sample utterances activate the skill

- [x]   **"How are the allergies today"**
The allergies today are low and 0.1 

>Good however I don't know what 0.1 means - maybe it could say something like and the allergy level is 0.1?

- [x]   **"how is the allergy level tomorrow"**
The allergies tomorrow are low and 0.1
>Nice, even the curveball I threw at it worked 😃 


## Summary
 - [ ] Please use the mycroft home api from mycroft core to get the location
 - [ ] Add error handling
 - [ ] Delete the settings.json file
 - [ ] Delete the settingsmeta.yaml file
 - [ ] Choose a different icon than the default icon
 - [ ] Add a license
 - [ ] Make it clear what the number in the response is

> This is a really useful skill - just complete these updates, and we'll be good to go!


Once you have completed any updates, you can update this pull request by running `msk submit /path/to/skill/directory`

**Comment by krisgesling** [comment]
Thanks for the review Linus!


@mofadashi - The location of the unit is actually provided as a property on the MycroftSkill class. So you can grab this by referencing `self.location`. This will give you an object with location data but does not include a zipcode, eg:
```
{
    "city": {
        "code": "Lawrence",
        "name": "Darwin",
        "state": {
            "code": "AU.03",
            "name": "Northern Territory",
            "country": {"code": "AU", "name": "Australia"},
        },
    },
    "coordinate": {"latitude": -12.46113, "longitude": 130.84185},
    "timezone": {
        "code": "Australia/Darwin",
        "name": "Australia/Darwin",
        "dstOffset": 3600000,
        "offset": 34200000,
        "dst_offset": 34200000,
    },
}
```
Does the API handle look ups by City and State, or coordinates?

Alternatively, you could ask users to set a zip code. We haven't needed it so we don't collect it by default.

**Comment by mofadashi** [comment]
The API doesn't accept city/state or coordinates being passed. Is the IP
address method acceptable? Or do I need to add functionality to request /
store / retrieve the zip code as a config item? Is there any chance the zip
code will be added to the mycroft properties?

**Comment by krisgesling** [comment]
No, I highly doubt we will add zip code anytime soon. 

Could you use something like [GeoPy](https://geopy.readthedocs.io/en/stable/#module-geopy.geocoders) and extract the zip code from the `geopy.location.Location` object's  `address`?

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
