### PR TITLE
Add caffeineWiz

### PR DESCRIPTION
**Pull request by NeonDaniel**
## Info

This PR adds the new skill, [caffeineWiz](https://github.com/NeonGeckoCom/CaffeineWiz.neon), to the skills repo.

## Description

The skill provides the functionality to inform the user of the caffeine content of the requested drink by collecting the required information from two data sources:

1.  [http://caffeinewiz.com/](http://caffeinewiz.com/) - the main source of information for the drink’s database
2.  [https://www.caffeineinformer.com/the-caffeine-database](https://www.caffeineinformer.com/the-caffeine-database) - secondary source for any non-duplicate drinks

CaffeineWiz uses [BeautifulSoup](https://www.crummy.com/software/BeautifulSoup/bs4/doc/) to pull the tables from the websites above, then strips the html tags, and later formats the results into the comprehensive list. That object is pickled for the future use.

The skill will check for updates periodically. You can modify that time period by changing `TIME_TO_CHECK` parameter on top of the file in the init.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1462)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1462/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1462/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1462/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1462/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1462/logs/enclosure.log)

**Comment by krisgesling** [comment]
Hi Daniel,

Thanks for submitting your Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running:
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir`

In terms of the failed test, it looks like your Skill is responding very broadly for example the test utterance: "What is a dinkel floep" has provided a response for the drink "ink". 

I had a very quick glance at your Skills code and thought you might be interested in a few newer methods we have available:
- [`self.file_system`](https://github.com/MycroftAI/mycroft-core/blob/dev/mycroft/filesystem/__init__.py) gives you access to a Skill namespaced filesystem that is read-writeable (eg `~/.mycroft/skills/MySkill`). That isn't guaranteed for the Skills directory.
- It's good to use the [translate methods](https://mycroft-core.readthedocs.io/en/master/source/mycroft.html#mycroft.MycroftSkill.translate) for any text in the Skills code that will be used in dialog eg [here](https://github.com/NeonGeckoCom/CaffeineWiz.neon/blob/f44e7afdf30ea3bbcce151bc313473a4d1c2fcee/__init__.py#L461). They do need to be added to your dialog directory, but means it will translate the entire string.

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by NeonDaniel** [comment]
Thanks for the feedback. I will look into the broad matches and try and adjust the confidence levels for the CommonQuery reply.

I'll also take a look at the new methods as well, thanks for highlighting those!

**Comment by NeonDaniel** [comment]
Accidentally uploaded changes to new PR #1466 due to case change in the branch name. Closing this PR as it is superseded.

New PR addresses feedback from @krisgesling

**Pull request closed without merging**
