### PR TITLE
Upgrade mycroft-timer

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-timer to include the following new commits:

 - [Merge pull request #78 from MycroftAI/bugfix/clear-xfails](https://github.com/MycroftAI/mycroft-timer/commit/6701e55565b80b00a7aaad95f098f9de08717ac3)
 - [remove steps that have been added to 20.08](https://github.com/MycroftAI/mycroft-timer/commit/dcba5266df06b289ad7ab87e00e5127fc31fcc7a)
 - [fix xfail tests with new vocab](https://github.com/MycroftAI/mycroft-timer/commit/9617481fb506f82d5b7fcd9628450ed241cb5785)
 - [Merge pull request #76 from MycroftAI/bugfix/triggering-on-alarm](https://github.com/MycroftAI/mycroft-timer/commit/e489387764008af37cf420c46ad4806f37890c6a)
 - [minor pylint fix](https://github.com/MycroftAI/mycroft-timer/commit/8c4550ecb5eb26e8e7dbd8065e024c46504a0f56)
 - [improve stopping vocab and fix failing test](https://github.com/MycroftAI/mycroft-timer/commit/50735635c024837aa3bae57f65bb7186b254bb37)
 - [remove phrases already caught by adapt](https://github.com/MycroftAI/mycroft-timer/commit/a3792452da7cdaa4c6a8ae41f4a594c963ee9d4d)
 - [add tests that should not reply](https://github.com/MycroftAI/mycroft-timer/commit/abcbadd4a9a1384a8c6f21f5711c2b5266d3ce2f)
 - [Merge pull request #72 from MycroftAI/feature/delay-beep](https://github.com/MycroftAI/mycroft-timer/commit/b93f2f3effcdeff8905005fe50a4b7b417643369)
 - [Merge pull request #69 from devs-mycroft/translations](https://github.com/MycroftAI/mycroft-timer/commit/21761b83cec1942028475083e65832de5f27f344)
 - [refactor busy detection](https://github.com/MycroftAI/mycroft-timer/commit/23ad4096720220225a285b49f40578149849b839)
 - [prevent beep between wake word and 'stop'](https://github.com/MycroftAI/mycroft-timer/commit/3fe655545a2b7daa75f97ab08066af67fe673e73)
 - [Merge pull request #71 from MycroftAI/refactor](https://github.com/MycroftAI/mycroft-timer/commit/da9253749016c5aaae3b98d1f7e94f8dc651210b)
 - [untag non-failing tests](https://github.com/MycroftAI/mycroft-timer/commit/d71206a2fa98dafdf39968fd9403327bc73af2f1)
 - [fix - remove self reference from staticmethod](https://github.com/MycroftAI/mycroft-timer/commit/e068289a6075404ad14cc5d310e457c1c9c22d92)
 - [Merge branch '20.02' into refactor](https://github.com/MycroftAI/mycroft-timer/commit/f7e531308cdb3f217c69942d92dd5c40e944cf43)
 - [refactor - minor refactor](https://github.com/MycroftAI/mycroft-timer/commit/a134603ccb3a2475d4ed747fa1aa25a62fddb6c5)
 - [refactor - docstrings PEP257 compliant](https://github.com/MycroftAI/mycroft-timer/commit/1092cffc224b571b5c80819a549f84cf7302cf8b)
 - [refactor - code styling](https://github.com/MycroftAI/mycroft-timer/commit/d76997a351b39e3f48bda6ab97e8c3d090457801)
 - [refactor - cleanup imports](https://github.com/MycroftAI/mycroft-timer/commit/814d5b1fa8e741fd4b9ebfab762fc771d2344b7d)
 - [refactor - abstract time remaining calculation](https://github.com/MycroftAI/mycroft-timer/commit/b1459909534e8d59941ae2fb88a116ed8063f114)
 - [Update translations](https://github.com/MycroftAI/mycroft-timer/commit/77d0be5109ca7228ce6a0dac6dcb7de3b0d4cdff)
 - [Merge pull request #68 from devs-mycroft/translations](https://github.com/MycroftAI/mycroft-timer/commit/458e23fe55418488866a2bf2703f89c3ee0683df)
 - [Update translations](https://github.com/MycroftAI/mycroft-timer/commit/a3ca31b194419c2eb699ead51c5629c0ec0af9b8)
 - [Merge pull request #65 from MycroftAI/conversation-tests](https://github.com/MycroftAI/mycroft-timer/commit/763dde5ccf7255898726cc2aba434e6c10b5b980)
 - [Merge branch '20.02' into conversation-tests](https://github.com/MycroftAI/mycroft-timer/commit/b6992d32e04937452d8146cb0351752d81db549c)
 - [Merge pull request #67 from MycroftAI/test/disable-even-more](https://github.com/MycroftAI/mycroft-timer/commit/6f3d3392864238fe9e6e55fdf71572f56bcfa908)
 - [Disable a couple of randomly failing examples](https://github.com/MycroftAI/mycroft-timer/commit/67aea52f7fd3a48a5f5bcaec006bcf6e5ee1bf1b)
 - [added # Jira ticket links to the @xfail](https://github.com/MycroftAI/mycroft-timer/commit/81a4f03147a746a0ba555c59f6d237db7355463c)
 - [Merge pull request #66 from devs-mycroft/translations](https://github.com/MycroftAI/mycroft-timer/commit/f906a1bfae246c4de917b512a5547b0d5bdf5441)
 - [Update translations](https://github.com/MycroftAI/mycroft-timer/commit/ef7bdde4779e8c487c94acfd1e9bbb8198c51854)
 - [added a scenario with jibberish conversation](https://github.com/MycroftAI/mycroft-timer/commit/fb215c4eff26b72d22729093427318c2f3bb2fe3)
 - [Added dismiss and nevermind scenarios to setting a timer conversations](https://github.com/MycroftAI/mycroft-timer/commit/d6e1af47ae050fca7dec5451b735bb276318f263)
 - [added # Jira ticket links to the @xfail](https://github.com/MycroftAI/mycroft-timer/commit/66baced29fe7f2d115f5ccbb6f11c96f9d7d6170)
 - [Merge pull request #64 from MycroftAI/feature/validate-duration](https://github.com/MycroftAI/mycroft-timer/commit/a08a89a61c222993f19f4a5ca8d5727dbbe01d3a)
 - [Validate the response when asking for a timer length](https://github.com/MycroftAI/mycroft-timer/commit/fa948222061d95d8865497bd207039fbfc9c6015)
 - [Merge pull request #63 from MycroftAI/behave-title-fix](https://github.com/MycroftAI/mycroft-timer/commit/49d86c314919d77b8e5da9e821bbbae4101e3fe6)
 - [Add a couple of xfail's](https://github.com/MycroftAI/mycroft-timer/commit/e6a7be7bfbd5d8014ef56f8a931326397afd4dfd)
 - [Added "started.ordinal.timer.with.name.dialog" Scenario](https://github.com/MycroftAI/mycroft-timer/commit/94c119d35a5b9fcbb6d896915bb42a64eaeedf67)
 - [changed table titles to be generic instead of utterance examples](https://github.com/MycroftAI/mycroft-timer/commit/8c13ea83e0c10c28c73edb844e17fec3b08b1b1d)
 - [Merge pull request #62 from MycroftAI/bugfix/test-speedup](https://github.com/MycroftAI/mycroft-timer/commit/4ba69dfacffdca214b93976903d3fea0714a4279)
 - [move "disable" stop command test to @xfail](https://github.com/MycroftAI/mycroft-timer/commit/afb3ca8987151b11d97e7d87b84747289ab0672c)
 - [Add correct dialog to wait for to speed up the tests](https://github.com/MycroftAI/mycroft-timer/commit/15f10b4a5c21b984aab016b7388793f84789ed95)
 - [Fix chicken timer](https://github.com/MycroftAI/mycroft-timer/commit/1c1d5fa1be5dd1cd5ac61fec9dce3193e1af3f46)
 - [Merge pull request #61 from MycroftAI/bugfix/rm-backup](https://github.com/MycroftAI/mycroft-timer/commit/905b24cd62a03a3c02dee9ff739613a00af1456f)
 - [Move "mute" to expected failures](https://github.com/MycroftAI/mycroft-timer/commit/265a7f71e1a8e45520222bdb6bf70dd5671c721c)
 - [Remove backup](https://github.com/MycroftAI/mycroft-timer/commit/35cb18c3b551f14e1e62e4cce00323c82efa6739)
 - [Merge pull request #60 from MycroftAI/feature/voight-kampff](https://github.com/MycroftAI/mycroft-timer/commit/4d7b02f25497021b2dc145ce005cb5e99475d633)
 - [Update with expected failures and corrections](https://github.com/MycroftAI/mycroft-timer/commit/27dc681a2c7b74e692c5cb80f0bb285abc3e8fcd)
 - [fixed some typos, removed @xfai](https://github.com/MycroftAI/mycroft-timer/commit/e0834ce337edf4415ddbc09ba240bedc53e3e059)
 - [changed scenarios for cancelled a name timer and cancel a specific timer](https://github.com/MycroftAI/mycroft-timer/commit/4ba63ecca62bfd2b77ebd378afdbf06f3549918d)
 - [Add step file for custom timer steps.](https://github.com/MycroftAI/mycroft-timer/commit/bda67e6053ba50d0b34fe11bdc0c07f19a590b55)
 - [Added And the volume is set to 5/max/mute for several of the scenarios](https://github.com/MycroftAI/mycroft-timer/commit/fb56bfae536e2c286548641526fd92b9311b0359)
 - [added given "and no timers are previously set"](https://github.com/MycroftAI/mycroft-timer/commit/fd7008015e0cc6523499e2418956cdc93d29eae4)
 - [fixed spelling](https://github.com/MycroftAI/mycroft-timer/commit/4e6b3744a510e6423a6d18f127bdec7c6dc2c363)
 - [Changed Scenario Outline Status of two timers](https://github.com/MycroftAI/mycroft-timer/commit/0d64b23bc1cbddd80c807d58eeddebadd6bfd0e8)
 - [Added Behave folder and Feature files for TImer](https://github.com/MycroftAI/mycroft-timer/commit/3471900b82a3e24dc3ada48f5d39e74edd65bff1)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1402)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1402/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1402/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1402/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1402/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1402/logs/enclosure.log)

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Tested locally and seems to work. If the autobots succeeds I say merge it :)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1402)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1402/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1402/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1402/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1402/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1402/logs/enclosure.log)

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Pull request closed without merging**
