### PR TITLE
Add laugh

### PR DESCRIPTION
**Pull request by JarbasAl**
## Info

This PR adds the new skill, [laugh](https://github.com/JarbasAl/skill-laugh), to the skills repo.

## Description

about

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Comment by JarbasAl** [comment]
same as https://github.com/MycroftAI/mycroft-skills/pull/602  , accidentally delete my fork of skills repo and can not update previous PR

**Review by KathyReid — CHANGES_REQUESTED** [review]
###  Meta
* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.8.5 stable
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Wed 14 Nov 16:08:58 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.
> `~~~~:39.335 - __main__:handle_utterance:61 - INFO - Utterance: ['install laugh']`
> Skill is not yet installed so voice install won't work. Using `mycroft-msm` install. 
```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ bin/mycroft-msm install https://github.com/JarbasAl/skill-laugh
INFO - Downloading skill: https://github.com/JarbasAl/skill-laugh
INFO - Successfully installed skill-laugh
```
=> Installed OK, no requirements or deps specified

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran the `dialog` through `mimic` - all good

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Intents look look, unlikely to overload other Skills

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> README looks good, Primary Category makes sense

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> no dependencies specified, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Couple of comments about the Settings; 
   - typing `male` or `female` is not user friendly. It would be better to use a `select` element with `option` elements. 
   - having just `male` or `female` is very binary thinking; ideally there would be a neutral option

=> I'm not going to hold back the Skill on this, but please consider for future iterations. 

### Python code checks of the Skill

* Inline documentation - is the code documented in line?
> Well documented

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> No dependencies

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> not required, skipping

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> errors degrade gracefully

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> checked, not used, all good

_NOTE: We do not enforce PEP8 Checks on Skills_

=> **ACTION REQUIRED** - there is no LICENSE file for this Skill - are you able to add a relevant license like Apache 2 or GPL as you prefer? 

### Functional checks

* `Hey Mycroft, laugh like Alexa`
> He laughed like Alexa :laughing: 

* `Hey Mycroft, random laughter`
> Random laughter output 

* `Hey Mycroft, do the evil laugh`
> scary af! ;-) 

### Test summary
Action is required before this Skill can be pulled in; 

* LICENSE file is required so that the license of the Skill is clear. 

Recommendations for future iterations of the Skill; 

* use `select` and `options` for the `settingsmeta.json`

**Comment by KathyReid** [comment]
One thing I've also noticed about this Skill is that the _random laughter_ happens periodically - I wasn't expecting this, and I don't know how to switch it off without uninstalling the Skill - is there a way to suppress the laugh?

**Comment by JarbasAl** [comment]
stop laughing  will stop it, the standard stop command/button press should also work

"having just male or female is very binary thinking; ideally there would be a neutral option"

  if you send gender neutral wav files i am glad to add more options, maybe a robot voice?


the random behaviour is on purpose, just like in the news a while back :D

**Comment by KathyReid** [comment]
This was resolved and merged in #724, closing

**Pull request closed without merging**
