### PR TITLE
Add meal-plan

### PR DESCRIPTION
**Pull request by mikejgray**
## Info

This PR adds the new skill, [meal-plan](https://github.com/mikejgray/meal-plan-skill), to the skills repo.

## Description

Suggests a meal for you to make, based on a short default list, but you can manage your own meals!

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1626)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1626/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1626/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1626/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1626/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1626/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Succeeded  ([Results](https://reports.mycroft.ai/skills/PR-1626))

**Comment by mikejgray** [comment]
@krisgesling Is there anything you need from me to get the review process started?

**Comment by krisgesling** [comment]
Hey Mike, sorry for the radio silence - we're really flat chat getting the release ready for the Mark II which is shipping next month. Once we hit code freeze for that I should have some time to get back to these.

**Comment by mikejgray** [comment]
RIP

**Pull request closed without merging**
