### PR TITLE
Add fallback-recommendations-skill

### PR DESCRIPTION
**Pull request by LinusSkucas**
## Info

This PR adds the new skill, [fallback-recommendations-skill](https://github.com/LinusS1/fallback-recommendations-skill), to the skills repo.

## Description

When Mycroft doesn't know something, he will look it up skills that could help you complete your intent. If he finds a skill, he will download it to your device.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by LinusSkucas** [comment]
Looks like travis is failing because it can't install the today in history skill:
`Failed to clone 'today-history.btotharye' a second time, aborting`

**Comment by forslund** [comment]
Thanks for notifying us. Will look into it asap

**Comment by LinusSkucas** [comment]
Just to note, that this was already tested here: #692 . The requested changes have been done.

**Comment by krisgesling** [comment]
Hi @LinusS1 - would you mind running `msk upload` again to pull in the latest commits from the `mycroft-skills` repo? It should just update this PR, and now that the archived skills have been removed from the submodules list, this should allow Travis CI to run properly.
Thanks!

**Comment by LinusSkucas** [comment]
Alright @krisgesling, I re submitted using msk, and it still won't pass the travis tests (And this time the skill tester tests). I'm going to close this pr off and create a new one.

**Comment by LinusSkucas** [comment]
Alright, new pr: #812

**Pull request closed without merging**
