### PR TITLE
Skill knock knock jokes

### PR DESCRIPTION
**Pull request by aussieW**
## Description:

In this skill a user interacts with Mycroft to tell a Knock Knock joke.

## Checklist:
  - [x] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [x] Skill has been tested and works
  - [x] README.md has been updated with the following:
  ```
  +[submodule "NAME OF YOUR SKILL"]
  +	path = name-of-your-skill-skill
  +	url = URL.FOR.YOUR.SKILL.git
 ```
 - [x] README.md has been updated with your skill phrase and description

### CODE REVIEW

**Comment by KathyReid** [comment]
Thank you so much for your work on this Skill. This Skill was submitted to the `mycroft-skills` repo just before we implemented [Skill Branching](https://mycroft.ai/blog/skill-branching-18-02/). We'd really like to include this Skill in our 18.02 branch, however this means that the Skill would need to be re-submitted to the `18.02` branch. We also now have some helpful documentation available on [Automated Skills Testing]() and our new [Mycroft Skills Kit]() which assists with Skill submission. We also recently [dropped support for Python 2.7 and have moved to Python 3.4+](). We look forward to working with you to bring your Skill into the `18.02` branch.

**Comment by aussieW** [comment]
Hi Kathy, I will work on a new version when i get back home. Been travelling for 5 weeks with limited internet access so I have a lot of catching up to do.

**Comment by KathyReid** [comment]
No worries mate, safe travels and sing out if you get stuck at all :-)

**Comment by KathyReid** [comment]
Leaving open as Skills Author intends to update Skill for Python 3 shortly

**Comment by aussieW** [comment]
I have submitted this under a new pull request using msk. I will close this one off.

**Pull request closed without merging**
