### PR TITLE
Add reddit-news

### PR DESCRIPTION
**Pull request by makew0rld**
## Info

This PR adds the new skill, [reddit-news](https://github.com/makeworld-the-better-one/reddit-news-skill), to the skills repo.

## Description

This skill scrapes from r/worldnews using a GET request, and then has mycroft read five of the headlines.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
## Meta

* Platform: Linux Ubuntu 18.04 LTS
* Device version: 18.8.9 `dev` branch
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Fri  4 Jan 04:05:52 AEDT 2019
* Language and dialect of tester: English native speaker, Australian accent

## Standard checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> new Skill; it won't be available for voice installation. Checking that the STT correctly transcribes. 
`~~~~7 - __main__:handle_utterance:62 - INFO - Utterance: ['install reddit news']`
> STT transcription of Skill name is OK. Proceeding to do an `msm install`

```bash
(.venv) kathyreid@kathyreid-ubuntu-X510UQ:~/mycroft-core$ msm install https://github.com/makeworld-the-better-one/reddit-news-skill
WARNING - No such default skill: plasma-user-control-skill
INFO - Downloading skill: https://github.com/makeworld-the-better-one/reddit-news-skill
INFO - Successfully installed reddit-news-skill
```
> Successfully installed Skill

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran each of the `dialog` files through `mimic`. All good. 

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Because the `IntentHandler` _requires_ the `Reddit` keyword, there should be no Intent Collisions. 

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> `regex` not used, skipping check

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> The README file has not been generated using the [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html) and is missing several components, such as Categories and Tags.

_ACTION REQUIRED: Please re-generate the README using the Meta Editor_

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> Not used, skipping check

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> Not used, skipping check

## Python code checks

* Is an appropriate LICENSE file used in the repo - such as Apache2 or GPL? 
> No, there is no LICENSE file
_ACTION REQUIRED_ - please add a license file - we recommend Apache 2 or GPL

* Inline documentation - is the code documented in line?
> The inline documentation is excellent

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?
> uses `requests` and `json`, fairly standard

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?
> n/a

* Error handling - are there any specific checks we make for error handling or graceful degradation?
> simple Skill; complex error handling not required

* Automatic tests - do automatic tests of the **Skill** pass?
> Yes

* Skill Settings using Python Booleans - Skill Settings were updated in August 2018 to use Python Booleans instead of text Boolean values used in Python 2.4. [This is a good example of the change to check for](https://github.com/MycroftAI/skill-date-time/pull/32/files?utf8=%E2%9C%93&diff=split)
> n/a

_NOTE: We do not enforce PEP8 Checks on Skills_

## Functional tests

* `Tell me the news from Reddit`
> Correctly provided the news

* `What's the news form Reddit`
> Correctly provided the news

* `random phrase with news and Reddit`
> Correctly provided the news

## Summary

* Please regenerate the README using the [Meta editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor.html)
* Please add a LICENSE file 

Otherwise, this Skill was neatly done! Thanks!

**Comment by makew0rld** [comment]
I'll do that in a couple of days. Thanks!

**Comment by makew0rld** [comment]
@KathyReid I've followed through with both requirements, the README is now correct and a LICENSE has been added.

**Comment by KathyReid** [comment]
Thanks so much @makeworld-the-better-one, there was just some very minor edits to the README - I made a PR which you can just merge then this will be ready to merge into `mycroft-skills` :-) 

Again, many thanks for all your efforts here, we really appreciate them. 

https://github.com/makeworld-the-better-one/reddit-news-skill/pull/1

**Comment by KathyReid** [comment]
This is just waiting on merging 
https://github.com/makeworld-the-better-one/reddit-news-skill/pull/1
then it can be merged into `mycroft-skills`

**Comment by makew0rld** [comment]
@KathyReid Sorry I took so long, your PR has been merged, and my skill be added now. Thanks!

**Comment by krisgesling** [comment]
Hi @makeworld-the-better-one thanks for merging those. The changes are in your repo but we need to update this PR to point to the latest commit before it can be merged into the Skills Marketplace.

You can do this using the Mycroft Skills Kit by running `mycroft-msk submit /path/to/your/skill/folder`

**Comment by krisgesling** [comment]
Hi @makeworld-the-better-one 

I'm going to close the PR for as it is against the 18.08 branch. 

If the changes you made are ready for our Skill Testing Team to check it out, please run `mycroft-msk submit /opt/mycroft/skills/your-skill-directory` and MSK will generate a new PR against the latest branch.

Thanks

**Pull request closed without merging**
