### PR TITLE
Add openhab-skill

### PR DESCRIPTION
**Pull request by mortommy**
## Info

This PR adds the new skill, [openhab-skill](https://github.com/openhab/openhab-mycroft), to the skills repo.

## Description

This skill adds [openHAB](http://www.openhab.org/) support to [Mycroft](https://mycroft.ai).
The skill takes advantage of the openHAB REST API, so it works both with the v1.x and v2.x of openHAB.

In order to make openHAB Items accessible to Mycroft, they need to be [tagged](https://www.openhab.org/addons/integrations/homekit/).
Device names recognized by Mycroft are matched against openHAB Item Labels.

The above examples would all work with the following set of openHAB Item definitons:

```java
Color DiningroomLight "Diningroom Light" <light> (gKitchen) [ "Lighting" ] {channel="hue:0200:1:bloom1:color"}
Color KitchenLight "Kitchen Light" <light> (gKitchen) [ "Lighting" ] {channel="hue:0200:1:bloom1:color"}
Switch GoodNight "Good Night"	[ "Switchable" ]

Number MqttID1Temperature "Bedroom Temperature" <temperature> [ "CurrentTemperature" ] {mqtt="<[mosquitto:mysensors/SI/1/1/1/0/0:state:default]"}
Number MqttID1Humidity "Bedroom Humidity" [ "CurrentHumidity" ] {mqtt="<[mosquitto:mysensors/SI/1/0/1/0/1:state:default]"}

Group gThermostat "Main Thermostat" [ "gMainThermostat" ]
Number MainThermostatCurrentTemp "Main Thermostat Current Temperature" (gMainThermostat) [ "CurrentTemperature" ]
Number MainThermostatTargetTemperature "Main Thermostat Target Temperature" (gMainThermostat) [ "TargetTemperature" ]
String MainThermostatHeatingCoolingMode "Main Thermostat Heating/Cooling Mode" (gMainThermostat) [ "homekit:HeatingCoolingMode" ]
```

If items are modified in openHAB, a refresh in Mycroft is needed by the command:

- *"Hey Mycroft, refresh openhab items"*

If you've forgotten what items have been identified, you can ask Mycroft:
- *"Hey Mycroft, list openhab items"*

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by mortommy** [comment]
Hi,
the skill it's now downloaded from the right repository. Tests failed I think because openHAB it's not installed.

**Comment by krisgesling** [comment]
run test

**Comment by krisgesling** [comment]
It looks like the Skill is installing. 

**The first two** failing tests are because of an intent conflict with the Weather Skill. It's particularly on phrases like:
- What's the humidity?
- What's the temperature?  

These are being interpreted by openhab as wanting the humidity/temperature from the item "the", eg "what's bedroom temperature". 

Currently `item.entity` accepts anything. I'm wondering if you could hold off registering that entity until you receive a list of items from the server, then populate a file and register the entity so only known items would match?

**The third test** failing is the openhab test
```
Traceback (most recent call last):
  File "/app/mycroft-core/mycroft/skills/mycroft_skill/event_container.py", line 66, in wrapper
    handler(message)
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 195, in handle_refresh_tagged_items_intent
    self.getTaggedItems()
  File "/opt/mycroft/skills/openhab-skill.openhab/__init__.py", line 125, in getTaggedItems
    requestUrl = self.url+"/items?recursive=false"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

You could test that `self.url is not None` either before calling `getTaggedItems()` or before assigning that variable. Alternatively you could shift the assignment of `requestUrl` into the `try` block immediately following it which should then get caught when it throws an exception. However if you intentionally caught it you could return the `configuration.needed.dialog`.

Curious that all of these passed previously but that's something I'll look into separately. Clearly the test runner failed in some way, possibly related to the git reference issue.

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
