### PR TITLE
Add Gui-Examples

### PR DESCRIPTION
**Pull request by AIIX**
## Info

This PR adds the new skill, [Gui-Examples](https://github.com/AIIX/Skill-Gui-Examples), to the skills repo.

## Description

Example skill to showcase Mycroft GUI supported delegates and skill displays

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Hi @AIIX I don't think you pushed the update you made to fix these issues.

**Comment by AIIX** [comment]
Hi @forslund have pushed fixes to the skill's master branch it does not seem to reflect here as the commit only shows the .gitmodule commit, Have submitted it via msk so not sure how to get it to reflect the changes and re-run the test here.

**Comment by forslund** [comment]
run `msk submit ...` again and this PR should be updated

**Comment by AIIX** [comment]
@forslund test seem to be failing in the auto tester again doesn't show exactly why except "failed to load skill" but when run locally they seem ok and don't report an error. Integration test output when run locally: https://pastebin.com/Z35FQjUu

**Comment by forslund** [comment]
I'll look at it. It may be that I need updated skill tester

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Looks good. Thanks @AIIX Merging now.

**Pull request merged**
