### PR TITLE
Upgrade moviemaster

### PR DESCRIPTION
**Pull request by builderjer**
This upgrades moviemaster to include the following new commits:

 - [changed movie that the intent is looking for](https://github.com/builderjer/moviemaster/commit/2e5f0231ed70b4e9bbdbe17358d625342ad740e8)
 - [Fixed start up message when using default API key](https://github.com/builderjer/moviemaster/commit/1434f7dea2f2e4980282462d3ad1868a230376b8)
 - [Updated README.md](https://github.com/builderjer/moviemaster/commit/987134560f4c21d64e9a5bcc75b59950ba017b01)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by builderjer** [comment]
One of the tests failed, and I'm not sure why.  Any help on fixing would be great!!

**Comment by forslund** [comment]
I'm on my phone but it looks a bit like film.title is a method and not an attribute. try `.title()`

**Comment by builderjer** [comment]
It was working correctly, it just had no information on the movie in the test.

**Comment by krisgesling** [comment]
Working great, thanks for the update!

**Pull request merged**
