### PR TITLE
Add telegram

### PR DESCRIPTION
**Pull request by luke5sky**
## Info

This PR adds the new skill, [telegram](https://github.com/luke5sky/telegram-skill), to the skills repo.

## Description

You need to create a telegram bot (via BotFather) and save the Bot Token, your ChatID and your MyCroft Device name on home.mycroft.ai under skill settings.
After this restart your MyCroft Unit.
You can now commmunicate with your MyCroft Unit via this bot.

Settings:
- BOT TOKEN (MANDATORY): Your bot token you got from BotFather
- MYCROFT DEVICE NAME (MANDATORY): Your Device name you configured on home.mycroft.ai - Devices - Registered Devices
- BOT TOKEN SECOND MYCROFT DEVICE (OPTIONAL): If you have a second Mycroft Device and you want to use this skill with it -> put your second bot token here (it has to be an other bot than the first one because telegram only allows one device to get updates from one bot)
- SECOND MYCROFT DEVICE NAME (IF YOU HAVE A SECOND DEVICE): Your Device name from your second Device you configured on home.mycroft.ai - Devices - Registered Devices
- USERNAME 1 (OPTIONAL): You do not need to put anything here, the skill does not use this field. It is only for yourself to know which Chat ID belongs to whom
- CHAT ID 1 (MANDATORY): You will get your Chat ID from the Telegram-Skill if you have configured BOT TOKEN (first field) and MYCROFT DEVICE NAME, saved and then write anything to the bot.
- USERNAME 2 (OPTIONAL): For second User if you have one
- CHAT ID 2 (IF YOU HAVE A SECOND USER): Same as CHAT ID 1 with Telegram-Account of second user

Detailed HowTo:

- Install this skill on your Mycroft Device

- Create a telegram bot:
Open Telegram App on your smartphone, click on the search symbol in the upper right corner<br/>
Search for BotFather and click on it<br/>
Now type /newbot hit enter<br/>
Botfather should reply with: Alright, a new bot. How are we going to call it? please chosse a name for your bot.<br/>
Give your bot a displayname like Mycroft<br/>
Botfather should reply with: Good. Now let's choose a username for your bot. It must end in bot. Like this, for example: TetrisBot or tetris-bot.<br/>
Give your bot unique username like lukesmycroftbot<br/>
Botfather should now give you your token for this bot<br/>
Save this token and don't post it online or send it to people, safety first!<br/>

Telegram documentation on botfather: https://core.telegram.org/bots#6-botfather

- Go to home.mycroft.ai - skills and search for the telegram-skills settings

- Copy/paste your token botfather gave you in the field BOT TOKEN (MANDATORY)

- Copy/paste your device name from home.mycroft.ai - devices in MYCROFT DEVICE NAME (MANDATORY)

- SAVE and wait till the settings are synced to your Mycroft Unit (or reboot your device to trigger the sync)

- Open Telegram App on your smartphone and search (upper right corner) for your bot (username or displayname) click on it and write test or hello to your bot
It should respond with: This is your ChatID: YOURCHATID

- Copy/paste this under CHAT ID 1 (MANDATORY)

- reboot your device to trigger the sync

- Your bot should send you this welcome message: Telegram-Skill on Mycroft Unit YOURUNIT is loaded and ready to use

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by luke5sky** [comment]
#687 i don't know why, but the last commit made a new pr (Maybe because GitHub could not get the repo-Name in PR 687?)

**Comment by KathyReid** [comment]
This was previously tested in #451 and issues were identified; I'm going to do a full re-test. 
This Skill has also been community-validated at https://community.mycroft.ai/t/testing-and-feedback-for-telegram-skill/4194

## Meta

* Platform: Ubuntu Linux 18.04 LTS
* Device version: 18.8.9
* Who: @kathyreid / @kathy-mycroft
* Datestamp: Fri 28 Dec 21:42:24 AEDT 2018
* Language and dialect of tester: English native speaker, Australian accent

## Standard checks

These were previously done in #451, there have been minor changes to the Skill, but not major rewrites, so just doing a cursory check. 

* The README has a broken link to the image, I've raised a PR to fix this; 
https://github.com/luke5sky/telegram-skill/pull/5

* The installation threw some errors; 

```
21:48:58.625 - telegram-skill_luke5sky - INFO - Telegram: Muting is off
~~~~l_luke5sky - INFO - No or incorrect Device Name specified! Your DeviceName is: ubuntu-X510UQ
~~~~ered an error: AttributeError("'TelegramSkill' object has no attribute 'telegram_updater'",)
~~~~- mycroft.skills.core:load_skill:159 - ERROR - Failed to load skill: telegram-skill.luke5sky
Traceback (most recent call last):
  File "/home/kathyreid/mycroft-core/mycroft/skills/core.py", line 143, in load_skill
    raise e
  File "/home/kathyreid/mycroft-core/mycroft/skills/core.py", line 139, in load_skill
    skill.initialize()
  File "/opt/mycroft/skills/telegram-skill.luke5sky/__init__.py", line 81, in initialize
    self.telegram_updater = Updater(token=self.bottoken) # get telegram Updates
~~~~croft-core/.venv/lib/python3.6/site-packages/telegram/ext/updater.py", line 129, in __init__
    private_key_password=private_key_password)
~~~~yreid/mycroft-core/.venv/lib/python3.6/site-packages/telegram/bot.py", line 116, in __init__
    self.token = self._validate_token(token)
~~~~ycroft-core/.venv/lib/python3.6/site-packages/telegram/bot.py", line 147, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
```
This might just be because my Skill Settings weren't set, but it might be useful to wrap some error checking around this. 

I followed the installation instructions, which were detailed and accurate, and was able to get the Skill working well - here are some screenshots both from Telegram and my `mycroft-core` instance. 

screenshot from 2018-12-28 22-36-36
screenshot from 2018-12-28 22-36-49


Functionally this is now working well, thanks @luke5sky 

## Summary

The only action required here before we can merge this in is to pull in the PR for the icon change in the README, then push that change to this repo.

**Comment by luke5sky** [comment]
run test

**Comment by luke5sky** [comment]
@KathyReid Thank you for the review and the PR (PR is merged).
Skill Tester throws an error in the Alarm skill, should not be related to the telegram skill

**Comment by KathyReid** [comment]
Thanks so much @luke5sky, confirming the Auto Tester errors are the "peaky alarm Skill failing on a Wednesday". LGTM, merging!

**Pull request merged**
