### PR TITLE
Add tv-remote-control

### PR DESCRIPTION
**Pull request by devvmh**
## Info

This PR adds the new skill, [tv-remote-control](https://github.com/devvmh/tv-remote-control-skill), to the skills repo.

## Description

This skill defines voice commands for controlling a tv. how this actually works is up to you - you'll need to install lirc or something and then create a shell script or something to actually turn on the tv.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1612)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1612/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1612/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1612/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1612/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1612/logs/enclosure.log)

**Comment by devvmh** [comment]
https://reports.mycroft.ai/skills/PR-1612 gives 404 not found? 

 I've updated to add tests, maybe this will help? Is there a way to retry?

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1612)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1612/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1612/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1612/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1612/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1612/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1612)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1612/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1612/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1612/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1612/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1612/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
