### PR TITLE
Upgrade mycroft-wiki

### PR DESCRIPTION
**Pull request by krisgesling**
This upgrades mycroft-wiki to include the following new commits:

 - [Merge pull request #70 from MycroftAI/feature/pymediawiki](https://github.com/MycroftAI/skill-wiki/commit/a38517cd3595825e7f00cfb40f4d0ab66b872c87)
 - [Merge pull request #71 from devs-mycroft/translations](https://github.com/MycroftAI/skill-wiki/commit/4887a3650b1b5d31fb2936c4bd09fef7ccf0940a)
 - [Merge pull request #72 from MycroftAI/bugfix/remove-fa-fa](https://github.com/MycroftAI/skill-wiki/commit/c8b62eb9f520655b9253053e83c10cb8fdb896cf)
 - [Remove incorrect Farsi language dir](https://github.com/MycroftAI/skill-wiki/commit/66c3fe699952fc2e7b9549a97bfc6cd6a6ae2315)
 - [Handle disambiguation results that contain a nested disambiguation](https://github.com/MycroftAI/skill-wiki/commit/e3f7e2ecc509648ce2dfad891b4462725c7e37ee)
 - [Catch connection errors from wiki.search](https://github.com/MycroftAI/skill-wiki/commit/d11332699a50846161a4c4ec1017f365df672e1a)
 - [Line too long](https://github.com/MycroftAI/skill-wiki/commit/c93dff65c1a379b7b4955bd5b86c299a9d2239f4)
 - [Split wiki text cleaning out to util function](https://github.com/MycroftAI/skill-wiki/commit/544232b1d190fcdb0921b67b0d1e6f6ea009b3f4)
 - [Style improvements - responding to feedback](https://github.com/MycroftAI/skill-wiki/commit/fab6da2476d3a482a009b90698549d65902ba3a2)
 - [Use system default font-family](https://github.com/MycroftAI/skill-wiki/commit/237a2d3da0374d8f7e1ee37a73be66b8a57ad26c)
 - [Use existing gridUnit alias in CardDelegate](https://github.com/MycroftAI/skill-wiki/commit/2ec0a827e5ba7a2377e57563f8018f83b5684a33)
 - [Remove unused GUI imports](https://github.com/MycroftAI/skill-wiki/commit/45989735354fe0824e438b3f893d9ff572f9116c)
 - [Update translations](https://github.com/MycroftAI/skill-wiki/commit/7baab2d379b4f6318c6551e282afc26af915961d)
 - [Catch additional Connection Error types](https://github.com/MycroftAI/skill-wiki/commit/c03e9a0443af6db4bb9f20cd52abfbb3b3ebaf94)
 - [gui released automatically by skill shutdown](https://github.com/MycroftAI/skill-wiki/commit/9d588bd6672baf1ab7d7415aa458e466ad423980)
 - [Bugfix - handle no result](https://github.com/MycroftAI/skill-wiki/commit/26bc2b2d0f4705ac270f3ffdd24e9e5328d6cdac)
 - [Clean all levels of Wikipedia headings](https://github.com/MycroftAI/skill-wiki/commit/37aba74c0ff9255fee617a109953e4f30777c2a9)
 - [Add license info to qml files](https://github.com/MycroftAI/skill-wiki/commit/14e39ddcfadb2c2e466bb426f7cb6a638978e894)
 - [Remove step that is now available in core](https://github.com/MycroftAI/skill-wiki/commit/b81c7ae958c74dec07b703f5e443c74630c43f3f)
 - [Add delay to reduce test runtime by factor of 4!](https://github.com/MycroftAI/skill-wiki/commit/509d55d64465e8fe49d740d9c9c5e2057ba04095)
 - [Add pytest cache to gitignore](https://github.com/MycroftAI/skill-wiki/commit/b65170a5034195314532bb5cbcf9342916b01dff)
 - [Further improvements to summary cleaning](https://github.com/MycroftAI/skill-wiki/commit/558167abc3603a8c016dad5ae229f10c9c0d638b)
 - [Remove rounding and cropping](https://github.com/MycroftAI/skill-wiki/commit/fc920c720078f02205b1f7e9b87a5efe6069e22e)
 - [Add todo - revisit duration of GUI during skills interaction sprint](https://github.com/MycroftAI/skill-wiki/commit/a7f7e570dbae99669834b317751391df302f5822)
 - [Clean up](https://github.com/MycroftAI/skill-wiki/commit/3ec03d42df0293838d10115021d7fa4d01ec7d63)
 - [Do not fetch image for 'tell me more'](https://github.com/MycroftAI/skill-wiki/commit/a78fbb4e432c6b14195c4a0b576e8bf7047ba909)
 - [Remove section headings from summary](https://github.com/MycroftAI/skill-wiki/commit/8d147bf7e747fc79064c27054794eee167a4e746)
 - [Add unit tests for wikipedia interface](https://github.com/MycroftAI/skill-wiki/commit/09c2dcfd291711a6e530006c4e35be905ba18593)
 - [Improve summary handling](https://github.com/MycroftAI/skill-wiki/commit/395b7f044320233db50314c24be631082e30e577)
 - [Add requests to Skill requirements](https://github.com/MycroftAI/skill-wiki/commit/cbdee6622b8858f34a5d1e8f467b7ef52836a0c8)
 - [Remove unused dependency](https://github.com/MycroftAI/skill-wiki/commit/366de094c585ed5e47ea45cca1b12c56ebf38437)
 - [Improved image fetching and display](https://github.com/MycroftAI/skill-wiki/commit/a5123f99bd6fa45f00c5ca56def22957b7c6552e)
 - [Add loading spinner for image](https://github.com/MycroftAI/skill-wiki/commit/87ff9304d2da7ee03b800bd068932b49c8ee325c)
 - [Add summary text page](https://github.com/MycroftAI/skill-wiki/commit/1b9330e9e30507d817a50b38ae4d0f7a82c2d47f)
 - [Add feature image per new design](https://github.com/MycroftAI/skill-wiki/commit/ac3b5a7e225224fe52090513e65c2a416b6d7f2f)
 - [extract topic for all wiki queries](https://github.com/MycroftAI/skill-wiki/commit/b0af237a38f5082aced8dc7b47b5b05cf7a89866)
 - [Show loading page as soon as answer is available](https://github.com/MycroftAI/skill-wiki/commit/c733d2cfe233ebabcd19727f31ee18c8a9d73d4b)
 - [Shift wiki specific methods out of the Skill](https://github.com/MycroftAI/skill-wiki/commit/4d00945891e1ecc8acb1cf609cdfe2b3a7aa22c5)
 - [Move Wiki class out of init file](https://github.com/MycroftAI/skill-wiki/commit/00abb42a753845d73b42322f6b2cbd8f5267e6e9)
 - [Remove dev logging](https://github.com/MycroftAI/skill-wiki/commit/92f668ca821fa62b7cdc6dab3361b947c88e0b7a)
 - [Add missing return types](https://github.com/MycroftAI/skill-wiki/commit/c7e398be93f9886d92922b86dc98a6c1acb86a31)
 - [Refactor Skill to use pymediawiki package](https://github.com/MycroftAI/skill-wiki/commit/2fd4b63107b87f9636aa02edf5dac66ea0d40092)
 - [Move excluded images to new submodule](https://github.com/MycroftAI/skill-wiki/commit/1652d4cf1a1fb1e9f7860a145b75ee5bd8223c45)
 - [Remove extra stop checking](https://github.com/MycroftAI/skill-wiki/commit/132f1c2ce164d8bbc34fbbbf7e4cb65b4b0535fd)
 - [Restore parralel lookups](https://github.com/MycroftAI/skill-wiki/commit/4dd5adfbfc005e5cf5867317b6d36929f081886a)
 - [Refactor answer trimming to common method](https://github.com/MycroftAI/skill-wiki/commit/953cbd3c9d4d58ef3dd6d04d778cb962af6c8056)
 - [Reorder methods for clarity.](https://github.com/MycroftAI/skill-wiki/commit/d5c0c707e27c034998455eaa0a5912fad7515a7d)
 - [AdaptIntent doesn't require empty strings](https://github.com/MycroftAI/skill-wiki/commit/45b61934dd65aa01e51592d5a356486061d07277)
 - [Improve constructor docstring](https://github.com/MycroftAI/skill-wiki/commit/8149b7335234c0a19f8f8e980732e23ea5d8f09b)
 - [Remove unused vocab sorting in constructor](https://github.com/MycroftAI/skill-wiki/commit/5447a0f9df144d2018bfe2a30b3d1dc6d10958cf)
 - [Extract wiki interface to submodule](https://github.com/MycroftAI/skill-wiki/commit/cfc39cad028e92c06a7d2699969e0b02efadd5c8)
 - [Make PageMatch.image a property](https://github.com/MycroftAI/skill-wiki/commit/f7028855137820fff50016af57e54089f329a543)
 - [Display article if answer is selected by CQS](https://github.com/MycroftAI/skill-wiki/commit/ed8ea97b353aac9d95bb0760bd6d4201f648b198)
 - [Fetch page once and use its summary.](https://github.com/MycroftAI/skill-wiki/commit/fe442aa34bf0dd10d3dc9b8b741d7e0abcd93848)
 - [Use patched wikipedia package to get better images](https://github.com/MycroftAI/skill-wiki/commit/704e75a34045a8b1fd0df42575f08d13e93a51f2)
 - [Ensure a space exists between joined sentences](https://github.com/MycroftAI/skill-wiki/commit/b8c6786ce15530f835c2eb7ce217f2b3ac7a06ae)
 - [Add title to GUI dict](https://github.com/MycroftAI/skill-wiki/commit/8236f1ae3e85731e7b63c485423dfafa902838d2)
 - [delay fetching image](https://github.com/MycroftAI/skill-wiki/commit/e80d2b94bd52d7ff6fd2d6b24d9a2ba777f7b50f)
 - [Handle auto_more in presentation layer](https://github.com/MycroftAI/skill-wiki/commit/6b2706e208e3f2affdcbb9bdc354103aa099d5a6)
 - [Tokenize sentences using quebra-frases by @jarbasAl](https://github.com/MycroftAI/skill-wiki/commit/8835d39782ed55a2ceb9396e54bfc414ceb17b5d)
 - [Remove repeated calls to wikipedia in tell more](https://github.com/MycroftAI/skill-wiki/commit/f7fc57fc992c675bf21b03ecd0fc9124f7df132c)
 - [remove attributes that are no longer used](https://github.com/MycroftAI/skill-wiki/commit/9a297be942437e925bbb28ca178c3a2d75b8f173)
 - [auto-format](https://github.com/MycroftAI/skill-wiki/commit/11c33abcddba75e1668f86dfe38107090a8d47ef)
 - [Merge pull request #68 from MycroftAI/jira_skill_253](https://github.com/MycroftAI/skill-wiki/commit/70491f4e526331d5f81a52cf06cf7a70f5994901)
 - [add missing vocab entries](https://github.com/MycroftAI/skill-wiki/commit/1531dd4f8832fd6067551f6f0563ec20f649101d)
 - [Merge pull request #67 from devs-mycroft/translations](https://github.com/MycroftAI/skill-wiki/commit/4fac16d8eec22f8ffdc8227c64ddedaf860b373d)
 - [Update translations](https://github.com/MycroftAI/skill-wiki/commit/97dd6ba708f9a1ee12bb85a118b4e5da14f8351b)
 - [fix two broken vk tests by using proper messages ratger than arbitrary timeouts](https://github.com/MycroftAI/skill-wiki/commit/692caf49c5a94d732668876743cc91ee13dcf4de)
 - [Merge pull request #65 from MycroftAI/add_intent_auto_more](https://github.com/MycroftAI/skill-wiki/commit/33267793c9bf85ddccf580ff4eb4fd650485a012)
 - [added doc string](https://github.com/MycroftAI/skill-wiki/commit/33a0d48cb981fb352d3bc88c38690c34b7e8d851)
 - [fix bug introduced by comment fix](https://github.com/MycroftAI/skill-wiki/commit/7b4009013840fc46430b89536f409b515de928a4)
 - [respond to PR feedback](https://github.com/MycroftAI/skill-wiki/commit/f7da2e10a93f25751004b4e01efc194d5eb01212)
 - [Merge branch '21.02' of https://github.com/MycroftAI/skill-wiki into add_intent_auto_more](https://github.com/MycroftAI/skill-wiki/commit/ba14f490a404b6e8a0155c7e3415eb6eb9059ce3)
 - [Merge pull request #66 from Mycroft-eus/basque](https://github.com/MycroftAI/skill-wiki/commit/b9caccd69ecc0a41c1a6cd0ff79b2e676a62566d)
 - ["Changes for Basque language"](https://github.com/MycroftAI/skill-wiki/commit/c7394998335c8432b32388ab8401602b754b537a)
 - [fix and add some vk tests](https://github.com/MycroftAI/skill-wiki/commit/65728a174cc26672e2991b81b109d485cbe2c751)
 - [convert to common query and make more behavior configurable](https://github.com/MycroftAI/skill-wiki/commit/b1096d8acf4e0215a7c6804d3a8d45bca367bbee)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.16</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1563)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1563/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1563/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1563/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1563/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1563/logs/enclosure.log)

**Comment by krisgesling** [comment]
@ken-mycroft just making sure you see the failing tests here

**Comment by ken-mycroft** [comment]
I did - but I also ran them locally and those tests actually passed. Could be timing or something to do with recognition. I did notice in both failed tests it returned an article about a woody allen movie. This shows they all passed locally. This leads me to believe we have the proper vk tests checked in. I'll see if there's anything special about these two tests. 

[WIKI_TEST_RESULTS.TXT](https://github.com/MycroftAI/mycroft-skills/files/7002245/WIKI_TEST_RESULTS.TXT)

**Comment by krisgesling** [comment]
As this relies on the improved confidence calculation in core, this will continue to fail until the next release of mycroft-core.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1563)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1563/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1563/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1563/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1563/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1563/logs/enclosure.log)

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1563)). 
Mycroft logs are also available: [skills.log](https://reports.mycroft.ai/skills/PR-1563/logs/skills.log), [audio.log](https://reports.mycroft.ai/skills/PR-1563/logs/audio.log), [voice.log](https://reports.mycroft.ai/skills/PR-1563/logs/voice.log), [bus.log](https://reports.mycroft.ai/skills/PR-1563/logs/bus.log), [enclosure.log](https://reports.mycroft.ai/skills/PR-1563/logs/enclosure.log)

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
