### PR TITLE
Add powerball-checker-skill

### PR DESCRIPTION
**Pull request by laurapalmerstolemyheart**
## Info

This PR adds the new skill, [powerball-checker-skill](https://github.com/laurapalmerstolemyheart/powerball-checker-skill), to the skills repo.

## Description

This skill allows mycroft to tell you the last winning Powerball numbers.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.13</sub>

### CODE REVIEW

**Comment by krisgesling** [comment]
Hi there,

Thanks for submitting your first Skill! :tada:

To be included in the Marketplace the Skill goes through three reviews by our [Skill Testing Team](https://github.com/MycroftAI/contributors/blob/master/team/Skill-Testing-Team.md). You can read more about these reviews and the overall Skills Acceptance Process here: https://mycroft.ai/documentation/skills/skills-acceptance-process/

If you have any updates in the meantime, you can update this pull request by running: 
`mycroft-msk submit /opt/mycroft/skills/your-skill-dir` 

Also feel free to post here or in the [Skills channel on Chat](https://chat.mycroft.ai/community/channels/skills) if you have any questions.

If you are already working on the updates you have commented, be sure to checkout [`extract_datetime`](https://mycroft-core.readthedocs.io/en/latest/source/mycroft.util.parse.html#mycroft.util.parse.extract_datetime) which handles all those vague and relative date references like "last wednesday".

Looking forward to trying out your Skill :slightly_smiling_face:

**Comment by laurapalmerstolemyheart** [comment]
Thank you for that suggestion!  I will definitely check out
extract_datetime.

**Comment by laurapalmerstolemyheart** [comment]
What is my next step?

**Comment by krisgesling** [comment]
Hi there, we need the Skill to be reviewed before we can merge it into the Marketplace. This can take some time as we have a limited number of Community testers and the internal team have been focused on the Mark II. 

If you are interested in helping out, we always need more testers on the team. You can read more about the process in [our docs](https://mycroft.ai/documentation/skills/skills-acceptance-process/) or sign up to the Skill Testing Team here:
https://mycroft.ai/contribute/#suggest-and-test-skills

Anyone that helps out by reviewing other peoples Skills gets bumped to the top of the queue for a review of their Skill :slightly_smiling_face:

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
