### PR TITLE
Add linux-application-launcher

### PR DESCRIPTION
**Pull request by BitiTiger**
## Info

This PR adds the new skill, [linux-application-launcher](https://github.com/Caton101/application-launcher-skill), to the skills repo.

## Description

This skill allows Mycroft to launch programs for the user. If this skill is the determined intention, it will check for the program in the user's `$PATH` variable by executing it in a subprocess. If a command is incorrect, it will try several variations of the program name.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.15</sub>

### CODE REVIEW

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1337))

**Comment by BitiTiger** [comment]
I just made this skill for fun and thought I would contribute it to the official repository. I am not sure what the errors mean. Skill tester says something like "mine" is not a git repository and Voight Kampff Integration Test says it can not clone my repo. I confirmed that my repo can be cloned to another machine. I assume these are either scripting errors in the repository or I missed something in the documentation.

Thank you all for making a great personal assistant and scripting API. I look forward to any replies.

**Comment by forslund** [comment]
Hi, it's a limitation with msm (the tool used to download and installed skills) it doesn't handle `git@github.com:...` urls only `https://`... :(

if possible change your origin remote for your skill to `https://github.com/Caton101/application-launcher-skill.git`

Sorry for the inconvenience

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1337))

**Comment by BitiTiger** [comment]
Thank you for your help.

**Comment by forslund** [comment]
Looked over the manifest and you list subprocess and sys as python dependencies. These are python built-ins and don't exist as packages on pypi. You can safely remove them and the skill should be able to install.

**Comment by BitiTiger** [comment]
Thank you @forslund for noticing issues in my manifest. That issue should be fixed now.

**Comment by BitiTiger** [comment]
I keep trying to add a new commit using `mycroft-msk` but it doesn't seem to be reflecting those changes. It successfully pushed changes to the `add-linux-application-launcher` branch on `Caton101/mycroft-skills`. I'm not sure why the changes are not reflected on this pull request.

**Comment by devops-mycroft** [comment]
Voight Kampff Integration Test Failed ([Results](https://reports.mycroft.ai/skills/PR-1337))

**Comment by krisgesling** [comment]
Looks like it's updated now. Github has been having some issues the last few weeks so could be a delay related to that. 

Regarding the failing test, this is not to do with your Skill. It's a separate issue we're looking into it at the moment.

**Comment by forslund** [comment]
Project is no longer maintained, closing.

**Pull request closed without merging**
