### PR TITLE
Upgrade mycroft-ip

### PR DESCRIPTION
**Pull request by forslund**
'This upgrades mycroft-ip to include the following new commits:

 - [Merge pull request #15 from MycroftAI/bugfix/last-digit-no-primary-device](https://github.com/MycroftAI/skill-ip/commit/618fa0948252462b0a746c600aada88080be911a)
 - [Handle "non-standard" devices](https://github.com/MycroftAI/skill-ip/commit/687415a0f087f397479d858c312dfe1f0f5a4165)
 - [Merge pull request #14 from MycroftAI/test/last-digits](https://github.com/MycroftAI/skill-ip/commit/735cf27d6bde9348e999151a2c3e3201044e02a8)
 - [Rename tests to reflect content better](https://github.com/MycroftAI/skill-ip/commit/36decdc779a80c5e163bba8af29b8912f21d5a45)
 - [Add test for last digits of ip](https://github.com/MycroftAI/skill-ip/commit/10cafc979c07981e886ceabac510183133032d32)
 - [Merge pull request #13 from MycroftAI/feature/ifaddr-update](https://github.com/MycroftAI/skill-ip/commit/8c2041c079bb11a747133513dd97ea7c3fef5575)
 - [Move to locale](https://github.com/MycroftAI/skill-ip/commit/a756a67b240c269a583ee948c1b1c88982258d8f)
 - [Add query for last digits of IP address](https://github.com/MycroftAI/skill-ip/commit/2959a09362331bae8fc405673398992c511a9075)
 - [Add git ignore](https://github.com/MycroftAI/skill-ip/commit/fbfe6feb8e1c777a8bc7e7d82e583628142ab6c2)
 - [Replace netifaces with ifaddr](https://github.com/MycroftAI/skill-ip/commit/bf17978b6a586d7a9efead1defff993c7eb1415d)

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.10</sub>

### CODE REVIEW

**Review by KathyReid — CHANGES_REQUESTED** [review]
### Ensure on correct commit
```
(.venv) kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-ip.mycroftai$ git log
commit 9b6b5b3d5ca1917d8edd438b66d5d83da0186762 (HEAD -> ifaddr, origin/ifaddr)
Author: Åke Forslund <ake.forslund@gmail.com>
Date:   Mon Oct 15 14:57:35 2018 +0200

    Move to locale

```

### Test case for last digits of IP address
* `Hey mycroft, what are the last digits of my IP address`
> "An error occurred while processing a request in IP Skill"

Checked `skills.log`

```
02:13:50.073 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.start", "data": {"name": "IPSkill.handle_query_last_part_IP"}, "context": {"client_name": "mycroft_listener", "ident": "1539789225.9069347448950995549828079", "target": null}}
02:13:50.077 - mycroft.skills.core:wrapper:745 - ERROR - An error occurred while processing a request in IP Skill
Traceback (most recent call last):
  File "/home/kathyreid/mycroft-core/mycroft/skills/core.py", line 736, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-ip.mycroftai/__init__.py", line 99, in handle_query_last_part_IP
    self.enclosure.mouth_text(ip_end)
UnboundLocalError: local variable 'ip_end' referenced before assignment
02:13:50.077 - SKILLS - DEBUG - {"type": "speak", "data": {"utterance": "An error occurred while processing a request in IP Skill", "expect_response": false}, "context": {"client_name": "mycroft_listener", "ident": "1539789225.9069347448950995549828079", "target": null}}
02:13:50.079 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
02:13:50.080 - SKILLS - DEBUG - {"type": "mycroft.skill.handler.complete", "data": {"name": "IPSkill.handle_query_last_part_IP", "exception": "UnboundLocalError(\"local variable 'ip_end' referenced before assignment\",)"}, "context": {"client_name": "mycroft_listener", "ident": "1539789225.9069347448950995549828079", "target": null}}
```

Tried again

* `Hey mycroft, what's the last part of my IP address`
> "An error occurred while processing a request in IP Skill"

Same error

==> requires investigation before merging, it's possible I could be on the wrong commit though; I had trouble git checking out, so cloned the `ifraddr` branch. 

### Test case for move to `locale`
As a test I inspected the structure of the filesystem => as expected

### Test case for change to `ifaddr`
Cannot test yet until previous error cleared

**Comment by KathyReid** [comment]
Hi @forslund does the commit earlier today mean I should close this PR?

**Comment by forslund** [comment]
No, I'll do an msk upgrade to update this PR.

**Comment by forslund** [comment]
@KathyReid I think you should be able to retest this when ever you get the time.

**Comment by KathyReid** [comment]
### Ensure on correct commit
```
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/mycroft-ip.mycroftai$ git log
commit 32503e121626391b987db76b6ce7aae7d61cadde (HEAD -> forslund-upgrade-mycroft-ip, 18.08)
Author: Åke Forslund <ake.forslund@gmail.com>
Date:   Thu Sep 27 12:21:31 2018 +0200

    Enforce reinstall of netifaces
```

### Test case for last digits of IP address

* `Hey Mycroft, what are the last digits of my IP address`
> "On wlp110s0 my I.P. address is 192
    dot 168 dot 0 dot 15."
On docker0 my I.P. address is 172
    dot 17 dot 0 dot 1.

=> these are both correct

Retest just to be absolutely certain as this test failed previously

* `Hey Mycroft, what are the last digits of my IP address`
> correct answer received again

TEST CASE PASSED

### Test case for ensuring `ifaddr` is installed in `venv`

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ pip3 list | grep ifaddr
ifaddr                   0.1.4 
```

TEST CASE PASSED

### Test case for no primary device

I wasn't sure how to construct a test case for this, so I read through the code, LGTM

---

LGTM, merging

**Review by KathyReid — APPROVED** [review]

**Pull request merged**
