### PR TITLE
Add Hal-and-TARS

### PR DESCRIPTION
**Pull request by PayloadBae**
## Info

This PR adds the new skill, [Hal-and-TARS](https://github.com/PayloadBae/movie-bot-quotes-skill), to the skills repo.

## Description

Movie ai quotes

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.12</sub>

### CODE REVIEW

**Comment by forslund** [comment]
Run test

**Comment by LinusSkucas** [comment]
# Skills test for Movie Bot Quotes 🤖 

## Meta
*   Platform: Picroft
*   Mycroft-core version: 19.02
*   Who: [@LinusS1](https://github.com/linuss1) Mattermost/forum: brrn
*   Datestamp: 2019-03-26_18:46:25_PDT
*   Language and dialect of tester: (American) English

## 0. Automated tests
Are all automated tests passing?
- [x] Skill tester - Jenkins
- [x] Continuous Integration - Travis-CI

## 1. Code Review - secure and stable
- [x]   **Code Quality**
Can you understand what the code is doing? Is there inline documentation? Do you have any concerns about this code running on your machine? Are there any performance issues such as nested or infinite loops? Do you have significant concerns about the overall code quality?
_NOTE: We do not enforce PEP8 Checks on Skills_

> Yep, fairly simple skill

- [x]   **Error Handling**
Are there any specific checks we make for error handling or graceful degradation?

>None needed

- [x]   **Libraries**
Does the Skill include the correct libraries? Does it use too many libraries or dependencies?

>No libraries needed

- [x]   **Required Dependencies**
Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that there is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed.
Also check to see if `requirements.txt` and `requirements.sh` are empty, if they are, they can be deleted.

>No `requirements.txt` file - all good

- [ ]   **Settings**
Is the `settingsmeta.json` file well laid out? If settings are not used, has the default file been deleted? If it is the default file, the first setting section will be called "Options << Name of section".

>`Settingsmeta.json` is still there.

_Action Required: Please delete the `settingsmeta.json` file._

- [ ]   **Integration Tests**
Does the skill include sufficient integration tests, included in the `test` folder?

>No tests.
_Action required: Please create tests for the skill by running `msk create-test` in the directory of your skill._


- [x]   **Other Files**
Are there any other files included that are unnecessary or you are unsure of their function?

>No odd files.


## 2. Information Review - accurate and understandable
This review checks the README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

_Action Required:_

- [ ] Please rework the README file using the meta generator: https://raw.githack.com/MycroftAI/mycroft-skills/19.02/meta_editor.html

Then I can check for completeness etc...

## 3. Functional Review - intuitive and expected
- [ ]   **Installation**

Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name. Please provide confirmation that the Skill was successfully installed and by what means (voice or `mycroft-msm install`), as well as what utterance was detected when invoking the install voice command.

> Install method:
>`msm install https://github.com/PayloadBae/HAL-SKILL.git`
>Installed!
> Checking that STT transcribes correctly:
> Mycroft can't understand when I say movie bot quotes (he thinks he heard moviebox)
> Mycroft also definitely not understand when I say Hal and tars
Not sure if it's my voice that's throwing Mycroft off, or if it's the stt, then the name would have to be changed. Pinging @krisgesling for this one.

- [ ]   **Settings**
If Skill includes a `settingsmeta.json` file - are the settings well laid out? Does the placeholder text make sense? This can also be checked on [home.mycroft.ai/#/skill](https://home.mycroft.ai/#/skill)

>Please delete the `settingsmeta.json` file.

- [-]   **Dialog**

Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/).

  Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used.  Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

>Sounds good. However, you should probably add more, just add lines to that same dialog file.

#### Skill Functions
For each function of the Skill add a new checkbox with the utterance used to invoke the functionality. Confirm the output and behaviour of each. If any setup is required to perform these tests please indicate this directly before the test is described. Also check that the sample utterances activate the skill

- [x]   **""Open the pod bay doors""**

>I'm sorry, I can't let you do that.

- [ ]   **"set humor to 80 percent"**

>Mycroft STT changes percent to %, which doesn't activate the skill. Change the percent in the intent file to %.


You might also consider adding more examples to activate the skill.

## Summary
 - [ ] Please rework the README file using the meta generator
 - [ ] Please delete the `settingsmeta.json` file.
 - [ ] Please create tests for the skill by running `msk create-test` in the directory of your skill.
 - [ ] Add more dialog to the dialog file
 - [ ] Change the percent in the intent file to %.

> Thanks for making this skill! It's fun! 

Once you have completed the updates, you can update this pull request by running `msk submit /path/to/skill/directory`

**Comment by krisgesling** [comment]
Thanks for doing the skill review Linus!

@PayloadBae - In terms of a Skill name that works well for speech recognition, I found that "AI Movie Quotes" got picked up quite well.

**Comment by krisgesling** [comment]
Hi @PayloadBae 

As we haven't heard from you in a while, I'm going to close this PR for now. 

If you're still interested in having the Skill included in the Marketplace, just run `mycroft-msk submit` and it will create a new PR against the latest 19.08 branch.

Thanks

**Pull request closed without merging**
