### PR TITLE
Add rss-reader

### PR DESCRIPTION
**Pull request by backassward**
## Info

This PR adds the new skill, [rss-reader](https://github.com/backassward/rss-reader-skill), to the skills repo.

## Description

This skill is a simple tool to get updates from your favorite news sources.

the main features are:
* manage your feed subscriptions from your [dashboard](https://home.mycroft.ai/),
* ask Mycroft to check if new articles have been published,
* ask Mycroft to read the titles and other information for you.

<sub>Created with [mycroft-skills-kit](https://github.com/mycroftai/mycroft-skills-kit) v0.3.9</sub>

### CODE REVIEW

**Comment by KathyReid** [comment]
## Test of `rss-reader`

* Platform: Mark 1
* Device version: 18.2.9b
* Who: @kathyreid / kathy-mycroft
* Datestamp: Thu  5 Jul 19:04:58 UTC 2018
* Language and dialect of tester: Native English Speaker, Australian accent

##### Standard checks (non-code checks)

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.

> The Skill is not yet in the `18.02` repository, so I manually installed using `msm`

```
pi@mark_1:~ $ msm install https://github.com/backassward/rss-reader-skill
INFO - Downloading skill: https://github.com/backassward/rss-reader-skill
INFO - Installing requirements.txt for rss-reader-skill
INFO - Successfully installed rss-reader-skill
```

> then validated successful install on the filesystem

```
pi@mark_1:~/skills/rss-reader-skill.backassward $ ls -las
total 96
 4 drwxr-xr-x  7 mycroft mycroft  4096 Jul  5 18:59 .
 4 drwxrwxrwx 37 mycroft mycroft  4096 Jul  5 18:58 ..
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jul  5 18:58 dialog
 4 drwxr-xr-x  8 mycroft mycroft  4096 Jul  5 18:58 .git
 4 -rw-r--r--  1 mycroft mycroft    33 Jul  5 18:58 .gitignore
12 -rw-r--r--  1 mycroft mycroft  8194 Jul  5 18:58 __init__.py
36 -rw-r--r--  1 mycroft mycroft 35147 Jul  5 18:58 LICENSE
 4 drwxr-xr-x  2 mycroft mycroft  4096 Jul  5 18:58 __pycache__
 4 -rw-r--r--  1 mycroft mycroft  2500 Jul  5 18:58 README.md
 4 -rw-r--r--  1 mycroft mycroft    11 Jul  5 18:58 requirements.txt
 4 -rw-r--r--  1 mycroft mycroft   162 Jul  5 19:01 settings.json
 4 -rw-r--r--  1 mycroft mycroft  2154 Jul  5 18:58 settingsmeta.json
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jul  5 18:58 test
 4 drwxr-xr-x  3 mycroft mycroft  4096 Jul  5 18:58 vocab
```
> Next, I checked to see that the name of the Skill would be picked up via voice commands. 

```
20:04:50.837 - SKILLS - DEBUG - {"context": {"ident": "1530821086.8681178211092889", "client_name": "mycroft_listener"}, "type": "recognizer_loop:utterance", "data": {"lang": "en-US", "utterances": ["rss2"], "session": "d7f27873-3437-4230-a3c5-0ee459624a8f"}}
20:07:19.158 - SKILLS - DEBUG - {"context": {"ident": "1530821235.476721416736187", "client_name": "mycroft_listener"}, "type": "recognizer_loop:utterance", "data": {"lang": "en-US", "utterances": ["rss kill"], "session": "d7f27873-3437-4230-a3c5-0ee459624a8f"}}
```
> The phrase `RSS skill` is being picked up as `rss2` or `rss kill`. I would recommend re-naming the Skill to make it something easier to pronounce so that it can be more easily installed using voice commands. I'm _not_ going to block the release of this Skill on this alone; just something to keep in mind for next time. 

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> Ran all the `dialog` through `mimic` - no issues

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

> Checked the Intents in the `.voc` files => fairly unique, should not lead to Intent Collisions

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Regex not used, check skipped

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on?

> README looks good, has everything that I would expect

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> just has `feedparser`, version not specified => OK

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> laid out well 

#### Python code checks of the Skill

* Inline documentation - is the code documented in line?

> there's _a little_ inline doco, but it could use more ;-) 

* Libraries - does the Skill include the correct libraries? Does it use too many libraries or dependencies?

> very light on dependencies, just `feedparser`

* Callback check - do we need to do a check for the callback error that was in the Spotify Skill?

> nope all good

* Error handling - are there any specific checks we make for error handling or graceful degradation?

> no, there's Intents that handle this OK

* Automatic tests - do automatic tests of the **Skill** pass?

> yes

#### Functional testing

No matter what I do, I can't get this Skill to work; 

```
kathyreid@kathyreid-N76VZ:~/Dropbox/PHPworkspace/mycroft-core/scripts/logs$ tail -f mycroft-skills.log | grep -i feed
06:55:05.101 - SKILLS - DEBUG - {"data": {"utterances": ["read my news feeds"], "session": "7972d2f2-f924-4e7d-a569-5efc140e24ce", "lang": "en-US"}, "context": {"client_name": "mycroft_listener", "ident": "1530824096.831368-8482393338858113432"}, "type": "recognizer_loop:utterance"}
06:55:05.110 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1530824096.831368-8482393338858113432"}, "type": "intent_failure", "data": {"utterance": "read my news feeds", "lang": "en-US"}}
06:55:05.113 - mycroft.skills.padatious_service:handle_fallback:103 - DEBUG - Padatious fallback attempt: read my news feeds
06:55:05.116 - WolframAlphaSkill - DEBUG - WolframAlpha fallback attempt: read my news feeds
06:55:05.116 - WolframAlphaSkill - DEBUG - Non-question, ignoring: read my news feeds
06:55:31.536 - SKILLS - DEBUG - {"data": {"utterances": ["read my new feeds"], "session": "7972d2f2-f924-4e7d-a569-5efc140e24ce", "lang": "en-US"}, "context": {"client_name": "mycroft_listener", "ident": "1530824127.926671-6784265124731052589"}, "type": "recognizer_loop:utterance"}
06:55:31.549 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1530824127.926671-6784265124731052589"}, "type": "intent_failure", "data": {"utterance": "read my new feeds", "lang": "en-US"}}
06:55:31.550 - mycroft.skills.padatious_service:handle_fallback:103 - DEBUG - Padatious fallback attempt: read my new feeds
```

It doesn't seem to be matching the Intent to this Skill - that is, when the Utterance is actually picked up as "new feeds" instead of "news feeds". 

I'm going to see if others get the same result, but I cannot pass this Skill in this state - it's just not working for me at all.

**Comment by KathyReid** [comment]
@backassward do the Intents work for you under testing? I couldn't get them to trigger and not sure if it's just my accent?

**Comment by backassward** [comment]
Hi @KathyReid and thanks for running tests on my skill!

The skill works fine on my linux installation, and I've been using it regularly on picroft since last week. After running `msm install https://github.com/backassward/rss-reader-skill`, I am able to get the default rss feed read by mycroft.

The skill trigger works for me even if English is not my mother tongue. I think you should be fine!

Is it possible that something went wrong during your skill installation process?
I'm thinking of a temporary failure or something of that sort.

**Comment by KathyReid** [comment]
Hmm, I still cannot trigger the Intents with my voice :(

Are you able to provide the `mycroft-skills.log` showing the `Utterance` and it matching to an Intent in this Skill? It's just another way for me to verify that the Intent is being correctly matched from the Utterance.

**Comment by backassward** [comment]
Sure!
```
10:16:31.168 - SKILLS - DEBUG - {"data": {"utterance": "hey mycroft", "session": "afd788c6-2171-458b-ad53-3694a952ec77"}, "context": null, "type": "recognizer_loop:wakeword"}
10:16:34.655 - SKILLS - DEBUG - {"data": {"session": "afd788c6-2171-458b-ad53-3694a952ec77", "utterances": ["read my news feeds from minecraft blog"], "lang": "en-US"}, "context": {"client_name": "mycroft_listener", "ident": "1531556191.1434073194297935"}, "type": "recognizer_loop:utterance"}
10:16:34.674 - mycroft.skills.intent_service:send_metrics:247 - DEBUG - Sending metric if opt_in is enabled
10:16:34.684 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "intent_failure", "data": {"utterance": "read my news feeds from minecraft blog", "lang": "en-US"}}
10:16:34.690 - mycroft.skills.padatious_service:handle_fallback:103 - DEBUG - Padatious fallback attempt: read my news feeds from minecraft blog
10:16:34.712 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "mycroft.skill.handler.start", "data": {"handler": "fallback"}}
10:16:34.732 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "rss-reader-skill:read.feeds.intent", "data": {"utterance": "read my news feeds from minecraft blog"}}
10:16:34.757 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "mycroft.skill.handler.complete", "data": {"fallback_handler": "PadatiousService.handle_fallback", "handler": "fallback"}}
10:16:34.779 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "mycroft.skill.handler.start", "data": {"name": "RssReader.handle_read_feeds_intent"}}
10:16:35.705 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "speak", "data": {"utterance": "I'm now reading your Mycroft blog feed.", "expect_response": false}}
10:16:35.722 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "speak", "data": {"utterance": "Mycroft AI at VOICE Summit", "expect_response": false}}
10:16:35.749 - SKILLS - DEBUG - {"data": {}, "context": null, "type": "recognizer_loop:audio_output_start"}
10:16:38.704 - SKILLS - DEBUG - {"data": {"side": "b"}, "context": null, "type": "enclosure.eyes.blink"}
10:16:40.019 - SKILLS - DEBUG - {"context": null, "type": "skill-date-time:TimeSkillupdate_display", "data": {}}
10:16:41.434 - SKILLS - DEBUG - {"data": {}, "context": null, "type": "recognizer_loop:audio_output_end"}
10:16:41.448 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "speak", "data": {"utterance": "What should I do now?", "expect_response": true}}
10:16:41.479 - SKILLS - DEBUG - {"data": {}, "context": null, "type": "recognizer_loop:audio_output_start"}
10:16:42.317 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
10:16:43.070 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/setting HTTP/1.1" 304 0
10:16:43.083 - mycroft.api:send:111 - DEBUG - Etag matched. Nothing changed for: device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/setting
10:16:43.098 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
10:16:43.175 - SKILLS - DEBUG - {"data": {}, "context": null, "type": "recognizer_loop:audio_output_end"}
10:16:43.188 - SKILLS - DEBUG - {"data": {"side": "b"}, "context": null, "type": "enclosure.eyes.blink"}
10:16:43.214 - SKILLS - DEBUG - {"data": {}, "context": null, "type": "recognizer_loop:record_begin"}
10:16:43.255 - SKILLS - DEBUG - {"context": null, "type": "active_skill_request", "data": {"skill_id": "rss-reader-skill"}}
10:16:43.805 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/location HTTP/1.1" 304 0
10:16:43.818 - mycroft.api:send:111 - DEBUG - Etag matched. Nothing changed for: device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/location
10:16:45.439 - SKILLS - DEBUG - {"data": {}, "context": null, "type": "recognizer_loop:record_end"}
10:16:45.464 - SKILLS - DEBUG - {"data": {"utterance": "hey mycroft", "session": "afd788c6-2171-458b-ad53-3694a952ec77"}, "context": null, "type": "recognizer_loop:wakeword"}
10:16:46.120 - mycroft.skills.settings:_request_other_settings:473 - DEBUG - syncing settings with other devices from server for RssReader
10:16:46.126 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
10:16:46.337 - mycroft.skills.settings:_request_my_settings:440 - DEBUG - getting skill settings from server for WeatherSkill
10:16:46.345 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
10:16:46.848 - mycroft.skills.settings:_request_my_settings:440 - DEBUG - getting skill settings from server for PodcastSkill
10:16:46.855 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
10:16:46.876 - mycroft.skills.settings:_request_my_settings:440 - DEBUG - getting skill settings from server for NewsSkill
10:16:46.882 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai:443
10:16:47.288 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/userSkill?identifier=RssReader--a21f4af85cc4a182ba8399e57f83fac8 HTTP/1.1" 304 0
10:16:47.320 - mycroft.api:send:111 - DEBUG - Etag matched. Nothing changed for: device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/userSkill?identifier=RssReader--a21f4af85cc4a182ba8399e57f83fac8
10:16:47.368 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/skill HTTP/1.1" 304 0
10:16:47.379 - mycroft.api:send:111 - DEBUG - Etag matched. Nothing changed for: device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/skill
10:16:47.489 - SKILLS - DEBUG - {"data": {"session": "afd788c6-2171-458b-ad53-3694a952ec77", "utterances": ["stop"], "lang": "en-US"}, "context": {"client_name": "mycroft_listener", "ident": "1531556205.4501805-1961649396"}, "type": "recognizer_loop:utterance"}
10:16:47.506 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"skill_id": "rss-reader-skill", "lang": "en-US", "utterances": ["stop"]}}
10:16:47.536 - SKILLS - DEBUG - {"context": {}, "type": "skill.converse.response", "data": {"skill_id": "rss-reader-skill", "result": true}}
10:16:47.569 - SKILLS - DEBUG - {"context": {"ident": "1531556191.1434073194297935", "client_name": "mycroft_listener"}, "type": "mycroft.skill.handler.complete", "data": {"name": "RssReader.handle_read_feeds_intent"}}
10:16:47.627 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/skill HTTP/1.1" 304 0
10:16:47.638 - urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "GET /v1/device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/skill HTTP/1.1" 304 0
10:16:47.654 - mycroft.api:send:111 - DEBUG - Etag matched. Nothing changed for: device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/skill
10:16:47.656 - mycroft.api:send:111 - DEBUG - Etag matched. Nothing changed for: device/9c45ecd5-edde-4d67-8151-c8a6942d12a6/skill
```

What I did here was asking picroft `read my news feeds from Mycroft blog`, and I've got back `I'm now reading your Mycroft blog feed. Mycroft AI at VOICE Summit. What should I do now?`. I replied `Stop` to cut it short.

In truth, the utter that Mycroft got was `read my news feeds from minecraft blog`. The code I wrote is a bit naive and Mycroft found a match comparing "Mycroft blog" and "minecraft blog" (this is a real life case where a bug it's actually a feature!). But this is all beyond the scope of this pull request, I just wanted to clarify.

**Comment by KathyReid** [comment]
Thanks so much for that @backassward, that was super useful.
On that basis, I'm going to approve this Skill into the `18.02` branch.

**Comment by backassward** [comment]
Thanks!!

**Pull request merged**
