### PR TITLE
New still - cut-up-skill

### PR DESCRIPTION
**Pull request by JonStratton**
Cut Up

## Description:

Repeat using the cut up technique.

## Checklist:
  - [X ] Used [Meta Editor](http://rawgit.com/MycroftAI/mycroft-skills/master/meta_editor.html) to generate the skill README
  - [ X] Skill has been tested and works 
  - [ X] Read and verified approval process - https://mycroft.ai/documentation/skills/skills-acceptance-process (Can require a community member vouching for skill)
  - [ X] .gitmodules has been updated with the following:
  
```
+[submodule "NAME OF YOUR SKILL"]
+	path = name-of-your-skill
+	url = URL.FOR.YOUR.SKILL.git
```

### CODE REVIEW

**Comment by JonStratton** [comment]
Not sure I understand the output of the skill tester, but I would assume this is failing due to my skill having a submodule and it not being downloaded when installed.

Any advice on how I should deal with this going forward? Just copying the lib into my project, and not using it as a submodule?

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
You can add a `requirements.sh` file to the repo which runs `git submodule update --init ...` See the [zork-skill](https://github.com/forslund/white-house-adventure/blob/master/requirements.sh#L6) for an example.

(Also I've updated the tester to give better clues to what is the issue when loading fails and it now shows exactly what you suspected)

**Comment by JonStratton** [comment]
Thanks @forslund , that seemed to do the trick.
My interpretation of the skill tester result is that its now failing on "mycroft-alarm.mycroftai/test/intent/007.delete.alarm.json", so I believe this is unrelated to the code added with this pull request.

**Comment by forslund** [comment]
That test case is acting up at times. I'll re-run the tests

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Run test

**Comment by forslund** [comment]
Found the issue in the alarm skill, all checks are now nice and green :)

**Comment by KathyReid** [comment]
### Meta

* Platform: Ubuntu 18.04 LTS
* Device version: 18.8.6 stable branch
* Who: @kathy-mycroft / @kathyreid
* Datestamp: Sat 15 Dec 00:58:36 AEDT 2018
* Language and dialect of tester: Native English speaker, Australian accent

### Standard checks

* Check that the Skill installs using voice commands. Mycroft will get the user to confirm which Skill should be installed if there is ambiguity in Skill names - such as duplicate names. If possible, name the Skill so that there is minimal duplication and/or conflict. You should also verify that the Skill name can be verbally pronounced by speaking the Skill name into the Mycroft command line several times, and reading the resulting transcriptions. Suggest alternative Skill names if it is difficult to verbally pronounce the Skill name.
> New Skill, voice install won't be available, using `msm` installation

```
(.venv) kathyreid@kathyreid-Oryx-Pro:~/mycroft-core$ msm install https://github.com/JonStratton/cut-up-skill
INFO - Downloading skill: https://github.com/JonStratton/cut-up-skill
Submodule 'brion-pysin' (https://github.com/JonStratton/brion-pysin.git) registered for path 'brion-pysin'
Cloning into '/opt/mycroft/skills/cut-up-skill.jonstratton/brion-pysin'...
Submodule path 'brion-pysin': checked out '1af34d5799abff7f85c73d16d9f6b179e936bb34'
INFO - Successfully ran requirements.sh for cut-up-skill
INFO - Successfully installed cut-up-skill
```
> Successfully installed

* Check the `dialog` directory to ensure that from a voice user interface perspective the dialogs read well. It is a good idea to run the `dialog` phrases through [mimic](https://mycroft.ai/documentation/mimic/). Sometimes the `dialog` files will need a small tweak such as a space between words, or extra vowel sounds, to sound realistic. Sometimes words don't render as expected and alternative wording should be used. Alway play every `dialog` phrase on the command line by doing `say <your dialog phrase here>` so that you can check how the `dialog` is spoken. Some of the tricks you might need to use include separating words by a space - such as `sub sonic` instead of `subsonic`, or `broad cast` instead of `broadcast`.

> No `dialog` used, skipping check

* Check the **Intents** defined in the `vocab` diectory. Determine if the **Intents** are likely to conflict with those from **Skills** that are installed by default, and if so, suggest alternatives if this makes sense, or at least advise the Skill Author that there are likely to be `Intent Collisions`. [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.

> Intents are quite unique, Intent Collisions are unlikely to occur.

_NOTE: Skills that are installed by default vary by `enclosure` and can be found in the `mycroft-skills` repo in the files called `DEFAULT.enclosure`. For example, the default Skills for Picroft are in a file called `DEFAULT.picroft`._

* Check the regular expressions defined in the `regex` directory - do they appear sensible? [Integration Test Runner](https://mycroft.ai/documentation/skills/automatic-testing/) can also assist with this.
> Regex is nicely done, great use of `\w` modifier

* Check README for completeness - does it follow the README template and include all the relevant sections such as Intents, known issues, dependencies and so on? Is at least one category selected? _At least one category must be selected for the Skill to be displayed correctly in the [Mycroft Marketplace](https://market.mycroft.ai)._

> README is _not_ generated using [Meta Editor](https://raw.githack.com/MycroftAI/mycroft-skills/18.08/meta_editor

_ACTION REQUIRED: Please regenerate the README using the Meta Editor so that your Skill displays properly on the [Mycroft Marketplace](https://market.mycroft.ai)_

* Check `requirements.txt` and `requirements.sh` - are the required dependencies listed? If `requirements.sh` is used, is some form of conditional processing done to match against multiple distros? Often Skill Authors will add requirements.txt using only an “library=1.x.x” instead of “library >=1.x.x”. Check to make sure that here is an equal or greater than in the requirements to help future-proof the Skill, unless a _specific_ version is needed. 

> one requirement pulled in using a `gitmodule`, all OK

* Check `settingsmeta.json` - are the settings well laid out? Does the placeholder text make sense?

> `settingsmeta.json` is not used, should be removed from repo

_ACTION REQUIRED: Please remove `settingsmeta.json` from the repo_

### Functional check

#### Test case for `cut up set minimum 1`
* `Hey Mycroft, cut up set minimum `
> no audio response, no logging response in CLI

#### Test case for `cut up set maximum 3`
* `Hey Mycroft, cut up set maximum 3`
> no audio response, no logging response in CLI

#### Test case for `cut up set randomness 75`
* `Hey Mycroft, cut up set randomness 75`
> This was all sorts of fun - essentially the STT had a very difficult time transcribing this utterance. 

screenshot from 2018-12-15 01-23-06
screenshot from 2018-12-15 01-24-42
screenshot from 2018-12-15 01-25-21
screenshot from 2018-12-15 01-26-23
screenshot from 2018-12-15 01-26-59
screenshot from 2018-12-15 01-27-55

_ACTION REQUIRED: I think this really needs some audio cues, like "I have set the maximum to 3" or similar. Is there a different Intent word that might transcribe more consistently on STT do you think?_

### Summary

* Please regenerate the README file using the Meta Editor
* Please remove `settingsmeta.json` from the repo
* I feel that the Skill needs audio cues for settings, and the STT transcription on the main commands fails frequently - recommend changing the word that it triggers on.

**Comment by JonStratton** [comment]
Thanks @KathyReid,
Ive redone the README, removed the requested json file, and made the following changes:

1. After a config is changed, its read back (ie "Randomness set to 75.0 percent.")
2. "Randomize" has been added as an alternative to "Cut Up". This makes this skill **much** saner to play around with. I was having issues with this too, but assumed it was just me for some reason.

Let me know if the changes are not pulled in with this pull request. I've updated the main skill, but I'm not sure if I have to do anything to my branch the skills...

**Comment by KathyReid** [comment]
Thanks so much @JonStratton 

## Quick test of issues identified during testing

### Ensure on correct commit
```bash
kathyreid@kathyreid-Oryx-Pro:/opt/mycroft/skills/cut-up-skill.jonstratton$ git log
commit ded957b5a73f81f9fbf1b3725e81f7c003351c0b (HEAD -> master, origin/master, origin/HEAD)
Author: jgstratton <jgstratt@sdf.org>
Date:   Fri Dec 14 19:07:54 2018 -0600
```

### Test case for reading back the change
* This worked really well, thank you

### README
* there's a broken link to the README image / icon, but we can live with that. 

I'm going to merge this in.

**Pull request merged**
